try{
var g,aa=aa||{},k=this,ba="closure_uid_"+(1E9*Math.random()>>>0),m=Date.now||function(){return+new Date};
}catch(e){_DumpException(e)}
try{
k.ace_i18n={chrome_ext_short_name:{message:"Hangouts"},chrome_ext_description:{message:"Hangouts brings conversations to life with photos, emoji, and even group video calls for free."},quasar_chat_toast_info:{message:"Click to go to page..."},quasar_answer_button_text:{message:"Answer"},quasar_decline_button_text:{message:"Decline"},quasar_help:{message:"Help"},quasar_legend_startup_shutdown:{message:"Application"},chrome_ext_run_at_browser_start:{message:"Sign in to Hangouts when Chrome starts"},
chrome_ext_run_after_browser_close:{message:"Allow background mode"},chrome_ext_new_windows_topmost:{message:"Keep Hangouts on top of other windows"},quasar_label_tray_icon:{message:"Show system tray icon"},quasar_legend_notifications:{message:"Notifications"},quasar_label_all_notification:{message:"Disable notifications"},quasar_label_chat_notification:{message:"Disable chat notifications"},quasar_label_toast_timeout_chat:{message:"Allow chat notifications to timeout automatically"},quasar_label_toast_duration_chat:{message:"Timeout length (in seconds):"},
quasar_button_save:{message:"Ok"},quasar_button_apply:{message:"Apply"},quasar_button_cancel:{message:"Cancel"},chrome_ext_menutext_feedback:{message:"Send feedback"},quasar_feedback_server_uri:{message:"https://www.google.com/tools/feedback"},chrome_ext_feedback_subtitle:{message:"Send feedback"},chrome_ext_feedback_comments:{message:"Comments"},quasar_feedback_system_legend:{message:"System Information"},quasar_feedback_platform_label:{message:"Platform:"},quasar_feedback_user_agent_label:{message:"User Agent:"},
quasar_feedback_privacy_legend:{message:"Privacy Statement"},quasar_feedback_privacy_text:{message:"The description, product information, additional information and your email address will be sent to Google. See the Google Feedback Terms of Service. By submitting this content you are granting to Google the right to use it to improve our products and services. See our Privacy Policy."},quasar_feedback_submit_button:{message:"Send Feedback"},quasar_feedback_cancel_button:{message:"Cancel"},quasar_video_title:{message:"Video call from $1...",
placeholders:{1:{content:"$1"}}},quasar_voice_title:{message:"Voice call from $1...",placeholders:{1:{content:"$1"}}},quasar_group_chat_title:{message:"From group chat..."},quasar_chat_title:{message:"$1 says...",placeholders:{1:{content:"$1"}}},quasar_hangout_title:{message:"$1 is hanging out",placeholders:{1:{content:"$1"}}},chrome_ext_oneonone_plus_hangout_details:{message:"is video calling you via Hangouts"},chrome_ext_group_plus_hangout_details:{message:"has invited you to a group Hangout video call"},
quasar_video_details:{message:"is calling you with video chat"},quasar_voice_details:{message:"is calling you"},quasar_tip_connected:{message:"Status: Connected"},chrome_ext_tip_connected_missed_messages:{message:"Status: Connected\nMissed messages"},quasar_tip_connecting:{message:"Status: Connecting"},quasar_tip_reconnecting:{message:"Status: Reconnecting"},quasar_tip_disconnected:{message:"Status: Disconnected"},quasar_tip_not_login:{message:"Status: Not logged in"},quasar_tip_not_load:{message:"Status: Loading error"},
chrome_ext_menutext_unsigned_user:{message:"Not signed in"},quasar_menutext_unknown_user:{message:"Unknown"},quasar_menutext_feedback:{message:"Feedback"},quasar_menutext_settings:{message:"Options"},quasar_menutext_quit:{message:"Exit"},quasar_menutext_signout:{message:"Sign out"},chrome_ext_cannot_connect:{message:"Unable to connect to Google. Please check your internet connection."},quasar_try_now:{message:"Try now"},quasar_sign_in_to_start_talking:{message:"Sign in to start talking with friends"}, quasar_sign_in:{message:"Sign in"}};

}catch(e){_DumpException(e)}
try{
var p=function(a){return void 0!==a},ca=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},da=function(a,b,c){return a.call.apply(a.bind,arguments)},fa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);
if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},q=function(a,b){function c(){}c.prototype=b.prototype;
a.q=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Jd=function(a,c,f){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}},ga=function(a,b){var c=a.split("."),d=k;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&p(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}},r=function(a,b,c){r=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?da:ca;return r.apply(null,arguments)},ha=function(a){var b=typeof a;
return"object"==b&&null!=a||"function"==b},s=function(a){return"function"==fa(a)},ia=function(a){return"number"==typeof a},t=function(a){return"string"==typeof a},ja=function(a){var b=fa(a);return"array"==b||"object"==b&&"number"==typeof a.length},u=function(a){return"array"==fa(a)},ka=function(){},ma=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,ma);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};q(ma,Error);ma.prototype.name="CustomError";
var oa=function(a,b){for(var c=0,d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=String(b).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=Math.max(d.length,e.length),h=0;0==c&&h<f;h++){var l=d[h]||"",n=e[h]||"",B=RegExp("(\\d*)(\\D*)","g"),K=RegExp("(\\d*)(\\D*)","g");do{var X=B.exec(l)||["","",""],R=K.exec(n)||["","",""];if(0==X[0].length&&0==R[0].length)break;c=na(0==X[1].length?0:parseInt(X[1],10),0==R[1].length?0:parseInt(R[1],10))||na(0==X[2].length,0==R[2].length)||na(X[2], R[2])}while(0==c)}return c},na=function(a,b){return a<b?-1:a>b?1:0};
var v=Array.prototype,pa=v.indexOf?function(a,b,c){return v.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(t(a))return t(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},qa=v.lastIndexOf?function(a,b,c){return v.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(t(a))return t(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;
return-1},w=v.forEach?function(a,b,c){v.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},ra=v.filter?function(a,b,c){return v.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,h=t(a)?a.split(""):a,l=0;l<d;l++)if(l in h){var n=h[l];b.call(c,n,l,a)&&(e[f++]=n)}return e},sa=v.map?function(a,b,c){return v.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=t(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,
f[h],h,a));return e},ta=v.reduce?function(a,b,c,d){d&&(b=r(b,d));return v.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;w(a,function(c,h){e=b.call(d,e,c,h,a)});return e},ua=v.some?function(a,b,c){return v.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1},va=function(a,b){var c=pa(a,b),d;(d=0<=c)&&v.splice.call(a,c,1);return d};
var wa=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;var xa=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},ya=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},za=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};var x=function(){},y=function(a,b,c,d){a.a={};b||(b=c?[c]:[]);a.n=c?String(c):void 0;a.b=0===c?-1:0;a.G=b;t:{if(a.G.length&&(b=a.G.length-1,(c=a.G[b])&&"object"==typeof c&&"number"!=typeof c.length)){a.e=b-a.b;a.c=c;break t}a.e=Number.MAX_VALUE}if(d)for(b=0;b<d.length;b++)c=d[b],c<a.e?(c+=a.b,a.G[c]=a.G[c]||[]):a.c[c]=a.c[c]||[]},z=function(a,b){return b<a.e?a.G[b+a.b]:a.c[b]};x.prototype.toString=function(){return this.G.toString()};var A=function(a,b){Aa[a]=b;b.messageId=a},Aa={};
var Ba="StopIteration"in k?k.StopIteration:Error("f"),Ca=function(){};Ca.prototype.next=function(){throw Ba;};Ca.prototype.ha=function(){return this};var Da;t:{var Ea=k.navigator;if(Ea){var Fa=Ea.userAgent;if(Fa){Da=Fa;break t}}Da=""}var Ga=function(a){return-1!=Da.indexOf(a)};var C=function(a,b){this.a={};this.b=[];this.e=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("h");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof C?(c=a.M(),d=a.A()):(c=za(a),d=ya(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};g=C.prototype;g.V=function(){return this.c};g.A=function(){Ha(this);for(var a=[],b=0;b<this.b.length;b++)a.push(this.a[this.b[b]]);return a};g.M=function(){Ha(this);return this.b.concat()};g.P=function(){return 0==this.c};
g.clear=function(){this.a={};this.e=this.c=this.b.length=0};g.remove=function(a){return Ia(this.a,a)?(delete this.a[a],this.c--,this.e++,this.b.length>2*this.c&&Ha(this),!0):!1};var Ha=function(a){if(a.c!=a.b.length){for(var b=0,c=0;b<a.b.length;){var d=a.b[b];Ia(a.a,d)&&(a.b[c++]=d);b++}a.b.length=c}if(a.c!=a.b.length){for(var e={},c=b=0;b<a.b.length;)d=a.b[b],Ia(e,d)||(a.b[c++]=d,e[d]=1),b++;a.b.length=c}};g=C.prototype;g.get=function(a,b){return Ia(this.a,a)?this.a[a]:b};
g.set=function(a,b){Ia(this.a,a)||(this.c++,this.b.push(a),this.e++);this.a[a]=b};g.forEach=function(a,b){for(var c=this.M(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};g.clone=function(){return new C(this)};g.ha=function(a){Ha(this);var b=0,c=this.b,d=this.a,e=this.e,f=this,h=new Ca;h.next=function(){for(;;){if(e!=f.e)throw Error("i");if(b>=c.length)throw Ba;var h=c[b++];return a?h:d[h]}};return h};var Ia=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
var Ja=function(a){if("function"==typeof a.A)return a.A();if(t(a))return a.split("");if(ja(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return ya(a)},Ka=function(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(ja(a)||t(a))w(a,b,c);else{var d;if("function"==typeof a.M)d=a.M();else if("function"!=typeof a.A)if(ja(a)||t(a)){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else d=za(a);else d=void 0;for(var e=Ja(a),f=e.length,h=0;h<f;h++)b.call(c,e[h],d&&d[h],a)}};
var La=Ga("Opera")||Ga("OPR"),D=Ga("Trident")||Ga("MSIE"),Ma=Ga("Gecko")&&-1==Da.toLowerCase().indexOf("webkit")&&!(Ga("Trident")||Ga("MSIE")),Na=-1!=Da.toLowerCase().indexOf("webkit"),Oa=k.navigator||null,Pa=Oa&&Oa.platform||"",Qa=function(){var a=k.document;return a?a.documentMode:void 0},Ra=function(){var a="",b;if(La&&k.opera)return a=k.opera.version,s(a)?a():a;Ma?b=/rv\:([^\);]+)(\)|;)/:D?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:Na&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(Da))?a[1]:"");return D&&(b= Qa(),b>parseFloat(a))?String(b):a}(),Sa={},Ta=function(a){return Sa[a]||(Sa[a]=0<=oa(Ra,a))},Ua=k.document,Va=Ua&&D?Qa()||("CSS1Compat"==Ua.compatMode?parseInt(Ra,10):5):void 0;
var E=function(){};E.prototype.D=!1;E.prototype.Eb=function(){return this.D};E.prototype.B=function(){this.D||(this.D=!0,this.l())};E.prototype.l=function(){if(this.t)for(;this.t.length;)this.t.shift()()};var F=function(a){a&&"function"==typeof a.B&&a.B()};
var Wa=!D||D&&9<=Va;!Ma&&!D||D&&D&&9<=Va||Ma&&Ta("1.9.1");D&&Ta("9");var Xa=function(a){Xa[" "](a);return a};Xa[" "]=ka;var Ya=function(a,b){try{return Xa(a[b]),!0}catch(c){}return!1};var Za=!D||D&&9<=Va,$a=D&&!Ta("9");!Na||Ta("528");Ma&&Ta("1.9b")||D&&Ta("8")||La&&Ta("9.5")||Na&&Ta("528");Ma&&!Ta("8")||D&&Ta("9");var G=function(a,b){this.type=a;this.a=this.target=b;this.wc=!0};G.prototype.B=function(){};G.prototype.b=function(){this.wc=!1};var ab=function(a,b){G.call(this,a?a.type:"");this.a=this.target=null;this.clientY=this.clientX=0;this.c=this.state=null;if(a){this.type=a.type;this.target=a.target||a.srcElement;this.a=b;var c=a.relatedTarget;c&&Ma&&Ya(c,"nodeName");this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:a.pageY;this.state=a.state;this.c=a;a.defaultPrevented&&this.b()}};q(ab,G); ab.prototype.b=function(){ab.q.b.call(this);var a=this.c;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,$a)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var bb="closure_listenable_"+(1E6*Math.random()|0),cb=function(a){return!(!a||!a[bb])},db=0;var eb=function(a,b,c,d,e){this.qa=a;this.proxy=null;this.src=b;this.type=c;this.Ya=!!d;this.fb=e;this.key=++db;this.removed=this.Xa=!1},fb=function(a){a.removed=!0;a.qa=null;a.proxy=null;a.src=null;a.fb=null};var gb=function(a){this.src=a;this.a={};this.b=0};gb.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var h=hb(a,b,d,e);-1<h?(b=a[h],c||(b.Xa=!1)):(b=new eb(b,this.src,f,!!d,e),b.Xa=c,a.push(b));return b};gb.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=hb(e,b,c,d);return-1<b?(fb(e[b]),v.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var ib=function(a,b){var c=b.type;if(!(c in a.a))return!1;var d=va(a.a[c],b);d&&(fb(b),0==a.a[c].length&&(delete a.a[c],a.b--));return d};gb.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,fb(d[e]);delete this.a[c];this.b--}return b}; var jb=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=hb(a,c,d,e));return-1<b?a[b]:null},hb=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.qa==b&&f.Ya==!!c&&f.fb==d)return e}return-1};
var kb="closure_lm_"+(1E6*Math.random()|0),lb={},mb=0,nb=function(a,b,c,d,e){if(u(b)){for(var f=0;f<b.length;f++)nb(a,b[f],c,d,e);return null}c=ob(c);return cb(a)?a.listen(b,c,d,e):pb(a,b,c,!1,d,e)},pb=function(a,b,c,d,e,f){if(!b)throw Error("l");var h=!!e,l=qb(a);l||(a[kb]=l=new gb(a));c=l.add(b,c,d,e,f);if(c.proxy)return c;d=rb();c.proxy=d;d.src=a;d.qa=c;a.addEventListener?a.addEventListener(b.toString(),d,h):a.attachEvent(sb(b.toString()),d);mb++;return c},rb=function(){var a=tb,b=Za?function(c){return a.call(b.src,
b.qa,c)}:function(c){c=a.call(b.src,b.qa,c);if(!c)return c};return b},ub=function(a,b,c,d,e){if(u(b))for(var f=0;f<b.length;f++)ub(a,b[f],c,d,e);else c=ob(c),cb(a)?a.Mb(b,c,d,e):a&&(a=qb(a))&&(b=jb(a,b,c,!!d,e))&&vb(b)},vb=function(a){if(ia(a)||!a||a.removed)return!1;var b=a.src;if(cb(b))return ib(b.U,a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.Ya):b.detachEvent&&b.detachEvent(sb(c),d);mb--;(c=qb(b))?(ib(c,a),0==c.b&&(c.src=null,b[kb]=null)):fb(a);return!0},sb=function(a){return a in
lb?lb[a]:lb[a]="on"+a},xb=function(a,b,c,d){var e=1;if(a=qb(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.Ya==c&&!f.removed&&(e&=!1!==wb(f,d))}return Boolean(e)},wb=function(a,b){var c=a.qa,d=a.fb||a.src;a.Xa&&vb(a);return c.call(d,b)},tb=function(a,b){if(a.removed)return!0;if(!Za){var c;if(!(c=b))t:{c=["window","event"];for(var d=k,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break t}c=d}e=c;c=new ab(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){t:{var f=
!1;if(0==e.keyCode)try{e.keyCode=-1;break t}catch(h){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.a;f;f=f.parentNode)e.push(f);for(var f=a.type,l=e.length-1;0<=l;l--)c.a=e[l],d&=xb(e[l],f,!0,c);for(l=0;l<e.length;l++)c.a=e[l],d&=xb(e[l],f,!1,c)}return d}return wb(a,new ab(b,this))},qb=function(a){a=a[kb];return a instanceof gb?a:null},yb="__closure_events_fn_"+(1E9*Math.random()>>>0),ob=function(a){if(s(a))return a;a[yb]||(a[yb]=function(b){return a.handleEvent(b)});return a[yb]};
var zb=function(a){y(this,a,"h_cc",[])};q(zb,x);A("h_cc",zb);zb.prototype.Y=function(){return z(this,19)};var H=function(a){this.J=a;this.g={}};q(H,E);var Ab=[];H.prototype.listen=function(a,b,c,d){return Bb(this,a,b,c,d)};var Bb=function(a,b,c,d,e,f){u(c)||(c&&(Ab[0]=c.toString()),c=Ab);for(var h=0;h<c.length;h++){var l=nb(b,c[h],d||a.handleEvent,e||!1,f||a.J||a);if(!l)break;a.g[l.key]=l}return a};
H.prototype.Mb=function(a,b,c,d,e){if(u(b))for(var f=0;f<b.length;f++)this.Mb(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.J||this,c=ob(c),d=!!d,b=cb(a)?jb(a.U,String(b),c,d,e):a?(a=qb(a))?jb(a,b,c,d,e):null:null,b&&(vb(b),delete this.g[b.key]);return this};H.prototype.removeAll=function(){xa(this.g,vb);this.g={}};H.prototype.l=function(){H.q.l.call(this);this.removeAll()};H.prototype.handleEvent=function(){throw Error("m");};
var I=function(){this.U=new gb(this);this.L=this;this.u=null};q(I,E);I.prototype[bb]=!0;g=I.prototype;g.addEventListener=function(a,b,c,d){nb(this,a,b,c,d)};g.removeEventListener=function(a,b,c,d){ub(this,a,b,c,d)};g.l=function(){I.q.l.call(this);this.U&&this.U.removeAll(void 0);this.u=null};g.listen=function(a,b,c,d){return this.U.add(String(a),b,!1,c,d)};g.Mb=function(a,b,c,d){return this.U.remove(String(a),b,c,d)}; g.da=function(a,b,c){a=this.U.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.Ya==b){var h=f.qa,l=f.fb||f.src;f.Xa&&ib(this.U,f);d=!1!==h.call(l,c)&&d}}return d&&0!=c.wc};
var Cb,Db,Eb,Fb,Gb,Hb,Ib;Ib=Hb=Gb=Fb=Eb=Db=Cb=!1;var Jb=Da;Jb&&(-1!=Jb.indexOf("Firefox")?Cb=!0:-1!=Jb.indexOf("Camino")?Db=!0:-1!=Jb.indexOf("iPhone")||-1!=Jb.indexOf("iPod")?Eb=!0:-1!=Jb.indexOf("iPad")?Fb=!0:-1!=Jb.indexOf("Chrome")?Hb=!0:-1!=Jb.indexOf("Android")?Gb=!0:-1!=Jb.indexOf("Safari")&&(Ib=!0));var Kb=Cb,Lb=Db,Ob=Eb,Pb=Fb,Qb=Gb,Rb=Hb,Sb=Ib;
var J=function(a){this.a=a};J.prototype.toString=function(){return this.a};var Tb=new J("fJuxOc"),Ub=new J("ZtVrH"),Vb=new J("zZa4xc"),Wb=new J("pVbxBc"),Xb=new J("byfTOb"),Yb=new J("LEikZe"),Zb=new J("rJmJrc");var $b=new J("a");var ac=function(a,b){for(var c=[],d=0;d<arguments.length;d++)c.push(arguments[d]||"");return c.join("_;_")},bc=function(){return 0<=navigator.userAgent.indexOf("CrOS")};var cc=function(a,b){this.e=a||"e";this.c=null!=a&&"p"==a?"e":"p";this.a=this.f=null;this.h=b||"u";this.b=this.t=null;this.g=[]};cc.prototype.message=function(){var a={};a.i=this.b;a.m=this.g;a.r=this.h;a.o=this.t;a.s=this.a;a.st=this.c;a.d=this.f;a.dt=this.e;return a};ga("ace.base.Message.prototype.message",cc.prototype.message);
var dc=function(a,b){for(var c in b)switch(c){case "r":a.h=b[c];break;case "i":a.b=b[c];break;case "m":a.g=b[c];break;case "o":a.t=b[c];break;case "s":a.a=b[c];break;case "d":a.f=b[c];break;case "st":a.c=b[c];break;case "dt":a.e=b[c]}return a},ec=function(a,b,c){null!=b&&(a.a=b,null!=c&&(a.c=c))},fc=function(a,b){null!=b&&(a.b=b)},gc=function(a,b){"object"==typeof b?a.g=b:a.g=[b]};cc.prototype.target=function(){return this.f};cc.prototype.content=function(){return this.g};
var hc=function(a,b,c,d,e){this.b=a;this.Ta=b;this.a=typeof b;this.Hb=c?c:!1;this.ba=!0;this.Cb=d?d:!1;this.vb=e?e:!1};q(hc,E);g=hc.prototype;g.l=function(){hc.q.l.call(this);this.b="";this.Ta=null;this.a=""};g.id=function(){return this.b};g.type=function(){return this.a};g.F=function(){return this.Ta};g.setEnabled=function(a){this.ba=a};
var ic=function(a){return(a=a.exec(Da))?a[1]:""},jc=function(){if(Kb)return ic(/Firefox\/([0-9.]+)/);if(D||La)return Ra;if(Rb)return ic(/Chrome\/([0-9.]+)/);if(Sb)return ic(/Version\/([0-9.]+)/);if(Ob||Pb){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(Da))return a[1]+"."+a[2]}else{if(Qb)return(a=ic(/Android\s+([0-9.]+)/))?a:ic(/Version\/([0-9.]+)/);if(Lb)return ic(/Camino\/([0-9.]+)/)}return""}();
var lc=function(a){this.a=new C;this.b=["https://talkgadget.google.com/talkgadget/notifier-js","","https://test.talkgadget.google.com/talkgadget/notifier-js?jsmode=debug_unobfuscated"];a&&kc(this,a)};q(lc,E);var mc=0<=oa(jc,"23.0.1262.0")&&!bc();lc.prototype.l=function(){lc.q.l.call(this);for(var a=this.a.M(),b=0;b<a.length;++b)F(this.a.get(a[b]));delete this.a};lc.prototype.getItem=function(a){return Ia(this.a.a,a)?this.a.get(a):null};lc.prototype.setItem=function(a){this.a.set(a.id(),a)}; var kc=function(a,b){for(var c in b){var d=b[c],e=null;Ia(a.a.a,c)?(e=a.a.get(c),e.Ta=d.value,d.changed&&(e.vb=d.changed)):(e=new hc(c,d.value,d.multiple,d.inverse,d.changed),e.setEnabled(!d.disabled));a.a.set(c,e)}};
var nc=function(a){k.setTimeout(function(){throw a;},0)},qc=function(a,b){var c=a;b&&(c=r(a,b));s(k.setImmediate)?k.setImmediate(c):(oc||(oc=pc()),oc(c))},oc,pc=function(){var a=k.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&(a=function(){var a=document.createElement("iframe");a.style.display="none";a.src="";document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+
Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=r(function(a){if(a.origin==d||a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a){var b=new a,c={},d=c;b.port1.onmessage=function(){c=c.next;var a=c.Yb;c.Yb=null;a()};return function(a){d.next={Yb:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in
document.createElement("script")?function(a){var b=document.createElement("script");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};document.documentElement.appendChild(b)}:function(a){k.setTimeout(a,0)}};
var wc=function(a,b){rc||sc();tc||(rc(),tc=!0);uc.push(new vc(a,b))},rc,sc=function(){if(k.Promise&&k.Promise.resolve){var a=k.Promise.resolve();rc=function(){a.then(xc)}}else rc=function(){qc(xc)}},tc=!1,uc=[],xc=function(){for(;uc.length;){var a=uc;uc=[];for(var b=0;b<a.length;b++){var c=a[b];try{c.a.call(c.b)}catch(d){nc(d)}}}tc=!1},vc=function(a,b){this.a=a;this.b=b};
var yc=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},zc=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var Bc=function(a,b){this.b=0;this.g=void 0;this.a=this.c=null;this.e=this.f=!1;try{var c=this;a.call(b,function(a){Ac(c,2,a)},function(a){Ac(c,3,a)})}catch(d){Ac(this,3,d)}},Dc=function(){var a,b=new Bc(function(b){a=b});return new Cc(b,a)};Bc.prototype.then=function(a,b,c){return Ec(this,s(a)?a:null,s(b)?b:null,c)};yc(Bc);
var Hc=function(a){0==a.b&&wc(function(){var a=new Fc(void 0);Gc(this,a)},a)},Gc=function(a,b){if(0==a.b)if(a.c){var c=a.c;if(c.a){for(var d=0,e=-1,f=0,h;h=c.a[f];f++)if(h=h.Za)if(d++,h==a&&(e=f),0<=e&&1<d)break;0<=e&&(0==c.b&&1==d?Gc(c,b):(d=c.a.splice(e,1)[0],Ic(c,d,3,b)))}}else Ac(a,3,b)},Kc=function(a,b){a.a&&a.a.length||2!=a.b&&3!=a.b||Jc(a);a.a||(a.a=[]);a.a.push(b)},Ec=function(a,b,c,d){var e={Za:null,qc:null,sc:null};e.Za=new Bc(function(a,h){e.qc=b?function(c){try{var e=b.call(d,c);a(e)}catch(B){h(B)}}:
a;e.sc=c?function(b){try{var e=c.call(d,b);!p(e)&&b instanceof Fc?h(b):a(e)}catch(B){h(B)}}:h});e.Za.c=a;Kc(a,e);return e.Za};Bc.prototype.t=function(a){this.b=0;Ac(this,2,a)};Bc.prototype.h=function(a){this.b=0;Ac(this,3,a)};
var Ac=function(a,b,c){if(0==a.b){if(a==c)b=3,c=new TypeError("Promise cannot resolve to itself");else{if(zc(c)){a.b=1;c.then(a.t,a.h,a);return}if(ha(c))try{var d=c.then;if(s(d)){Lc(a,c,d);return}}catch(e){b=3,c=e}}a.g=c;a.b=b;Jc(a);3!=b||c instanceof Fc||Mc(a,c)}},Lc=function(a,b,c){a.b=1;var d=!1,e=function(b){d||(d=!0,a.t(b))},f=function(b){d||(d=!0,a.h(b))};try{c.call(b,e,f)}catch(h){f(h)}},Jc=function(a){a.f||(a.f=!0,wc(a.j,a))};
Bc.prototype.j=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=[];for(var b=0;b<a.length;b++)Ic(this,a[b],this.b,this.g)}this.f=!1};var Ic=function(a,b,c,d){if(2==c)b.qc(d);else{for(;a&&a.e;a=a.c)a.e=!1;b.sc(d)}},Mc=function(a,b){a.e=!0;wc(function(){a.e&&Nc.call(null,b)})},Nc=nc,Fc=function(a){ma.call(this,a)};q(Fc,ma);Fc.prototype.name="cancel";var Cc=function(a,b){this.b=a;this.a=b};
var Qc=function(){this.c=new C;this.a=null;this.b=!1;this.a=new Oc;this.b=!0;Pc(this)};Qc.va=function(){return Qc.a?Qc.a:Qc.a=new Qc};var Pc=function(a,b){var c=b||ka;a.b?c():chrome.storage.local.get(r(function(a){if(!this.b){for(var b in a)this.c.set(b,a[b]);this.b=!0}c()},a))};Qc.prototype.get=function(a){return this.a.get(a)};Qc.prototype.set=function(a,b){var c=Dc();this.a.set(a,b);c.a(void 0);return c.b};Qc.prototype.remove=function(a){this.a.remove(a)};Qc.prototype.clear=function(){this.a.clear()};
var Oc=function(){this.a=window.localStorage};Oc.prototype.clear=function(){this.a.clear()};Oc.prototype.get=function(a){a=this.a.getItem(a);if(a){var b=JSON.parse(a);a=b.data;if("jspb"==b.type){b=Aa[a[0]];if(!b)throw Error("e`"+a[0]);a=new b(a)}}else a=null;return a};Oc.prototype.set=function(a,b){var c=null;b instanceof x&&(b=b.G,c="jspb");var d={};d.data=b;d.timestamp=m();c&&(d.type=c);c=JSON.stringify(d);try{this.a.setItem(a,c)}catch(e){}};Oc.prototype.remove=function(a){try{this.a.removeItem(a)}catch(b){}};
var Rc=function(a,b){this.b=a;this.a=b;this.constructor.Wb||(this.constructor.Wb={});this.constructor.Wb[this.toString()]=this};Rc.prototype.toString=function(){this.c||(this.c=this.b.a+":"+this.a);return this.c};var L=function(a,b){Rc.call(this,a,b)};q(L,Rc);var Sc=function(a){this.a=a},Tc=new Sc("lib");/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
var Uc=function(a,b){this.e=[];this.u=b||null;this.b=this.a=!1;this.c=void 0;this.k=this.n=this.g=!1;this.f=0;this.h=null;this.p=0};Uc.prototype.j=function(a,b){this.g=!1;Vc(this,a,b)};var Vc=function(a,b,c){a.a=!0;a.c=c;a.b=!b;Wc(a)},Yc=function(a){if(a.a){if(!a.k)throw new Xc;a.k=!1}};Uc.prototype.t=function(a){Yc(this);Vc(this,!0,a)};var Zc=function(a,b,c,d){a.e.push([b,c,d]);a.a&&Wc(a)};
Uc.prototype.then=function(a,b,c){var d,e,f=new Bc(function(a,b){d=a;e=b});Zc(this,d,function(a){"undefined"!=typeof $c&&a instanceof $c?Hc(f):e(a)});return f.then(a,b,c)};yc(Uc);
var ad=function(a){return ua(a.e,function(a){return s(a[1])})},Wc=function(a){if(a.f&&a.a&&ad(a)){var b=a.f,c=bd[b];c&&(k.clearTimeout(c.ab),delete bd[b]);a.f=0}a.h&&(a.h.p--,delete a.h);for(var b=a.c,d=c=!1;a.e.length&&!a.g;){var e=a.e.shift(),f=e[0],h=e[1],e=e[2];if(f=a.b?h:f)try{var l=f.call(e||a.u,b);p(l)&&(a.b=a.b&&(l==b||l instanceof Error),a.c=b=l);zc(b)&&(d=!0,a.g=!0)}catch(n){b=n,a.b=!0,ad(a)||(c=!0)}}a.c=b;d&&(l=r(a.j,a,!0),d=r(a.j,a,!1),b instanceof Uc?(Zc(b,l,d),b.n=!0):b.then(l,d));c&&
(b=new cd(b),bd[b.ab]=b,a.f=b.ab)},Xc=function(){ma.call(this)};q(Xc,ma);Xc.prototype.message="Deferred has already fired";Xc.prototype.name="AlreadyCalledError";var cd=function(a){this.ab=k.setTimeout(r(this.b,this),0);this.a=a};cd.prototype.b=function(){delete bd[this.ab];throw this.a;};var bd={};

}catch(e){_DumpException(e)}
try{
var ld={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},md=function(a,b){b.push('"',a.replace(wa,function(a){if(a in ld)return ld[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return ld[a]=e+b.toString(16)}),'"')},nd="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),od=function(a,b,c){switch(typeof b){case "string":md(b,c);break;case "number":c.push(isFinite(b)&&
!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if(u(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),od(a,b[f],c),e=",";c.push("]");break}c.push("{");d="";for(e in b)Object.prototype.hasOwnProperty.call(b,e)&&(f=b[e],"function"!=typeof f&&(c.push(d),md(e,c),c.push(":"),od(a,f,c),d=","));c.push("}");break;case "function":break;default:throw Error("d`"+typeof b);}},pd=function(){},qd=function(a,
b,c,d,e){if(u(b)){for(var f=0;f<b.length;f++)qd(a,b[f],c,d,e);return null}c=ob(c);return cb(a)?a.U.add(String(b),c,!0,d,e):pb(a,b,c,!0,d,e)},rd=Na,sd=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,td=function(a,b){a.t||(a.t=[]);a.t.push(p(void 0)?r(b,void 0):b)},M=function(a,b,c){b<a.e?a.G[b+a.b]=c:a.c[b]=c},ud=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<nd.length;f++)c=nd[f],
Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}},vd=function(a){var b=[];od(new pd,a,b);return b.join("")},wd=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}},xd=function(a,b,c){null!=b&&(a.f=b,null!=c&&(a.e=c))},N=function(a,b){var c,d=a.u;if(d)for(c=[];d;d=d.u)c.push(d);var d=a.L,e=b,f=e.type||e;if(t(e))e=new G(e,d);else if(e instanceof G)e.target=e.target||d;else{var h=e,e=new G(f,d);ud(e,h)}var h=
!0,l;if(c)for(var n=c.length-1;0<=n;n--)l=e.a=c[n],h=l.da(f,!0,e)&&h;l=e.a=d;h=l.da(f,!0,e)&&h;h=l.da(f,!1,e)&&h;if(c)for(n=0;n<c.length;n++)l=e.a=c[n],h=l.da(f,!1,e)&&h},yd=function(a,b,c,d,e,f){if(u(c))for(var h=0;h<c.length;h++)yd(a,b,c[h],d,e,f);else{b=qd(b,c,d||a.handleEvent,e,f||a.J||a);if(!b)return a;a.g[b.key]=b}return a},zd=function(a){if(rd){rd=!1;var b=k.location;if(b){var c=b.href;if(c&&(c=(c=zd(c)[3]||null)&&decodeURIComponent(c))&&c!=b.hostname)throw rd=!0,Error();}}return a.match(sd)},
O=function(a,b){td(a,wd(F,b))},Ad=function(a,b,c){var d=c?c.G:c;a.a[b]=c;M(a,b,d)},Bd=function(a,b,c){if(!a.a[c]){var d=z(a,c);d&&(a.a[c]=new b(d))}return a.a[c]},Cd=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Dd=function(a,b){return a?b?decodeURI(a):decodeURIComponent(a):""},Ed=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},Fd=function(a){return v.concat.apply(v,arguments)},Hd=function(a,b,c){this.a=a||null;this.b=
!!c},Jd=function(a){if(!a.H&&(a.H=new C,a.O=0,a.a))for(var b=a.a.split("&"),c=0;c<b.length;c++){var d=b[c].indexOf("="),e=null,f=null;0<=d?(e=b[c].substring(0,d),f=b[c].substring(d+1)):e=b[c];e=decodeURIComponent(e.replace(/\+/g," "));e=Id(a,e);a.add(e,f?decodeURIComponent(f.replace(/\+/g," ")):"")}};g=Hd.prototype;g.H=null;g.O=null;g.V=function(){Jd(this);return this.O};g.add=function(a,b){Jd(this);this.a=null;a=Id(this,a);var c=this.H.get(a);c||this.H.set(a,c=[]);c.push(b);this.O++;return this};
g.remove=function(a){Jd(this);a=Id(this,a);return Ia(this.H.a,a)?(this.a=null,this.O-=this.H.get(a).length,this.H.remove(a)):!1};g.clear=function(){this.H=this.a=null;this.O=0};g.P=function(){Jd(this);return 0==this.O};var Kd=function(a,b){Jd(a);b=Id(a,b);return Ia(a.H.a,b)};Hd.prototype.M=function(){Jd(this);for(var a=this.H.A(),b=this.H.M(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};
Hd.prototype.A=function(a){Jd(this);var b=[];if(t(a))Kd(this,a)&&(b=Fd(b,this.H.get(Id(this,a))));else{a=this.H.A();for(var c=0;c<a.length;c++)b=Fd(b,a[c])}return b};Hd.prototype.set=function(a,b){Jd(this);this.a=null;a=Id(this,a);Kd(this,a)&&(this.O-=this.H.get(a).length);this.H.set(a,[b]);this.O++;return this};Hd.prototype.get=function(a,b){var c=a?this.A(a):[];return 0<c.length?String(c[0]):b};var Ld=function(a,b,c){a.remove(b);0<c.length&&(a.a=null,a.H.set(Id(a,b),Ed(c)),a.O+=c.length)};
Hd.prototype.toString=function(){if(this.a)return this.a;if(!this.H)return"";for(var a=[],b=this.H.M(),c=0;c<b.length;c++)for(var d=b[c],e=encodeURIComponent(String(d)),d=this.A(d),f=0;f<d.length;f++){var h=e;""!==d[f]&&(h+="="+encodeURIComponent(String(d[f])));a.push(h)}return this.a=a.join("&")};Hd.prototype.clone=function(){var a=new Hd;a.a=this.a;this.H&&(a.H=this.H.clone(),a.O=this.O);return a};
var Id=function(a,b){var c=String(b);a.b&&(c=c.toLowerCase());return c},Md=function(a,b){b&&!a.b&&(Jd(a),a.a=null,a.H.forEach(function(a,b){var e=b.toLowerCase();b!=e&&(this.remove(b),Ld(this,e,a))},a));a.b=b},Nd=/#/g,Od=/[\#\?@]/g,Pd=/[\#\?]/g,Qd=/[\#\?:]/g,Rd=/[#\/\?@]/g,Sd=function(a,b,c){return t(a)?(a=encodeURI(a).replace(b,Cd),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},Td=function(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^
m()).toString(36)},Ud=function(a,b){var c;"undefined"!=typeof Ud&&a instanceof Ud?(this.ma=p(b)?b:a.ma,Vd(this,a.fa),this.sa=a.sa,this.S=a.S,Wd(this,a.ea),this.N=a.N,Xd(this,a.a.clone()),this.la=a.la):a&&(c=zd(String(a)))?(this.ma=!!b,Vd(this,c[1]||"",!0),this.sa=Dd(c[2]||""),this.S=Dd(c[3]||"",!0),Wd(this,c[4]),this.N=Dd(c[5]||"",!0),Xd(this,c[6]||"",!0),this.la=Dd(c[7]||"")):(this.ma=!!b,this.a=new Hd(null,0,this.ma))};g=Ud.prototype;g.fa="";g.sa="";g.S="";g.ea=null;g.N="";g.la="";g.ma=!1;
g.toString=function(){var a=[],b=this.fa;b&&a.push(Sd(b,Rd,!0),":");if(b=this.S){a.push("//");var c=this.sa;c&&a.push(Sd(c,Rd,!0),"@");a.push(encodeURIComponent(String(b)).replace(/%25([0-9a-fA-F]{2})/g,"%$1"));b=this.ea;null!=b&&a.push(":",String(b))}if(b=this.N)this.S&&"/"!=b.charAt(0)&&a.push("/"),a.push(Sd(b,"/"==b.charAt(0)?Pd:Qd,!0));(b=this.a.toString())&&a.push("?",b);(b=this.la)&&a.push("#",Sd(b,Nd));return a.join("")};
var Yd=function(a,b){var c=a.clone(),d=!!b.fa;d?Vd(c,b.fa):d=!!b.sa;d?c.sa=b.sa:d=!!b.S;d?c.S=b.S:d=null!=b.ea;var e=b.N;if(d)Wd(c,b.ea);else if(d=!!b.N){if("/"!=e.charAt(0))if(a.S&&!a.N)e="/"+e;else{var f=c.N.lastIndexOf("/");-1!=f&&(e=c.N.substr(0,f+1)+e)}f=e;if(".."==f||"."==f)e="";else if(-1!=f.indexOf("./")||-1!=f.indexOf("/.")){for(var e=0==f.lastIndexOf("/",0),f=f.split("/"),h=[],l=0;l<f.length;){var n=f[l++];"."==n?e&&l==f.length&&h.push(""):".."==n?((1<h.length||1==h.length&&""!=h[0])&&h.pop(),
e&&l==f.length&&h.push("")):(h.push(n),e=!0)}e=h.join("/")}else e=f}d?c.N=e:d=""!==b.a.toString();d?Xd(c,Dd(b.a.toString())):d=!!b.la;d&&(c.la=b.la);return c};Ud.prototype.clone=function(){return new Ud(this)};
var Vd=function(a,b,c){a.fa=c?Dd(b,!0):b;a.fa&&(a.fa=a.fa.replace(/:$/,""))},Wd=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("j`"+b);a.ea=b}else a.ea=null},Xd=function(a,b,c){b instanceof Hd?(a.a=b,Md(a.a,a.ma)):(c||(b=Sd(b,Od)),a.a=new Hd(b,0,a.ma))},P=function(a,b,c){a.a.set(b,c)},Zd=function(a,b,c){u(c)||(c=[String(c)]);Ld(a.a,b,c)},$d=function(a,b){return a.a.get(b)},ae=function(a,b){return 0<=pa(a,b)},be=function(a,b,c){if(s(a))c&&(a=r(a,c));else if(a&&"function"==typeof a.handleEvent)a=
r(a.handleEvent,a);else throw Error("n");return 2147483647<b?-1:k.setTimeout(a,b||0)},ce=function(a){k.clearTimeout(a)},de=function(a){var b={},c;for(c in a)b[c]=a[c];return b},ee=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c],e;if(u(d)||(e=ja(d))&&Object.prototype.hasOwnProperty.call(d,"callee"))a.push.apply(a,d);else if(e)for(var f=a.length,h=d.length,l=0;l<h;l++)a[f+l]=d[l];else a.push(d)}},fe=function(a,b){var c;t:{c=a.length;for(var d=t(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){c=e;break t}c=-1}return 0>c?null:t(a)?a.charAt(c):a[c]};
var ge=function(){},je=function(a){var b=a.ia,c=function(a){c.q.constructor.call(this,a);var b=this.T.length;this.a=[];for(var d=0;d<b;++d)this.T[d].Ld||(this.a[d]=new this.T[d](a))};q(c,b);for(var d=[];a;){if(b=a.ia){b.T&&ee(d,b.T);var b=b.prototype,e;for(e in b)if(b.hasOwnProperty(e)&&s(b[e])&&b[e]!==a){var f=!!b[e].Tc,h=he(e,b,d,f);(f=ie(e,b,h,f))&&(c.prototype[e]=f)}}a=a.q&&a.q.constructor}c.prototype.T=d;return c},he=function(a,b,c,d){for(var e=[],f=0;f<c.length&&(c[f].prototype[a]===b[a]||(e.push(f),
!d));++f);return e},ie=function(a,b,c,d){var e;c.length?d?e=function(b){var d=this.a[c[0]];return d?d[a].apply(this.a[c[0]],arguments):this.T[c[0]].prototype[a].apply(this,arguments)}:b[a].Vc?e=function(b){var d;t:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var n=this.a[c[e]];if(n=n?n[a].apply(n,d):this.T[c[e]].prototype[a].apply(this,d)){d=n;break t}}d=!1}return d}:b[a].Uc?e=function(b){var d;t:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var n=
this.a[c[e]],n=n?n[a].apply(n,d):this.T[c[e]].prototype[a].apply(this,d);if(null!=n){d=n;break t}}d=void 0}return d}:b[a].oc?e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=0;e<c.length;++e){var n=this.a[c[e]];n?n[a].apply(n,d):this.T[c[e]].prototype[a].apply(this,d)}}:e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=[],n=0;n<c.length;++n){var B=this.a[c[n]];e.push(B?B[a].apply(B,d):this.T[c[n]].prototype[a].apply(this,d))}return e}:d||b[a].Vc||b[a].Uc||b[a].oc? e=null:e=ke;return e},ke=function(){return[]};ge.prototype.zb=function(a){if(this.a)for(var b=0;b<this.a.length;++b)if(this.a[b]instanceof a)return this.a[b];return null};
var me=function(a){if(!a.wb){var b;for(b=a.constructor;b&&!b.ia;)b=b.q&&b.q.constructor;b.ia.ac||(b.ia.ac=je(b));b=new b.ia.ac(a);a.wb=b;a.zb||(a.zb=le)}},le=function(a){return this.wb.zb(a)};var ne=function(){};ne.prototype.a=null;var pe=function(a){var b;(b=a.a)||(b={},oe(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b};var qe,re=function(){};q(re,ne);var se=function(a){return(a=oe(a))?new ActiveXObject(a):new XMLHttpRequest},oe=function(a){if(!a.b&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.b=d}catch(e){}}throw Error("t");}return a.b};qe=new re;
var te=function(a){I.call(this);this.C=new C;this.j=a||null;this.b=!1;this.h=this.a=null;this.p="";this.e=0;this.c=this.n=this.f=this.k=!1;this.v=0;this.g=null;this.J="";this.w=this.aa=!1};q(te,I);var ue=/^https?$/i,ve=["POST","PUT"],we=[];te.prototype.Q=function(){this.B();va(we,this)};
te.prototype.send=function(a,b,c,d){if(this.a)throw Error("u`"+this.p+"`"+a);b=b?b.toUpperCase():"GET";this.p=a;this.e=0;this.k=!1;this.b=!0;this.a=this.j?se(this.j):se(qe);this.h=this.j?pe(this.j):pe(qe);this.a.onreadystatechange=r(this.I,this);try{this.n=!0,this.a.open(b,String(a),!0),this.n=!1}catch(e){xe(this);return}a=c||"";var f=this.C.clone();d&&Ka(d,function(a,b){f.set(b,a)});d=fe(f.M(),ye);c=k.FormData&&a instanceof k.FormData;!ae(ve,b)||d||c||f.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");
f.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.J&&(this.a.responseType=this.J);"withCredentials"in this.a&&(this.a.withCredentials=this.aa);try{ze(this),0<this.v&&((this.w=Ae(this.a))?(this.a.timeout=this.v,this.a.ontimeout=r(this.K,this)):this.g=be(this.K,this.v,this)),this.f=!0,this.a.send(a),this.f=!1}catch(h){xe(this)}};var Ae=function(a){return D&&Ta(9)&&ia(a.timeout)&&p(a.ontimeout)},ye=function(a){return"content-type"==a.toLowerCase()};
te.prototype.K=function(){"undefined"!=typeof aa&&this.a&&(this.e=8,N(this,"timeout"),Be(this,8))};var xe=function(a){a.b=!1;a.a&&(a.c=!0,a.a.abort(),a.c=!1);a.e=5;Ce(a);De(a)},Ce=function(a){a.k||(a.k=!0,N(a,"complete"),N(a,"error"))},Be=function(a,b){a.a&&a.b&&(a.b=!1,a.c=!0,a.a.abort(),a.c=!1,a.e=b||7,N(a,"complete"),N(a,"abort"),De(a))};te.prototype.l=function(){this.a&&(this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1),De(this,!0));te.q.l.call(this)};
te.prototype.I=function(){this.D||(this.n||this.f||this.c?Ee(this):this.$())};te.prototype.$=function(){Ee(this)};
var Ee=function(a){if(a.b&&"undefined"!=typeof aa&&(!a.h[1]||4!=(a.a?a.a.readyState:0)||2!=Fe(a)))if(a.f&&4==(a.a?a.a.readyState:0))be(a.I,0,a);else if(N(a,"readystatechange"),4==(a.a?a.a.readyState:0)){a.b=!1;try{Ge(a)?(N(a,"complete"),N(a,"success")):(a.e=6,Ce(a))}finally{De(a)}}},De=function(a,b){if(a.a){ze(a);var c=a.a,d=a.h[0]?ka:null;a.a=null;a.h=null;b||N(a,"ready");try{c.onreadystatechange=d}catch(e){}}},ze=function(a){a.a&&a.w&&(a.a.ontimeout=null);ia(a.g)&&(ce(a.g),a.g=null)},Ge=function(a){var b=
Fe(a),c;t:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:c=!0;break t;default:c=!1}if(!c){if(b=0===b)a=zd(String(a.p))[1]||null,!a&&self.location&&(a=self.location.protocol,a=a.substr(0,a.length-1)),b=!ue.test(a?a.toLowerCase():"");c=b}return c},Fe=function(a){try{return 2<(a.a?a.a.readyState:0)?a.a.status:-1}catch(b){return-1}},He=function(a){try{return a.a?a.a.responseText:""}catch(b){return""}};
var Ie=function(a){y(this,a,"h_icr",[])};q(Ie,x);A("h_icr",Ie);var Je=function(a){y(this,a,"h_cs",[])};q(Je,x);A("h_cs",Je);var Ke=new J("HwdKC");
}catch(e){_DumpException(e)}
try{
var Og=function(a){for(var b=a.a.M(),c={},d=0;d<b.length;d++){var e=b[d],f=a.a.get(e);c[e]={value:f.F(),type:f.type(),multiple:f.Hb,disabled:!f.ba,inverse:f.Cb,changed:f.vb}}return c},Pg=function(a,b){return t(b)?a.getElementById(b):b},Q=function(a){return Pg(document,a)},S=function(a){var b;b=b||[];b.length||(b[0]="");var c=chrome.i18n.getMessage(a,b);if(c)return c;(c=(c=k.ace_i18n[a.toLowerCase()])?c.message:k.ace_i18n["MSG_"+a])&&(c=c.replace("$1",b[0]).replace("$2",b[1]).replace("$3",b[2]));return c};

}catch(e){_DumpException(e)}
try{
var Qg=function(a){return a.b[0]},Rg=function(a){return(a=a.a.get("TopMost"))&&a.ba?a.F():!0},Sg=function(){return!0},Tg={},Ug=0,Vg=function(a){a&&a!=chrome.windows.WINDOW_ID_NONE&&chrome.windows.update(a,{focused:!0})},Wg=function(a){if(Tg[a])return Tg[a];a=String(a);if(!Tg[a]){var b=/function ([^\(]+)/.exec(a);Tg[a]=b?b[1]:"[Anonymous]"}return Tg[a]},Xg=function(a){return a[ba]||(a[ba]=++Ug)},Yg=function(a){chrome.windows.getAll({populate:!0},function(b){for(var c=0;c<b.length;++c){var d=b[c].tabs;
if(null!=d)for(var e=0;e<d.length;++e)if(d[e].selected&&d[e].url==a){Vg(b[c].id);return}}})},Zg=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c},$g=function(){return null!=navigator.platform.match(/Mac.*/)},ah=function(){return!bc()&&null!=navigator.platform.match(/Linux.*/)},bh=function(a){this.a=a||k.document||document};bh.prototype.fc=function(){var a=this.a;return a.parentWindow||a.defaultView};
bh.prototype.contains=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};
var ch=function(a,b){var c=[];if(ae(b,a))c.push("[...circular reference...]");else if(a&&50>b.length){c.push(Wg(a)+"(");for(var d=a.arguments,e=0;d&&e<d.length;e++){0<e&&c.push(", ");var f;f=d[e];switch(typeof f){case "object":f=f?"object":"null";break;case "string":break;case "number":f=String(f);break;case "boolean":f=f?"true":"false";break;case "function":f=(f=Wg(f))?f:"[fn]";break;default:f=typeof f}40<f.length&&(f=f.substr(0,40)+"...");c.push(f)}b.push(a);c.push(")\n");try{c.push(ch(a.caller,
b))}catch(h){c.push("[exception trying to get caller]\n")}}else a?c.push("[...long stack...]"):c.push("[end]");return c.join("")},dh=function(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+Xg(a):b.substr(0,1)+a},eh=function(a){if(a instanceof Ca)return a;if("function"==typeof a.ha)return a.ha(!1);if(ja(a)){var b=0,c=new Ca;c.next=function(){for(;;){if(b>=a.length)throw Ba;if(b in a)return a[b++];b++}};return c}throw Error("g");},fh=function(a,b){return a>b?1:a<b?-1:0},gh=function(a,b){null!=
a&&(window.open(a,"winid_"+(new Date).getTime(),b),be(r(Yg,null,a),1E3))},hh=function(a,b){null!=a&&(b?a=chrome.runtime.getURL("images_3/"+a):0==a.indexOf("images_3/")&&(a=chrome.runtime.getURL(a)));return a},ih=function(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d};ih.prototype.clone=function(){return new ih(this.left,this.top,this.width,this.height)};
ih.prototype.contains=function(a){return"undefined"!=typeof ih&&a instanceof ih?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};ih.prototype.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
ih.prototype.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};var jh=[/^https?:\/\/.*.google.com(:[0-9]+)?\/talkgadget\/success/,/^https:\/\/accounts.google.com\/ServiceLogin/],kh=[1E4,12E4,144E5],lh=[200,2E3,3E5],T=function(a){return T.b(a)};T.b=function(a){return a+"_"};T.t=function(){throw Error("o");};
T.f=function(a){if(a&&a.constructor&&a.constructor.toString()===Object.toString()){var b={},c;for(c in a)a.hasOwnProperty(c)&&(b[T.b(c)]=a[c]);return b}throw Error("p");};T.c=!0;T.e=function(){};T.g=function(){return!0};var mh=function(a,b){I.call(this);this.c=a||1;this.b=b||k;this.f=r(this.h,this);this.g=m()};q(mh,I);mh.prototype.e=!1;mh.prototype.a=null;mh.prototype.setInterval=function(a){this.c=a;this.a&&this.e?(this.stop(),nh(this)):this.a&&this.stop()};
mh.prototype.h=function(){if(this.e){var a=m()-this.g;0<a&&a<.8*this.c?this.a=this.b.setTimeout(this.f,this.c-a):(this.a&&(this.b.clearTimeout(this.a),this.a=null),N(this,"tick"),this.e&&(this.a=this.b.setTimeout(this.f,this.c),this.g=m()))}};var nh=function(a){a.e=!0;a.a||(a.a=a.b.setTimeout(a.f,a.c),a.g=m())};mh.prototype.stop=function(){this.e=!1;this.a&&(this.b.clearTimeout(this.a),this.a=null)};mh.prototype.l=function(){mh.q.l.call(this);this.stop();delete this.b};
var oh=function(a,b){this.width=a;this.height=b};oh.prototype.clone=function(){return new oh(this.width,this.height)};oh.prototype.P=function(){return!(this.width*this.height)};oh.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};oh.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
var ph=function(a){var b;b||(b=ch(a||arguments.callee.caller,[]));return b},qh=function(a){this.a=new C;if(a){a=Ja(a);for(var b=a.length,c=0;c<b;c++)this.add(a[c])}};g=qh.prototype;g.V=function(){return this.a.V()};g.add=function(a){this.a.set(dh(a),a)};g.removeAll=function(a){a=Ja(a);for(var b=a.length,c=0;c<b;c++)this.remove(a[c])};g.remove=function(a){return this.a.remove(dh(a))};g.clear=function(){this.a.clear()};g.P=function(){return this.a.P()};
g.contains=function(a){a=dh(a);return Ia(this.a.a,a)};g.A=function(){return this.a.A()};g.clone=function(){return new qh(this)};g.ha=function(){return this.a.ha(!1)};
var rh=function(a,b){if(ja(a))try{w(a,b,void 0)}catch(c){if(c!==Ba)throw c;}else{a=eh(a);try{for(;;)b.call(void 0,a.next(),void 0,a)}catch(d){if(d!==Ba)throw d;}}},sh=function(a,b,c){c=c||[];for(var d=[],e=0;e<c.length;e++)d[e]=c[e].G;a.a[b]=c;M(a,b,d)},th=function(a,b,c){if(!a.a[c]){for(var d=z(a,c),e=[],f=0;f<d.length;f++)e[f]=new b(d[f]);a.a[c]=e}return a.a[c]},uh=function(a){var b=arguments.length;if(1==b&&u(arguments[0]))return uh.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]= !0;return c},vh=function(a,b){a.sort(b||fh)},wh=function(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=4294967296;return b};
var xh=function(a){y(this,a,"dpgi",[])};q(xh,x);A("dpgi",xh);var yh=function(a){y(this,a,"dri",[])};q(yh,x);A("dri",yh);var zh=function(a){y(this,a,"di",[6,7,10,11,12])};q(zh,x);A("di",zh);var Ah=function(a){y(this,a,"e",[])};q(Ah,x);A("e",Ah);var Bh=function(a){y(this,a,"f.ri",[])};q(Bh,x);A("f.ri",Bh);var Ch=function(){};q(Ch,E);
var Fh=function(a,b){var c=Dh;if(!(c.D||"undefined"!=typeof $c&&b instanceof $c))if(c.b){var c=c.b,d=Eh();d["call-stack"]=ph();a&&(d.message=a);var e;b instanceof Error?e=b:e=b||"";var f,h="";e&&(h=(e.lineNumber||"unknown")+":"+wh(e.fileName||"unknown")+":"+wh(e.message||"unknown"));var l="";for(f in d){var n;n="call-stack"==f?d[f].replace(/\(.*\)/g,""):d[f];l=l+f+":"+n+":"}f=h+"::"+l;h=c.c[f];h||(h={time:0,count:0},c.c[f]=h);if(1E4>m()-h.time)h.count++,1==h.count&&(d=Eh(),d.message="Throttling: "+ f,c.a.a(e,d));else{h.count&&(d["dropped-instances"]=h.count);h.time=m();for(f=h.count=0;f<c.b.length;f++)c.b[f](e,d);c.a.a(e,d)}}else c.a&&10>c.a.length&&c.a.push([a,b])},Dh=new Ch;
var Gh=function(a){var b=window;if(!b.location){var c;try{c=vd(b)}catch(d){c=za(b).toString()}Fh(null,Error("x`"+c))}c=b.location&&b.location.ancestorOrigins;if(p(c))return c&&c.length?c[a?0:c.length-1]==b.location.origin:!0;try{return p((a?b.parent:b.top).location.href)}catch(e){return!1}};
var Hh={},Eh=function(){var a={};a.location=document.location.toString();if(Gh(!1))try{a["top.location"]=top.location.toString()}catch(b){a["top.location"]="[external]"}else a["top.location"]="[external]";for(var c in Hh)try{a[c]=Hh[c].call()}catch(d){a[c]="[error] "+d.message}return a};
uh("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));uh("action","cite","data","formaction","href","manifest","poster","src");uh("link","script","style");var Ih={},Jh=function(){delete Ih.W},Kh=function(){Ih.W(1)};var Lh=function(a,b){if(a)this.focused=a.focused,this.alwaysOnTop=a.alwaysOnTop,this.top=a.top,this.left=a.left,this.width=a.width,this.height=a.height,this.state=a.state;else if(b){this.focused=b.contentWindow.document.hasFocus();this.alwaysOnTop=b.isAlwaysOnTop();var c=b.getBounds();this.top=c.top;this.left=c.left;this.width=c.width;this.height=c.height;this.state=b.isMinimized()?"minimized":"normal"}else this.alwaysOnTop=this.focused=!1,this.height=this.width=this.left=this.top=0,this.state=""}; Lh.prototype.isMinimized=function(){return"minimized"==this.state};
var Mh=function(){this.a=new qh};q(Mh,E);Mh.prototype.da=function(a){var b,c=Array.prototype.slice.call(arguments);w(this.a.A(),function(a){b=a.apply(null,c)});return b};Mh.prototype.addListener=function(a){this.a.add(a)};Mh.prototype.removeListener=function(a){this.a.remove(a)};Mh.prototype.l=function(){this.a.clear();Mh.q.l.call(this)};
var Ph=function(){this.b=[];this.h=new Mh;O(this,this.h);this.f=new Mh;O(this,this.f);this.onClosed=new Mh;this.g=!1;this.c=null;this.j=r(this.w,this);Nh.addListener(this.j);this.k=r(this.v,this);Oh.addListener(this.k)};q(Ph,E);Ph.prototype.l=function(){Qh(this)||void 0!=this.a&&chrome.windows.remove(this.a);Rh(this);this.j&&(Nh.removeListener(this.j),Oh.removeListener(this.k));F(this.onClosed);Ph.q.l.call(this)};var Nh=chrome.windows&&chrome.windows.onRemoved,Oh=chrome.windows&&chrome.windows.onFocusChanged;
Ph.prototype.create=function(a){chrome.windows.create(a,r(function(a){this.D?chrome.windows.remove(a.id):(this.a=a.id,Sh(this))},this))};var Sh=function(a){if(null!=a.b&&Th(a))if(Qh(a))Rh(a);else{for(;a.b.length&&!Qh(a);)a.b.shift()(a);a.b=null}},Th=function(a){return!(!ia(a.a)||!a.e)},Uh=function(a,b){Qh(a)?Rh(a):null==a.b?b(a):a.b.push(b)},Qh=function(a){return!(!a.e||!a.e.closed)};Ph.prototype.w=function(){Qh(this)&&Rh(this)};
var Rh=function(a){if(!a.g){var b=a.onClosed;a.onClosed=new Mh;be(r(function(){this.g||(this.g=!0,b.da(this));F(b)},a))}};Ph.prototype.v=function(a){if(a!=this.a){if(null===this.c||this.c)this.c&&(this.c=!1),this.f.da(this)}else this.c=!0,this.h.da(this)};var Vh=function(a){var b;b=a.a?a.e:null;return!b||Qh(a)?null:b};Ph.prototype.minimize=function(){Uh(this,r(function(){chrome.windows.update(this.a,{state:"minimized"})},this))};
Ph.prototype.focus=function(){Uh(this,r(function(){chrome.windows.update(this.a,{focused:!0})},this))};var Wh=function(a,b){Uh(a,r(function(){chrome.windows.update(this.a,{drawAttention:b})},a))},Yh=function(a,b){Uh(a,wd(Xh,[a],function(a){b(a[0])}))},Xh=function(a,b){chrome.windows.getAll(function(c){var d={};w(c,function(a){d[a.id]=a});var e=[];w(a,function(a){var b;a&&Th(a)&&!Qh(a)&&(b=d[a.a]);var c;b&&(c=new Lh(b));e.push(c)});b(e)})};
var Zh=new J("b"),$h=new J("c"),ai=new J("d"),bi=new J("e"),ci=new J("f"),di=new J("g"),ei=new J("h"),id=new J("i"),fi=new J("j");var gi=function(a,b){this.a=a;this.p=b;this.k=this.n=this.e="";this.b=null;this.g="";this.t=0;this.c=[];this.h=!1;this.j=""},hi=function(a,b){this.name=a;this.title=b||""};g=gi.prototype;g.setTitle=function(a){this.n=a};g.sb=function(){return this.n||""};g.Ka=function(){return this.g||""};g.type=function(){return this.p};g.wa=function(){if(this.Fb())return null;var a=this.a;null!=this.f?a+=this.f:null!=this.g&&(a+=this.g);return a};g.Fb=function(){return!1};
var ii=function(a){return a.replace(/^(\<br\>)+/,"")},ji=function(a){var b=a.sb();a.k&&(b+=" "+(a.k||""));var c=ii(a.Ka()),d=sa(a.c,function(a){var b;if(!(b=a.title))t:{switch(a.name){case "answer":case "join hangout":b=S("QUASAR_ANSWER_BUTTON_TEXT");break t;case "ignore":b=S("QUASAR_DECLINE_BUTTON_TEXT");break t}b=""}return{title:b}},a);return{type:"basic",iconUrl:(0==a.e.indexOf("data:")||0==a.e.indexOf("chrome-extension:")?a.e:"")||chrome.runtime.getURL("images_3/icon-128x128.png"),title:b,message:c, buttons:d,priority:2}};
var ki=function(a){gi.call(this,a,2)};q(ki,gi);ki.prototype.sb=function(){var a=ki.q.sb.call(this);return this.h&&!a?S("QUASAR_GROUP_CHAT_TITLE"):a};ki.prototype.Ka=function(){return 0<=this.a.indexOf("video")?S("QUASAR_VIDEO_DETAILS"):0<=this.a.indexOf("voice")?S("QUASAR_VOICE_DETAILS"):ki.q.Ka.call(this)};ki.prototype.Fb=function(){return 0<=this.a.indexOf("voice")||0<=this.a.indexOf("video")};
var U;var li=function(a){gi.call(this,a,2)};q(li,gi);li.prototype.wa=function(){return null!=this.f?li.q.wa.call(this):null};var mi=function(a){this.c=a;this.a=new lc;this.b=a.get($b);this.a.setItem(new hc("StartOnBrowserLaunch",!0,!1,!1));mc&&this.a.setItem(new hc("TopMost",!0));a=new hc("StopOnBrowserClose",!1,!1,!1);a.setEnabled(!1);this.a.setItem(a);a=new hc("TrayIcon",!0,!1,!1);a.setEnabled(null!=navigator.platform.match(/Win.*/)||ah()||$g());this.a.setItem(a);(a=this.b.get("settings"))&&kc(this.a,a);this.b.set("settings",Og(this.a))};ga("ace.core.SettingsManager",mi);
var ni=chrome.runtime&&chrome.runtime.getURL&&chrome.runtime.getURL("settingsdialog.html")||"";mi.prototype.f=function(){this.b.set("settings",Og(this.a));var a=U.e("setting");if(a&&0!=a.length)oi(a[0],"focus");else{var a=Math.floor((screen.height-200)/2),b=Math.floor((screen.width-520)/2),c=["width=520"];c.push("height=200");c.push("top="+a);c.push("left="+b);c.push("location=no");gh(ni,c.join(","))}};mi.prototype.launchSettingsDialog=mi.prototype.f;
mi.prototype.g=function(){var a=new lc(Og(this.a)),b=this.b.get("settings");kc(this.a,b);var c=new lc(b),b=c.getItem("StopOnBrowserClose"),a=a.getItem("TrayIcon"),c=c.getItem("TrayIcon");a.ba&&(c.F()||b.F()?(b=this.c.get($h),pi(b),qi(b)):c.F()||b.F()||ri(this.c.get($h)))};mi.prototype.updateSettingsFromStorage=mi.prototype.g;mi.prototype.e=function(){var a=U.e("setting");if(a)for(var b=0;b<a.length;++b)oi(a[b],"close")};mi.prototype.closeUI=mi.prototype.e; var oi=function(a,b){var c=new cc;fc(c,b);gc(c,[]);U.b(a).sendMessage(c)};
var V=new Sc("act"),si=new Sc("impr"),ti=new Sc("tran"),ui=new Sc("perf");new L(V,1);new L(V,2);new L(V,3);new L(V,4);new L(V,5);new L(V,6);new L(V,7);new L(V,8);new L(V,9);new L(V,10);new L(V,11);new L(V,12);new L(V,13);new L(V,14);new L(V,15);new L(V,22);new L(V,16);new L(V,17);new L(V,18);new L(V,19);new L(V,20);new L(V,21);new L(V,23);new L(V,24);var vi=new L(si,1E3);new L(ti,1001);new L(ui,1002);
var wi=new J("k");var W=function(a){this.j=a;this.n=a.get(ei);this.b=a.get($b);this.a=1;this.e=this.h=null;this.g=this.c=!1;this.k=r(this.p,this);pi(this);qi(this);null!=this.b.a.get("UnreadIndicator")&&this.b.remove("UnreadIndicator");null!=this.b.a.get("app_status")&&this.b.remove("app_status");null!=this.b.a.get("user_id")&&this.b.remove("user_id");null!=this.b.a.get("client_state")&&this.b.remove("client_state")};q(W,E);ga("ace.core.DesktopManager",W);W.prototype.l=function(){ri(this);W.q.l.call(this)};
W.prototype.f=function(a,b){this.a!=b&&(this.a=b,qi(this),xi(this),1==this.a&&(this.e=this.h=null,this.g=this.c=!1,ri(this),this.n.e(),this.j.get(ci).b()),U.g())};W.prototype.changeDesktop=W.prototype.f;W.prototype.u=function(a,b){this.c!=b&&(this.c=b,qi(this),xi(this))};W.prototype.setMainUiShowing=W.prototype.u;
var pi=function(a){var b=a.n.a,c;if(c=null!=navigator.platform.match(/Win.*/)||ah()||$g())c=b.a.get("StopOnBrowserClose"),(c=c&&c.ba?c.F():!1)||(c=(b=b.a.get("TrayIcon"))&&b.ba?b.F():!1);c&&chrome.systemIndicator&&(chrome.systemIndicator.enable(),chrome.systemIndicator.onClicked.addListener(a.k))},ri=function(a){chrome.systemIndicator&&(chrome.systemIndicator.disable(),chrome.systemIndicator.onClicked.removeListener(a.k))},xi=function(a){var b;switch(a.a){case 2:b=S("QUASAR_TIP_CONNECTING");break;
case 3:b=S("QUASAR_TIP_NOT_LOGIN");break;case 4:case 9:case 8:b=a.c?a.g?S("CHROME_EXT_TIP_CONNECTED_MISSED_MESSAGES"):S("QUASAR_TIP_CONNECTED"):S("QUASAR_TIP_NOT_LOGIN");break;case 6:b=S("QUASAR_TIP_NOT_LOAD");break;default:b=S("QUASAR_TIP_DISCONNECTED")}a=a.e?"\n"+a.e:"";(b=S("CHROME_EXT_SHORT_NAME")+a+"\n"+b)&&chrome.browserAction.setTitle({title:b})};W.prototype.w=function(a,b,c){1!=this.a&&(a=b||S("QUASAR_MENUTEXT_UNKNOWN_USER"),a!=this.h&&(this.h=a),this.e=c)};W.prototype.updateUserName=W.prototype.w;
W.prototype.v=function(a,b){this.g!=b&&(this.g=b,qi(this),xi(this))};W.prototype.setUnreadIndicator=W.prototype.v;
var qi=function(a){chrome.browserAction.setIcon(yi(a,!0));chrome.systemIndicator&&chrome.systemIndicator.setIcon(yi(a))},zi=function(a){switch(a.a){case 2:return"offline_working";case 4:case 9:case 8:return a.c?a.g?"available_missed":"available":"offline";case 6:return"offline_unknown";default:return"offline"}},yi=function(a,b){var c=!b&&$g()?"_mac_":"_",d=zi(a),e=chrome.runtime.getURL("images_3/presence/"+d+c+"19.png"),c=chrome.runtime.getURL("images_3/presence/"+d+c+"38.png");return{path:{19:e, 38:c}}};W.prototype.p=function(){var a=U.a();this.j.get(wi).a("qstcl");a.rb();a.b("onTrayClick",[1])};
var Ai=function(a,b,c){I.call(this);this.a=b.createElement("IFRAME");b.body.appendChild(this.a);this.a.src=a;c&&(this.a.id=c,this.a.name=c);a=new H(this);O(this,a);a=yd(a,this.a,"load",this.c,void 0);yd(a,this.a,"error",Kh,void 0).listen(b.defaultView,"focus",this.b).listen(b.body,"focus",this.b)};q(Ai,I);Ai.prototype.b=function(){qc(this.a.focus,this.a)};Ai.prototype.c=function(){this.b()};Ai.prototype.l=function(){this.a.parentElement.removeChild(this.a);this.a=null;Ai.q.l.call(this)};
var Fi=function(a,b){H.call(this);this.b=a;ac("viewer",""+(new Date).getTime());this.e=this.f=null;this.k=U;this.u=m();this.j=a.get($h);var c=a.get(di),d=S("CHROME_EXT_SHORT_NAME"),e=hh("viewer-14.png",!0),f=hh("viewer-28.png",!0),d=Bi(c,"viewer","viewer","viewer.html?viewer",d,e,f),e=b?Bd(b,Ci,2).Ma():null,e=Di(c,new oh(260,460),!0,e);Ei(c,d.id,e);this.a=d;this.a.onClosed.addListener(r(this.B,this));Uh(this.a,r(this.n,this))};q(Fi,H);
Fi.prototype.l=function(){this.b.b(id)==this&&this.b.u();this.removeAll();Fi.q.l.call(this)};var Gi=function(a){F(a.f);a.f=null;F(a.e);a.e=null;Pg(a.c.a,"retryInfo").style.display="none"};Fi.prototype.close=function(){F(this.a);this.b.b(id)==this&&this.b.u()};
Fi.prototype.n=function(){this.c=new bh(Vh(this.a).document);this.a.setTitle(S("CHROME_EXT_SHORT_NAME"));Pg(this.c.a,"retryMessage").textContent=S("CHROME_EXT_CANNOT_CONNECT");var a=Pg(this.c.a,"retryLink");a.textContent=S("QUASAR_TRY_NOW");this.listen(a,"click",this.p);this.listen(this.k,"onStatusChange",this.h);this.h()};Fi.prototype.p=function(a){a.b();this.b.get(Zh).f()};
Fi.prototype.h=function(){switch(this.j.a){case 3:if(!this.f){Gi(this);var a;a=this.b.get(ei).a;a=new Ud(a.b[0]);var b=new Ud("/talkgadget/qsignin");P(b,"passive","1");P(b,"hl",chrome.i18n.getMessage("@@ui_locale"));a=Yd(a,b).toString();this.f=new Ai(a,this.c.a)}break;case 2:Gi(this);break;case 6:Gi(this);Pg(this.c.a,"retryInfo").style.display="block";break;default:Hi(this)}};var Hi=function(a){a.e||(Gi(a),Ii(a.b.get(Zh)).then(function(a){this.e=new Ai(a,this.c.a,"popoutRoster")},void 0,a))};
var Ji=function(a,b){this.b=Ed(a);this.a=0;this.c=b||!1};Ji.prototype.F=function(a){var b=this.b[this.a],b=(.5+1*Math.random())*b;a&&Ki(this);return b};var Ki=function(a){a.c&&a.a==a.b.length-1||a.a++};var Li=function(a,b,c){this.b=a;this.e=b||0;this.c=c;this.W=r(this.f,this)};q(Li,E);Li.prototype.a=0;Li.prototype.l=function(){Li.q.l.call(this);this.stop();delete this.b;delete this.c};var Mi=function(a,b){a.stop();a.a=be(a.W,p(b)?b:a.e)};Li.prototype.stop=function(){0!=this.a&&ce(this.a);this.a=0};Li.prototype.f=function(){this.a=0;this.b&&this.b.call(this.c)};
var Ni=function(a,b,c){this.c=a;this.b=b;this.a=c;this.W=r(this.Zc,this)};q(Ni,E);g=Ni.prototype;g.Sa=!1;g.na=null;g.stop=function(){this.na&&(ce(this.na),this.na=null,this.Sa=!1)};g.l=function(){Ni.q.l.call(this);this.stop()};g.Zc=function(){this.na=null;this.Sa&&(this.Sa=!1,Oi(this))};var Oi=function(a){a.na=be(a.W,a.b);a.c.call(a.a)};
var Y=function(a){H.call(this);this.a=a;this.c=a.get($h);this.Q=a.b(di);this.L=Dc();this.k=null;this.I=new Ni(this.f,6E4,this);O(this,this.I);a=r(this.ld,this);Ih.W=a;td(this,Jh);this.h=!1;this.p=new Ji(kh,!0);this.K=new Li(this.yd,this.p.F(),this);O(this,this.K);this.j=new Li(this.vc,2E4,this);O(this,this.j);this.listen(window,"online",this.rd);this.w=this.C=0;this.b=new Ji(lh);this.e=new Li(this.Ca,this.b.F(),this);O(this,this.e);chrome.cookies.onChanged.addListener(r(this.Da,this));this.v=r(this.aa,
this);this.u=r(this.$,this);chrome.tabs.onUpdated.addListener(this.v);chrome.tabs.onCreated.addListener(this.u)};q(Y,H);ga("ace.core.DataChannelManager",Y);Y.prototype.l=function(){chrome.tabs.onCreated.removeListener(this.u);chrome.tabs.onUpdated.removeListener(this.v);delete this.u;delete this.v;F(this.k);Y.q.l.call(this)};Y.prototype.n=function(a,b){Pi(this);t:{var c=this.a,d=c.b(id);if(d){if(Th(d.a)?!Qh(d.a):1E3>m()-d.u){d.a.focus();break t}d.close()}d=new Fi(c,b);c.a(id,d,!0)}};
Y.prototype.showViewer=Y.prototype.n;Y.prototype.Ua=function(a,b){this.L.a(b||"")};Y.prototype.setRosterUrl=Y.prototype.Ua;var Ii=function(a){return a.L.b};Y.prototype.Ba=function(){this.c.f(0,1);var a=this.a.b(id);a&&a.close();Qi(this);this.h=!1};Y.prototype.terminateApplication=Y.prototype.Ba;var Pi=function(a){a.h||(a.listen(U,"onStatusChange",a.Oc),a.f(),a.a.get(ei),a.h=!0)};
Y.prototype.f=function(){this.D||(this.c.f(0,2),Qi(this),this.k=new Ai(chrome.runtime.getURL("datachannel.html"),document,"centralRoster"))};var Qi=function(a){a.Q.f();a.a.get(ci).b();F(a.k);a.k=null;a.L=Dc()},Si=function(a,b){var c=Qg(a.a.get(ei).a);chrome.cookies.getAll({url:c},r(function(a){a=a&&Ri("SID",a)&&Ri("SSID",a)&&Ri("SAPISID",a);b(a)},a))};Y.prototype.Ea=function(a){var b=this.c.a;if(a){if(3==b){if(a=0==this.e.a)a=this.b,a=a.a<a.b.length;a&&Mi(this.e,this.b.F())}}else 3!=b&&this.f()};
Y.prototype.Da=function(a){"SSID"!=a.cookie.name&&"SAPISID"!=a.cookie.name||".google.com"!=a.cookie.domain||Si(this,r(this.Ea,this))};var Ri=function(a,b){return ua(b,function(b){var d=b.expirationDate&&b.expirationDate<m()/1E3;return b.name==a&&".google.com"==b.domain&&!d})};g=Y.prototype;g.Oc=function(){this.K.stop();this.j.stop();switch(this.c.a){case 2:Mi(this.j);break;case 6:Mi(this.K,this.p.F());break;case 4:case 9:case 8:case 5:this.p.a=0,this.e.stop()}};
g.rd=function(){if(4!=this.c.a){var a=this.I;a.na?a.Sa=!0:Oi(a)}};g.yd=function(){Ki(this.p);this.f()};g.ld=function(a){Qi(this);switch(a){case 1:this.vc();break;case 2:a=this.I,a.na?a.Sa=!0:Oi(a)}};g.vc=function(){this.D||(this.j.stop(),this.c.f(0,6))};var Ti=function(a){a.w++;var b=a.a.get(wi);1==a.w?b.a("qccro"):2==a.w?b.a("qccrt"):b.a("qccrm")};Y.prototype.Ca=function(){Ki(this.b);Ti(this);Si(this,r(function(a){a&&this.f()},this))};Y.prototype.aa=function(a,b){b.url&&Ui(this,b.url)};
Y.prototype.$=function(a){a.url&&Ui(this,a.url)};var Vi=function(a){a.C++;var b=a.a.get(wi);1==a.C?b.a("qctro"):2==a.C?b.a("qctrt"):b.a("qctrm")},Ui=function(a,b){ua(jh,function(a){return a.test(b)})&&0!=a.b.a&&(a.b.a=0,Vi(a),0!=a.e.a&&Mi(a.e,a.b.F()))};
var Wi=function(a){this.a=0;this.c=a.get($b);null!=this.c.a.get("dupDetectionQueue.latestChat")&&(this.a=this.c.get("dupDetectionQueue.latestChat"));this.b=0;this.f=new C;this.e=new mh(18E5);nb(this.e,"tick",r(this.g,this,this.f,0,200));nh(this.e)};q(Wi,E);Wi.prototype.l=function(){this.e.B()};var Xi=function(a,b){var c=b.wa();if(null==c)return!1;switch(b.type()){case 7:case 2:if(null!=b.b&&b.b<=a.a)if(31536E7<a.a-b.b)a.a=0,a.b=0;else return!0;else return Ia(a.f.a,c)}return!1};
Wi.prototype.add=function(a){var b=a.wa();if(null!=b&&!Xi(this,a))switch(a.type()){case 7:case 2:null!=a.b&&this.b<a.b&&(this.b=a.b,this.c.set("dupDetectionQueue.latestChat",this.b)),this.f.set(b,m()+18E5)}};
Wi.prototype.g=function(a,b,c){var d=a.V();if(0!=d){var e=0;null!=b&&0<b&&(e=b<d?b:d);b=d;null!=c&&c<d&&(b=0<c?c:0);e>b&&(e=b);var f=[];c=a.ha(!0);rh(c,function(b){f.push([b,a.get(b)])});f.sort(function(a,b){return a[1]-b[1]});if(31536E7<f[d-1][1]-f[0][1])a.clear();else{c=0;b=d-b;for(var d=d-e,e=m(),h=0;h<f.length;++h)if(c<b||c<d&&f[h][1]<=e)a.remove(f[h][0]),c+=1;else break}}};
var Yi=function(a){y(this,a,"acr:bcr",[])};q(Yi,x);A("acr:bcr",Yi);var Zi=function(a){y(this,a,"acr:srs",[])};q(Zi,x);A("acr:srs",Zi);var $i=function(a){y(this,a,"acr:rss",[])};q($i,x);A("acr:rss",$i);var aj=function(a){y(this,a,"acr:rrs",[])};q(aj,x);A("acr:rrs",aj);var bj=function(a){y(this,a,"acr:rsr",[])};q(bj,x);A("acr:rsr",bj);var cj=function(a){y(this,a,"acr:wrs",[1])};q(cj,x);A("acr:wrs",cj);var dj=function(a){y(this,a,0,[])};q(dj,x);dj.prototype.Y=function(){return z(this,2)}; dj.prototype.La=function(){return z(this,11)};
var ej=function(a){y(this,a,"acq:rs",[3])};q(ej,x);A("acq:rs",ej);var fj=function(a){y(this,a,0,[])};q(fj,x);var Ci=function(a){y(this,a,0,[])};q(Ci,x);Ci.prototype.Ma=function(){return Bd(this,fj,1)};var gj=function(a,b){Ad(a,1,b)},hj=function(a){y(this,a,0,[])};q(hj,x);hj.prototype.Y=function(){return z(this,1)};hj.prototype.Ma=function(){return Bd(this,fj,2)};var ij=function(a,b){Ad(a,2,b)};hj.prototype.La=function(){return z(this,3)};
var jj=function(a){this.c=a;this.a={};this.b=a.get($b)},kj=function(a,b){return(null!=a?a:"null")+"-"+(null!=b?b:"null")},nj=function(a,b){be(a.reload,6E4,a);var c=[],d={},e=a.c.get(di),f=th(b,dj,1)||[];w(f,function(a){c.push(z(a,1));d[kj(a.Y(),a.La())]=a});var h=c.length;c.push("viewer");lj(e,c,r(function(a){for(var c=[],e=0;e<f.length;e++){var K=a[e];if(K){var X=f[e],R=new hj;M(R,3,X.La());M(R,1,X.Y());ij(R,mj(K));c.push(R)}}vh(c,function(a,b){var c=b.Ma(),c=z(c,2),d=a.Ma();return c-z(d,2)});w(c,
function(a,b){M(d[kj(a.Y(),a.La())],3,b)});a=a[h];e=new ej;a&&(K=new Ci,gj(K,mj(a)),Ad(e,2,K));sh(e,3,c);sh(b,1,f);Ad(e,1,b);this.b.set("ReloadState",e.G);U.a().b("eventReloadStateSaved",[])},a))},mj=function(a){var b=new fj;M(b,1,a.top);M(b,2,a.left);M(b,3,a.width);M(b,4,a.height);M(b,5,a.focused);M(b,6,a.state);M(b,7,a.alwaysOnTop);return b};jj.prototype.read=function(){var a=this.e;this.e=null;U.a().b("eventReloadStateRead",[a&&a.G||null])};jj.prototype.reload=function(){chrome.runtime.reload()};
var Z=function(a){this.a=new jj(a);this.b=a;chrome.runtime.onUpdateAvailable.addListener(r(this.t,this))};ga("ace.core.ExtensionLibrary",Z);Z.prototype.t=function(){U.a().b("eventReloadClient",[]);be(this.a.reload,864E5+288E5*Math.random(),this.a)};Z.prototype.p=function(a,b,c,d){a=U.b(b);null!=a&&p(d)&&d&&(d=a.h,null!=d&&null!=d.id&&(chrome.tabs.update(d.id,{selected:!0}),c&&chrome.tabs.get(d.id,function(a){Vg(a.windowId)})))};Z.prototype.selectTab=Z.prototype.p;
Z.prototype.h=function(a,b,c){c?gh(b,"width=500,height=400"):chrome.tabs.create({url:b,selected:!0},function(a){null!=a?be(function(){chrome.tabs.get(a.id,function(a){Vg(a.windowId)})},2E3):gh(b)})};Z.prototype.openUrl=Z.prototype.h;Z.prototype.g=function(a,b){this.c=this.b.get(di);this.c.focus(b)};Z.prototype.focusMoleByFrameId=Z.prototype.g;Z.prototype.f=function(){U.a().rb()};Z.prototype.showApplication=Z.prototype.f;Z.prototype.n=function(a,b){var c=new cj(b);nj(this.a,c)};
Z.prototype.saveReloadState=Z.prototype.n;Z.prototype.j=function(){this.a.read()};Z.prototype.readReloadState=Z.prototype.j;Z.prototype.k=function(){this.a.reload()};Z.prototype.reloadExtension=Z.prototype.k;Z.prototype.e=function(){U.a().Mc()};Z.prototype.onHostReady=Z.prototype.e;
var oj=function(a){gi.call(this,a,7);this.c.push(new hi("join hangout"));this.c.push(new hi("ignore"))};q(oj,gi);oj.prototype.Ka=function(){var a=oj.q.Ka.call(this);return a?a:this.h?S("CHROME_EXT_GROUP_PLUS_HANGOUT_DETAILS"):S("CHROME_EXT_ONEONONE_PLUS_HANGOUT_DETAILS")};oj.prototype.wa=function(){return null!=this.f?oj.q.wa.call(this):null};
var pj=function(a,b){this.a=b||new Lh;b||(this.a.alwaysOnTop=Rg(a.get(ei).a))},rj=function(a,b,c){(b=b.j)?qj(a.get(di),b,function(b){c(new pj(a,b))}):c(new pj(a))};var sj=function(){Ph.call(this)};q(sj,Ph);sj.prototype.setTitle=function(a){Uh(this,r(function(){Vh(this).document.title=a},this))};
var uj=function(a,b){a.p=b;Uh(a,r(function(){tj(this)},a))},vj=function(a,b){a.u=b;Uh(a,r(function(){tj(this)},a))},tj=function(a){var b=Vh(a).document,c=b.querySelector("HEAD"),d=c.querySelectorAll("link[rel='shortcut icon']"),e=hh("icon-24x24.png",!0);a=[a.p||e,a.u];for(var e=bc()?2:1,f="",h=0;h<e;++h)if(a[h]&&a!=f){var f=a[h],l=d[h];l||(l=b.createElement("LINK"),c.appendChild(l));l.rel="shortcut icon";var n=a[h];l.type=Zg(n,".ico")?"image/x-icon":Zg(n,".gif")?"image/gif":"image/png";l.href=a[h]}};
var xj=function(a){this.a={};if(a)for(var b=0;b<a.length;b++)this.a[wj(a[b])]=null;for(var c in Object.prototype);},yj={},wj=function(a){return a in yj||32==String(a).charCodeAt(0)?" "+a:a},zj=function(a){return 32==a.charCodeAt(0)?a.substr(1):a};g=xj.prototype;g.add=function(a){this.a[wj(a)]=null};g.clear=function(){this.a={}};g.clone=function(){var a=new xj,b;for(b in this.a)a.a[b]=null;return a};g.contains=function(a){return wj(a)in this.a};
g.forEach=function(a,b){for(var c in this.a)a.call(b,zj(c),void 0,this)};g.V=Object.keys?function(){return Object.keys(this.a).length}:function(){var a=0,b;for(b in this.a)a++;return a};g.A=Object.keys?function(){return Object.keys(this.a).map(zj,this)}:function(){var a=[],b;for(b in this.a)a.push(zj(b));return a};g.P=function(){for(var a in this.a)return!1;return!0};g.remove=function(a){a=wj(a);return a in this.a?(delete this.a[a],!0):!1};g.ha=function(){return eh(this.A())};
var $=function(a){this.h=a;this.a={};this.c={};this.b=new xj;ga("__onPanelLoad",r(this.I,this));this.n=a.get($h);a=new H(this);O(this,a);a.listen(U,"onStatusChange",this.v)};q($,E);ga("ace.core.PanelsManager",$);$.prototype.l=function(){for(var a in this.a)this.kb(this.a[a]);$.q.l.call(this)};$.prototype.u=function(a,b){var c=function(a){a=a?!a.isMinimized():null;U.a().b("eventIsMinimizedResponse",[b,a])},d=this.a[b];d?Yh(d,c):c(void 0)};$.prototype.isMaximized=$.prototype.u;
$.prototype.K=function(a,b,c,d,e,f,h,l,n,B){a="panel.html?"+b;d=d||S("CHROME_EXT_SHORT_NAME");b=Bi(this,b,l||b,a,d,e,h);Uh(b,r(this.j,this,c));c=new oh(280,420);n||B?(n=n||null,e=B||null,B=this.h.get(ai).a,n=kj(n,e),(e=B.a[n])&&delete B.a[n],B=e?e.Ma():null):B=null;f=Di(this,c,!!f,B);Ei(this,b.id,f)};$.prototype.openPanel=$.prototype.K;
$.prototype.w=function(a,b,c,d,e,f,h){a="dialog.html?"+b;d=d||S("CHROME_EXT_SHORT_NAME");b=Bi(this,b,b,a,d);Uh(b,r(this.j,this,c));c=Di(this,new oh(f,h),e,null);c.dd=!0;Ei(this,b.id,c);return b};$.prototype.openDialog=$.prototype.w;var Bi=function(a,b,c,d,e,f,h){a.a[b]&&a.kb(a.a[b]);var l=new sj;l.id=b;l.key=c;l.url=d;l.setTitle(e);uj(l,f);vj(l,h);a.a[b]=l;a.c[c]=b;return l};$.prototype.j=function(a,b){b.n=new Ai(a,Vh(b).document);O(b,b.n)};
var Di=function(a,b,c,d){b={focus:c,Aa:null,width:b.width,height:b.height,minimize:!1};if(d){b.top=z(d,1);b.left=z(d,2);c=z(d,3);var e=z(d,4);z(d,7)?(b.width=Math.max(b.width,c),b.height=Math.max(b.height,e)):(b.width=c,b.height=e);"minimized"==z(d,6)&&(b.minimize=!0);b.Aa=z(d,7);b.focus=z(d,5)}b.Aa="boolean"==typeof b.Aa?b.Aa:Rg(a.h.get(ei).a);return b},Ei=function(a,b,c){var d=a.a[b];d.onClosed.addListener(r(a.kb,a));d.h.addListener(r(a.J,a));d.f.addListener(r(a.C,a));c.minimize&&d.minimize();b=
"panel";c.Aa||(b=ah()?"popup":"detached_panel");c.dd&&(b="popup");var e={type:b,url:d.url,focused:c.focus,width:c.width,height:c.height};if(b=null!=c.top&&null!=c.left)e.top=c.top,e.left=c.left;b||c.Aa?d.create(e):lj(a,Object.keys(a.c),r(function(a){var b=screen,c;c=new oh(260,460);var n=new oh(280,420);c=new oh(Math.max(c.width,n.width),Math.max(c.height,n.height));for(var B=b.availWidth,K=b.availHeight-50,n=b.availTop+K%c.height,b=b.availLeft+B%c.width,B=Math.floor(B/c.width),X=Math.floor(K/c.height),
K=Array(B*X),R=0;R<a.length;R++){var la=a[R];if(la){for(var Mb=[la.left,la.left+la.width-1],la=[la.top,la.top+la.height-1],ea=0;2>ea;ea++)Mb[ea]=Math.floor(Math.max(0,Mb[ea]-b)/c.width),la[ea]=Math.floor(Math.max(0,la[ea]-n)/c.height);for(ea=Mb[0];ea<=Mb[1];ea++)for(var Nb=la[0];Nb<=la[1];Nb++)ea<B&&Nb<X&&(K[ea+Nb*B]=1)}}a=K.length-1;for(R=K.length-1;0<=R;R--)if(!K[R]){a=R;break}K=a%B*c.width;e.top=n+Math.floor(a/B)*c.height+(c.height-e.height);e.left=b+K+(c.width-e.width);d.create(e)},a))};
$.prototype.g=function(a,b){var c=this.a[b];c&&F(c)};$.prototype.closePanel=$.prototype.g;$.prototype.f=function(){for(var a in this.a)0==this.a[a].url.indexOf("panel.html")&&this.g(0,a)};$.prototype.closeAllPanels=$.prototype.f;$.prototype.setTitle=function(a,b,c){(a=this.a[b])&&a.setTitle(c)};$.prototype.setTitle=$.prototype.setTitle;$.prototype.p=function(a,b,c){this.a[b]&&Wh(this.a[b],c)};$.prototype.drawAttention=$.prototype.p;
$.prototype.focus=function(a){if(this.a[a]){var b=this.a[a];Yh(b,r(function(a){if(a&&(a=Vh(b),0==a.outerWidth&&0==a.outerHeight)){this.kb(b);return}b.focus()},this))}};$.prototype.Q=function(a,b,c){this.a[b]&&uj(this.a[b],c)};$.prototype.setPresence=$.prototype.Q;$.prototype.L=function(a,b,c){this.a[b]&&vj(this.a[b],c)};$.prototype.setAvatar=$.prototype.L;$.prototype.e=function(a,b,c){for(var d in this.a)(b||this.b.contains(d))&&this.k(0,d,b,c);b||this.b.clear()};
$.prototype.minimizeAllPanelsIfTopmost=$.prototype.e;$.prototype.k=function(a,b,c,d){var e=this.a[b];e&&Yh(e,r(function(a){if(a&&a.alwaysOnTop&&!this.D)if(c){var h;(h=!d)||(h=new ih(a.left,a.top,a.width,a.height),h=h.left<=d.left+d.width&&d.left<=h.left+h.width&&h.top<=d.top+d.height&&d.top<=h.top+h.height);h&&!a.isMinimized()&&(e.minimize(),this.b.add(b))}else chrome.windows.update(e.a,{state:"normal"}),this.b.remove(b)},this))};$.prototype.minimizePanelIfTopmost=$.prototype.k;
$.prototype.I=function(a){var b=this.a[a.location.search.substring(1)];b&&(b.e=a,Sh(b))};var qj=function(a,b,c){a=a.a[a.c[b]];!a||Qh(a)?c(void 0):Yh(a,c)},lj=function(a,b,c){var d=[];w(b,r(function(a){d.push(this.a[this.c[a]])},a));Xh(d,c)};$.prototype.kb=function(a){this.a[a.id]==a&&(this.b.remove(a.id),delete this.c[a.key],delete this.a[a.id],F(a))};$.prototype.J=function(a){this.a[a.id]==a&&this.b.remove(a.id)};$.prototype.C=function(a){this.a[a.id]==a&&U.a().b("eventBlurred",[a.id])}; $.prototype.v=function(){3==this.n.a&&this.f()};
var Aj=function(a){this.j=a;this.a=new C;this.h=new C;this.c=new Wi(a);O(this,this.c);this.g=r(this.gd,this);chrome.notifications.onClosed.addListener(this.g);this.e=r(this.Pc,this);chrome.notifications.onClicked.addListener(this.e);this.f=r(this.fd,this);chrome.notifications.onButtonClicked.addListener(this.f)};q(Aj,E);ga("ace.core.NotificationManager",Aj);
Aj.prototype.l=function(){w(this.a.A(),F);this.a.clear();chrome.notifications.onClosed.removeListener(this.g);chrome.notifications.onClicked.removeListener(this.e);chrome.notifications.onButtonClicked.removeListener(this.f);Aj.q.l.call(this)};
Aj.prototype.n=function(a,b){var c;if(b&&b.Content){c=[b.Id.ServiceUrl,b.Id.ServiceId].join(";");c=0==c.indexOf("bc")?new li(c):0<c.indexOf("chat")||0<=c.indexOf("voice")||0<=c.indexOf("video")?new ki(c):0==c.indexOf("hangout")?new oj(c):new gi(c,8);c.setTitle(b.Content.TitleText);c.k=b.Content.SubtitleText;c.g=b.Content.BodyText;c.f=b.Content.BodyTextId||b.Content.BodyTimestamp;c.b=b.Content.BodyTimestamp;var d=0;b.Content.EndTimeMs&&(d=b.Content.EndTimeMs,isNaN(d)||!isFinite(d))&&(d=0);d=d||m()+
1E4;c.t=d;b.Content.ServiceIcon?(d=b.Content.ServiceIcon,c.e=d&&hh(d)||""):b.Content.TitleTemplate&&(d=b.Content.TitleTemplate.IconUrl,c.e=d&&hh(d)||"");b.Content.IsGroupChat&&(c.h=!0);b.Content.FrameId&&(c.j=b.Content.FrameId);if(b.Content.BodyTemplate)for(var d=b.Content.BodyTemplate.Action,e=0;e<d.length;e++)d[e].Name&&c.c.push(new hi(d[e].Name,d[e].Text))}else c=null;c&&(U.a().b("eventLogImpression",["qnop"]),Xi(this.c,c)?Bj(c.a,"toastEventOnNotDisplayed"):(this.c.add(c),Cj(this,c)))};
Aj.prototype.registerNotification=Aj.prototype.n;var Cj=function(a,b){2==b.type()||b.j?rj(a.j,b,function(c){c=c.a;c.focused||c.alwaysOnTop?Bj(b.a,"toastEventOnNotDisplayed"):Dj(a,b)}):Dj(a,b)},Dj=function(a,b){var c=b.a,d=b.t-m();0>=d?a.ic(c):(a.a.set(c,b),chrome.notifications.create(c,ji(b),function(){U.a().b("eventLogImpression",["qtod"])}),ce(a.h.get(c,null)),b.t!=Number.MAX_VALUE&&a.h.set(c,be(r(a.ic,a,c),d)),U.a().b("eventLogImpression",["qnst"]))};
Aj.prototype.b=function(){w(ra(this.a.A(),Sg),this.Ga,this)};Aj.prototype.cleanAllNotifications=Aj.prototype.b;Aj.prototype.k=function(a,b){var c=this.a.get(b);c&&this.Ga(c)};Aj.prototype.cleanANotification=Aj.prototype.k;g=Aj.prototype;g.Ga=function(a){a=a.a;chrome.notifications.clear(a,ka);this.a.remove(a)};g.gd=function(a,b){if(b){var c=this.a.get(a);c&&(this.a.remove(a),c.Fb()?Bj(a,"toastEventOnButton","ignore"):Bj(a,"toastEventOnClose"))}};
g.Pc=function(a){var b=this.a.get(a);b&&(Bj(a,"toastEventOnBody"),this.Ga(b))};g.fd=function(a,b){var c=this.a.get(a);c&&(Bj(a,"toastEventOnButton",c.c[b].name),this.Ga(c))};g.ic=function(a){var b=this.a.get(a);b&&(Bj(a,"toastEventOnTimeout"),this.Ga(b))};var Bj=function(a,b,c){var d=U;(d=d&&d.a())&&!d.D&&U.a().b(b,[a,c,"",!1])};
var Ej=function(a){y(this,a,"f.mt",[])};q(Ej,x);A("f.mt",Ej);var Fj=function(a){y(this,a,"er",[])};q(Fj,x);A("er",Fj);Fj.prototype.Bb=function(){return z(this,9)};Fj.prototype.getData=function(){return z(this,4)};new qh;D&&Ta(8);var Gj=function(){throw Error("y");};Gj.prototype.a=null;Gj.prototype.toString=function(){return this.content};var Hj=function(){Gj.call(this)};q(Hj,Gj);(function(a){function b(){}b.prototype=a.prototype;return function(a,d){if(!String(a))return"";var e=new b;e.content=String(a);void 0!==d&&(e.a=d);return e}})(Hj);var Ij=function(a,b){Rc.call(this,a,b)};q(Ij,Rc);var Jj=function(a){this.a=a?z(a,1)||-1:-1},Kj=new Jj;var Lj=function(){};q(Lj,ge);Lj.prototype.b=function(){};Lj.prototype.b.oc=!0;Lj.q||q(Lj,ge);T.a={};T.a.pb="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";T.a.nb=T.a.pb+"0123456789";T.a.qb=T.a.pb.length;T.a.ob=T.a.nb.length;T.a.Nb=-2147483648;T.a.zd=function(a){for(var b=0,c=a.length-1;0<=c;c--)b=b*(0==c?T.a.qb:T.a.ob)+T.a.nb.indexOf(a.charAt(c));return b+T.a.Nb};T.a.toString=function(a){var b=[],c=0;a-=T.a.Nb;b[c++]=T.a.pb.charAt(a%T.a.qb);for(a=Math.floor(a/T.a.qb);0<a;)b[c++]=T.a.nb.charAt(a%T.a.ob),a=Math.floor(a/T.a.ob);return b.join("")};
new Ij(Tc,"f_req");
}catch(e){_DumpException(e)}
try{
var zm=function(a,b,c){a.timeOfStartCall=(new Date).getTime();if(b&&JSON&&JSON.stringify){var d=JSON.stringify(b);200>=d.length&&(a.psdJson=d)}d=c||k;d.GOOGLE_FEEDBACK_START_ARGUMENTS=arguments;var e=a.serverUri||"//www.google.com/tools/feedback",f=d.GOOGLE_FEEDBACK_START;if(f)f.apply(d,arguments);else{var e=e+"/load.js?",h;for(h in a)f=a[h],null!=f&&!ha(f)&&(e+=encodeURIComponent(h)+"="+encodeURIComponent(f)+"&");h=d.document;d=h.createElement("script");d.src=e;h.body.appendChild(d)}}; ga("userfeedback.api.startFeedback",zm);
var Am=function(){H.call(this);this.listen(window,"unload",this.B);document.title=S("CHROME_EXT_SHORT_NAME")+": "+S("CHROME_EXT_FEEDBACK_SUBTITLE");Q("system-legend").innerText=S("QUASAR_FEEDBACK_SYSTEM_LEGEND");Q("system-platform-label").innerText=S("QUASAR_FEEDBACK_PLATFORM_LABEL");Q("system-platform-value").innerText=navigator.platform;Q("system-user-agent-label").innerText=S("QUASAR_FEEDBACK_USER_AGENT_LABEL");Q("system-user-agent-value").innerText=navigator.userAgent;Q("user-legend").innerText=
S("CHROME_EXT_FEEDBACK_COMMENTS");Q("privacy-legend").innerText=S("QUASAR_FEEDBACK_PRIVACY_LEGEND");Q("privacy-text").innerText=S("QUASAR_FEEDBACK_PRIVACY_TEXT");var a=Q("submit-button");a.innerText=S("QUASAR_FEEDBACK_SUBMIT_BUTTON");this.listen(a,"click",this.b);a=Q("cancel-button");a.innerText=S("QUASAR_FEEDBACK_CANCEL_BUTTON");this.listen(a,"click",this.a);Q("user-text-value").focus()};q(Am,H);
Am.prototype.b=function(){var a=Q("user-text-value").value;if(a&&(a=a.trim())){var a={flow:"submit",serverUri:S("QUASAR_FEEDBACK_SERVER_URI"),productId:83052,locale:chrome.i18n.getMessage("@@ui_locale"),report:{description:a},callback:this.a},b={version:chrome.runtime.getManifest().version,build:chrome.runtime.id};Q("submit-button").disabled=!0;zm(a,b)}};Am.prototype.a=function(){window.close()};window.addEventListener("load",function(){new Am},!1);

}catch(e){_DumpException(e)}
// Google Inc.
