var CUSTOM_OPTIONS_IDENTIFIER="custom_options_list",SPOOF_OPTIONS_IDENTIFIER="spoofer_list",BASE_OPTIONS_IDENTIFIER="base_options_list",USE_PRESETS_IDENTIFIER="use_presets",REPORT_ERRORS_IDENTIFIER="report_errors",USE_SPOOF_PER_TAB="use_per_tab",PRESET_LIST_IDENTIFIER="preset_list",ERROR_IDENTIFIER="error_",SPOOFER_LIST="spoofer_list",HOTLIST_INDEX="hotlist_index",PERMANENT_OVERRIDE="permanent_override",NO_SPOOF_PER_TAB="no_spoof",update_url="http://spoofer-extension.appspot.com/update",error_url=
"http://spoofer-extension.appspot.com/error",last_update_time=null,storage_location=null,PLATFORM_SPOOF={Macintosh:"MacIntel",Android:"Android",Linux:"Linux",iPhone:"iPhone",iPod:"iPod",iPad:"iPad",Windows:"Windows"},USE_SYNC="use_sync",MAX_IMPORT_COUNT=450,MAX_MEMORY_USAGE=0.98,req,TEST_ERROR_CODE="0",OUT_OF_SPACE="1",MIGRATION_INCOMPLETE="2",MIGRATION_FAILED_THROTTLED_USER_AGENTS="3",MIGRATION_FAILED_THROTTLED_SPOOFS="4",THROTTLED_WRITES="5",ERROR_CODES=[TEST_ERROR_CODE,OUT_OF_SPACE,MIGRATION_INCOMPLETE,
MIGRATION_FAILED_THROTTLED_USER_AGENTS,MIGRATION_FAILED_THROTTLED_SPOOFS,THROTTLED_WRITES],CUSTOM_OPTIONS_LIST_PREFIX="c_",SPOOF_OPTIONS_LIST_PREFIX="s_",user_agent_cache=[],spoof_cache=[];updateCache(function(){});
function UserAgent(a,c,b,d,e,f){this.title=a;this.ua_string=c;this.vendor=b;this.badge=d;this.is_preset=e;this.append_to_default_ua=!1;this.group=f;this.show_in_list=!1;this.key="";this.getUserAgentString=new function(a){return this.append_to_default_ua?a+" "+this.ua_string:this.ua_string}}function PresetSpoof(a,c){this.domain=a;this.user_agent=c;this.key=""}function ErrorReport(a,c){this.error_code=a;this.error_message=c}function getItem(a){return localStorage[a]}
function storeItem(a,c){localStorage[a]=c}function _isUsingLocalStorage(){return 0<localStorage[CUSTOM_OPTIONS_IDENTIFIER]||0<localStorage[SPOOF_OPTIONS_IDENTIFIER]}
function _testMigration(){var a=new UserAgent("Opera 10","Opera/9.80 (Macintosh; Intel Mac OS X; U; en) Presto/2.2.15 Version/10.00","Mozilla, Inc.","O10",!0,"Opera"),c=new PresetSpoof("www.test.com",a),b=[];b.push(a);a=[];a.push(c);storeItem(CUSTOM_OPTIONS_IDENTIFIER,JSON.stringify(b));storeItem(SPOOF_OPTIONS_IDENTIFIER,JSON.stringify(a));_moveLocalStorageToSyncStorage()}
function resetEverything(){var a={};a[""+CUSTOM_OPTIONS_IDENTIFIER]=[];var c={};c[""+SPOOF_OPTIONS_IDENTIFIER]=[];getStorageLocation().set(a,function(){getStorageLocation().set(c,function(){updateCache(function(){})})});localStorage[CUSTOM_OPTIONS_IDENTIFIER]="";localStorage[SPOOF_OPTIONS_IDENTIFIER]=""}
function _moveLocalStorageToSyncStorage(){_moveSpoofsToSyncStorage(function(){console.log("Migrated spoofs to sync storage.")});_moveUserAgentsToSyncStorage(function(){console.log("Migrated user agents to sync storage.")});_isUsingLocalStorage()?(console.log("Migration still incomplete -- waiting for next time to finish up."),recordError(MIGRATION_INCOMPLETE,"")):console.log("Migration complete!")}
function getPercentOfStorageUsed(a){getStorageLocation().getBytesInUse(null,function(c){a(c/getStorageLocation().QUOTA_BYTES)})}
function _moveUserAgentsToSyncStorage(a){var c=JSON.parse(getItem(CUSTOM_OPTIONS_IDENTIFIER));_addMultipleUserAgents(c,function(b,c){b&&c&&0<c.length?(recordError(MIGRATION_FAILED_THROTTLED_USER_AGENTS,""),console.log(""+c.length+" user-agents were not able to be "),console.log("migrated.  Leaving them in local storage until we can re-try."),storeItem(CUSTOM_OPTIONS_IDENTIFIER,c)):storeItem(CUSTOM_OPTIONS_IDENTIFIER,"");a()})}
function _moveSpoofsToSyncStorage(a){var c=JSON.parse(getItem(SPOOF_OPTIONS_IDENTIFIER));_addMultipleSpoofs(c,function(b,c){b&&c&&0<c.length?(recordError(MIGRATION_FAILED_THROTTLED_SPOOFS,""),console.log(""+c.length+" spoofs were not able to be "),console.log("migrated.  Leaving them in local storage until we can re-try."),storeItem(SPOOF_OPTIONS_IDENTIFIER,c)):storeItem(SPOOF_OPTIONS_IDENTIFIER,"");a()})}
function _syncSpoofsAcrossStorageLocations(a,c,b){storage_location=a;_getSpoofList(function(b){storage_location=c;_addMultipleSpoofs(b,function(b,d){console.log("Migrated spoofs from "+a+" to "+c)})});storage_location=a;b()}function _syncUserAgentsAcrossStorageLocations(a,c,b){storage_location=a;_getUserAgentList(function(b){storage_location=c;_addMultipleUserAgents(b,function(b,d){console.log("Migrated user_agents from "+a+" to "+c)})});storage_location=a;b()}
function _syncDataAcrossStorageLocations(a,c,b){c.clear(function(){_syncUserAgentsAcrossStorageLocations(a,c,function(){_syncSpoofsAcrossStorageLocations(a,c,function(){})})});b()}function getStorageLocation(){storage_location||(storage_location=getUseSync()?chrome.storage.sync:chrome.storage.local);return storage_location}function setUseSync(a){a?(storeItem(USE_SYNC,"true"),storage_location=chrome.storage.sync):(storeItem(USE_SYNC,""),storage_location=chrome.storage.local)}
function getUseSync(){var a=getItem(USE_SYNC);return a&&"true"==a}function setReportErrors(a){storeItem(REPORT_ERRORS_IDENTIFIER,""+a)}function getReportErrors(){var a=getItem(REPORT_ERRORS_IDENTIFIER);return!a||"true"==a}function setSpoofPerTab(a){storeItem(USE_SPOOF_PER_TAB,""+a)}function getSpoofPerTab(){var a=getItem(USE_SPOOF_PER_TAB);return a&&"true"==a}function setPermanentSpoofOverride(a){storeItem(PERMANENT_OVERRIDE,""+a)}
function getPermanentSpoofOverride(){var a=getItem(PERMANENT_OVERRIDE);return a&&"true"==a}function getErrors(){var a=getItem(ERROR_IDENTIFIER);return a=a?JSON.parse(a):{}}function recordError(a,c){var b=getErrors();b[a]=b[a]?parseInt(b[a])+1:1;storeItem(ERROR_IDENTIFIER,JSON.stringify(b))}function clearErrors(){storeItem(ERROR_IDENTIFIER,JSON.stringify({}))}function generateTestError(){recordError(TEST_ERROR_CODE,"")}
function updateCache(a){_getUserAgentList(function(c){user_agent_cache=c;_getSpoofList(function(b){spoof_cache=b;return a()})})}function _getUserAgentPointerList(a){getStorageLocation().get(CUSTOM_OPTIONS_IDENTIFIER,function(c){if(a)return a(c?c[""+CUSTOM_OPTIONS_IDENTIFIER]:[])})}function _getUserAgentByKey(a,c){getStorageLocation().get(a,function(b){return c(b[a])})}
function _getUserAgentList(a){_getUserAgentPointerList(function(c){if(!c||0==c.length)return a([]);getStorageLocation().get(c,function(b){var c=[],e;for(e in b)c.push(b[e]);return a(c)})})}
function _addUserAgent(a,c){_getUserAgentPointerList(function(b){b||(b=[]);if(!a.key||""==a.key){var d=0;if(b&&0<b.length)for(var e=0;e<b.length;e++){var f=parseInt(b[e].substring(CUSTOM_OPTIONS_LIST_PREFIX.length));f>=d&&(d=f)}a.key=CUSTOM_OPTIONS_LIST_PREFIX+(d+1)}d={};d[""+a.key]=a;getStorageLocation().set(d,function(){b.push(a.key);var d={};d[""+CUSTOM_OPTIONS_IDENTIFIER]=b;c=c?c:function(){};getStorageLocation().set(d,function(){updateCache(c)})})})}
function _addMultipleUserAgents(a,c){if(!a||0==a.length)return c();_getUserAgentPointerList(function(b){b=b?b:[];var d=0;if(b&&0<b.length)for(var e=0;e<b.length;e++){var f=parseInt(b[e].substring(CUSTOM_OPTIONS_LIST_PREFIX.length));f>=d&&(d=f)}for(e=0;e<a.length;e++)a[e].key=CUSTOM_OPTIONS_LIST_PREFIX+(d+1+e);var g=function(a,b,c){if(!a||0==a.length)return c(b);getPercentOfStorageUsed(function(a){a>MAX_MEMORY_USAGE&&(recordError(OUT_OF_SPACE,""),console.log("Error in adding user-agents: ran out of space."))});
var d=a.pop();if(!d)return c(b);var e=d.key;if(!e)return console.log("User agent does not have a key -- bailing out."),c(b);var f={};f[""+e]=d;getStorageLocation().set(f,function(){chrome.runtime.lastError?(recordError(OUT_OF_SPACE,""),console.log("Error in adding user-agent: "+d.title),console.log("We likely hit the maximum writes per hour."),updateCache(c(b))):(b.push(""+e),g(a,b,c))})};g(a,b,function(a){if(null==a)recordError(THROTTLED_WRITES,"");else{var b={};b[""+CUSTOM_OPTIONS_IDENTIFIER]=a;
c=c?c:function(){};getStorageLocation().set(b,function(){updateCache(c)})}})})}function _deleteUserAgentByKey(a,c){_getUserAgentPointerList(function(b){for(var d=0;d<b.length;d++)if(b[d]==a){b.splice(d,1);break}getStorageLocation().set({CUSTOM_OPTIONS_IDENTIFIER:b},function(){getStorageLocation().remove(a,function(){updateCache(c)})})})}function _getSpoofPointerList(a){getStorageLocation().get(SPOOF_OPTIONS_IDENTIFIER,function(c){a&&a(c?c[""+SPOOF_OPTIONS_IDENTIFIER]:[])})}
function _getSpoofList(a){_getSpoofPointerList(function(c){if(!c||0==c.length)return a([]);getStorageLocation().get(c,function(b){var c=[],e;for(e in b)c.push(b[e]);a(c)})})}
function _addSpoof(a,c){a?_getSpoofPointerList(function(b){b=b?b:[];if(!a.key||""==a.key){var d=0;if(b&&0<b.length)for(var e=0;e<b.length;e++){var f=parseInt(b[e].substring(SPOOF_OPTIONS_LIST_PREFIX.length));f>=d&&(d=f)}a.key=SPOOF_OPTIONS_LIST_PREFIX+(d+1)}d={};d[""+a.key]=a;getStorageLocation().set(d,function(){b.push(a.key);var d={};d[""+SPOOF_OPTIONS_IDENTIFIER]=b;c=c?c:function(){};getStorageLocation().set(d,function(){updateCache(c)})})}):console.log("Preset spoof to add doesn't exist, bailing.")}
function _addMultipleSpoofs(a,c){if(!a||0==a.length)return c();_getSpoofPointerList(function(b){b=b?b:[];var d=0;if(b&&0<b.length)for(var e=0;e<b.length;e++){var f=parseInt(b[e].substring(SPOOF_OPTIONS_LIST_PREFIX.length));f>=d&&(d=f)}for(e=0;e<a.length;e++)a[e].key=SPOOF_OPTIONS_LIST_PREFIX+(d+1+e);var g=function(a,b,c){a&&0!=a.length||c(b);getPercentOfStorageUsed(function(a){a>MAX_MEMORY_USAGE&&console.log("Error in adding spoofs: Ran out of space")});var d=a.pop();if(!d)return c(b);var e=d.key;
if(!e)return console.log("Spoof does not have a key.  Bailing out."),c(b);var f={};f[""+e]=d;getStorageLocation().set(f,function(){chrome.runtime.lastError?(console.log("Error in adding user-agents: "+chrome.runtime.lastError),console.log("We likely hit the maximum writes per hour."),recordError(THROTTLED_WRITES,""),updateCache(c(b,a))):(b.push(""+e),g(a,b,c))})};g(a,b,function(a){if(null==a)recordError(MIGRATION_FAILED_THROTTLED_SPOOFS,"");else{var b={};b[""+SPOOF_OPTIONS_IDENTIFIER]=a;c=c?c:function(){};
getStorageLocation().set(b,function(){updateCache(c)})}})})}function _deleteSpoofByKey(a,c){_getSpoofPointerList(function(b){for(var d=0;d<b.length;d++)if(b[d]==a){b.splice(d,1);break}getStorageLocation().set({SPOOF_OPTIONS_IDENTIFIER:b},function(){getStorageLocation().remove(a,function(){updateCache(c)})})})}function getOptionsByGroup(a){_getUserAgentList(function(c){for(var b={},d=0;d<c.length;d++)if(c[d]){var e=getUserAgentGroup(c[d]);b[e]||(b[e]=[]);b[e].push(c[d])}a(b)})}
function findHostname(a){var c=document.createElement("a");c.href=a;return c.host}function isDomainName(a){return/^(https?:\/\/)?((([a-zd]([a-zd-]*[a-zd])*).)+[a-z]{2,}|((d{1,3}.){3}d{1,3}))(:d+)?(\/[-a-zd%_.~+]*)*$/i.test(a)}
function getBaseOptionsList(a,c){var b=[];c=c?c:function(){};b.push(new UserAgent("Default","","","",!0,"Chrome"));b.push(new UserAgent("Windows Firefox 3.5","Mozilla/5.0 (Windows; U; Windows NT 6.0; en; rv:1.9.1.7) Gecko/20091221 Firefox/3.5.7","Mozilla, Inc.","FF3",!0,"Firefox"));b.push(new UserAgent("Windows Firefox 4","Mozilla/5.0 (Windows NT 6.1; rv:2.0.1) Gecko/20100101 Firefox/4.0.1","Mozilla, Inc.","FF4",!0,"Firefox"));b.push(new UserAgent("Windows Firefox 15","Mozilla/5.0 (Windows NT 6.1; WOW64; rv:15.0) Gecko/20120427 Firefox/15.0a1",
"Mozilla, Inc.","F15",!0,"Firefox"));b.push(new UserAgent("Opera 10","Opera/9.80 (Macintosh; Intel Mac OS X; U; en) Presto/2.2.15 Version/10.00","Mozilla, Inc.","O10",!0,"Opera"));b.push(new UserAgent("OSX Safari 5","Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/534.55.3 (KHTML, like Gecko) Version/5.1.3 Safari/534.53.10","Apple, Inc.","S5",!0,"Safari"));b.push(new UserAgent("Internet Explorer 6","Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.0; WOW64; Trident/4.0; SLCC1)","Microsoft",
"IE6",!0,"Internet Explorer"));b.push(new UserAgent("Internet Explorer 7","Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0; WOW64; Trident/4.0; SLCC1)","Microsoft","IE7",!0,"Internet Explorer"));b.push(new UserAgent("Internet Explorer 8","Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.0; WOW64; Trident/4.0; SLCC1)","Microsoft","IE8",!0,"Internet Explorer"));b.push(new UserAgent("Internet Explorer 9","Mozilla/5.0 (MSIE 9.0; Windows NT 6.1; Trident/5.0)","Microsoft","IE9",!0,"Internet Explorer"));
b.push(new UserAgent("iPhone 4","Mozilla/5.0 (iPhone; U; CPU iPhone OS 4_3_2 like Mac OS X; en-us) AppleWebKit/533.17.9 (KHTML, like Gecko) Version/5.0.2 Mobile/8H7 Safari/6533.18.5","Apple, Inc.","IP4",!0,"iOS"));b.push(new UserAgent("iPad","Mozilla/5.0 (iPad; U; CPU OS 3_2 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Version/4.0.4 Mobile/7B334b Safari/531.21.10","Apple, Inc.","iPad",!0,"iOS"));b.push(new UserAgent("Android 4.1 - Nexus 7","Mozilla/5.0 (Linux; Android 4.1.1; Nexus 7 Build/JRO03D) AppleWebKit/535.19 (KHTML, like Gecko) Chrome/18.0.1025.166  Safari/535.19",
"","AND",!0,"Android"));b.push(new UserAgent("Windows Phone 7","Mozilla/5.0 (compatible; MSIE 9.0; Windows Phone OS 7.5; Trident/5.0; IEMobile/9.0; NOKIA; Lumia 800)","","WP7",!0,"Windows Phone"));a&&_getUserAgentList(function(a){for(var e=[],f=0;f<a.length;f++)e.push(a[f].key);e&&0<e.length?getStorageLocation().remove(e,function(){getStorageLocation().remove(CUSTOM_OPTIONS_IDENTIFIER,function(){_addMultipleUserAgents(b,c)})}):_addMultipleUserAgents(b,c)});c(b)}
function __addBaseOption(a){a&&0!=a.length&&_addUserAgent(a.pop(),function(){__addBaseOption(a)})}function addCustomUAOption(a,c,b,d,e,f){a=new UserAgent(a,c,"",d,!1,e);a.append_to_default_ua=b;_addUserAgent(a,f)}function deleteCustomUAOption(a,c){_getUserAgentList(function(b){for(var d=0;d<b.length;d++)if(b[d].title==a){_deleteUserAgentByKey(b[d].key,c);break}})}function isRemovable(a){return!isDefault(a)}
function getDisplayUserAgentString(a){return""==a.ua_string?"[Use default User-agent string]":a.ua_string}function getDisplayAppendOrReplaceString(a){return""==a.ua_string?"N/A":a.append_to_default_ua?"Append":"Replace"}
function guessUserAgentGroup(a){if(!a)return"";for(var c=[["Chrome","Chrome"],["Firefox","Firefox"],["Opera","Opera"],["Safari","Safari"],["IE","Internet Explorer"],["Internet Explorer","Internet Explorer"],["iPhone","iPhone"],["iPad","iPad"],["iOS","iOS"]],b=0;b<c.length;b++)if(-1<a.toUpperCase().indexOf(c[b][0].toUpperCase()))return c[b][1];return""}function getUserAgentGroup(a){return a?a.group?a.group:"":""}
function importUserAgentData(a,c){_getUserAgentList(function(b){for(var d=0,e=0,f={},g=0;g<b.length;g++)f[b[g].ua_string]="1";var h=[];$("useragent",a).each(function(){var a=new UserAgent($(this).attr("description"),$(this).attr("useragent"),"","X",!1,_getParentFolderName($(this).parent()));"UA List :: About"!=a.group&&(f[a.ua_string]?e++:d<MAX_IMPORT_COUNT&&(f[a.ua_string]="1",h.push(a),d++))});_addMultipleUserAgents(h,c({import_count:d,duplicates:e}))})}
function _getParentFolderName(a){var c=$(a)&&0<$(a).parent().length?_getParentFolderName($(a).parent()):null;a=$(a).attr("description");return c?c+" - "+a:a?a:null}function getHotlistMap(){var a=getItem(HOTLIST_INDEX);return a=a?JSON.parse(a):{}}function getHotlistIndex(a,c){return getHotlistIndexById(a.id,c)}
function getHotlistIndexById(a,c){if(!a)return console.log("no tab provided, returning nothing"),null;var b=getHotlistMap();getSpoofPerTab()||(a=NO_SPOOF_PER_TAB);b=b[a]?b[a]:null;c&&c(b);return b}function setHotlistIndex(a,c){if(a&&a.id){var b=getSpoofPerTab()?a.id:NO_SPOOF_PER_TAB,d=getHotlistMap();d[b]=c;console.log("Storing "+c+" under tab "+b);storeItem(HOTLIST_INDEX,JSON.stringify(d));updateCache(function(){})}else console.log("no tab passed, not saving anything.")}
function getHotlist(a,c){getHotlistIndex(a,function(a){a&&""!=a?_getUserAgentByKey(a,c):c(null)})}function setHotlist(a,c){setHotlistIndex(a,c)}
function _reportErrors(){req=new XMLHttpRequest;req.open("POST",error_url,!0);req.setRequestHeader("Accept","text/plain");req.onreadystatechange=function(){if(4==req.readyState)if(200==req.status||req.responseText)try{JSON.parse(req.responseText),console.log("Error reporting succeeded"),clearErrors()}catch(a){console.log("Update failed: "+a),console.log("response text:"+req.responseText)}else console.log("Update failed.  Will re-attempt later.")};var a="cv="+_getChromeVersion()+"&ev="+chrome.app.getDetails().version+
"&",c=getErrors(),b=0,d;for(d in ERROR_CODES)c[d]&&(a=a+d+"="+c[d]+"&",b++);b&&(console.log("error string is"+a),req.setRequestHeader("Content-type","application/x-www-form-urlencoded"),req.send(a))}function _getChromeVersion(){return/Chrome\/[0-9\.]*/.exec(window.navigator.userAgent)}function getPresets(){if(shouldUsePresets()){var a=new Date;a.setDate(a.getDate()-1);if(!last_update_time||a>last_update_time)last_update_time=new Date}}function clearPresets(){}
function getBadge(a,c){a&&""!=a||c("");_getUserAgentList(function(b){for(var d=0;d<b.length;d++)if(b[d].ua_string==a){c(b[d].badge);return}c("")})}function _addOption(a,c,b){console.log("Adding new preset spoof with key of "+c);getStorageLocation().get(c,function(d){(d=d[c])&&""!=d||(d=new UserAgent("","","","",!0,""));console.log("Adding new preset spoof with "+d);_addSpoof(new PresetSpoof(a,d),b)})}
function _isApplicableMatch(a,c){if(!c)return!1;var b=findHostname(c),d=isDomainName(a),e=RegExp(a);return!d&&e.test(c)||e.test(b)||a==b||a==c||d&&-1<b.indexOf(a)}function getSpoofValuesForUrl(a,c){a?_getSpoofList(function(b){for(var d=0;d<b.length;d++)if(a&&b[d]&&b[d].domain&&b[d].user_agent&&_isApplicableMatch(b[d].domain,a)){c(b[d].user_agent);return}c(null)}):c(null)}function isDefault(a){return!a||""==a.ua_string}
function getSpoofValues(a,c){var b=getPermanentSpoofOverride();chrome.tabs.getSelected(function(d){getHotlist(d,function(d){getSpoofValuesForUrl(a,function(a){(a=b?a?a:d:isDefault(d)?a:d)?(a.platform=getPlatformSpoofValues(a),a.appname=getAppnameSpoofValues(a),c(a)):c({})})})})}
function getCacheSpoofValuesForUrl(a){if(!a)return null;for(var c=spoof_cache,b=0;b<c.length;b++)if(a&&c[b]&&c[b].domain&&_isApplicableMatch(c[b].domain,a))return c[b].user_agent&&c[b].user_agent.ua_string?c[b].user_agent:"string"==typeof c[b].user_agent?new UserAgent("",c[b].user_agent,"","",!1,""):new UserAgent("","","","",!1,"");return null}
function getCacheSpoofValues(a,c){for(var b=getPermanentSpoofOverride(),d=getHotlistIndexById(c),e=null,f=0;f<user_agent_cache.length&&!e;f++)user_agent_cache[f].key==d&&(e=user_agent_cache[f]);isDefault(e)&&(e=null);d=getCacheSpoofValuesForUrl(a);if(b=b?d?d:e:e?e:d)b.platform=getPlatformSpoofValues(b),b.appname=getAppnameSpoofValues(b);return b}function getPlatformSpoofValues(a){for(var c in PLATFORM_SPOOF)if(a&&a.ua_string&&-1<a.ua_string.indexOf(c))return PLATFORM_SPOOF[c];return null}
function getAppnameSpoofValues(a){return a&&a.ua_string&&-1<a.ua_string.indexOf("MSIE")?"Microsoft Internet Explorer":"Netscape"}function updateBadge(a){a&&getSpoofValues(a.url,function(c){var b="";c&&c.badge&&""!=c.badge&&(b=c.badge);chrome.browserAction.setBadgeText({tabId:a.id,text:b})})};