try{
var g,aa=aa||{},k=this,ba="closure_uid_"+(1E9*Math.random()>>>0),m=Date.now||function(){return+new Date};
}catch(e){_DumpException(e)}
try{
k.ace_i18n={chrome_ext_short_name:{message:"Hangouts"},chrome_ext_description:{message:"Hangouts brings conversations to life with photos, emoji, and even group video calls for free."},quasar_chat_toast_info:{message:"Click to go to page..."},quasar_answer_button_text:{message:"Answer"},quasar_decline_button_text:{message:"Decline"},quasar_help:{message:"Help"},quasar_legend_startup_shutdown:{message:"Application"},chrome_ext_run_at_browser_start:{message:"Sign in to Hangouts when Chrome starts"},
chrome_ext_run_after_browser_close:{message:"Allow background mode"},chrome_ext_new_windows_topmost:{message:"Keep Hangouts on top of other windows"},quasar_label_tray_icon:{message:"Show system tray icon"},quasar_legend_notifications:{message:"Notifications"},quasar_label_all_notification:{message:"Disable notifications"},quasar_label_chat_notification:{message:"Disable chat notifications"},quasar_label_toast_timeout_chat:{message:"Allow chat notifications to timeout automatically"},quasar_label_toast_duration_chat:{message:"Timeout length (in seconds):"},
quasar_button_save:{message:"Ok"},quasar_button_apply:{message:"Apply"},quasar_button_cancel:{message:"Cancel"},chrome_ext_menutext_feedback:{message:"Send feedback"},quasar_feedback_server_uri:{message:"https://www.google.com/tools/feedback"},chrome_ext_feedback_subtitle:{message:"Send feedback"},chrome_ext_feedback_comments:{message:"Comments"},quasar_feedback_system_legend:{message:"System Information"},quasar_feedback_platform_label:{message:"Platform:"},quasar_feedback_user_agent_label:{message:"User Agent:"},
quasar_feedback_privacy_legend:{message:"Privacy Statement"},quasar_feedback_privacy_text:{message:"The description, product information, additional information and your email address will be sent to Google. See the Google Feedback Terms of Service. By submitting this content you are granting to Google the right to use it to improve our products and services. See our Privacy Policy."},quasar_feedback_submit_button:{message:"Send Feedback"},quasar_feedback_cancel_button:{message:"Cancel"},quasar_video_title:{message:"Video call from $1...",
placeholders:{1:{content:"$1"}}},quasar_voice_title:{message:"Voice call from $1...",placeholders:{1:{content:"$1"}}},quasar_group_chat_title:{message:"From group chat..."},quasar_chat_title:{message:"$1 says...",placeholders:{1:{content:"$1"}}},quasar_hangout_title:{message:"$1 is hanging out",placeholders:{1:{content:"$1"}}},chrome_ext_oneonone_plus_hangout_details:{message:"is video calling you via Hangouts"},chrome_ext_group_plus_hangout_details:{message:"has invited you to a group Hangout video call"},
quasar_video_details:{message:"is calling you with video chat"},quasar_voice_details:{message:"is calling you"},quasar_tip_connected:{message:"Status: Connected"},chrome_ext_tip_connected_missed_messages:{message:"Status: Connected\nMissed messages"},quasar_tip_connecting:{message:"Status: Connecting"},quasar_tip_reconnecting:{message:"Status: Reconnecting"},quasar_tip_disconnected:{message:"Status: Disconnected"},quasar_tip_not_login:{message:"Status: Not logged in"},quasar_tip_not_load:{message:"Status: Loading error"},
chrome_ext_menutext_unsigned_user:{message:"Not signed in"},quasar_menutext_unknown_user:{message:"Unknown"},quasar_menutext_feedback:{message:"Feedback"},quasar_menutext_settings:{message:"Options"},quasar_menutext_quit:{message:"Exit"},quasar_menutext_signout:{message:"Sign out"},chrome_ext_cannot_connect:{message:"Unable to connect to Google. Please check your internet connection."},quasar_try_now:{message:"Try now"},quasar_sign_in_to_start_talking:{message:"Sign in to start talking with friends"}, quasar_sign_in:{message:"Sign in"}};

}catch(e){_DumpException(e)}
try{
var p=function(a){return void 0!==a},ca=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},da=function(a,b,c){return a.call.apply(a.bind,arguments)},fa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);
if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},q=function(a,b){function c(){}c.prototype=b.prototype;
a.q=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Jd=function(a,c,f){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}},ga=function(a,b){var c=a.split("."),d=k;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&p(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}},r=function(a,b,c){r=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?da:ca;return r.apply(null,arguments)},ha=function(a){var b=typeof a;
return"object"==b&&null!=a||"function"==b},s=function(a){return"function"==fa(a)},ia=function(a){return"number"==typeof a},t=function(a){return"string"==typeof a},ja=function(a){var b=fa(a);return"array"==b||"object"==b&&"number"==typeof a.length},u=function(a){return"array"==fa(a)},ka=function(){},ma=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,ma);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};q(ma,Error);ma.prototype.name="CustomError";
var oa=function(a,b){for(var c=0,d=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),e=String(b).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),f=Math.max(d.length,e.length),h=0;0==c&&h<f;h++){var l=d[h]||"",n=e[h]||"",B=RegExp("(\\d*)(\\D*)","g"),K=RegExp("(\\d*)(\\D*)","g");do{var X=B.exec(l)||["","",""],R=K.exec(n)||["","",""];if(0==X[0].length&&0==R[0].length)break;c=na(0==X[1].length?0:parseInt(X[1],10),0==R[1].length?0:parseInt(R[1],10))||na(0==X[2].length,0==R[2].length)||na(X[2], R[2])}while(0==c)}return c},na=function(a,b){return a<b?-1:a>b?1:0};
var v=Array.prototype,pa=v.indexOf?function(a,b,c){return v.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(t(a))return t(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},qa=v.lastIndexOf?function(a,b,c){return v.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(t(a))return t(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;
return-1},w=v.forEach?function(a,b,c){v.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},ra=v.filter?function(a,b,c){return v.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,h=t(a)?a.split(""):a,l=0;l<d;l++)if(l in h){var n=h[l];b.call(c,n,l,a)&&(e[f++]=n)}return e},sa=v.map?function(a,b,c){return v.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=t(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,
f[h],h,a));return e},ta=v.reduce?function(a,b,c,d){d&&(b=r(b,d));return v.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;w(a,function(c,h){e=b.call(d,e,c,h,a)});return e},ua=v.some?function(a,b,c){return v.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1},va=function(a,b){var c=pa(a,b),d;(d=0<=c)&&v.splice.call(a,c,1);return d};
var wa=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;var xa=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},ya=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},za=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};var x=function(){},y=function(a,b,c,d){a.a={};b||(b=c?[c]:[]);a.n=c?String(c):void 0;a.b=0===c?-1:0;a.G=b;t:{if(a.G.length&&(b=a.G.length-1,(c=a.G[b])&&"object"==typeof c&&"number"!=typeof c.length)){a.e=b-a.b;a.c=c;break t}a.e=Number.MAX_VALUE}if(d)for(b=0;b<d.length;b++)c=d[b],c<a.e?(c+=a.b,a.G[c]=a.G[c]||[]):a.c[c]=a.c[c]||[]},z=function(a,b){return b<a.e?a.G[b+a.b]:a.c[b]};x.prototype.toString=function(){return this.G.toString()};var A=function(a,b){Aa[a]=b;b.messageId=a},Aa={};
var Ba="StopIteration"in k?k.StopIteration:Error("f"),Ca=function(){};Ca.prototype.next=function(){throw Ba;};Ca.prototype.ha=function(){return this};var Da;t:{var Ea=k.navigator;if(Ea){var Fa=Ea.userAgent;if(Fa){Da=Fa;break t}}Da=""}var Ga=function(a){return-1!=Da.indexOf(a)};var C=function(a,b){this.a={};this.b=[];this.e=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("h");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof C?(c=a.M(),d=a.A()):(c=za(a),d=ya(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};g=C.prototype;g.V=function(){return this.c};g.A=function(){Ha(this);for(var a=[],b=0;b<this.b.length;b++)a.push(this.a[this.b[b]]);return a};g.M=function(){Ha(this);return this.b.concat()};g.P=function(){return 0==this.c};
g.clear=function(){this.a={};this.e=this.c=this.b.length=0};g.remove=function(a){return Ia(this.a,a)?(delete this.a[a],this.c--,this.e++,this.b.length>2*this.c&&Ha(this),!0):!1};var Ha=function(a){if(a.c!=a.b.length){for(var b=0,c=0;b<a.b.length;){var d=a.b[b];Ia(a.a,d)&&(a.b[c++]=d);b++}a.b.length=c}if(a.c!=a.b.length){for(var e={},c=b=0;b<a.b.length;)d=a.b[b],Ia(e,d)||(a.b[c++]=d,e[d]=1),b++;a.b.length=c}};g=C.prototype;g.get=function(a,b){return Ia(this.a,a)?this.a[a]:b};
g.set=function(a,b){Ia(this.a,a)||(this.c++,this.b.push(a),this.e++);this.a[a]=b};g.forEach=function(a,b){for(var c=this.M(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};g.clone=function(){return new C(this)};g.ha=function(a){Ha(this);var b=0,c=this.b,d=this.a,e=this.e,f=this,h=new Ca;h.next=function(){for(;;){if(e!=f.e)throw Error("i");if(b>=c.length)throw Ba;var h=c[b++];return a?h:d[h]}};return h};var Ia=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
var Ja=function(a){if("function"==typeof a.A)return a.A();if(t(a))return a.split("");if(ja(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return ya(a)},Ka=function(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(ja(a)||t(a))w(a,b,c);else{var d;if("function"==typeof a.M)d=a.M();else if("function"!=typeof a.A)if(ja(a)||t(a)){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else d=za(a);else d=void 0;for(var e=Ja(a),f=e.length,h=0;h<f;h++)b.call(c,e[h],d&&d[h],a)}};
var La=Ga("Opera")||Ga("OPR"),D=Ga("Trident")||Ga("MSIE"),Ma=Ga("Gecko")&&-1==Da.toLowerCase().indexOf("webkit")&&!(Ga("Trident")||Ga("MSIE")),Na=-1!=Da.toLowerCase().indexOf("webkit"),Oa=k.navigator||null,Pa=Oa&&Oa.platform||"",Qa=function(){var a=k.document;return a?a.documentMode:void 0},Ra=function(){var a="",b;if(La&&k.opera)return a=k.opera.version,s(a)?a():a;Ma?b=/rv\:([^\);]+)(\)|;)/:D?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:Na&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(Da))?a[1]:"");return D&&(b= Qa(),b>parseFloat(a))?String(b):a}(),Sa={},Ta=function(a){return Sa[a]||(Sa[a]=0<=oa(Ra,a))},Ua=k.document,Va=Ua&&D?Qa()||("CSS1Compat"==Ua.compatMode?parseInt(Ra,10):5):void 0;
var E=function(){};E.prototype.D=!1;E.prototype.Eb=function(){return this.D};E.prototype.B=function(){this.D||(this.D=!0,this.l())};E.prototype.l=function(){if(this.t)for(;this.t.length;)this.t.shift()()};var F=function(a){a&&"function"==typeof a.B&&a.B()};
var Wa=!D||D&&9<=Va;!Ma&&!D||D&&D&&9<=Va||Ma&&Ta("1.9.1");D&&Ta("9");var Xa=function(a){Xa[" "](a);return a};Xa[" "]=ka;var Ya=function(a,b){try{return Xa(a[b]),!0}catch(c){}return!1};var Za=!D||D&&9<=Va,$a=D&&!Ta("9");!Na||Ta("528");Ma&&Ta("1.9b")||D&&Ta("8")||La&&Ta("9.5")||Na&&Ta("528");Ma&&!Ta("8")||D&&Ta("9");var G=function(a,b){this.type=a;this.a=this.target=b;this.wc=!0};G.prototype.B=function(){};G.prototype.b=function(){this.wc=!1};var ab=function(a,b){G.call(this,a?a.type:"");this.a=this.target=null;this.clientY=this.clientX=0;this.c=this.state=null;if(a){this.type=a.type;this.target=a.target||a.srcElement;this.a=b;var c=a.relatedTarget;c&&Ma&&Ya(c,"nodeName");this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:a.pageY;this.state=a.state;this.c=a;a.defaultPrevented&&this.b()}};q(ab,G); ab.prototype.b=function(){ab.q.b.call(this);var a=this.c;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,$a)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var bb="closure_listenable_"+(1E6*Math.random()|0),cb=function(a){return!(!a||!a[bb])},db=0;var eb=function(a,b,c,d,e){this.qa=a;this.proxy=null;this.src=b;this.type=c;this.Ya=!!d;this.fb=e;this.key=++db;this.removed=this.Xa=!1},fb=function(a){a.removed=!0;a.qa=null;a.proxy=null;a.src=null;a.fb=null};var gb=function(a){this.src=a;this.a={};this.b=0};gb.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var h=hb(a,b,d,e);-1<h?(b=a[h],c||(b.Xa=!1)):(b=new eb(b,this.src,f,!!d,e),b.Xa=c,a.push(b));return b};gb.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=hb(e,b,c,d);return-1<b?(fb(e[b]),v.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var ib=function(a,b){var c=b.type;if(!(c in a.a))return!1;var d=va(a.a[c],b);d&&(fb(b),0==a.a[c].length&&(delete a.a[c],a.b--));return d};gb.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,fb(d[e]);delete this.a[c];this.b--}return b}; var jb=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=hb(a,c,d,e));return-1<b?a[b]:null},hb=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.qa==b&&f.Ya==!!c&&f.fb==d)return e}return-1};
var kb="closure_lm_"+(1E6*Math.random()|0),lb={},mb=0,nb=function(a,b,c,d,e){if(u(b)){for(var f=0;f<b.length;f++)nb(a,b[f],c,d,e);return null}c=ob(c);return cb(a)?a.listen(b,c,d,e):pb(a,b,c,!1,d,e)},pb=function(a,b,c,d,e,f){if(!b)throw Error("l");var h=!!e,l=qb(a);l||(a[kb]=l=new gb(a));c=l.add(b,c,d,e,f);if(c.proxy)return c;d=rb();c.proxy=d;d.src=a;d.qa=c;a.addEventListener?a.addEventListener(b.toString(),d,h):a.attachEvent(sb(b.toString()),d);mb++;return c},rb=function(){var a=tb,b=Za?function(c){return a.call(b.src,
b.qa,c)}:function(c){c=a.call(b.src,b.qa,c);if(!c)return c};return b},ub=function(a,b,c,d,e){if(u(b))for(var f=0;f<b.length;f++)ub(a,b[f],c,d,e);else c=ob(c),cb(a)?a.Mb(b,c,d,e):a&&(a=qb(a))&&(b=jb(a,b,c,!!d,e))&&vb(b)},vb=function(a){if(ia(a)||!a||a.removed)return!1;var b=a.src;if(cb(b))return ib(b.U,a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.Ya):b.detachEvent&&b.detachEvent(sb(c),d);mb--;(c=qb(b))?(ib(c,a),0==c.b&&(c.src=null,b[kb]=null)):fb(a);return!0},sb=function(a){return a in
lb?lb[a]:lb[a]="on"+a},xb=function(a,b,c,d){var e=1;if(a=qb(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.Ya==c&&!f.removed&&(e&=!1!==wb(f,d))}return Boolean(e)},wb=function(a,b){var c=a.qa,d=a.fb||a.src;a.Xa&&vb(a);return c.call(d,b)},tb=function(a,b){if(a.removed)return!0;if(!Za){var c;if(!(c=b))t:{c=["window","event"];for(var d=k,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break t}c=d}e=c;c=new ab(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){t:{var f=
!1;if(0==e.keyCode)try{e.keyCode=-1;break t}catch(h){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.a;f;f=f.parentNode)e.push(f);for(var f=a.type,l=e.length-1;0<=l;l--)c.a=e[l],d&=xb(e[l],f,!0,c);for(l=0;l<e.length;l++)c.a=e[l],d&=xb(e[l],f,!1,c)}return d}return wb(a,new ab(b,this))},qb=function(a){a=a[kb];return a instanceof gb?a:null},yb="__closure_events_fn_"+(1E9*Math.random()>>>0),ob=function(a){if(s(a))return a;a[yb]||(a[yb]=function(b){return a.handleEvent(b)});return a[yb]};
var zb=function(a){y(this,a,"h_cc",[])};q(zb,x);A("h_cc",zb);zb.prototype.Y=function(){return z(this,19)};var H=function(a){this.J=a;this.g={}};q(H,E);var Ab=[];H.prototype.listen=function(a,b,c,d){return Bb(this,a,b,c,d)};var Bb=function(a,b,c,d,e,f){u(c)||(c&&(Ab[0]=c.toString()),c=Ab);for(var h=0;h<c.length;h++){var l=nb(b,c[h],d||a.handleEvent,e||!1,f||a.J||a);if(!l)break;a.g[l.key]=l}return a};
H.prototype.Mb=function(a,b,c,d,e){if(u(b))for(var f=0;f<b.length;f++)this.Mb(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.J||this,c=ob(c),d=!!d,b=cb(a)?jb(a.U,String(b),c,d,e):a?(a=qb(a))?jb(a,b,c,d,e):null:null,b&&(vb(b),delete this.g[b.key]);return this};H.prototype.removeAll=function(){xa(this.g,vb);this.g={}};H.prototype.l=function(){H.q.l.call(this);this.removeAll()};H.prototype.handleEvent=function(){throw Error("m");};
var I=function(){this.U=new gb(this);this.L=this;this.u=null};q(I,E);I.prototype[bb]=!0;g=I.prototype;g.addEventListener=function(a,b,c,d){nb(this,a,b,c,d)};g.removeEventListener=function(a,b,c,d){ub(this,a,b,c,d)};g.l=function(){I.q.l.call(this);this.U&&this.U.removeAll(void 0);this.u=null};g.listen=function(a,b,c,d){return this.U.add(String(a),b,!1,c,d)};g.Mb=function(a,b,c,d){return this.U.remove(String(a),b,c,d)}; g.da=function(a,b,c){a=this.U.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.Ya==b){var h=f.qa,l=f.fb||f.src;f.Xa&&ib(this.U,f);d=!1!==h.call(l,c)&&d}}return d&&!1!=c.wc};
var Cb,Db,Eb,Fb,Gb,Hb,Ib;Ib=Hb=Gb=Fb=Eb=Db=Cb=!1;var Jb=Da;Jb&&(-1!=Jb.indexOf("Firefox")?Cb=!0:-1!=Jb.indexOf("Camino")?Db=!0:-1!=Jb.indexOf("iPhone")||-1!=Jb.indexOf("iPod")?Eb=!0:-1!=Jb.indexOf("iPad")?Fb=!0:-1!=Jb.indexOf("Chrome")?Hb=!0:-1!=Jb.indexOf("Android")?Gb=!0:-1!=Jb.indexOf("Safari")&&(Ib=!0));var Kb=Cb,Lb=Db,Ob=Eb,Pb=Fb,Qb=Gb,Rb=Hb,Sb=Ib;
var J=function(a){this.a=a};J.prototype.toString=function(){return this.a};var Tb=new J("b"),Ub=new J("c"),Vb=new J("h"),Wb=new J("k"),Xb=new J("G"),Yb=new J("M"),Zb=new J("N");var $b=new J("ea");var ac=function(a,b){for(var c=[],d=0;d<arguments.length;d++)c.push(arguments[d]||"");return c.join("_;_")},bc=function(){return 0<=navigator.userAgent.indexOf("CrOS")};var cc=function(a,b){this.e=a||"e";this.c=null!=a&&"p"==a?"e":"p";this.a=this.f=null;this.h=b||"u";this.b=this.t=null;this.g=[]};cc.prototype.message=function(){var a={};a.i=this.b;a.m=this.g;a.r=this.h;a.o=this.t;a.s=this.a;a.st=this.c;a.d=this.f;a.dt=this.e;return a};ga("ace.base.Message.prototype.message",cc.prototype.message);
var dc=function(a,b){for(var c in b)switch(c){case "r":a.h=b[c];break;case "i":a.b=b[c];break;case "m":a.g=b[c];break;case "o":a.t=b[c];break;case "s":a.a=b[c];break;case "d":a.f=b[c];break;case "st":a.c=b[c];break;case "dt":a.e=b[c]}return a},ec=function(a,b,c){null!=b&&(a.a=b,null!=c&&(a.c=c))},fc=function(a,b){null!=b&&(a.b=b)},gc=function(a,b){"object"==typeof b?a.g=b:a.g=[b]};cc.prototype.target=function(){return this.f};cc.prototype.content=function(){return this.g};
var hc=function(a,b,c,d,e){this.b=a;this.Ta=b;this.a=typeof b;this.Hb=c?c:!1;this.ba=!0;this.Cb=d?d:!1;this.vb=e?e:!1};q(hc,E);g=hc.prototype;g.l=function(){hc.q.l.call(this);this.b="";this.Ta=null;this.a=""};g.id=function(){return this.b};g.type=function(){return this.a};g.F=function(){return this.Ta};g.setEnabled=function(a){this.ba=a};
var ic=function(a){return(a=a.exec(Da))?a[1]:""},jc=function(){if(Kb)return ic(/Firefox\/([0-9.]+)/);if(D||La)return Ra;if(Rb)return ic(/Chrome\/([0-9.]+)/);if(Sb)return ic(/Version\/([0-9.]+)/);if(Ob||Pb){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(Da))return a[1]+"."+a[2]}else{if(Qb)return(a=ic(/Android\s+([0-9.]+)/))?a:ic(/Version\/([0-9.]+)/);if(Lb)return ic(/Camino\/([0-9.]+)/)}return""}();
var lc=function(a){this.a=new C;this.b=["https://talkgadget.google.com/talkgadget/notifier-js","","https://test.talkgadget.google.com/talkgadget/notifier-js?jsmode=debug_unobfuscated"];a&&kc(this,a)};q(lc,E);var mc=0<=oa(jc,"23.0.1262.0")&&!bc();lc.prototype.l=function(){lc.q.l.call(this);for(var a=this.a.M(),b=0;b<a.length;++b)F(this.a.get(a[b]));delete this.a};lc.prototype.getItem=function(a){return Ia(this.a.a,a)?this.a.get(a):null};lc.prototype.setItem=function(a){this.a.set(a.id(),a)}; var kc=function(a,b){for(var c in b){var d=b[c],e=null;Ia(a.a.a,c)?(e=a.a.get(c),e.Ta=d.value,d.changed&&(e.vb=d.changed)):(e=new hc(c,d.value,d.multiple,d.inverse,d.changed),e.setEnabled(!d.disabled));a.a.set(c,e)}};
var nc=function(a){k.setTimeout(function(){throw a;},0)},qc=function(a,b){var c=a;b&&(c=r(a,b));s(k.setImmediate)?k.setImmediate(c):(oc||(oc=pc()),oc(c))},oc,pc=function(){if(k.Promise&&k.Promise.resolve){var a=k.Promise.resolve();return function(b){a.then(function(){try{b()}catch(a){nc(a)}})}}var b=k.MessageChannel;"undefined"===typeof b&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&(b=function(){var a=document.createElement("iframe");a.style.display="none";a.src="";
document.documentElement.appendChild(a);var b=a.contentWindow,a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d=b.location.protocol+"//"+b.location.host,a=r(function(a){if(a.origin==d||a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof b){var c=new b,d={},e=d;c.port1.onmessage=function(){d=d.next;var a=d.Yb;d.Yb=null;a()};return function(a){e.next=
{Yb:a};e=e.next;c.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in document.createElement("script")?function(a){var b=document.createElement("script");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};document.documentElement.appendChild(b)}:function(a){k.setTimeout(a,0)}};
var vc=function(a,b){rc||(qc(sc),rc=!0);tc.push(new uc(a,b))},rc=!1,tc=[],sc=function(){for(;tc.length;){var a=tc;tc=[];for(var b=0;b<a.length;b++){var c=a[b];try{c.a.call(c.b)}catch(d){nc(d)}}}rc=!1},uc=function(a,b){this.a=a;this.b=b};var wc=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},xc=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var zc=function(a,b){this.b=0;this.g=void 0;this.a=this.c=null;this.e=this.f=!1;try{var c=this;a.call(b,function(a){yc(c,2,a)},function(a){yc(c,3,a)})}catch(d){yc(this,3,d)}},Bc=function(){var a,b=new zc(function(b){a=b});return new Ac(b,a)};zc.prototype.then=function(a,b,c){return Cc(this,s(a)?a:null,s(b)?b:null,c)};wc(zc);
var Fc=function(a){0==a.b&&vc(function(){var a=new Dc(void 0);Ec(this,a)},a)},Ec=function(a,b){if(0==a.b)if(a.c){var c=a.c;if(c.a){for(var d=0,e=-1,f=0,h;h=c.a[f];f++)if(h=h.Za)if(d++,h==a&&(e=f),0<=e&&1<d)break;0<=e&&(0==c.b&&1==d?Ec(c,b):(d=c.a.splice(e,1)[0],Gc(c,d,3,b)))}}else yc(a,3,b)},Ic=function(a,b){a.a&&a.a.length||2!=a.b&&3!=a.b||Hc(a);a.a||(a.a=[]);a.a.push(b)},Cc=function(a,b,c,d){var e={Za:null,qc:null,sc:null};e.Za=new zc(function(a,h){e.qc=b?function(c){try{var e=b.call(d,c);a(e)}catch(B){h(B)}}:
a;e.sc=c?function(b){try{var e=c.call(d,b);!p(e)&&b instanceof Dc?h(b):a(e)}catch(B){h(B)}}:h});e.Za.c=a;Ic(a,e);return e.Za};zc.prototype.t=function(a){this.b=0;yc(this,2,a)};zc.prototype.h=function(a){this.b=0;yc(this,3,a)};
var yc=function(a,b,c){if(0==a.b){if(a==c)b=3,c=new TypeError("Promise cannot resolve to itself");else{if(xc(c)){a.b=1;c.then(a.t,a.h,a);return}if(ha(c))try{var d=c.then;if(s(d)){Jc(a,c,d);return}}catch(e){b=3,c=e}}a.g=c;a.b=b;Hc(a);3!=b||c instanceof Dc||Kc(a,c)}},Jc=function(a,b,c){a.b=1;var d=!1,e=function(b){d||(d=!0,a.t(b))},f=function(b){d||(d=!0,a.h(b))};try{c.call(b,e,f)}catch(h){f(h)}},Hc=function(a){a.f||(a.f=!0,vc(a.j,a))};
zc.prototype.j=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=[];for(var b=0;b<a.length;b++)Gc(this,a[b],this.b,this.g)}this.f=!1};var Gc=function(a,b,c,d){if(2==c)b.qc(d);else{for(;a&&a.e;a=a.c)a.e=!1;b.sc(d)}},Kc=function(a,b){a.e=!0;vc(function(){a.e&&Lc.call(null,b)})},Lc=nc,Dc=function(a){ma.call(this,a)};q(Dc,ma);Dc.prototype.name="cancel";var Ac=function(a,b){this.b=a;this.a=b};
var Oc=function(){this.c=new C;this.a=null;this.b=!1;this.a=new Mc;this.b=!0;Nc(this)};Oc.va=function(){return Oc.a?Oc.a:Oc.a=new Oc};var Nc=function(a,b){var c=b||ka;a.b?c():chrome.storage.local.get(r(function(a){if(!this.b){for(var b in a)this.c.set(b,a[b]);this.b=!0}c()},a))};Oc.prototype.get=function(a){return this.a.get(a)};Oc.prototype.set=function(a,b){var c=Bc();this.a.set(a,b);c.a(void 0);return c.b};Oc.prototype.remove=function(a){this.a.remove(a)};Oc.prototype.clear=function(){this.a.clear()};
var Mc=function(){this.a=window.localStorage};Mc.prototype.clear=function(){this.a.clear()};Mc.prototype.get=function(a){a=this.a.getItem(a);if(a){var b=JSON.parse(a);a=b.data;if("jspb"==b.type){b=Aa[a[0]];if(!b)throw Error("e`"+a[0]);a=new b(a)}}else a=null;return a};Mc.prototype.set=function(a,b){var c=null;b instanceof x&&(b=b.G,c="jspb");var d={};d.data=b;d.timestamp=m();c&&(d.type=c);c=JSON.stringify(d);try{this.a.setItem(a,c)}catch(e){}};Mc.prototype.remove=function(a){try{this.a.removeItem(a)}catch(b){}};
var Pc=function(a,b){this.b=a;this.a=b;this.constructor.Wb||(this.constructor.Wb={});this.constructor.Wb[this.toString()]=this};Pc.prototype.toString=function(){this.c||(this.c=this.b.a+":"+this.a);return this.c};var L=function(a,b){Pc.call(this,a,b)};q(L,Pc);var Qc=function(a){this.a=a},Rc=new Qc("lib");/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
var Sc=function(a,b){this.e=[];this.u=b||null;this.b=this.a=!1;this.c=void 0;this.k=this.n=this.g=!1;this.f=0;this.h=null;this.p=0};Sc.prototype.j=function(a,b){this.g=!1;Tc(this,a,b)};var Tc=function(a,b,c){a.a=!0;a.c=c;a.b=!b;Uc(a)},Wc=function(a){if(a.a){if(!a.k)throw new Vc;a.k=!1}};Sc.prototype.t=function(a){Wc(this);Tc(this,!0,a)};var Xc=function(a,b,c,d){a.e.push([b,c,d]);a.a&&Uc(a)};
Sc.prototype.then=function(a,b,c){var d,e,f=new zc(function(a,b){d=a;e=b});Xc(this,d,function(a){"undefined"!=typeof Yc&&a instanceof Yc?Fc(f):e(a)});return f.then(a,b,c)};wc(Sc);
var Zc=function(a){return ua(a.e,function(a){return s(a[1])})},Uc=function(a){if(a.f&&a.a&&Zc(a)){var b=a.f,c=$c[b];c&&(k.clearTimeout(c.ab),delete $c[b]);a.f=0}a.h&&(a.h.p--,delete a.h);for(var b=a.c,d=c=!1;a.e.length&&!a.g;){var e=a.e.shift(),f=e[0],h=e[1],e=e[2];if(f=a.b?h:f)try{var l=f.call(e||a.u,b);p(l)&&(a.b=a.b&&(l==b||l instanceof Error),a.c=b=l);xc(b)&&(d=!0,a.g=!0)}catch(n){b=n,a.b=!0,Zc(a)||(c=!0)}}a.c=b;d&&(l=r(a.j,a,!0),d=r(a.j,a,!1),b instanceof Sc?(Xc(b,l,d),b.n=!0):b.then(l,d));c&&
(b=new ad(b),$c[b.ab]=b,a.f=b.ab)},Vc=function(){ma.call(this)};q(Vc,ma);Vc.prototype.message="Deferred has already fired";Vc.prototype.name="AlreadyCalledError";var ad=function(a){this.ab=k.setTimeout(r(this.b,this),0);this.a=a};ad.prototype.b=function(){delete $c[this.ab];throw this.a;};var $c={};

}catch(e){_DumpException(e)}
try{
var bd=function(){return chrome.runtime.getURL("feedbackdialog.html")},cd=function(a,b){for(var c=t(a)?a.split(""):a,d=a.length-1;0<=d;--d)d in c&&b.call(void 0,c[d],d,a)};var ed=function(a){this.c={};this.h={};this.j={};this.e={};this.k={};this.p={};this.n=a?a.ua():new I;this.w=!a;this.f=null;a?(this.f=a,this.j=a.j,this.e=a.e,this.h=a.h,this.k=a.k):m();a=dd(this);this!=a&&(a.g?a.g.push(this):a.g=[this])};q(ed,E);var dd=function(a){for(;a.f;)a=a.f;return a};ed.prototype.get=function(a){var b=this.b(a);if(null==b)throw new fd(a);return b};
ed.prototype.b=function(a){for(var b=this;b;b=b.f){if(b.D)throw Error("o");if(b.c[a])return b.c[a][0];if(b.p[a])break}if(b=this.j[a]){b=b(this);if(null==b)throw Error("p`"+a);this.a(a,b);return b}return null};ed.prototype.a=function(a,b,c){if(this.D)c||F(b);else{this.c[a]=[b,!c];b=gd(this,this,a);for(c=0;c<b.length;c++)b[c].t(null);delete this.h[a]}};ed.prototype.u=function(){var a=hd;if(!this.c[a])throw Error("q`"+a);var b=this.c[a];delete this.c[a];b[1]&&F(b[0])};
var gd=function(a,b,c){var d=[],e=a.e[c];e&&(cd(e,function(a){var c;t:{for(c=a.Xb;c;){if(c==b){c=!0;break t}c=c.f}c=!1}c&&(d.push(a.Kd),va(e,a))}),0==e.length&&delete a.e[c]);return d},id=function(a,b){a.e&&Ka(a.e,function(a,d,e){cd(a,function(d){d.Xb==b&&va(a,d)});0==a.length&&delete e[d]})};
ed.prototype.l=function(){if(dd(this)==this){var a=this.g;if(a)for(;a.length;)a[0].B()}else for(var a=dd(this).g,b=0;b<a.length;b++)if(a[b]==this){a.splice(b,1);break}for(var c in this.c)a=this.c[c],a[1]&&"undefined"!=typeof a[0].B&&a[0].B();this.c=null;this.w&&this.n.B();id(this,this);this.e=null;F(this.v);this.p=this.v=null;ed.q.l.call(this)};ed.prototype.ua=function(){return this.n};var fd=function(a){ma.call(this);this.id=a;this.message='Service for "'+a+'" is not registered'};q(fd,ma); var jd=new Qc("fva");new L(jd,1);

}catch(e){_DumpException(e)}
try{
var kd={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},ld=function(a,b){b.push('"',a.replace(wa,function(a){if(a in kd)return kd[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return kd[a]=e+b.toString(16)}),'"')},md="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),nd=function(a,b,c){switch(typeof b){case "string":ld(b,c);break;case "number":c.push(isFinite(b)&&
!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if(u(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),nd(a,b[f],c),e=",";c.push("]");break}c.push("{");d="";for(e in b)Object.prototype.hasOwnProperty.call(b,e)&&(f=b[e],"function"!=typeof f&&(c.push(d),ld(e,c),c.push(":"),nd(a,f,c),d=","));c.push("}");break;case "function":break;default:throw Error("d`"+typeof b);}},od=function(){},pd=function(a,
b,c,d,e){if(u(b)){for(var f=0;f<b.length;f++)pd(a,b[f],c,d,e);return null}c=ob(c);return cb(a)?a.U.add(String(b),c,!0,d,e):pb(a,b,c,!0,d,e)},qd=Na,rd=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,sd=function(a,b){a.t||(a.t=[]);a.t.push(p(void 0)?r(b,void 0):b)},M=function(a,b,c){b<a.e?a.G[b+a.b]=c:a.c[b]=c},td=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<md.length;f++)c=md[f],
Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}},ud=function(a){var b=[];nd(new od,a,b);return b.join("")},vd=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}},wd=function(a,b,c){null!=b&&(a.f=b,null!=c&&(a.e=c))},N=function(a,b){var c,d=a.u;if(d)for(c=[];d;d=d.u)c.push(d);var d=a.L,e=b,f=e.type||e;if(t(e))e=new G(e,d);else if(e instanceof G)e.target=e.target||d;else{var h=e,e=new G(f,d);td(e,h)}var h=
!0,l;if(c)for(var n=c.length-1;0<=n;n--)l=e.a=c[n],h=l.da(f,!0,e)&&h;l=e.a=d;h=l.da(f,!0,e)&&h;h=l.da(f,!1,e)&&h;if(c)for(n=0;n<c.length;n++)l=e.a=c[n],h=l.da(f,!1,e)&&h},xd=function(a,b,c,d,e,f){if(u(c))for(var h=0;h<c.length;h++)xd(a,b,c[h],d,e,f);else{b=pd(b,c,d||a.handleEvent,e,f||a.J||a);if(!b)return a;a.g[b.key]=b}return a},yd=function(a){if(qd){qd=!1;var b=k.location;if(b){var c=b.href;if(c&&(c=(c=yd(c)[3]||null)&&decodeURIComponent(c))&&c!=b.hostname)throw qd=!0,Error();}}return a.match(rd)},
O=function(a,b){sd(a,vd(F,b))},zd=function(a,b,c){var d=c?c.G:c;a.a[b]=c;M(a,b,d)},Ad=function(a,b,c){if(!a.a[c]){var d=z(a,c);d&&(a.a[c]=new b(d))}return a.a[c]},Bd=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Cd=function(a){return a?decodeURIComponent(a):""},Dd=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},Ed=function(a){return v.concat.apply(v,arguments)},Fd=function(a,b,c){this.a=a||null;this.b=!!c},Id=function(a){if(!a.H&&
(a.H=new C,a.O=0,a.a))for(var b=a.a.split("&"),c=0;c<b.length;c++){var d=b[c].indexOf("="),e=null,f=null;0<=d?(e=b[c].substring(0,d),f=b[c].substring(d+1)):e=b[c];e=decodeURIComponent(e.replace(/\+/g," "));e=Hd(a,e);a.add(e,f?decodeURIComponent(f.replace(/\+/g," ")):"")}};g=Fd.prototype;g.H=null;g.O=null;g.V=function(){Id(this);return this.O};g.add=function(a,b){Id(this);this.a=null;a=Hd(this,a);var c=this.H.get(a);c||this.H.set(a,c=[]);c.push(b);this.O++;return this};
g.remove=function(a){Id(this);a=Hd(this,a);return Ia(this.H.a,a)?(this.a=null,this.O-=this.H.get(a).length,this.H.remove(a)):!1};g.clear=function(){this.H=this.a=null;this.O=0};g.P=function(){Id(this);return 0==this.O};var Jd=function(a,b){Id(a);b=Hd(a,b);return Ia(a.H.a,b)};Fd.prototype.M=function(){Id(this);for(var a=this.H.A(),b=this.H.M(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};
Fd.prototype.A=function(a){Id(this);var b=[];if(t(a))Jd(this,a)&&(b=Ed(b,this.H.get(Hd(this,a))));else{a=this.H.A();for(var c=0;c<a.length;c++)b=Ed(b,a[c])}return b};Fd.prototype.set=function(a,b){Id(this);this.a=null;a=Hd(this,a);Jd(this,a)&&(this.O-=this.H.get(a).length);this.H.set(a,[b]);this.O++;return this};Fd.prototype.get=function(a,b){var c=a?this.A(a):[];return 0<c.length?String(c[0]):b};var Kd=function(a,b,c){a.remove(b);0<c.length&&(a.a=null,a.H.set(Hd(a,b),Dd(c)),a.O+=c.length)};
Fd.prototype.toString=function(){if(this.a)return this.a;if(!this.H)return"";for(var a=[],b=this.H.M(),c=0;c<b.length;c++)for(var d=b[c],e=encodeURIComponent(String(d)),d=this.A(d),f=0;f<d.length;f++){var h=e;""!==d[f]&&(h+="="+encodeURIComponent(String(d[f])));a.push(h)}return this.a=a.join("&")};Fd.prototype.clone=function(){var a=new Fd;a.a=this.a;this.H&&(a.H=this.H.clone(),a.O=this.O);return a};
var Hd=function(a,b){var c=String(b);a.b&&(c=c.toLowerCase());return c},Ld=function(a,b){b&&!a.b&&(Id(a),a.a=null,a.H.forEach(function(a,b){var e=b.toLowerCase();b!=e&&(this.remove(b),Kd(this,e,a))},a));a.b=b},Md=/#/g,Nd=/[\#\?@]/g,Od=/[\#\?]/g,Pd=/[\#\?:]/g,Qd=/[#\/\?@]/g,Rd=function(a,b){return t(a)?encodeURI(a).replace(b,Bd):null},Sd=function(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^m()).toString(36)},Td=function(a,b){var c;"undefined"!=
typeof Td&&a instanceof Td?(this.ma=p(b)?b:a.ma,Ud(this,a.fa),this.sa=a.sa,this.S=a.S,Vd(this,a.ea),this.N=a.N,Wd(this,a.a.clone()),this.la=a.la):a&&(c=yd(String(a)))?(this.ma=!!b,Ud(this,c[1]||"",!0),this.sa=Cd(c[2]||""),this.S=Cd(c[3]||""),Vd(this,c[4]),this.N=Cd(c[5]||""),Wd(this,c[6]||"",!0),this.la=Cd(c[7]||"")):(this.ma=!!b,this.a=new Fd(null,0,this.ma))};g=Td.prototype;g.fa="";g.sa="";g.S="";g.ea=null;g.N="";g.la="";g.ma=!1;
g.toString=function(){var a=[],b=this.fa;b&&a.push(Rd(b,Qd),":");if(b=this.S){a.push("//");var c=this.sa;c&&a.push(Rd(c,Qd),"@");a.push(encodeURIComponent(String(b)));b=this.ea;null!=b&&a.push(":",String(b))}if(b=this.N)this.S&&"/"!=b.charAt(0)&&a.push("/"),a.push(Rd(b,"/"==b.charAt(0)?Od:Pd));(b=this.a.toString())&&a.push("?",b);(b=this.la)&&a.push("#",Rd(b,Md));return a.join("")};
var Xd=function(a,b){var c=a.clone(),d=!!b.fa;d?Ud(c,b.fa):d=!!b.sa;d?c.sa=b.sa:d=!!b.S;d?c.S=b.S:d=null!=b.ea;var e=b.N;if(d)Vd(c,b.ea);else if(d=!!b.N){if("/"!=e.charAt(0))if(a.S&&!a.N)e="/"+e;else{var f=c.N.lastIndexOf("/");-1!=f&&(e=c.N.substr(0,f+1)+e)}f=e;if(".."==f||"."==f)e="";else if(-1!=f.indexOf("./")||-1!=f.indexOf("/.")){for(var e=0==f.lastIndexOf("/",0),f=f.split("/"),h=[],l=0;l<f.length;){var n=f[l++];"."==n?e&&l==f.length&&h.push(""):".."==n?((1<h.length||1==h.length&&""!=h[0])&&h.pop(),
e&&l==f.length&&h.push("")):(h.push(n),e=!0)}e=h.join("/")}else e=f}d?c.N=e:d=""!==b.a.toString();d?Wd(c,Cd(b.a.toString())):d=!!b.la;d&&(c.la=b.la);return c};Td.prototype.clone=function(){return new Td(this)};
var Ud=function(a,b,c){a.fa=c?Cd(b):b;a.fa&&(a.fa=a.fa.replace(/:$/,""))},Vd=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("j`"+b);a.ea=b}else a.ea=null},Wd=function(a,b,c){b instanceof Fd?(a.a=b,Ld(a.a,a.ma)):(c||(b=Rd(b,Nd)),a.a=new Fd(b,0,a.ma))},P=function(a,b,c){a.a.set(b,c)},Yd=function(a,b,c){u(c)||(c=[String(c)]);Kd(a.a,b,c)},Zd=function(a,b){return a.a.get(b)},$d=function(a,b){return 0<=pa(a,b)},ae=function(a,b,c){if(s(a))c&&(a=r(a,c));else if(a&&"function"==typeof a.handleEvent)a=
r(a.handleEvent,a);else throw Error("n");return 2147483647<b?-1:k.setTimeout(a,b||0)},be=function(a){k.clearTimeout(a)},ce=function(a){var b={},c;for(c in a)b[c]=a[c];return b},de=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c],e;if(u(d)||(e=ja(d))&&Object.prototype.hasOwnProperty.call(d,"callee"))a.push.apply(a,d);else if(e)for(var f=a.length,h=d.length,l=0;l<h;l++)a[f+l]=d[l];else a.push(d)}},ee=function(a,b){var c;t:{c=a.length;for(var d=t(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){c=e;break t}c=-1}return 0>c?null:t(a)?a.charAt(c):a[c]};
var fe=function(){},ie=function(a){var b=a.ia,c=function(a){c.q.constructor.call(this,a);var b=this.T.length;this.a=[];for(var d=0;d<b;++d)this.T[d].Ld||(this.a[d]=new this.T[d](a))};q(c,b);for(var d=[];a;){if(b=a.ia){b.T&&de(d,b.T);var b=b.prototype,e;for(e in b)if(b.hasOwnProperty(e)&&s(b[e])&&b[e]!==a){var f=!!b[e].Tc,h=ge(e,b,d,f);(f=he(e,b,h,f))&&(c.prototype[e]=f)}}a=a.q&&a.q.constructor}c.prototype.T=d;return c},ge=function(a,b,c,d){for(var e=[],f=0;f<c.length&&(c[f].prototype[a]===b[a]||(e.push(f),
!d));++f);return e},he=function(a,b,c,d){var e;c.length?d?e=function(b){var d=this.a[c[0]];return d?d[a].apply(this.a[c[0]],arguments):this.T[c[0]].prototype[a].apply(this,arguments)}:b[a].Vc?e=function(b){var d;t:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var n=this.a[c[e]];if(n=n?n[a].apply(n,d):this.T[c[e]].prototype[a].apply(this,d)){d=n;break t}}d=!1}return d}:b[a].Uc?e=function(b){var d;t:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var n=
this.a[c[e]],n=n?n[a].apply(n,d):this.T[c[e]].prototype[a].apply(this,d);if(null!=n){d=n;break t}}d=void 0}return d}:b[a].oc?e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=0;e<c.length;++e){var n=this.a[c[e]];n?n[a].apply(n,d):this.T[c[e]].prototype[a].apply(this,d)}}:e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=[],n=0;n<c.length;++n){var B=this.a[c[n]];e.push(B?B[a].apply(B,d):this.T[c[n]].prototype[a].apply(this,d))}return e}:d||b[a].Vc||b[a].Uc||b[a].oc? e=null:e=je;return e},je=function(){return[]};fe.prototype.zb=function(a){if(this.a)for(var b=0;b<this.a.length;++b)if(this.a[b]instanceof a)return this.a[b];return null};
var le=function(a){if(!a.wb){var b;for(b=a.constructor;b&&!b.ia;)b=b.q&&b.q.constructor;b.ia.ac||(b.ia.ac=ie(b));b=new b.ia.ac(a);a.wb=b;a.zb||(a.zb=ke)}},ke=function(a){return this.wb.zb(a)};var me=function(){};me.prototype.a=null;var oe=function(a){var b;(b=a.a)||(b={},ne(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b};var pe,qe=function(){};q(qe,me);var re=function(a){return(a=ne(a))?new ActiveXObject(a):new XMLHttpRequest},ne=function(a){if(!a.b&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.b=d}catch(e){}}throw Error("r");}return a.b};pe=new qe;
var se=function(a){I.call(this);this.C=new C;this.j=a||null;this.b=!1;this.h=this.a=null;this.p="";this.e=0;this.c=this.n=this.f=this.k=!1;this.v=0;this.g=null;this.J="";this.w=this.aa=!1};q(se,I);var te=/^https?$/i,ue=["POST","PUT"],ve=[];se.prototype.Q=function(){this.B();va(ve,this)};
se.prototype.send=function(a,b,c,d){if(this.a)throw Error("s`"+this.p+"`"+a);b=b?b.toUpperCase():"GET";this.p=a;this.e=0;this.k=!1;this.b=!0;this.a=this.j?re(this.j):re(pe);this.h=this.j?oe(this.j):oe(pe);this.a.onreadystatechange=r(this.I,this);try{this.n=!0,this.a.open(b,String(a),!0),this.n=!1}catch(e){we(this);return}a=c||"";var f=this.C.clone();d&&Ka(d,function(a,b){f.set(b,a)});d=ee(f.M(),xe);c=k.FormData&&a instanceof k.FormData;!$d(ue,b)||d||c||f.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");
f.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.J&&(this.a.responseType=this.J);"withCredentials"in this.a&&(this.a.withCredentials=this.aa);try{ye(this),0<this.v&&((this.w=ze(this.a))?(this.a.timeout=this.v,this.a.ontimeout=r(this.K,this)):this.g=ae(this.K,this.v,this)),this.f=!0,this.a.send(a),this.f=!1}catch(h){we(this)}};var ze=function(a){return D&&Ta(9)&&ia(a.timeout)&&p(a.ontimeout)},xe=function(a){return"content-type"==a.toLowerCase()};
se.prototype.K=function(){"undefined"!=typeof aa&&this.a&&(this.e=8,N(this,"timeout"),Ae(this,8))};var we=function(a){a.b=!1;a.a&&(a.c=!0,a.a.abort(),a.c=!1);a.e=5;Be(a);Ce(a)},Be=function(a){a.k||(a.k=!0,N(a,"complete"),N(a,"error"))},Ae=function(a,b){a.a&&a.b&&(a.b=!1,a.c=!0,a.a.abort(),a.c=!1,a.e=b||7,N(a,"complete"),N(a,"abort"),Ce(a))};se.prototype.l=function(){this.a&&(this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1),Ce(this,!0));se.q.l.call(this)};
se.prototype.I=function(){this.D||(this.n||this.f||this.c?De(this):this.$())};se.prototype.$=function(){De(this)};
var De=function(a){if(a.b&&"undefined"!=typeof aa&&(!a.h[1]||4!=(a.a?a.a.readyState:0)||2!=Ee(a)))if(a.f&&4==(a.a?a.a.readyState:0))ae(a.I,0,a);else if(N(a,"readystatechange"),4==(a.a?a.a.readyState:0)){a.b=!1;try{Fe(a)?(N(a,"complete"),N(a,"success")):(a.e=6,Be(a))}finally{Ce(a)}}},Ce=function(a,b){if(a.a){ye(a);var c=a.a,d=a.h[0]?ka:null;a.a=null;a.h=null;b||N(a,"ready");try{c.onreadystatechange=d}catch(e){}}},ye=function(a){a.a&&a.w&&(a.a.ontimeout=null);ia(a.g)&&(be(a.g),a.g=null)},Fe=function(a){var b=
Ee(a),c;t:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:c=!0;break t;default:c=!1}if(!c){if(b=0===b)a=yd(String(a.p))[1]||null,!a&&self.location&&(a=self.location.protocol,a=a.substr(0,a.length-1)),b=!te.test(a?a.toLowerCase():"");c=b}return c},Ee=function(a){try{return 2<(a.a?a.a.readyState:0)?a.a.status:-1}catch(b){return-1}},Ge=function(a){try{return a.a?a.a.responseText:""}catch(b){return""}};
var He=function(a){y(this,a,"h_icr",[])};q(He,x);A("h_icr",He);var Ie=function(a){y(this,a,"h_cs",[])};q(Ie,x);A("h_cs",Ie);var Je=new J("HwdKC");
}catch(e){_DumpException(e)}
try{
var Ke=function(a){return a instanceof Td?a.clone():new Td(a,void 0)},Le=function(a){y(this,a,0,[])};q(Le,x);var Me=function(a){y(this,a,0,[])};q(Me,x);var Ne=function(a){y(this,a,0,[])};q(Ne,x);
var Oe=/[?&]($|#)/,Pe=/#|$/,Qe=function(a,b,c,d){for(var e=c.length;0<=(b=a.indexOf(c,b))&&b<d;){var f=a.charCodeAt(b-1);if(38==f||63==f)if(f=a.charCodeAt(b+e),!f||61==f||38==f||35==f)return b;b+=e+1}return-1},Re=function(a){if(a&&"number"==typeof a.length){if(ha(a))return"function"==typeof a.item||"string"==typeof a.item;if(s(a))return"function"==typeof a.item}return!1},Se={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",
role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},Te=/[\x00&<>"']/,Ue=/\x00/g,Ve=/'/g,We=/"/g,Xe=/>/g,Ye=/</g,Ze=/&/g,$e=function(a,b,c){function d(c){c&&b.appendChild(t(c)?a.createTextNode(c):c)}for(var e=2;e<c.length;e++){var f=c[e];!ja(f)||ha(f)&&0<f.nodeType?d(f):w(Re(f)?Dd(f):f,d)}},af=function(a,b){xa(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in Se?a.setAttribute(Se[d],b):0==d.lastIndexOf("aria-",0)||0==
d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})},bf=function(a){if(!Te.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Ze,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Ye,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Xe,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(We,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Ve,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Ue,"&#0;"));return a},cf={LOADING:0,Cc:1,Gd:2,Hd:3,ERROR:4,LOADED:5,Bc:6},df=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,
ef=function(a,b,c){for(var d=a.search(Pe),e=0,f,h=[];0<=(f=Qe(a,e,b,d));)h.push(a.substring(e,f)),e=Math.min(a.indexOf("&",f)+1||d,d);h.push(a.substr(e));a=[h.join("").replace(Oe,"$1"),"&",b];null!=c&&a.push("=",encodeURIComponent(String(c)));a[1]&&(c=a[0],b=c.indexOf("#"),0<=b&&(a.push(c.substr(b)),a[0]=c=c.substr(0,b)),b=c.indexOf("?"),0>b?a[1]="?":b==c.length-1&&(a[1]=void 0));return a.join("")},ff=function(a){I.call(this);this.c=a;this.a=cf.LOADING;this.b=new H(this);O(this,this.b);this.b.listen(this.c.ua(),
"h_cs",this.e)};q(ff,I);ff.prototype.e=function(a){a=new Ie(a.gb);this.a!=z(a,1)&&(this.a=z(a,1),N(this,"i"))};
var gf=function(a){(a?a:function(){}).Tc=!0},hf=function(a,b,c){var d=arguments,e=document,f=d[0],h=d[1];if(!Wa&&h&&(h.name||h.type)){f=["<",f];h.name&&f.push(' name="',bf(h.name),'"');if(h.type){f.push(' type="',bf(h.type),'"');var l={};td(l,h);delete l.type;h=l}f.push(">");f=f.join("")}f=e.createElement(f);h&&(t(h)?f.className=h:u(h)?f.className=h.join(" "):af(f,h));2<d.length&&$e(e,f,d);return f},jf=function(a){var b=a||document,c=null;if(b.querySelectorAll&&b.querySelector)c=b.querySelector(".talk_loading_msg");
else{var d,b=document;a=a||b;if(a.querySelectorAll&&a.querySelector)a=a.querySelectorAll(".talk_loading_msg");else if(a.getElementsByClassName){var e=a.getElementsByClassName("talk_loading_msg");a=e}else{e=a.getElementsByTagName("*");d={};for(b=c=0;a=e[b];b++){var f=a.className;"function"==typeof f.split&&$d(f.split(/\s+/),"talk_loading_msg")&&(d[c++]=a)}d.length=c;a=d}c=a[0]}return c||null},kf=function(a){var b;b=b||0;return function(){return a.apply(this,Array.prototype.slice.call(arguments,0,b))}};
var lf=function(a){this.a=a;D||(delete this.a.lpu,delete this.a.ppu)},mf=["cn","tp"],nf=function(a,b){var c=null,d;if(s(document.postMessage)||s(window.postMessage)||D&&window.postMessage)d=1;else if(Ma)d=2;else{if(c=D){c=!1;try{d=window.opener,window.opener={},c=Ya(window,"opener"),window.opener=d}catch(e){}}d=c?6:4}c=d;d={};d.cn=Math.floor(2147483648*Math.random()).toString(36);d.tp=c;d.ifrid=b;d.pu=a;return new lf(d)};ga("GTalk_IFrameChannelConfig.build",nf);
var of=function(){};q(of,fe);of.prototype.b=function(a){return a};gf(of.prototype.b);of.prototype.c=function(){return!0};gf(of.prototype.c);var pf=function(a){y(this,a,0,[])};q(pf,x);var qf=function(a,b){var c=new pf;M(c,1,b);M(c,2,a);return c},rf=qf("?",0),sf=qf("q",1),tf=qf("<",2),uf=qf(">",3),vf=qf("~",4),wf=qf("s",5),xf={f:rf,j:sf,t:tf,h:uf,g:vf,k:wf};var yf=function(a){y(this,a,"ci:dc",[])};q(yf,x);A("ci:dc",yf);var zf=function(a){y(this,a,"ci:ec",[])};q(zf,x);A("ci:ec",zf);var Af=function(a){return null!=z(a,2)?z(a,2):!1};var Bf=function(a){this.a=a},Cf=/\s*;\s*/;g=Bf.prototype;g.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error("v`"+a);if(/[;\r\n]/.test(b))throw Error("w`"+b);p(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(m()+1E3*c)).toUTCString();this.a.cookie=a+"="+b+e+d+c+f};
g.get=function(a,b){for(var c=a+"=",d=(this.a.cookie||"").split(Cf),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};g.remove=function(a,b,c){var d=p(this.get(a));this.set(a,"",0,b,c);return d};g.M=function(){return Df(this).keys};g.A=function(){return Df(this).Fd};g.P=function(){return!this.a.cookie};g.V=function(){return this.a.cookie?(this.a.cookie||"").split(Cf).length:0};g.clear=function(){for(var a=Df(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])}; var Df=function(a){a=(a.a.cookie||"").split(Cf);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,Fd:c}};
var Ef=function(a,b,c){le(this);var d=this.wb.b(a.clientBaseUrl||"https://talkgadget.google.com/talkgadget/");if(0==d.lastIndexOf("https://talkgadget.google.com/talkgadget/",0)){var e=(new Bf(window.document)).get("WCSDBG",""),e=e.split(";")[0],e=e.split("|")[0],f=["plus.google.com"],h=/^[-_a-zA-Z0-9\.]+\.talkgadget\.google\.com$/;0<e.length&&!$d(f,e)&&h.test(e)&&(d=Ke(d),d=Ke("https://"+e+d.N).toString())}this.ca=d;this.c=c||new zf;a.notificationsOnly&&M(this.c,1,!0);this.b="0";null!=a.authUser?
this.b=a.authUser:(c=Zd(new Td(window.location.href),"authuser"),null!=c&&(this.b=c));this.e=a.clientUrl||"notifierclient";c=Zd(Ke(this.e),"authuser");null!=c&&(this.b=c);this.h=a.propertyName||"Google Talk";this.n=a.cssUrl;this.locale=a.locale;this.g=a.debug;this.Tb=a.userJid;this.Rb=a.uiVersion;this.Ac=null!=a.rosterExpanded?a.rosterExpanded:!0;this.Q=a.hostLogMinValue;this.Ob=a.hideChat;this.Hc=a.refresh;this.J=a.hideProfileCard;this.L=a.hideStatusMsgs;this.K=a.hideRosterOptions;this.I=a.hideRecentConversations;
this.C=a.hideOTR;this.Ec=a.hostServerMessageCallback||!1;this.aa=a.isCentralRoster;this.Gc=a.isFullFrame||!1;this.Kc=a.rosterClass||"talk_roster";this.Ua=a.rosterId||"talk_roster";this.a="gtn-roster-iframe-id";a.rosterFrameId&&a.rosterFrameId.match(/[\w-]/)&&(this.a=a.rosterFrameId);a.rosterIframeIdB&&a.rosterIframeIdB.match(/[\w-]/);this.f=a.parentToken;this.Jc=b||!1;p(a.isRtl)||df.test(this.locale);this.t=a.position||"l";if(!a.keyboardShortcuts){b=[];for(var l in xf)b.push(xf[l].G)}this.u=a.entityId;
this.Sb=a.useQuasarPanels||!1;this.Pb=a.silent||!1;this.Fc=a.ignoreCentralRoster||!1;this.Ic=a.lazy||!1;this.Dc=a.handleProfileLinks||!1;this.$=a.hostSettings;this.j=a.screen;this.p=a.docsConfig;this.Ba=a.jsmode;this.Ea=a.moleWidth;this.Da=a.moleHeight;this.Ca=a.minimizedMoleHeight||36;this.Lc=a.derp;this.Qb=window.location.protocol+"//"+window.location.host;this.v=a.optOutAllowed;this.w=a.showWelcomePromo;this.k=a.conversationId};of.q||q(of,fe);Ef.ia=of;
var Ff=function(a){switch(a){case 1:return"homepage";case 2:return"Orkut";case 3:return"iGoogle";case 4:return"Google Translator Toolkit";case 5:return"Google Sites";case 6:return"customersupport";case 9:return"present";case 15:return"hangout";case 18:return"gmail";case 20:return"docs";case 24:return"docs_hangout";case 22:return"hangout_lite";case 23:return"aChromeExtension";case 25:return"bigtop";case 27:return"ChromeApp";case 29:return"potluck"}},Gf=function(a){if(a.Ba)a=a.Ba;else{a=window.location.href; var b=a.search(Pe),c=Qe(a,0,"jsmode",b);if(0>c)a=null;else{var d=a.indexOf("&",c);if(0>d||d>b)d=b;c+=7;a=decodeURIComponent(a.substr(c,d-c).replace(/\+/g," "))}}return a};
var Hf=function(a,b,c,d,e){this.a=a;this.b=d||window.document;this.c=new H(this);O(this,this.c);var f=Da;d=new Td(a.ca+a.e);Af(a.c)||(P(d,"ts","0"),P(d,"re",a.Ac),P(d,"ref",a.Hc));P(d,"client","sm");P(d,"prop",a.h);P(d,"nav","true");P(d,"fid",a.a);a.g&&P(d,"debug",a.g);P(d,"os",Pa);P(d,"stime",c);a.Ob&&P(d,"hc",a.Ob);for(c=0;c<mf.length;++c);b=ud(b.a);P(d,"xpc",b);P(d,"ec",ud(a.c.G));a.j&&P(d,"screen",a.j);-1!=f.indexOf("MSIE")&&P(d,"ua",f);a.f&&P(d,"pvt",a.f);a.Ec&&P(d,"hsmc","true");p(a.Q)&&P(d,
"logl",a.Q);b=window.location.href;0>b.indexOf("?rel=1")&&(b=b.split("?"),b[1]=1==b.length?"rel=1":["rel=1&",b[1]].join(""),P(d,"href",b.join("?")));b=new Td(window.location.href);"false"==Zd(b,"uacheck")&&P(d,"uacheck",!1);(f=Gf(a))&&P(d,"jsmode",f);(f=Zd(b,"cssmode"))&&P(d,"cssmode",f);(f=Zd(b,"convid"))&&P(d,"convid",f);(f=b.a.A("convp"))&&Yd(d,"convp",f);(f=Zd(b,"smexp"))&&P(d,"smexp",f);f=b.a.A("mods");a.Ic&&f.push("lazy");e&&(f=Ed(f,e));0<f.length&&P(d,"mods",f.join(","));if(!a.ca||0>a.ca.indexOf("/u/"))(e=
Zd(b,"authuser"))?P(d,"authuser",e):null!=a.b&&P(d,"authuser",a.b);e=Zd(b,"eid");null!=e&&P(d,"eid",e);null!=this.a.u&&P(d,"eid",this.a.u);null!=this.a.t&&P(d,"pos",this.a.t);p(a.Rb)&&P(d,"uiv",this.a.Rb);a.n&&P(d,"css",a.n);e=a.locale||Zd(b,"hl");null!=e&&P(d,"hl",e);p(a.Tb)&&P(d,"uj",a.Tb);null!=a.J&&P(d,"hpc",a.J);null!=a.L&&P(d,"hsm",a.L);null!=a.K&&P(d,"hro",a.K);null!=a.I&&P(d,"hrc",a.I);null!=a.C&&P(d,"hotr",a.C);null!=a.aa&&P(d,"pop",a.aa);a.Jc&&P(d,"pal","1");null!=a.Sb&&P(d,"uqp",a.Sb);
null!=a.v&&P(d,"gooa",a.v);null!=a.w&&P(d,"gswp",a.w);null!=a.Pb&&P(d,"sl",a.Pb);a.Fc&&P(d,"icr","1");a.Dc&&P(d,"hpl","1");a.$&&P(d,"hs",a.$);a.p&&P(d,"dc",ud(a.p.G));null!=a.Ea&&P(d,"molew",a.Ea);null!=a.Da&&P(d,"moleh",a.Da);null!=a.Ca&&P(d,"mmoleh",a.Ca);a.Lc&&P(d,"derp","1");null!=a.Qb&&P(d,"two",a.Qb);null!=a.k&&P(d,"convid",a.k);P(d,"host","1");P(d,"zx",Sd());this.e=d.toString()};q(Hf,E);
var If=function(a,b,c,d){var e=a.b.getElementById(b);e||(e=a.b.createElement("div"),e.id=b,e.className=a.a.Kc,a.b.body.appendChild(e));a=r(function(){var a="";this.a.Gc||(a="height:400px");var b=this.b.createElement("iframe");af(b,{id:this.a.a,name:this.a.a,"class":"talk_iframe",frameborder:"0",style:a});if(!jf(e))for(var a=e,l;l=a.firstChild;)a.removeChild(l);e.appendChild(b);b=this.b.getElementById(this.a.a);xd(this.c,b,["load","error"],kf(d),void 0);b.src=this.e.toString();c()},a);window.setTimeout(a, 0)};
var Jf=function(a){G.call(this,a[0]);this.gb=a};q(Jf,G);var Kf=function(a){y(this,a,"h_ccf",[])};q(Kf,x);A("h_ccf",Kf);var Lf=function(a){y(this,a,"h_rtp",[])};q(Lf,x);A("h_rtp",Lf);var Mf=function(a,b){this.w=m();this.v=a;this.document=b||window.document;this.a=new Ef(a,!0,a.endpointConfig);this.f=[];this.n=new I};q(Mf,E);Mf.prototype.l=function(){Mf.q.l.call(this);this.b&&this.j&&this.b.parentNode.removeEventListener("DOMAttrModified",this.j,!0)};Mf.prototype.c=function(a,b){this.e?this.e[a]&&this.e[a].apply(this.e,Array.prototype.slice.call(arguments,1)):this.f.push(arguments)};
Mf.prototype.g=function(){var a=this.fc().GTalkNotifier;if(a){var b=ce(this.v);b.endpointConfig=this.a.c.G;this.e=new a(b,!0);for(a=0;a<this.f.length;a++)this.c.apply(this,this.f[a]);this.f=[];a=r(this.onMessage,this);this.c("_addClientMessageCallback",a);this.c("_addHostBundleMessageCallback",a)}};Mf.prototype.onMessage=function(a){switch(a[0]){case "h_ccf":new Kf(a)}N(this.n,new Jf(a))};var Nf=function(a,b){a.c("_h",b.G)};g=Mf.prototype;g.sendMessage=function(a){Nf(this,a)};g.ua=function(){return this.n};
g.fc=function(){return this.document.parentWindow||this.document.defaultView};g.bd=function(a,b){if(b.target==a&&("style"==b.attrName||"class"==b.attrName)){var c=new Lf;Nf(this,c)}};g.cd=function(){jf(this.document.getElementById(this.a.Ua))&&(this.document.getElementById(this.a.a).style.display="none")};
var Of=function(a){var b=a.a.ca+"host-js",b=ef(b,"prop",a.a.h),c=Gf(a.a);c&&(b=ef(b,"jsmode",c));Af(a.a.c)&&(b=ef(b,"b","1"));var b=ef(b,"zx",Sd()),d=r(a.g,a),e=hf("script",{type:"text/javascript",src:b}),f=!1;e.onload=e.onreadystatechange=function(){f||e.readyState&&"loaded"!=e.readyState&&"complete"!=e.readyState||(f=!0,d())};e.onerror=r(a.p,a,e);a.document.body.appendChild(e)};Mf.prototype.p=function(){};
var Pf=function(a){if(a.classList)return a.classList;a=a.className;return t(a)&&a.match(/\S+/g)||[]},Qf=function(a){return a.classList?a.classList.contains("talk_network_warning"):$d(Pf(a),"talk_network_warning")},Rf=function(a){a.classList?a.classList.add("talk_network_warning"):Qf(a)||(a.className+=0<a.className.length?" talk_network_warning":"talk_network_warning")},Sf=function(a){a.classList?a.classList.remove("talk_network_warning"):Qf(a)&&(a.className=ra(Pf(a),function(a){return"talk_network_warning"!= a}).join(" "))};
var Tf=function(a,b){this.b=b;this.a=a};Tf.prototype.F=function(){return this.a};var Uf=function(a){a.a=Math.min(a.b,2*a.a)};var Vf=function(a,b,c){var d={},e=null!=z(a,1)?z(a,1):"talkgadget.google.com",f="";0>e.indexOf("://")&&(f="https://",0<=e.indexOf(":")&&23!=z(a,2)&&27!=z(a,2)&&(f="http://"));d.clientBaseUrl=f+e+"/talkgadget/_/";d.authUser=null!=z(a,8)?z(a,8):"0";d.clientUrl="chat";d.propertyName=Ff(z(a,2));d.locale=z(a,4);d.hideProfileCard=!0;d.parentToken=z(a,3);d.isRtl=null!=z(a,6)?z(a,6):!1;d.lazy=null!=z(a,7)?z(a,7):!1;d.entityId=z(a,9);d.hostSettings=z(a,5);d.jsmode=z(a,11);d.isFullFrame=null!=z(a,13)?z(a,13):
!1;d.rosterId=null!=z(a,12)?z(a,12):"talk_roster";d.rosterIframeIdB=null!=z(a,15)?z(a,15):"gtn-roster-iframe-id-b";d.derp=!(null==z(a,16)||!z(a,16));e=Ad(a,Le,14);null!=e&&(d.isCentralRoster=null!=z(e,1)?z(e,1):!1,d.useQuasarPanels=null!=z(e,2)?z(e,2):!1);e=Ad(a,Ne,10);null!=e&&(d.moleManagerLeftMargin=z(e,1),d.moleManagerMiddleMargin=z(e,2),d.moleManagerRightMargin=z(e,3),d.moleManagerNoMoleAreaMargin=z(e,4),d.moleManagerBoundingElementId=z(e,5),d.moleWidth=z(e,6),d.moleHeight=z(e,7),d.minimizedMoleHeight=
z(e,8));e=Ad(a,Me,18);null!=e&&(d.optOutAllowed=null!=z(e,1)?z(e,1):!0,d.showWelcomePromo=z(e,2));d.uiVersion=2;d.hideStatusMsgs=!0;d.hideRecentConversations=!0;e=new zf;M(e,2,!0);M(e,1,!0);M(e,3,!1);d.endpointConfig=e;d.ignoreAutomatedRoster=null!=z(a,17)?z(a,17):!1;d.conversationId=a.Y();d.hostCallback=c;Mf.call(this,d,b);this.k=new Tf(5E3,3E5);this.u=null};q(Vf,Mf);
Vf.prototype.p=function(a){var b=jf(this.document.body);b&&Rf(b);this.u=ae(function(){null==this.e&&(this.document.body.removeChild(a),Of(this))},this.k.F(),this);Uf(this.k)};Vf.prototype.g=function(){Vf.q.g.call(this);var a=jf(this.document.body);a&&Sf(a)};Vf.prototype.l=function(){Vf.q.l.call(this);be(this.u)};
var Wf=function(a){y(this,a,"h_exts",[2])};q(Wf,x);A("h_exts",Wf);var Xf=function(){this.b=" "};q(Xf,E);var Yf=function(a,b,c){a.a=c;b=new Td(b);b=Xd(b,new Td("/talkgadget/_/extension-start"));a=r(a.c,a);c=new se;ve.push(c);a&&c.listen("complete",a);c.U.add("ready",c.Q,!0,void 0,void 0);c.send(b,void 0,void 0,void 0)};Xf.prototype.c=function(a){if(!this.D){if(Fe(a.target))try{var b=JSON.parse(Ge(a.target)),c=new Wf(b);this.b=z(c,1)||""}catch(d){this.b=""}this.a&&(this.a(),this.a=null)}};
var Zf=function(a){I.call(this);this.c=a?a:null;this.a=null;this.e=!1;this.b=[];this.f=r(this.Nc,this);this.g=r(this.Ub,this);this.h=null};q(Zf,I);var $f=function(a){G.call(this,"message");this.message=a};q($f,G);g=Zf.prototype;g.l=function(){Zf.q.l.call(this);be(this.h);this.Ub(!0);for(var a=0;a<this.b.length;++a)F(this.b[a]);delete this.b;delete this.f;delete this.g};
g.sendMessage=function(a){if(null==a||null==a.message)return!1;ec(a,this.c,"p");this.a&&this.e?this.a.postMessage(a.message()):this.b.push(a);return!0};g.connect=function(){if(null==this.c)return!1;try{if(this.a=chrome.runtime.connect({name:this.c}),null==this.a)return!1}catch(a){return!1}this.e=!0;this.a.onMessage.addListener(this.f);this.a.onDisconnect.addListener(this.g);for(var b=this.b.shift();null!=b;)ec(b,this.c,"p"),this.a.postMessage(b.message()),b=this.b.shift();return!0};
g.Nc=function(a){N(this,new $f(dc(new cc,a)))};g.Ub=function(a){this.a&&(this.a.onMessage.removeListener(this.f),this.a.onDisconnect.removeListener(this.g),this.a.disconnect(),delete this.a);this.e=!1;a||(this.h=ae(this.xd,5E3,this))};g.xd=function(){this.connect()?N(this,{type:"reconnected"}):N(this,{type:"disconnected"})};
var ag=function(a){y(this,a,"h_cp",[])};q(ag,x);A("h_cp",ag);var bg=function(a){y(this,a,"rbc_d",[])};q(bg,x);A("rbc_d",bg);bg.prototype.setTitle=function(a){M(this,1,a)};var cg=function(a){y(this,a,"h_cd",[1,4,5])};q(cg,x);A("h_cd",cg);cg.prototype.Y=function(){return z(this,2)};var dg=function(a){y(this,a,"h_hn",[])};q(dg,x);A("h_hn",dg);var eg=function(a){y(this,a,"h_hs",[])};q(eg,x);A("h_hs",eg);var fg=function(a){y(this,a,"h_jm",[2])};q(fg,x);A("h_jm",fg);var gg=function(a){y(this,a,"h_oc",[])};q(gg,x);A("h_oc",gg);var hg=function(a){y(this,a,"h_opc",[])};q(hg,x);A("h_opc",hg);var ig=function(a){y(this,a,"h_ogc",[])};q(ig,x);A("h_ogc",ig);var jg=function(a){y(this,a,"h_sc",[])};q(jg,x);A("h_sc",jg);var kg=function(a){y(this,a,"h_ssc",[5])};q(kg,x);A("h_ssc",kg);var lg=function(a){y(this,a,"h_sm",[1,3])};q(lg,x);A("h_sm",lg);var mg=function(a){I.call(this);this.a=a};q(mg,I);var ng=new J("O9EQob");var og=function(a){y(this,a,"capi:clstup",[])};q(og,x);A("capi:clstup",og);var pg=function(a){y(this,a,"capi:r_clre",[])};q(pg,x);A("capi:r_clre",pg);var qg=function(a){y(this,a,"capi:r_rrst",[])};q(qg,x);A("capi:r_rrst",qg);var rg=function(a){y(this,a,"capi:r_rers",[])};q(rg,x);A("capi:r_rers",rg);var sg=function(a){y(this,a,"capi:r_recl",[])};q(sg,x);A("capi:r_recl",sg);var tg=function(a){y(this,a,"capi:r_rstr",[])};q(tg,x);A("capi:r_rstr",tg);
var ug=new J("nED8Yb"),vg=new J("xclgJb");var wg=function(a){y(this,a,"h_ec",[])};q(wg,x);A("h_ec",wg);var xg=function(a){y(this,a,"h_fr",[])};q(xg,x);A("h_fr",xg);var yg=function(a){y(this,a,"capii_c_cel",[])};q(yg,x);A("capii_c_cel",yg);var zg=function(a){y(this,a,"capi:rfc",[])};q(zg,x);A("capi:rfc",zg);var Ag=function(a){y(this,a,"capii_c_ucmc",[])};q(Ag,x);A("capii_c_ucmc",Ag);var Bg=function(a){y(this,a,"capii_c_rc",[])};q(Bg,x);A("capii_c_rc",Bg);Bg.prototype.Y=function(){return z(this,1)};
var Cg=function(a){I.call(this);this.c=a.get(ug);this.a=this.f=0;this.e=this.b=!1;a=new H(this);O(this,a);a.listen(this.c.ua(),"capii_c_ucmc",this.g);this.c.sendMessage(new Ag)};q(Cg,I);Cg.prototype.g=function(a){a=new Ag(a.gb);this.b||(this.b=!0,this.e&&(M(a,5,!0),this.e=!1));var b=this.f!=z(a,1);this.f=Number(z(a,1));var c=this.a!=z(a,2);this.a=Number(z(a,2));z(a,5)?N(this,"m"):(b&&N(this,"o"),c&&N(this,"n"))};
var Dg=function(a){y(this,a,"h_rha",[])};q(Dg,x);A("h_rha",Dg);var Eg=function(a){y(this,a,"h_ssf",[])};q(Eg,x);A("h_ssf",Eg);var Fg=function(a,b){this.a=new H(this);O(this,this.a);this.a.listen(a.ua(),"h_ssf",function(a){a=new Eg(a.gb);a=z(a,1);var c;if(null!=a&&JSON&&JSON.parse)try{c=JSON.parse(a)}catch(f){}b(c)});var c=new Dg;M(c,1,1);Nf(a,c)};q(Fg,E);var Gg=function(a){y(this,a,"h_ext",[])};q(Gg,x);A("h_ext",Gg);var Hg=function(a){y(this,a,"h_sru",[])};q(Hg,x);A("h_sru",Hg);var Kg=function(){H.call(this);this.b=new ed;O(this,this.b);this.k=this.h=this.j=this.a=null;this.p=ac("quasar",""+(new Date).getTime());this.c=[];this.e=new Zf(this.p);O(this,this.e);this.f=null;this.e.connect();Bb(this,this.e,"message",this.I,!0,this);this.n=new Xf;O(this,this.n);this.listen(window,"unload",this.B);this.listen(window,"load",this.v);Ig(this,r(function(){Jg(this,["onHostReady"],"extensionLibrary")},this))},Lg;q(Kg,H);var Ig=function(a,b){null==a.c?b():a.c.push(b)};
Kg.prototype.v=function(){var a=new lc(Oc.va().get("settings"));this.f=a.b[0];F(a);Yf(this.n,this.f,r(function(){if(!this.D&&-1!=this.f.lastIndexOf("talkgadget/")){var a=new zf;M(a,2,!0);var a=new zb,c=Ke(this.f),d=c.S;null!=c.ea&&(d+=":"+c.ea);M(a,1,d);M(a,2,23);d=chrome.i18n.getMessage("@@ui_locale");M(a,4,d);M(a,13,!0);M(a,17,!0);(d=this.n.b)&&M(a,3,d);c=Zd(c,"jsmode");null!=c&&M(a,11,c);c=new Le;M(c,2,!0);M(c,1,!0);zd(a,14,c);a=new Vf(a,void 0,r(this.C,this));t(void 0)&&(a.a.f=void 0);c=a.a;var e=
a.a.ca,d=a.a.b,f=Ke(e),h=f.N;if(0<=h.indexOf("/u/"))d=e;else{e=h.lastIndexOf("_/");if(0>e||e!=h.length-2)h+="_/";f.N="/u/"+d+h;d=f.toString()}c.ca=d;a.a.e=a.a.e.replace("notifierclient","chat");a.h||(c=nf(a.a.ca,a.a.a),a.h=new Hf(a.a,c,a.w,a.document,void 0),O(a,a.h));If(a.h,a.a.Ua,r(a.cd,a),r(a.c,a,"_rosterIframeLoaded"));Kb&&(a.b=a.document.createElement("IFRAME"),a.b.id="gth-talk-plugin-frame-id",a.b.name="gth-talk-plugin-frame-id",a.b.src=a.a.ca+"blank",a.b.style.cssText="width: 0px; height: 0px; position: absolute; top: 0px; left: 0px; visibility:hidden;",
a.document.documentElement.appendChild(a.b),a.j=r(a.bd,a,a.b.parentNode),a.b.parentNode.addEventListener("DOMAttrModified",a.j,!0));Of(a);this.a=a;this.b.a(ug,this.a);this.j=new ff(this.a);this.b.a(Je,this.j);this.listen(this.j,"i",this.w);this.h=new mg(this.a);this.b.a(ng,this.h);this.k=new Cg(this.b);this.b.a(vg,this.k);this.listen(this.k,"n",this.u);this.u();a=new Fg(this.a,r(this.K,this));O(this,a);this.listen(this.a.ua(),"h_sru",this.L)}for(;this.c.length;)this.c.shift()();this.c=null},this))};
Kg.prototype.C=function(a,b){if("extensionMessage"==a)if("__reload__"==b)chrome.runtime.reload();else{var c=new cc;dc(c,JSON.parse(b)||{});this.e.sendMessage(c)}};Kg.prototype.w=function(){var a;switch(this.j.a){case cf.LOADING:a=2;break;case cf.Cc:a=4;break;case cf.Bc:a=3;break;default:return}Jg(this,["changeDesktop",a],"desktopManager")};
Kg.prototype.I=function(a){Ig(this,r(function(){var b=a.message;switch(b.b){case "onSendHostMessage":var c=new Gg,b=b.content().toString();M(c,1,b);this.a.sendMessage(c);break;case "onOpenConversation":var b=b.content()[0],c=this.h,d=new gg;M(d,1,b);Nf(c.a,d);d=new cg;M(d,1,[b]);b=new hg;zd(b,1,d);Nf(c.a,b);break;case "h_icr":c=b.content()[0],b=this.h,d=new He,M(d,1,c),Nf(b.a,d)}},this))};var Jg=function(a,b,c){var d=new cc;ec(d,a.p,"p");wd(d,"","e");gc(d,b);null!=c&&(d.t=c);fc(d,""+m());a.e.sendMessage(d)}; Kg.prototype.K=function(){var a=bd();window.open(a)};Kg.prototype.L=function(a){a=new Hg(a.gb);Jg(this,["setRosterUrl",z(a,2)],"dataChannelManager")};Kg.prototype.u=function(){Jg(this,["setUnreadIndicator",!!this.k.a],"desktopManager")};
if(!p(Lg)||null==Lg||Lg.D)Lg=new Kg;
}catch(e){_DumpException(e)}
// Google Inc.
