try{
var g,aa=aa||{},k=this,ba="closure_uid_"+(1E9*Math.random()>>>0),m=Date.now||function(){return+new Date};
}catch(e){_DumpException(e)}
try{
k.ace_i18n={chrome_ext_short_name:{message:"Hangouts"},chrome_ext_description:{message:"Hangouts brings conversations to life with photos, emoji, and even group video calls for free."},quasar_chat_toast_info:{message:"Click to go to page..."},quasar_answer_button_text:{message:"Answer"},quasar_decline_button_text:{message:"Decline"},quasar_help:{message:"Help"},quasar_legend_startup_shutdown:{message:"Application"},chrome_ext_run_at_browser_start:{message:"Sign in to Hangouts when Chrome starts"},
chrome_ext_run_after_browser_close:{message:"Allow background mode"},chrome_ext_new_windows_topmost:{message:"Keep Hangouts on top of other windows"},quasar_label_tray_icon:{message:"Show system tray icon"},quasar_legend_notifications:{message:"Notifications"},quasar_label_all_notification:{message:"Disable notifications"},quasar_label_chat_notification:{message:"Disable chat notifications"},quasar_label_toast_timeout_chat:{message:"Allow chat notifications to timeout automatically"},quasar_label_toast_duration_chat:{message:"Timeout length (in seconds):"},
quasar_button_save:{message:"Ok"},quasar_button_apply:{message:"Apply"},quasar_button_cancel:{message:"Cancel"},chrome_ext_menutext_feedback:{message:"Send feedback"},quasar_feedback_server_uri:{message:"https://www.google.com/tools/feedback"},chrome_ext_feedback_subtitle:{message:"Send feedback"},chrome_ext_feedback_comments:{message:"Comments"},quasar_feedback_system_legend:{message:"System Information"},quasar_feedback_platform_label:{message:"Platform:"},quasar_feedback_user_agent_label:{message:"User Agent:"},
quasar_feedback_privacy_legend:{message:"Privacy Statement"},quasar_feedback_privacy_text:{message:"The description, product information, additional information and your email address will be sent to Google. See the Google Feedback Terms of Service. By submitting this content you are granting to Google the right to use it to improve our products and services. See our Privacy Policy."},quasar_feedback_submit_button:{message:"Send Feedback"},quasar_feedback_cancel_button:{message:"Cancel"},quasar_video_title:{message:"Video call from $1...",
placeholders:{1:{content:"$1"}}},quasar_voice_title:{message:"Voice call from $1...",placeholders:{1:{content:"$1"}}},quasar_group_chat_title:{message:"From group chat..."},quasar_chat_title:{message:"$1 says...",placeholders:{1:{content:"$1"}}},quasar_hangout_title:{message:"$1 is hanging out",placeholders:{1:{content:"$1"}}},chrome_ext_oneonone_plus_hangout_details:{message:"is video calling you via Hangouts"},chrome_ext_group_plus_hangout_details:{message:"has invited you to a group Hangout video call"},
quasar_video_details:{message:"is calling you with video chat"},quasar_voice_details:{message:"is calling you"},quasar_tip_connected:{message:"Status: Connected"},chrome_ext_tip_connected_missed_messages:{message:"Status: Connected\nMissed messages"},quasar_tip_connecting:{message:"Status: Connecting"},quasar_tip_reconnecting:{message:"Status: Reconnecting"},quasar_tip_disconnected:{message:"Status: Disconnected"},quasar_tip_not_login:{message:"Status: Not logged in"},quasar_tip_not_load:{message:"Status: Loading error"},
chrome_ext_menutext_unsigned_user:{message:"Not signed in"},quasar_menutext_unknown_user:{message:"Unknown"},quasar_menutext_feedback:{message:"Feedback"},quasar_menutext_settings:{message:"Options"},quasar_menutext_quit:{message:"Exit"},quasar_menutext_signout:{message:"Sign out"},chrome_ext_cannot_connect:{message:"Unable to connect to Google. Please check your internet connection."},quasar_try_now:{message:"Try now"},quasar_sign_in_to_start_talking:{message:"Sign in to start talking with friends"},
quasar_sign_in:{message:"Sign in"},chrome_app_connection_error_title:{message:"Connection Error"},chrome_app_connection_error_detail:{message:"Make sure you are connected to the Internet and try again"},chrome_app_connection_error_button:{message:"Try again"},chrome_app_welcome_message:{message:"Enjoy private and group conversations with text, photos, gifs, voice, video and more."},chrome_app_chrome_signin_message:{message:"Sign in to Chrome to get started."},chrome_app_learn_more_message:{message:"Learn more"},
chrome_app_signin_button:{message:"Sign in"},chrome_app_exit_title:{message:"Are you sure you want to quit Hangouts?"},chrome_app_exit_detail:{message:"Once quit, you will not receive new messages or calls"},chrome_app_exit_no:{message:"No"},chrome_app_exit_quit:{message:"Quit"}};

}catch(e){_DumpException(e)}
try{
var n=function(a){return void 0!==a},da=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},ea=function(a,b,c){return a.call.apply(a.bind,arguments)},fa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);
if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},p=function(a,b){function c(){}c.prototype=b.prototype;
a.t=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Jd=function(a,c,f){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}},ga=function(a,b){var c=a.split("."),d=k;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&n(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}},r=function(a,b,c){r=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ea:da;return r.apply(null,arguments)},ha=function(a){var b=typeof a;
return"object"==b&&null!=a||"function"==b},s=function(a){return"function"==fa(a)},ia=function(a){return"number"==typeof a},t=function(a){return"string"==typeof a},ja=function(a){var b=fa(a);return"array"==b||"object"==b&&"number"==typeof a.length},u=function(a){return"array"==fa(a)},ka=function(){},ma=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,ma);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};p(ma,Error);ma.prototype.name="CustomError";
var oa=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},qa=function(a,b){for(var c=0,d=oa(String(a)).split("."),e=oa(String(b)).split("."),f=Math.max(d.length,e.length),h=0;0==c&&h<f;h++){var l=d[h]||"",q=e[h]||"",B=RegExp("(\\d*)(\\D*)","g"),K=RegExp("(\\d*)(\\D*)","g");do{var ca=B.exec(l)||["","",""],O=K.exec(q)||["","",""];if(0==ca[0].length&&0==O[0].length)break;c=pa(0==ca[1].length?0:parseInt(ca[1],10),0==O[1].length?0:parseInt(O[1], 10))||pa(0==ca[2].length,0==O[2].length)||pa(ca[2],O[2])}while(0==c)}return c},pa=function(a,b){return a<b?-1:a>b?1:0};
var v=Array.prototype,ra=v.indexOf?function(a,b,c){return v.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(t(a))return t(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},sa=v.lastIndexOf?function(a,b,c){return v.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(t(a))return t(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;
return-1},w=v.forEach?function(a,b,c){v.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},ta=v.filter?function(a,b,c){return v.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,h=t(a)?a.split(""):a,l=0;l<d;l++)if(l in h){var q=h[l];b.call(c,q,l,a)&&(e[f++]=q)}return e},ua=v.map?function(a,b,c){return v.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=t(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,
f[h],h,a));return e},va=v.reduce?function(a,b,c,d){d&&(b=r(b,d));return v.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;w(a,function(c,h){e=b.call(d,e,c,h,a)});return e},wa=v.some?function(a,b,c){return v.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1},xa=function(a,b){var c=ra(a,b),d;(d=0<=c)&&v.splice.call(a,c,1);return d};
var ya=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;var za=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},Aa=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},Ba=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};var x=function(){},y=function(a,b,c,d){a.a={};b||(b=c?[c]:[]);a.p=c?String(c):void 0;a.b=0===c?-1:0;a.G=b;t:{if(a.G.length&&(b=a.G.length-1,(c=a.G[b])&&"object"==typeof c&&"number"!=typeof c.length)){a.j=b-a.b;a.c=c;break t}a.j=Number.MAX_VALUE}if(d)for(b=0;b<d.length;b++)c=d[b],c<a.j?(c+=a.b,a.G[c]=a.G[c]||[]):a.c[c]=a.c[c]||[]},z=function(a,b){return b<a.j?a.G[b+a.b]:a.c[b]};x.prototype.toString=function(){return this.G.toString()};var A=function(a,b){Ca[a]=b;b.messageId=a},Ca={};
var Da="StopIteration"in k?k.StopIteration:Error("f"),Ea=function(){};Ea.prototype.next=function(){throw Da;};Ea.prototype.ha=function(){return this};var Fa;t:{var Ga=k.navigator;if(Ga){var Ha=Ga.userAgent;if(Ha){Fa=Ha;break t}}Fa=""}var Ia=function(a){return-1!=Fa.indexOf(a)};var C=function(a,b){this.a={};this.b=[];this.j=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("h");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof C?(c=a.M(),d=a.A()):(c=Ba(a),d=Aa(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};g=C.prototype;g.U=function(){return this.c};g.A=function(){Ja(this);for(var a=[],b=0;b<this.b.length;b++)a.push(this.a[this.b[b]]);return a};g.M=function(){Ja(this);return this.b.concat()};g.P=function(){return 0==this.c};
g.clear=function(){this.a={};this.j=this.c=this.b.length=0};g.remove=function(a){return Ka(this.a,a)?(delete this.a[a],this.c--,this.j++,this.b.length>2*this.c&&Ja(this),!0):!1};var Ja=function(a){if(a.c!=a.b.length){for(var b=0,c=0;b<a.b.length;){var d=a.b[b];Ka(a.a,d)&&(a.b[c++]=d);b++}a.b.length=c}if(a.c!=a.b.length){for(var e={},c=b=0;b<a.b.length;)d=a.b[b],Ka(e,d)||(a.b[c++]=d,e[d]=1),b++;a.b.length=c}};g=C.prototype;g.get=function(a,b){return Ka(this.a,a)?this.a[a]:b};
g.set=function(a,b){Ka(this.a,a)||(this.c++,this.b.push(a),this.j++);this.a[a]=b};g.forEach=function(a,b){for(var c=this.M(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};g.clone=function(){return new C(this)};g.ha=function(a){Ja(this);var b=0,c=this.b,d=this.a,e=this.j,f=this,h=new Ea;h.next=function(){for(;;){if(e!=f.j)throw Error("i");if(b>=c.length)throw Da;var h=c[b++];return a?h:d[h]}};return h};var Ka=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
var La=function(a){if("function"==typeof a.A)return a.A();if(t(a))return a.split("");if(ja(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Aa(a)},Ma=function(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(ja(a)||t(a))w(a,b,c);else{var d;if("function"==typeof a.M)d=a.M();else if("function"!=typeof a.A)if(ja(a)||t(a)){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else d=Ba(a);else d=void 0;for(var e=La(a),f=e.length,h=0;h<f;h++)b.call(c,e[h],d&&d[h],a)}};
var Na=Ia("Opera")||Ia("OPR"),D=Ia("Trident")||Ia("MSIE"),Oa=Ia("Gecko")&&-1==Fa.toLowerCase().indexOf("webkit")&&!(Ia("Trident")||Ia("MSIE")),Pa=-1!=Fa.toLowerCase().indexOf("webkit"),Qa=k.navigator||null,Ra=Qa&&Qa.platform||"",Sa=function(){var a=k.document;return a?a.documentMode:void 0},Ta=function(){var a="",b;if(Na&&k.opera)return a=k.opera.version,s(a)?a():a;Oa?b=/rv\:([^\);]+)(\)|;)/:D?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:Pa&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(Fa))?a[1]:"");return D&&(b= Sa(),b>parseFloat(a))?String(b):a}(),Ua={},Va=function(a){return Ua[a]||(Ua[a]=0<=qa(Ta,a))},Wa=k.document,Xa=Wa&&D?Sa()||("CSS1Compat"==Wa.compatMode?parseInt(Ta,10):5):void 0;
var E=function(){this.C=this.C;this.j=this.j};E.prototype.C=!1;E.prototype.Eb=function(){return this.C};E.prototype.B=function(){this.C||(this.C=!0,this.n())};E.prototype.n=function(){if(this.j)for(;this.j.length;)this.j.shift()()};var F=function(a){a&&"function"==typeof a.B&&a.B()};
var Ya=!D||D&&9<=Xa;!Oa&&!D||D&&D&&9<=Xa||Oa&&Va("1.9.1");D&&Va("9");var Za=function(a){Za[" "](a);return a};Za[" "]=ka;var $a=function(a,b){try{return Za(a[b]),!0}catch(c){}return!1};var ab=!D||D&&9<=Xa,bb=D&&!Va("9");!Pa||Va("528");Oa&&Va("1.9b")||D&&Va("8")||Na&&Va("9.5")||Pa&&Va("528");Oa&&!Va("8")||D&&Va("9");var G=function(a,b){this.type=a;this.a=this.target=b;this.wc=!0};G.prototype.B=function(){};G.prototype.b=function(){this.wc=!1};var cb=function(a,b){G.call(this,a?a.type:"");this.a=this.target=null;this.clientY=this.clientX=0;this.c=this.state=null;if(a){this.type=a.type;this.target=a.target||a.srcElement;this.a=b;var c=a.relatedTarget;c&&Oa&&$a(c,"nodeName");this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:a.pageY;this.state=a.state;this.c=a;a.defaultPrevented&&this.b()}};p(cb,G); cb.prototype.b=function(){cb.t.b.call(this);var a=this.c;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,bb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var eb="closure_listenable_"+(1E6*Math.random()|0),fb=function(a){return!(!a||!a[eb])},gb=0;var hb=function(a,b,c,d,e){this.qa=a;this.proxy=null;this.src=b;this.type=c;this.Ya=!!d;this.fb=e;this.key=++gb;this.removed=this.Xa=!1},ib=function(a){a.removed=!0;a.qa=null;a.proxy=null;a.src=null;a.fb=null};var jb=function(a){this.src=a;this.a={};this.b=0};jb.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var h=kb(a,b,d,e);-1<h?(b=a[h],c||(b.Xa=!1)):(b=new hb(b,this.src,f,!!d,e),b.Xa=c,a.push(b));return b};jb.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=kb(e,b,c,d);return-1<b?(ib(e[b]),v.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var lb=function(a,b){var c=b.type;if(!(c in a.a))return!1;var d=xa(a.a[c],b);d&&(ib(b),0==a.a[c].length&&(delete a.a[c],a.b--));return d};jb.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,ib(d[e]);delete this.a[c];this.b--}return b}; var mb=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=kb(a,c,d,e));return-1<b?a[b]:null},kb=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.qa==b&&f.Ya==!!c&&f.fb==d)return e}return-1};
var nb="closure_lm_"+(1E6*Math.random()|0),ob={},pb=0,qb=function(a,b,c,d,e){if(u(b)){for(var f=0;f<b.length;f++)qb(a,b[f],c,d,e);return null}c=rb(c);return fb(a)?a.listen(b,c,d,e):sb(a,b,c,!1,d,e)},sb=function(a,b,c,d,e,f){if(!b)throw Error("l");var h=!!e,l=tb(a);l||(a[nb]=l=new jb(a));c=l.add(b,c,d,e,f);if(c.proxy)return c;d=ub();c.proxy=d;d.src=a;d.qa=c;a.addEventListener?a.addEventListener(b.toString(),d,h):a.attachEvent(vb(b.toString()),d);pb++;return c},ub=function(){var a=wb,b=ab?function(c){return a.call(b.src,
b.qa,c)}:function(c){c=a.call(b.src,b.qa,c);if(!c)return c};return b},xb=function(a,b,c,d,e){if(u(b))for(var f=0;f<b.length;f++)xb(a,b[f],c,d,e);else c=rb(c),fb(a)?a.Mb(b,c,d,e):a&&(a=tb(a))&&(b=mb(a,b,c,!!d,e))&&yb(b)},yb=function(a){if(ia(a)||!a||a.removed)return!1;var b=a.src;if(fb(b))return lb(b.T,a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.Ya):b.detachEvent&&b.detachEvent(vb(c),d);pb--;(c=tb(b))?(lb(c,a),0==c.b&&(c.src=null,b[nb]=null)):ib(a);return!0},vb=function(a){return a in
ob?ob[a]:ob[a]="on"+a},Ab=function(a,b,c,d){var e=1;if(a=tb(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.Ya==c&&!f.removed&&(e&=!1!==zb(f,d))}return Boolean(e)},zb=function(a,b){var c=a.qa,d=a.fb||a.src;a.Xa&&yb(a);return c.call(d,b)},wb=function(a,b){if(a.removed)return!0;if(!ab){var c;if(!(c=b))t:{c=["window","event"];for(var d=k,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break t}c=d}e=c;c=new cb(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){t:{var f=
!1;if(0==e.keyCode)try{e.keyCode=-1;break t}catch(h){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.a;f;f=f.parentNode)e.push(f);for(var f=a.type,l=e.length-1;0<=l;l--)c.a=e[l],d&=Ab(e[l],f,!0,c);for(l=0;l<e.length;l++)c.a=e[l],d&=Ab(e[l],f,!1,c)}return d}return zb(a,new cb(b,this))},tb=function(a){a=a[nb];return a instanceof jb?a:null},Bb="__closure_events_fn_"+(1E9*Math.random()>>>0),rb=function(a){if(s(a))return a;a[Bb]||(a[Bb]=function(b){return a.handleEvent(b)});return a[Bb]};
var Cb=function(a){y(this,a,"h_cc",[])};p(Cb,x);A("h_cc",Cb);Cb.prototype.Y=function(){return z(this,19)};var H=function(a){E.call(this);this.J=a;this.g={}};p(H,E);var Db=[];H.prototype.listen=function(a,b,c,d){return Eb(this,a,b,c,d)};var Eb=function(a,b,c,d,e,f){u(c)||(c&&(Db[0]=c.toString()),c=Db);for(var h=0;h<c.length;h++){var l=qb(b,c[h],d||a.handleEvent,e||!1,f||a.J||a);if(!l)break;a.g[l.key]=l}return a};
H.prototype.Mb=function(a,b,c,d,e){if(u(b))for(var f=0;f<b.length;f++)this.Mb(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.J||this,c=rb(c),d=!!d,b=fb(a)?mb(a.T,String(b),c,d,e):a?(a=tb(a))?mb(a,b,c,d,e):null:null,b&&(yb(b),delete this.g[b.key]);return this};H.prototype.removeAll=function(){za(this.g,yb);this.g={}};H.prototype.n=function(){H.t.n.call(this);this.removeAll()};H.prototype.handleEvent=function(){throw Error("m");};
var I=function(){E.call(this);this.T=new jb(this);this.L=this;this.u=null};p(I,E);I.prototype[eb]=!0;g=I.prototype;g.addEventListener=function(a,b,c,d){qb(this,a,b,c,d)};g.removeEventListener=function(a,b,c,d){xb(this,a,b,c,d)};g.n=function(){I.t.n.call(this);this.T&&this.T.removeAll(void 0);this.u=null};g.listen=function(a,b,c,d){return this.T.add(String(a),b,!1,c,d)};g.Mb=function(a,b,c,d){return this.T.remove(String(a),b,c,d)}; g.da=function(a,b,c){a=this.T.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.Ya==b){var h=f.qa,l=f.fb||f.src;f.Xa&&lb(this.T,f);d=!1!==h.call(l,c)&&d}}return d&&0!=c.wc};
var Fb,Gb,Hb,Ib,Jb,Kb,Lb;Lb=Kb=Jb=Ib=Hb=Gb=Fb=!1;var Mb=Fa;Mb&&(-1!=Mb.indexOf("Firefox")?Fb=!0:-1!=Mb.indexOf("Camino")?Gb=!0:-1!=Mb.indexOf("iPhone")||-1!=Mb.indexOf("iPod")?Hb=!0:-1!=Mb.indexOf("iPad")?Ib=!0:-1!=Mb.indexOf("Chrome")?Kb=!0:-1!=Mb.indexOf("Android")?Jb=!0:-1!=Mb.indexOf("Safari")&&(Lb=!0));var Ob=Fb,Pb=Gb,Qb=Hb,Rb=Ib,Sb=Jb,Tb=Kb,Ub=Lb;
var Vb=function(a){k.setTimeout(function(){throw a;},0)},Yb=function(a,b){var c=a;b&&(c=r(a,b));!s(k.setImmediate)||k.Window&&k.Window.prototype.setImmediate==k.setImmediate?(Wb||(Wb=Xb()),Wb(c)):k.setImmediate(c)},Wb,Xb=function(){var a=k.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&(a=function(){var a=document.createElement("iframe");a.style.display="none";a.src="";document.documentElement.appendChild(a);var b=a.contentWindow,a=
b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=r(function(a){if(a.origin==d||a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!Ia("Trident")&&!Ia("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){c=c.next;var a=c.Xb;c.Xb=null;a()};return function(a){d.next={Xb:a};
d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in document.createElement("script")?function(a){var b=document.createElement("script");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};document.documentElement.appendChild(b)}:function(a){k.setTimeout(a,0)}};
var dc=function(a,b){Zb||$b();ac||(Zb(),ac=!0);bc.push(new cc(a,b))},Zb,$b=function(){if(k.Promise&&k.Promise.resolve){var a=k.Promise.resolve();Zb=function(){a.then(ec)}}else Zb=function(){Yb(ec)}},ac=!1,bc=[],ec=function(){for(;bc.length;){var a=bc;bc=[];for(var b=0;b<a.length;b++){var c=a[b];try{c.a.call(c.b)}catch(d){Vb(d)}}}ac=!1},cc=function(a,b){this.a=a;this.b=b};
var fc=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},gc=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var ic=function(a,b){this.b=0;this.f=void 0;this.a=this.c=null;this.j=this.e=!1;try{var c=this;a.call(b,function(a){hc(c,2,a)},function(a){hc(c,3,a)})}catch(d){hc(this,3,d)}},kc=function(){var a,b=new ic(function(b){a=b});return new jc(b,a)};ic.prototype.then=function(a,b,c){return lc(this,s(a)?a:null,s(b)?b:null,c)};fc(ic);
var oc=function(a){0==a.b&&dc(function(){var a=new mc(void 0);nc(this,a)},a)},nc=function(a,b){if(0==a.b)if(a.c){var c=a.c;if(c.a){for(var d=0,e=-1,f=0,h;h=c.a[f];f++)if(h=h.Za)if(d++,h==a&&(e=f),0<=e&&1<d)break;0<=e&&(0==c.b&&1==d?nc(c,b):(d=c.a.splice(e,1)[0],pc(c,d,3,b)))}}else hc(a,3,b)},rc=function(a,b){a.a&&a.a.length||2!=a.b&&3!=a.b||qc(a);a.a||(a.a=[]);a.a.push(b)},lc=function(a,b,c,d){var e={Za:null,qc:null,sc:null};e.Za=new ic(function(a,h){e.qc=b?function(c){try{var e=b.call(d,c);a(e)}catch(B){h(B)}}:
a;e.sc=c?function(b){try{var e=c.call(d,b);!n(e)&&b instanceof mc?h(b):a(e)}catch(B){h(B)}}:h});e.Za.c=a;rc(a,e);return e.Za};ic.prototype.g=function(a){this.b=0;hc(this,2,a)};ic.prototype.h=function(a){this.b=0;hc(this,3,a)};
var hc=function(a,b,c){if(0==a.b){if(a==c)b=3,c=new TypeError("Promise cannot resolve to itself");else{if(gc(c)){a.b=1;c.then(a.g,a.h,a);return}if(ha(c))try{var d=c.then;if(s(d)){sc(a,c,d);return}}catch(e){b=3,c=e}}a.f=c;a.b=b;qc(a);3!=b||c instanceof mc||tc(a,c)}},sc=function(a,b,c){a.b=1;var d=!1,e=function(b){d||(d=!0,a.g(b))},f=function(b){d||(d=!0,a.h(b))};try{c.call(b,e,f)}catch(h){f(h)}},qc=function(a){a.e||(a.e=!0,dc(a.k,a))};
ic.prototype.k=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=[];for(var b=0;b<a.length;b++)pc(this,a[b],this.b,this.f)}this.e=!1};var pc=function(a,b,c,d){if(2==c)b.qc(d);else{for(;a&&a.j;a=a.c)a.j=!1;b.sc(d)}},tc=function(a,b){a.j=!0;dc(function(){a.j&&uc.call(null,b)})},uc=Vb,mc=function(a){ma.call(this,a)};p(mc,ma);mc.prototype.name="cancel";var jc=function(a,b){this.b=a;this.a=b};
var J=function(a){this.a=a};J.prototype.toString=function(){return this.a};var vc=new J("fJuxOc"),wc=new J("ZtVrH"),xc=new J("zZa4xc"),yc=new J("pVbxBc"),zc=new J("byfTOb"),Ac=new J("LEikZe"),Bc=new J("rJmJrc");var Cc=new J("a");var Dc=function(a,b){for(var c=[],d=0;d<arguments.length;d++)c.push(arguments[d]||"");return c.join("_;_")},Ec=function(){return 0<=navigator.userAgent.indexOf("CrOS")};var Fc=function(a,b){this.j=a||"e";this.c=null!=a&&"p"==a?"e":"p";this.b=this.e=null;this.h=b||"u";this.a=this.g=null;this.f=[]};Fc.prototype.message=function(){var a={};a.i=this.a;a.m=this.f;a.r=this.h;a.o=this.g;a.s=this.b;a.st=this.c;a.d=this.e;a.dt=this.j;return a};ga("ace.base.Message.prototype.message",Fc.prototype.message);
var Gc=function(a,b){for(var c in b)switch(c){case "r":a.h=b[c];break;case "i":a.a=b[c];break;case "m":a.f=b[c];break;case "o":a.g=b[c];break;case "s":a.b=b[c];break;case "d":a.e=b[c];break;case "st":a.c=b[c];break;case "dt":a.j=b[c]}return a},Hc=function(a,b,c){null!=b&&(a.b=b,null!=c&&(a.c=c))},Ic=function(a,b){null!=b&&(a.a=b)},Jc=function(a,b){"object"==typeof b?a.f=b:a.f=[b]};Fc.prototype.source=function(){return this.b};Fc.prototype.target=function(){return this.e};Fc.prototype.content=function(){return this.f};
var Kc=function(a,b,c,d,e){E.call(this);this.b=a;this.Ta=b;this.a=typeof b;this.Hb=c?c:!1;this.ba=!0;this.Cb=d?d:!1;this.vb=e?e:!1};p(Kc,E);g=Kc.prototype;g.n=function(){Kc.t.n.call(this);this.b="";this.Ta=null;this.a=""};g.id=function(){return this.b};g.type=function(){return this.a};g.F=function(){return this.Ta};g.setEnabled=function(a){this.ba=a};
var Lc=function(a){return(a=a.exec(Fa))?a[1]:""},Mc=function(){if(Ob)return Lc(/Firefox\/([0-9.]+)/);if(D||Na)return Ta;if(Tb)return Lc(/Chrome\/([0-9.]+)/);if(Ub)return Lc(/Version\/([0-9.]+)/);if(Qb||Rb){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(Fa))return a[1]+"."+a[2]}else{if(Sb)return(a=Lc(/Android\s+([0-9.]+)/))?a:Lc(/Version\/([0-9.]+)/);if(Pb)return Lc(/Camino\/([0-9.]+)/)}return""}();
var Oc=function(a){E.call(this);this.a=new C;this.b=["https://talkgadget.google.com/talkgadget/notifier-js","","https://test.talkgadget.google.com/talkgadget/notifier-js?jsmode=debug_unobfuscated"];a&&Nc(this,a)};p(Oc,E);var Pc=0<=qa(Mc,"23.0.1262.0")&&!Ec();Oc.prototype.n=function(){Oc.t.n.call(this);for(var a=this.a.M(),b=0;b<a.length;++b)F(this.a.get(a[b]));delete this.a};Oc.prototype.getItem=function(a){return Ka(this.a.a,a)?this.a.get(a):null};
Oc.prototype.setItem=function(a){this.a.set(a.id(),a)};var Nc=function(a,b){for(var c in b){var d=b[c],e=null;Ka(a.a.a,c)?(e=a.a.get(c),e.Ta=d.value,d.changed&&(e.vb=d.changed)):(e=new Kc(c,d.value,d.multiple,d.inverse,d.changed),e.setEnabled(!d.disabled));a.a.set(c,e)}};
var Sc=function(){this.c=new C;this.a=null;this.b=!1;this.a=new Qc;this.b=!0;Rc(this)};Sc.va=function(){return Sc.a?Sc.a:Sc.a=new Sc};var Rc=function(a,b){var c=b||ka;a.b?c():chrome.storage.local.get(r(function(a){if(!this.b){for(var b in a)this.c.set(b,a[b]);this.b=!0}c()},a))};Sc.prototype.get=function(a){return this.a.get(a)};Sc.prototype.set=function(a,b){var c=kc();this.a.set(a,b);c.a(void 0);return c.b};Sc.prototype.remove=function(a){this.a.remove(a)};Sc.prototype.clear=function(){this.a.clear()};
var Qc=function(){this.a=window.localStorage};Qc.prototype.clear=function(){this.a.clear()};Qc.prototype.get=function(a){a=this.a.getItem(a);if(a){var b=JSON.parse(a);a=b.data;if("jspb"==b.type){b=Ca[a[0]];if(!b)throw Error("e`"+a[0]);a=new b(a)}}else a=null;return a};Qc.prototype.set=function(a,b){var c=null;b instanceof x&&(b=b.G,c="jspb");var d={};d.data=b;d.timestamp=m();c&&(d.type=c);c=JSON.stringify(d);try{this.a.setItem(a,c)}catch(e){}};Qc.prototype.remove=function(a){try{this.a.removeItem(a)}catch(b){}};
var Tc=function(a,b){this.b=a;this.a=b;this.constructor.Vb||(this.constructor.Vb={});this.constructor.Vb[this.toString()]=this};Tc.prototype.toString=function(){this.c||(this.c=this.b.a+":"+this.a);return this.c};var L=function(a,b){Tc.call(this,a,b)};p(L,Tc);var Uc=function(a){this.a=a},Vc=new Uc("lib");/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
var Wc=function(a,b){this.j=[];this.u=b||null;this.b=this.a=!1;this.c=void 0;this.l=this.p=this.f=!1;this.e=0;this.h=null;this.q=0};Wc.prototype.k=function(a,b){this.f=!1;Xc(this,a,b)};var Xc=function(a,b,c){a.a=!0;a.c=c;a.b=!b;Yc(a)},$c=function(a){if(a.a){if(!a.l)throw new Zc;a.l=!1}};Wc.prototype.g=function(a){$c(this);Xc(this,!0,a)};var ad=function(a,b,c,d){a.j.push([b,c,d]);a.a&&Yc(a)};
Wc.prototype.then=function(a,b,c){var d,e,f=new ic(function(a,b){d=a;e=b});ad(this,d,function(a){"undefined"!=typeof bd&&a instanceof bd?oc(f):e(a)});return f.then(a,b,c)};fc(Wc);
var cd=function(a){return wa(a.j,function(a){return s(a[1])})},Yc=function(a){if(a.e&&a.a&&cd(a)){var b=a.e,c=dd[b];c&&(k.clearTimeout(c.ab),delete dd[b]);a.e=0}a.h&&(a.h.q--,delete a.h);for(var b=a.c,d=c=!1;a.j.length&&!a.f;){var e=a.j.shift(),f=e[0],h=e[1],e=e[2];if(f=a.b?h:f)try{var l=f.call(e||a.u,b);n(l)&&(a.b=a.b&&(l==b||l instanceof Error),a.c=b=l);gc(b)&&(d=!0,a.f=!0)}catch(q){b=q,a.b=!0,cd(a)||(c=!0)}}a.c=b;d&&(l=r(a.k,a,!0),d=r(a.k,a,!1),b instanceof Wc?(ad(b,l,d),b.p=!0):b.then(l,d));c&&
(b=new ed(b),dd[b.ab]=b,a.e=b.ab)},Zc=function(){ma.call(this)};p(Zc,ma);Zc.prototype.message="Deferred has already fired";Zc.prototype.name="AlreadyCalledError";var ed=function(a){this.ab=k.setTimeout(r(this.b,this),0);this.a=a};ed.prototype.b=function(){delete dd[this.ab];throw this.a;};var dd={};

}catch(e){_DumpException(e)}
try{
var fd=function(a,b){for(var c=t(a)?a.split(""):a,d=a.length-1;0<=d;--d)d in c&&b.call(void 0,c[d],d,a)};var hd=function(a){E.call(this);this.c={};this.h={};this.k={};this.e={};this.l={};this.q={};this.p=a?a.ua():new I;this.w=!a;this.f=null;a?(this.f=a,this.k=a.k,this.e=a.e,this.h=a.h,this.l=a.l):m();a=gd(this);this!=a&&(a.g?a.g.push(this):a.g=[this])};p(hd,E);var gd=function(a){for(;a.f;)a=a.f;return a};hd.prototype.get=function(a){var b=this.b(a);if(null==b)throw new id(a);return b};
hd.prototype.b=function(a){for(var b=this;b;b=b.f){if(b.C)throw Error("q");if(b.c[a])return b.c[a][0];if(b.q[a])break}if(b=this.k[a]){b=b(this);if(null==b)throw Error("r`"+a);this.a(a,b);return b}return null};hd.prototype.a=function(a,b,c){if(this.C)c||F(b);else{this.c[a]=[b,!c];b=jd(this,this,a);for(c=0;c<b.length;c++)b[c].g(null);delete this.h[a]}};hd.prototype.u=function(){var a=kd;if(!this.c[a])throw Error("s`"+a);var b=this.c[a];delete this.c[a];b[1]&&F(b[0])};
var jd=function(a,b,c){var d=[],e=a.e[c];e&&(fd(e,function(a){var c;t:{for(c=a.Wb;c;){if(c==b){c=!0;break t}c=c.f}c=!1}c&&(d.push(a.Kd),xa(e,a))}),0==e.length&&delete a.e[c]);return d},ld=function(a,b){a.e&&Ma(a.e,function(a,d,e){fd(a,function(d){d.Wb==b&&xa(a,d)});0==a.length&&delete e[d]})};
hd.prototype.n=function(){if(gd(this)==this){var a=this.g;if(a)for(;a.length;)a[0].B()}else for(var a=gd(this).g,b=0;b<a.length;b++)if(a[b]==this){a.splice(b,1);break}for(var c in this.c)a=this.c[c],a[1]&&"undefined"!=typeof a[0].B&&a[0].B();this.c=null;this.w&&this.p.B();ld(this,this);this.e=null;F(this.v);this.q=this.v=null;hd.t.n.call(this)};hd.prototype.ua=function(){return this.p};var id=function(a){ma.call(this);this.id=a;this.message='Service for "'+a+'" is not registered'};p(id,ma); var md=new Uc("fva");new L(md,1);

}catch(e){_DumpException(e)}
try{
var nd={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},od=function(a,b){b.push('"',a.replace(ya,function(a){if(a in nd)return nd[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return nd[a]=e+b.toString(16)}),'"')},pd="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),qd=function(a,b,c){switch(typeof b){case "string":od(b,c);break;case "number":c.push(isFinite(b)&&
!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if(u(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),qd(a,b[f],c),e=",";c.push("]");break}c.push("{");d="";for(e in b)Object.prototype.hasOwnProperty.call(b,e)&&(f=b[e],"function"!=typeof f&&(c.push(d),od(e,c),c.push(":"),qd(a,f,c),d=","));c.push("}");break;case "function":break;default:throw Error("d`"+typeof b);}},rd=function(){},sd=function(a,
b,c,d,e){if(u(b)){for(var f=0;f<b.length;f++)sd(a,b[f],c,d,e);return null}c=rb(c);return fb(a)?a.T.add(String(b),c,!0,d,e):sb(a,b,c,!0,d,e)},td=function(a){return a?decodeURI(a):a},ud=Pa,vd=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,wd=function(a,b){a.j||(a.j=[]);a.j.push(n(void 0)?r(b,void 0):b)},M=function(a,b,c){b<a.j?a.G[b+a.b]=c:a.c[b]=c},xd=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=
d[c];for(var f=0;f<pd.length;f++)c=pd[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}},yd=function(a){var b=[];qd(new rd,a,b);return b.join("")},zd=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}},Ad=function(a,b,c){null!=b&&(a.e=b,null!=c&&(a.j=c))},N=function(a,b){var c,d=a.u;if(d)for(c=[];d;d=d.u)c.push(d);var d=a.L,e=b,f=e.type||e;if(t(e))e=new G(e,d);else if(e instanceof G)e.target=e.target||
d;else{var h=e,e=new G(f,d);xd(e,h)}var h=!0,l;if(c)for(var q=c.length-1;0<=q;q--)l=e.a=c[q],h=l.da(f,!0,e)&&h;l=e.a=d;h=l.da(f,!0,e)&&h;h=l.da(f,!1,e)&&h;if(c)for(q=0;q<c.length;q++)l=e.a=c[q],h=l.da(f,!1,e)&&h},Bd=function(a,b,c,d,e,f){if(u(c))for(var h=0;h<c.length;h++)Bd(a,b,c[h],d,e,f);else{b=sd(b,c,d||a.handleEvent,e,f||a.J||a);if(!b)return a;a.g[b.key]=b}return a},Cd=function(a){if(ud){ud=!1;var b=k.location;if(b){var c=b.href;if(c&&(c=td(Cd(c)[3]||null))&&c!=b.hostname)throw ud=!0,Error();
}}return a.match(vd)},P=function(a,b){wd(a,zd(F,b))},Dd=function(a,b,c){var d=c?c.G:c;a.a[b]=c;M(a,b,d)},Q=function(a,b,c){if(!a.a[c]){var d=z(a,c);d&&(a.a[c]=new b(d))}return a.a[c]},Ed=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Fd=function(a,b){return a?b?decodeURI(a):decodeURIComponent(a):""},Gd=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},Hd=function(a){return v.concat.apply(v,arguments)},Jd=function(a,
b,c){this.a=a||null;this.b=!!c},Ld=function(a){if(!a.H&&(a.H=new C,a.O=0,a.a))for(var b=a.a.split("&"),c=0;c<b.length;c++){var d=b[c].indexOf("="),e=null,f=null;0<=d?(e=b[c].substring(0,d),f=b[c].substring(d+1)):e=b[c];e=decodeURIComponent(e.replace(/\+/g," "));e=Kd(a,e);a.add(e,f?decodeURIComponent(f.replace(/\+/g," ")):"")}};g=Jd.prototype;g.H=null;g.O=null;g.U=function(){Ld(this);return this.O};
g.add=function(a,b){Ld(this);this.a=null;a=Kd(this,a);var c=this.H.get(a);c||this.H.set(a,c=[]);c.push(b);this.O++;return this};g.remove=function(a){Ld(this);a=Kd(this,a);return Ka(this.H.a,a)?(this.a=null,this.O-=this.H.get(a).length,this.H.remove(a)):!1};g.clear=function(){this.H=this.a=null;this.O=0};g.P=function(){Ld(this);return 0==this.O};var Md=function(a,b){Ld(a);b=Kd(a,b);return Ka(a.H.a,b)};
Jd.prototype.M=function(){Ld(this);for(var a=this.H.A(),b=this.H.M(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};Jd.prototype.A=function(a){Ld(this);var b=[];if(t(a))Md(this,a)&&(b=Hd(b,this.H.get(Kd(this,a))));else{a=this.H.A();for(var c=0;c<a.length;c++)b=Hd(b,a[c])}return b};Jd.prototype.set=function(a,b){Ld(this);this.a=null;a=Kd(this,a);Md(this,a)&&(this.O-=this.H.get(a).length);this.H.set(a,[b]);this.O++;return this};
Jd.prototype.get=function(a,b){var c=a?this.A(a):[];return 0<c.length?String(c[0]):b};var Nd=function(a,b,c){a.remove(b);0<c.length&&(a.a=null,a.H.set(Kd(a,b),Gd(c)),a.O+=c.length)};Jd.prototype.toString=function(){if(this.a)return this.a;if(!this.H)return"";for(var a=[],b=this.H.M(),c=0;c<b.length;c++)for(var d=b[c],e=encodeURIComponent(String(d)),d=this.A(d),f=0;f<d.length;f++){var h=e;""!==d[f]&&(h+="="+encodeURIComponent(String(d[f])));a.push(h)}return this.a=a.join("&")};
Jd.prototype.clone=function(){var a=new Jd;a.a=this.a;this.H&&(a.H=this.H.clone(),a.O=this.O);return a};
var Kd=function(a,b){var c=String(b);a.b&&(c=c.toLowerCase());return c},Od=function(a,b){b&&!a.b&&(Ld(a),a.a=null,a.H.forEach(function(a,b){var e=b.toLowerCase();b!=e&&(this.remove(b),Nd(this,e,a))},a));a.b=b},Pd=/#/g,Qd=/[\#\?@]/g,Rd=/[\#\?]/g,Sd=/[\#\?:]/g,Td=/[#\/\?@]/g,Ud=function(a,b,c){return t(a)?(a=encodeURI(a).replace(b,Ed),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},Vd=function(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^
m()).toString(36)},Wd=function(a,b){var c;"undefined"!=typeof Wd&&a instanceof Wd?(this.ma=n(b)?b:a.ma,Xd(this,a.fa),this.sa=a.sa,this.R=a.R,Yd(this,a.ea),this.N=a.N,Zd(this,a.a.clone()),this.la=a.la):a&&(c=Cd(String(a)))?(this.ma=!!b,Xd(this,c[1]||"",!0),this.sa=Fd(c[2]||""),this.R=Fd(c[3]||"",!0),Yd(this,c[4]),this.N=Fd(c[5]||"",!0),Zd(this,c[6]||"",!0),this.la=Fd(c[7]||"")):(this.ma=!!b,this.a=new Jd(null,0,this.ma))};g=Wd.prototype;g.fa="";g.sa="";g.R="";g.ea=null;g.N="";g.la="";g.ma=!1;
g.toString=function(){var a=[],b=this.fa;b&&a.push(Ud(b,Td,!0),":");if(b=this.R){a.push("//");var c=this.sa;c&&a.push(Ud(c,Td,!0),"@");a.push(encodeURIComponent(String(b)).replace(/%25([0-9a-fA-F]{2})/g,"%$1"));b=this.ea;null!=b&&a.push(":",String(b))}if(b=this.N)this.R&&"/"!=b.charAt(0)&&a.push("/"),a.push(Ud(b,"/"==b.charAt(0)?Rd:Sd,!0));(b=this.a.toString())&&a.push("?",b);(b=this.la)&&a.push("#",Ud(b,Pd));return a.join("")};
var $d=function(a,b){var c=a.clone(),d=!!b.fa;d?Xd(c,b.fa):d=!!b.sa;d?c.sa=b.sa:d=!!b.R;d?c.R=b.R:d=null!=b.ea;var e=b.N;if(d)Yd(c,b.ea);else if(d=!!b.N){if("/"!=e.charAt(0))if(a.R&&!a.N)e="/"+e;else{var f=c.N.lastIndexOf("/");-1!=f&&(e=c.N.substr(0,f+1)+e)}f=e;if(".."==f||"."==f)e="";else if(-1!=f.indexOf("./")||-1!=f.indexOf("/.")){for(var e=0==f.lastIndexOf("/",0),f=f.split("/"),h=[],l=0;l<f.length;){var q=f[l++];"."==q?e&&l==f.length&&h.push(""):".."==q?((1<h.length||1==h.length&&""!=h[0])&&h.pop(),
e&&l==f.length&&h.push("")):(h.push(q),e=!0)}e=h.join("/")}else e=f}d?c.N=e:d=""!==b.a.toString();d?Zd(c,Fd(b.a.toString())):d=!!b.la;d&&(c.la=b.la);return c};Wd.prototype.clone=function(){return new Wd(this)};
var Xd=function(a,b,c){a.fa=c?Fd(b,!0):b;a.fa&&(a.fa=a.fa.replace(/:$/,""))},Yd=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("j`"+b);a.ea=b}else a.ea=null},Zd=function(a,b,c){b instanceof Jd?(a.a=b,Od(a.a,a.ma)):(c||(b=Ud(b,Qd)),a.a=new Jd(b,0,a.ma))},R=function(a,b,c){a.a.set(b,c)},ae=function(a,b,c){u(c)||(c=[String(c)]);Nd(a.a,b,c)},be=function(a,b){return a.a.get(b)},ce=function(a,b){return 0<=ra(a,b)},de=function(a,b,c){if(s(a))c&&(a=r(a,c));else if(a&&"function"==typeof a.handleEvent)a=
r(a.handleEvent,a);else throw Error("n");return 2147483647<b?-1:k.setTimeout(a,b||0)},ee=function(a){k.clearTimeout(a)},fe=function(a){var b={},c;for(c in a)b[c]=a[c];return b},ge=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c],e;if(u(d)||(e=ja(d))&&Object.prototype.hasOwnProperty.call(d,"callee"))a.push.apply(a,d);else if(e)for(var f=a.length,h=d.length,l=0;l<h;l++)a[f+l]=d[l];else a.push(d)}},he=function(a,b){var c;t:{c=a.length;for(var d=t(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){c=e;break t}c=-1}return 0>c?null:t(a)?a.charAt(c):a[c]};
var ie=function(){},le=function(a){var b=a.ia,c=function(a){c.t.constructor.call(this,a);var b=this.S.length;this.a=[];for(var d=0;d<b;++d)this.S[d].Ld||(this.a[d]=new this.S[d](a))};p(c,b);for(var d=[];a;){if(b=a.ia){b.S&&ge(d,b.S);var b=b.prototype,e;for(e in b)if(b.hasOwnProperty(e)&&s(b[e])&&b[e]!==a){var f=!!b[e].Uc,h=je(e,b,d,f);(f=ke(e,b,h,f))&&(c.prototype[e]=f)}}a=a.t&&a.t.constructor}c.prototype.S=d;return c},je=function(a,b,c,d){for(var e=[],f=0;f<c.length&&(c[f].prototype[a]===b[a]||(e.push(f),
!d));++f);return e},ke=function(a,b,c,d){var e;c.length?d?e=function(b){var d=this.a[c[0]];return d?d[a].apply(this.a[c[0]],arguments):this.S[c[0]].prototype[a].apply(this,arguments)}:b[a].Wc?e=function(b){var d;t:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var q=this.a[c[e]];if(q=q?q[a].apply(q,d):this.S[c[e]].prototype[a].apply(this,d)){d=q;break t}}d=!1}return d}:b[a].Vc?e=function(b){var d;t:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var q=
this.a[c[e]],q=q?q[a].apply(q,d):this.S[c[e]].prototype[a].apply(this,d);if(null!=q){d=q;break t}}d=void 0}return d}:b[a].oc?e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=0;e<c.length;++e){var q=this.a[c[e]];q?q[a].apply(q,d):this.S[c[e]].prototype[a].apply(this,d)}}:e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=[],q=0;q<c.length;++q){var B=this.a[c[q]];e.push(B?B[a].apply(B,d):this.S[c[q]].prototype[a].apply(this,d))}return e}:d||b[a].Wc||b[a].Vc||b[a].oc? e=null:e=me;return e},me=function(){return[]};ie.prototype.zb=function(a){if(this.a)for(var b=0;b<this.a.length;++b)if(this.a[b]instanceof a)return this.a[b];return null};
var oe=function(a){if(!a.wb){var b;for(b=a.constructor;b&&!b.ia;)b=b.t&&b.t.constructor;b.ia.$b||(b.ia.$b=le(b));b=new b.ia.$b(a);a.wb=b;a.zb||(a.zb=ne)}},ne=function(a){return this.wb.zb(a)};var pe=function(){};pe.prototype.a=null;var re=function(a){var b;(b=a.a)||(b={},qe(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b};var se,te=function(){};p(te,pe);var ue=function(a){return(a=qe(a))?new ActiveXObject(a):new XMLHttpRequest},qe=function(a){if(!a.b&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.b=d}catch(e){}}throw Error("t");}return a.b};se=new te;
var ve=function(a){I.call(this);this.D=new C;this.k=a||null;this.b=!1;this.h=this.a=null;this.q="";this.e=0;this.c=this.p=this.f=this.l=!1;this.v=0;this.g=null;this.J="";this.w=this.aa=!1};p(ve,I);var we=/^https?$/i,xe=["POST","PUT"],ye=[];ve.prototype.V=function(){this.B();xa(ye,this)};
ve.prototype.send=function(a,b,c,d){if(this.a)throw Error("u`"+this.q+"`"+a);b=b?b.toUpperCase():"GET";this.q=a;this.e=0;this.l=!1;this.b=!0;this.a=this.k?ue(this.k):ue(se);this.h=this.k?re(this.k):re(se);this.a.onreadystatechange=r(this.I,this);try{this.p=!0,this.a.open(b,String(a),!0),this.p=!1}catch(e){ze(this);return}a=c||"";var f=this.D.clone();d&&Ma(d,function(a,b){f.set(b,a)});d=he(f.M(),Ae);c=k.FormData&&a instanceof k.FormData;!ce(xe,b)||d||c||f.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");
f.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.J&&(this.a.responseType=this.J);"withCredentials"in this.a&&(this.a.withCredentials=this.aa);try{Be(this),0<this.v&&((this.w=Ce(this.a))?(this.a.timeout=this.v,this.a.ontimeout=r(this.K,this)):this.g=de(this.K,this.v,this)),this.f=!0,this.a.send(a),this.f=!1}catch(h){ze(this)}};var Ce=function(a){return D&&Va(9)&&ia(a.timeout)&&n(a.ontimeout)},Ae=function(a){return"content-type"==a.toLowerCase()};
ve.prototype.K=function(){"undefined"!=typeof aa&&this.a&&(this.e=8,N(this,"timeout"),De(this,8))};var ze=function(a){a.b=!1;a.a&&(a.c=!0,a.a.abort(),a.c=!1);a.e=5;Ee(a);Fe(a)},Ee=function(a){a.l||(a.l=!0,N(a,"complete"),N(a,"error"))},De=function(a,b){a.a&&a.b&&(a.b=!1,a.c=!0,a.a.abort(),a.c=!1,a.e=b||7,N(a,"complete"),N(a,"abort"),Fe(a))};ve.prototype.n=function(){this.a&&(this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1),Fe(this,!0));ve.t.n.call(this)};
ve.prototype.I=function(){this.C||(this.p||this.f||this.c?Ge(this):this.$())};ve.prototype.$=function(){Ge(this)};
var Ge=function(a){if(a.b&&"undefined"!=typeof aa&&(!a.h[1]||4!=(a.a?a.a.readyState:0)||2!=He(a)))if(a.f&&4==(a.a?a.a.readyState:0))de(a.I,0,a);else if(N(a,"readystatechange"),4==(a.a?a.a.readyState:0)){a.b=!1;try{Ie(a)?(N(a,"complete"),N(a,"success")):(a.e=6,Ee(a))}finally{Fe(a)}}},Fe=function(a,b){if(a.a){Be(a);var c=a.a,d=a.h[0]?ka:null;a.a=null;a.h=null;b||N(a,"ready");try{c.onreadystatechange=d}catch(e){}}},Be=function(a){a.a&&a.w&&(a.a.ontimeout=null);ia(a.g)&&(ee(a.g),a.g=null)},Ie=function(a){var b=
He(a),c;t:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:c=!0;break t;default:c=!1}if(!c){if(b=0===b)a=Cd(String(a.q))[1]||null,!a&&self.location&&(a=self.location.protocol,a=a.substr(0,a.length-1)),b=!we.test(a?a.toLowerCase():"");c=b}return c},He=function(a){try{return 2<(a.a?a.a.readyState:0)?a.a.status:-1}catch(b){return-1}},Je=function(a){try{return a.a?a.a.responseText:""}catch(b){return""}};
var Ke=function(a){y(this,a,"h_icr",[])};p(Ke,x);A("h_icr",Ke);var Le=function(a){y(this,a,"h_cs",[])};p(Le,x);A("h_cs",Le);Le.prototype.getState=function(){return z(this,1)};var Me=new J("HwdKC");
}catch(e){_DumpException(e)}
try{
var Ne=function(){return chrome.runtime.getURL("feedbackdialog.html")};
}catch(e){_DumpException(e)}
try{
var Oe=function(a){return a instanceof Wd?a.clone():new Wd(a,void 0)},Pe=function(a){y(this,a,0,[])};p(Pe,x);var Qe=function(a){y(this,a,0,[])};p(Qe,x);var Re=function(a){y(this,a,0,[])};p(Re,x);
var Se=/[?&]($|#)/,Te=/#|$/,Ue=function(a,b,c,d){for(var e=c.length;0<=(b=a.indexOf(c,b))&&b<d;){var f=a.charCodeAt(b-1);if(38==f||63==f)if(f=a.charCodeAt(b+e),!f||61==f||38==f||35==f)return b;b+=e+1}return-1},Ve=function(a){if(a&&"number"==typeof a.length){if(ha(a))return"function"==typeof a.item||"string"==typeof a.item;if(s(a))return"function"==typeof a.item}return!1},We={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",
role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"},Xe=/[\x00&<>"']/,Ye=/\x00/g,Ze=/'/g,$e=/"/g,af=/>/g,bf=/</g,cf=/&/g,df=function(a,b,c){function d(c){c&&b.appendChild(t(c)?a.createTextNode(c):c)}for(var e=2;e<c.length;e++){var f=c[e];!ja(f)||ha(f)&&0<f.nodeType?d(f):w(Ve(f)?Gd(f):f,d)}},ef=function(a,b){za(b,function(b,d){"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:d in We?a.setAttribute(We[d],b):0==d.lastIndexOf("aria-",0)||0==
d.lastIndexOf("data-",0)?a.setAttribute(d,b):a[d]=b})},ff=function(a){if(!Xe.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(cf,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(bf,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(af,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace($e,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Ze,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Ye,"&#0;"));return a},gf={LOADING:0,Dc:1,Gd:2,Hd:3,ERROR:4,LOADED:5,Cc:6},hf=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Arab|Hebr|Thaa|Nkoo|Tfng))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,
jf=function(a,b,c){for(var d=a.search(Te),e=0,f,h=[];0<=(f=Ue(a,e,b,d));)h.push(a.substring(e,f)),e=Math.min(a.indexOf("&",f)+1||d,d);h.push(a.substr(e));a=[h.join("").replace(Se,"$1"),"&",b];null!=c&&a.push("=",encodeURIComponent(String(c)));a[1]&&(c=a[0],b=c.indexOf("#"),0<=b&&(a.push(c.substr(b)),a[0]=c=c.substr(0,b)),b=c.indexOf("?"),0>b?a[1]="?":b==c.length-1&&(a[1]=void 0));return a.join("")},kf=function(a){I.call(this);this.c=a;this.a=gf.LOADING;this.b=new H(this);P(this,this.b);this.b.listen(this.c.ua(),
"h_cs",this.e)};p(kf,I);kf.prototype.getState=function(){return this.a};kf.prototype.e=function(a){a=new Le(a.gb);this.a!=a.getState()&&(this.a=a.getState(),N(this,"c"))};
var lf=function(a){(a?a:function(){}).Uc=!0},mf=function(a,b,c){var d=arguments,e=document,f=d[0],h=d[1];if(!Ya&&h&&(h.name||h.type)){f=["<",f];h.name&&f.push(' name="',ff(h.name),'"');if(h.type){f.push(' type="',ff(h.type),'"');var l={};xd(l,h);delete l.type;h=l}f.push(">");f=f.join("")}f=e.createElement(f);h&&(t(h)?f.className=h:u(h)?f.className=h.join(" "):ef(f,h));2<d.length&&df(e,f,d);return f},nf=function(a){var b=a||document,c=null;if(b.querySelectorAll&&b.querySelector)c=b.querySelector(".talk_loading_msg");
else{var d,b=document;a=a||b;if(a.querySelectorAll&&a.querySelector)a=a.querySelectorAll(".talk_loading_msg");else if(a.getElementsByClassName){var e=a.getElementsByClassName("talk_loading_msg");a=e}else{e=a.getElementsByTagName("*");d={};for(b=c=0;a=e[b];b++){var f=a.className;"function"==typeof f.split&&ce(f.split(/\s+/),"talk_loading_msg")&&(d[c++]=a)}d.length=c;a=d}c=a[0]}return c||null},of=function(a){var b;b=b||0;return function(){return a.apply(this,Array.prototype.slice.call(arguments,0,b))}};
var pf=function(a){this.a=a;D||(delete this.a.lpu,delete this.a.ppu)},qf=["cn","tp"],rf=function(a,b){var c=null,d;if(s(document.postMessage)||s(window.postMessage)||D&&window.postMessage)d=1;else if(Oa)d=2;else{if(c=D){c=!1;try{d=window.opener,window.opener={},c=$a(window,"opener"),window.opener=d}catch(e){}}d=c?6:4}c=d;d={};d.cn=Math.floor(2147483648*Math.random()).toString(36);d.tp=c;d.ifrid=b;d.pu=a;return new pf(d)};ga("GTalk_IFrameChannelConfig.build",rf);
var sf=function(){};p(sf,ie);sf.prototype.b=function(a){return a};lf(sf.prototype.b);sf.prototype.c=function(){return!0};lf(sf.prototype.c);var tf=function(a){y(this,a,0,[])};p(tf,x);var uf=function(a,b){var c=new tf;M(c,1,b);M(c,2,a);return c},vf=uf("?",0),wf=uf("q",1),xf=uf("<",2),yf=uf(">",3),zf=uf("~",4),Af=uf("s",5),Bf={e:vf,k:wf,g:xf,h:yf,f:zf,l:Af};var Cf=function(a){y(this,a,"ci:dc",[])};p(Cf,x);A("ci:dc",Cf);var Df=function(a){y(this,a,"ci:ec",[])};p(Df,x);A("ci:ec",Df);var Ef=function(a){return null!=z(a,2)?z(a,2):!1};var Ff=function(a){this.a=a},Gf=/\s*;\s*/;g=Ff.prototype;g.set=function(a,b,c,d,e,f){if(/[;=\s]/.test(a))throw Error("v`"+a);if(/[;\r\n]/.test(b))throw Error("w`"+b);n(c)||(c=-1);e=e?";domain="+e:"";d=d?";path="+d:"";f=f?";secure":"";c=0>c?"":0==c?";expires="+(new Date(1970,1,1)).toUTCString():";expires="+(new Date(m()+1E3*c)).toUTCString();this.a.cookie=a+"="+b+e+d+c+f};
g.get=function(a,b){for(var c=a+"=",d=(this.a.cookie||"").split(Gf),e=0,f;f=d[e];e++){if(0==f.lastIndexOf(c,0))return f.substr(c.length);if(f==a)return""}return b};g.remove=function(a,b,c){var d=n(this.get(a));this.set(a,"",0,b,c);return d};g.M=function(){return Hf(this).keys};g.A=function(){return Hf(this).Fd};g.P=function(){return!this.a.cookie};g.U=function(){return this.a.cookie?(this.a.cookie||"").split(Gf).length:0};g.clear=function(){for(var a=Hf(this).keys,b=a.length-1;0<=b;b--)this.remove(a[b])}; var Hf=function(a){a=(a.a.cookie||"").split(Gf);for(var b=[],c=[],d,e,f=0;e=a[f];f++)d=e.indexOf("="),-1==d?(b.push(""),c.push(e)):(b.push(e.substring(0,d)),c.push(e.substring(d+1)));return{keys:b,Fd:c}};
var If=function(a,b,c){oe(this);var d=this.wb.b(a.clientBaseUrl||"https://talkgadget.google.com/talkgadget/");if(0==d.lastIndexOf("https://talkgadget.google.com/talkgadget/",0)){var e=(new Ff(window.document)).get("WCSDBG",""),e=e.split(";")[0],e=e.split("|")[0],f=["plus.google.com"],h=/^[-_a-zA-Z0-9\.]+\.talkgadget\.google\.com$/;0<e.length&&!ce(f,e)&&h.test(e)&&(d=Oe(d),d=Oe("https://"+e+d.N).toString())}this.ca=d;this.c=c||new Df;a.notificationsOnly&&M(this.c,1,!0);this.b="0";null!=a.authUser?
this.b=a.authUser:(c=be(new Wd(window.location.href),"authuser"),null!=c&&(this.b=c));this.j=a.clientUrl||"notifierclient";c=be(Oe(this.j),"authuser");null!=c&&(this.b=c);this.g=a.propertyName||"Google Talk";this.l=a.cssUrl;this.locale=a.locale;this.f=a.debug;this.Sb=a.userJid;this.Qb=a.uiVersion;this.Mc=null!=a.rosterExpanded?a.rosterExpanded:!0;this.L=a.hostLogMinValue;this.Ua=a.hideChat;this.Ic=a.refresh;this.D=a.hideProfileCard;this.K=a.hideStatusMsgs;this.I=a.hideRosterOptions;this.J=a.hideRecentConversations;
this.w=a.hideOTR;this.Fc=a.hostServerMessageCallback||!1;this.$=a.isCentralRoster;this.Hc=a.isFullFrame||!1;this.Lc=a.rosterClass||"talk_roster";this.Ea=a.rosterId||"talk_roster";this.a="gtn-roster-iframe-id";a.rosterFrameId&&a.rosterFrameId.match(/[\w-]/)&&(this.a=a.rosterFrameId);a.rosterIframeIdB&&a.rosterIframeIdB.match(/[\w-]/);this.e=a.parentToken;this.Kc=b||!1;n(a.isRtl)||hf.test(this.locale);this.position=a.position||"l";if(!a.keyboardShortcuts){b=[];for(var l in Bf)b.push(Bf[l].G)}this.q=
a.entityId;this.Rb=a.useQuasarPanels||!1;this.Ob=a.silent||!1;this.Gc=a.ignoreCentralRoster||!1;this.Jc=a.lazy||!1;this.Ec=a.handleProfileLinks||!1;this.V=a.hostSettings;this.h=a.screen;this.p=a.docsConfig;this.aa=a.jsmode;this.Da=a.moleWidth;this.Ca=a.moleHeight;this.Ba=a.minimizedMoleHeight||36;this.Bc=a.derp;this.Pb=window.location.protocol+"//"+window.location.host;this.u=a.optOutAllowed;this.v=a.showWelcomePromo;this.k=a.conversationId};sf.t||p(sf,ie);If.ia=sf;
var Jf=function(a){switch(a){case 1:return"homepage";case 2:return"Orkut";case 3:return"iGoogle";case 4:return"Google Translator Toolkit";case 5:return"Google Sites";case 6:return"customersupport";case 9:return"present";case 15:return"hangout";case 18:return"gmail";case 20:return"docs";case 24:return"docs_hangout";case 22:return"hangout_lite";case 23:return"aChromeExtension";case 25:return"bigtop";case 27:return"ChromeApp";case 29:return"potluck"}};
var Kf=function(a,b,c,d,e){E.call(this);this.a=a;this.b=d||window.document;this.c=new H(this);P(this,this.c);var f=Fa;d=new Wd(a.ca+a.j);Ef(a.c)||(R(d,"ts","0"),R(d,"re",a.Mc),R(d,"ref",a.Ic));R(d,"client","sm");R(d,"prop",a.g);R(d,"nav","true");R(d,"fid",a.a);a.f&&R(d,"debug",a.f);R(d,"os",Ra);R(d,"stime",c);a.Ua&&R(d,"hc",a.Ua);for(c=0;c<qf.length;++c);b=yd(b.a);R(d,"xpc",b);R(d,"ec",yd(a.c.G));a.h&&R(d,"screen",a.h);-1!=f.indexOf("MSIE")&&R(d,"ua",f);a.e&&R(d,"pvt",a.e);a.Fc&&R(d,"hsmc","true");
n(a.L)&&R(d,"logl",a.L);b=window.location.href;0>b.indexOf("?rel=1")&&(b=b.split("?"),b[1]=1==b.length?"rel=1":["rel=1&",b[1]].join(""),R(d,"href",b.join("?")));b=new Wd(window.location.href);"false"==be(b,"uacheck")&&R(d,"uacheck",!1);(f=a.aa)&&R(d,"jsmode",f);(f=be(b,"cssmode"))&&R(d,"cssmode",f);(f=be(b,"convid"))&&R(d,"convid",f);(f=b.a.A("convp"))&&ae(d,"convp",f);(f=be(b,"smexp"))&&R(d,"smexp",f);f=b.a.A("mods");a.Jc&&f.push("lazy");e&&(f=Hd(f,e));0<f.length&&R(d,"mods",f.join(","));if(!a.ca||
0>a.ca.indexOf("/u/"))(e=be(b,"authuser"))?R(d,"authuser",e):null!=a.b&&R(d,"authuser",a.b);e=be(b,"eid");null!=e&&R(d,"eid",e);null!=this.a.q&&R(d,"eid",this.a.q);null!=this.a.position&&R(d,"pos",this.a.position);n(a.Qb)&&R(d,"uiv",this.a.Qb);a.l&&R(d,"css",a.l);e=a.locale||be(b,"hl");null!=e&&R(d,"hl",e);n(a.Sb)&&R(d,"uj",a.Sb);null!=a.D&&R(d,"hpc",a.D);null!=a.K&&R(d,"hsm",a.K);null!=a.I&&R(d,"hro",a.I);null!=a.J&&R(d,"hrc",a.J);null!=a.w&&R(d,"hotr",a.w);null!=a.$&&R(d,"pop",a.$);a.Kc&&R(d,"pal",
"1");null!=a.Rb&&R(d,"uqp",a.Rb);null!=a.u&&R(d,"gooa",a.u);null!=a.v&&R(d,"gswp",a.v);null!=a.Ob&&R(d,"sl",a.Ob);a.Gc&&R(d,"icr","1");a.Ec&&R(d,"hpl","1");a.V&&R(d,"hs",a.V);a.p&&R(d,"dc",yd(a.p.G));null!=a.Da&&R(d,"molew",a.Da);null!=a.Ca&&R(d,"moleh",a.Ca);null!=a.Ba&&R(d,"mmoleh",a.Ba);a.Bc&&R(d,"derp","1");null!=a.Pb&&R(d,"two",a.Pb);null!=a.k&&R(d,"convid",a.k);R(d,"host","1");R(d,"zx",Vd());this.e=d.toString()};p(Kf,E);
var Lf=function(a,b,c,d){var e=a.b.getElementById(b);e||(e=a.b.createElement("div"),e.id=b,e.className=a.a.Lc,a.b.body.appendChild(e));a=r(function(){var a="";this.a.Hc||(a="height:400px");var b=this.b.createElement("iframe");ef(b,{id:this.a.a,name:this.a.a,"class":"talk_iframe",frameborder:"0",style:a});if(!nf(e))for(var a=e,l;l=a.firstChild;)a.removeChild(l);e.appendChild(b);b=this.b.getElementById(this.a.a);Bd(this.c,b,["load","error"],of(d),void 0);b.src=this.e.toString();c()},a);window.setTimeout(a, 0)};
var Mf=function(a){G.call(this,a[0]);this.gb=a};p(Mf,G);var Nf=function(a){y(this,a,"h_ccf",[])};p(Nf,x);A("h_ccf",Nf);var Of=function(a){y(this,a,"h_rtp",[])};p(Of,x);A("h_rtp",Of);var Pf=function(a,b){E.call(this);this.w=m();this.v=a;this.document=b||window.document;this.a=new If(a,!0,a.endpointConfig);this.f=[];this.p=new I};p(Pf,E);Pf.prototype.n=function(){Pf.t.n.call(this);this.b&&this.k&&this.b.parentNode.removeEventListener("DOMAttrModified",this.k,!0)};Pf.prototype.c=function(a,b){this.e?this.e[a]&&this.e[a].apply(this.e,Array.prototype.slice.call(arguments,1)):this.f.push(arguments)};
Pf.prototype.g=function(){var a=this.fc().GTalkNotifier;if(a){var b=fe(this.v);b.endpointConfig=this.a.c.G;this.e=new a(b,!0);for(a=0;a<this.f.length;a++)this.c.apply(this,this.f[a]);this.f=[];a=r(this.onMessage,this);this.c("_addClientMessageCallback",a);this.c("_addHostBundleMessageCallback",a)}};Pf.prototype.onMessage=function(a){switch(a[0]){case "h_ccf":new Nf(a)}N(this.p,new Mf(a))};var Qf=function(a,b){a.c("_h",b.G)};g=Pf.prototype;g.sendMessage=function(a){Qf(this,a)};g.ua=function(){return this.p};
g.fc=function(){return this.document.parentWindow||this.document.defaultView};g.cd=function(a,b){if(b.target==a&&("style"==b.attrName||"class"==b.attrName)){var c=new Of;Qf(this,c)}};g.dd=function(){nf(this.document.getElementById(this.a.Ea))&&(this.document.getElementById(this.a.a).style.display="none")};
var Rf=function(a){var b=a.a.ca+"host-js",b=jf(b,"prop",a.a.g),c=a.a.aa;c&&(b=jf(b,"jsmode",c));Ef(a.a.c)&&(b=jf(b,"b","1"));var b=jf(b,"zx",Vd()),d=r(a.g,a),e=mf("script",{type:"text/javascript",src:b}),f=!1;e.onload=e.onreadystatechange=function(){f||e.readyState&&"loaded"!=e.readyState&&"complete"!=e.readyState||(f=!0,d())};e.onerror=r(a.q,a,e);a.document.body.appendChild(e)};Pf.prototype.q=function(){};
var Sf=function(a){if(a.classList)return a.classList;a=a.className;return t(a)&&a.match(/\S+/g)||[]},Tf=function(a){return a.classList?a.classList.contains("talk_network_warning"):ce(Sf(a),"talk_network_warning")},Uf=function(a){a.classList?a.classList.add("talk_network_warning"):Tf(a)||(a.className+=0<a.className.length?" talk_network_warning":"talk_network_warning")},Vf=function(a){a.classList?a.classList.remove("talk_network_warning"):Tf(a)&&(a.className=ta(Sf(a),function(a){return"talk_network_warning"!= a}).join(" "))};
var Wf=function(a,b){this.b=b;this.a=a};Wf.prototype.F=function(){return this.a};var Xf=function(a){a.a=Math.min(a.b,2*a.a)};var Yf=function(a,b,c){var d={},e=null!=z(a,1)?z(a,1):"talkgadget.google.com",f="";0>e.indexOf("://")&&(f="https://",0<=e.indexOf(":")&&23!=z(a,2)&&27!=z(a,2)&&(f="http://"));d.clientBaseUrl=f+e+"/talkgadget/_/";d.authUser=null!=z(a,8)?z(a,8):"0";d.clientUrl="chat";d.propertyName=Jf(z(a,2));d.locale=z(a,4);d.hideProfileCard=!0;d.parentToken=z(a,3);d.isRtl=null!=z(a,6)?z(a,6):!1;d.lazy=null!=z(a,7)?z(a,7):!1;d.entityId=z(a,9);d.hostSettings=z(a,5);d.jsmode=z(a,11);d.isFullFrame=null!=z(a,13)?z(a,13):
!1;d.rosterId=null!=z(a,12)?z(a,12):"talk_roster";d.rosterIframeIdB=null!=z(a,15)?z(a,15):"gtn-roster-iframe-id-b";d.derp=!(null==z(a,16)||!z(a,16));e=Q(a,Pe,14);null!=e&&(d.isCentralRoster=null!=z(e,1)?z(e,1):!1,d.useQuasarPanels=null!=z(e,2)?z(e,2):!1);e=Q(a,Re,10);null!=e&&(d.moleManagerLeftMargin=z(e,1),d.moleManagerMiddleMargin=z(e,2),d.moleManagerRightMargin=z(e,3),d.moleManagerNoMoleAreaMargin=z(e,4),d.moleManagerBoundingElementId=z(e,5),d.moleWidth=z(e,6),d.moleHeight=z(e,7),d.minimizedMoleHeight=
z(e,8));e=Q(a,Qe,18);null!=e&&(d.optOutAllowed=null!=z(e,1)?z(e,1):!0,d.showWelcomePromo=z(e,2));d.uiVersion=2;d.hideStatusMsgs=!0;d.hideRecentConversations=!0;e=new Df;M(e,2,!0);M(e,1,!0);M(e,3,!1);d.endpointConfig=e;d.ignoreAutomatedRoster=null!=z(a,17)?z(a,17):!1;d.conversationId=a.Y();d.hostCallback=c;Pf.call(this,d,b);this.l=new Wf(5E3,3E5);this.u=null};p(Yf,Pf);
Yf.prototype.q=function(a){var b=nf(this.document.body);b&&Uf(b);this.u=de(function(){null==this.e&&(this.document.body.removeChild(a),Rf(this))},this.l.F(),this);Xf(this.l)};Yf.prototype.g=function(){Yf.t.g.call(this);var a=nf(this.document.body);a&&Vf(a)};Yf.prototype.n=function(){Yf.t.n.call(this);ee(this.u)};
var Zf=function(a){y(this,a,"h_exts",[2])};p(Zf,x);A("h_exts",Zf);var $f=function(){E.call(this);this.b=" "};p($f,E);var ag=function(a,b,c){a.a=c;b=new Wd(b);b=$d(b,new Wd("/talkgadget/_/extension-start"));a=r(a.c,a);c=new ve;ye.push(c);a&&c.listen("complete",a);c.T.add("ready",c.V,!0,void 0,void 0);c.send(b,void 0,void 0,void 0)};$f.prototype.c=function(a){if(!this.C){if(Ie(a.target))try{var b=JSON.parse(Je(a.target)),c=new Zf(b);this.b=z(c,1)||""}catch(d){this.b=""}this.a&&(this.a(),this.a=null)}};
var bg=function(a){I.call(this);this.c=a?a:null;this.a=null;this.e=!1;this.b=[];this.f=r(this.Oc,this);this.g=r(this.Tb,this);this.h=null};p(bg,I);var cg=function(a){G.call(this,"message");this.message=a};p(cg,G);g=bg.prototype;g.n=function(){bg.t.n.call(this);ee(this.h);this.Tb(!0);for(var a=0;a<this.b.length;++a)F(this.b[a]);delete this.b;delete this.f;delete this.g};
g.sendMessage=function(a){if(null==a||null==a.message)return!1;Hc(a,this.c,"p");this.a&&this.e?this.a.postMessage(a.message()):this.b.push(a);return!0};g.connect=function(){if(null==this.c)return!1;try{if(this.a=chrome.runtime.connect({name:this.c}),null==this.a)return!1}catch(a){return!1}this.e=!0;this.a.onMessage.addListener(this.f);this.a.onDisconnect.addListener(this.g);for(var b=this.b.shift();null!=b;)Hc(b,this.c,"p"),this.a.postMessage(b.message()),b=this.b.shift();return!0};
g.Oc=function(a){N(this,new cg(Gc(new Fc,a)))};g.Tb=function(a){this.a&&(this.a.onMessage.removeListener(this.f),this.a.onDisconnect.removeListener(this.g),this.a.disconnect(),delete this.a);this.e=!1;a||(this.h=de(this.yd,5E3,this))};g.yd=function(){this.connect()?N(this,{type:"reconnected"}):N(this,{type:"disconnected"})};
var dg=function(a){y(this,a,"h_cp",[])};p(dg,x);A("h_cp",dg);var eg=function(a){y(this,a,"rbc_d",[])};p(eg,x);A("rbc_d",eg);eg.prototype.setTitle=function(a){M(this,1,a)};var fg=function(a){y(this,a,"h_cd",[1,4,5])};p(fg,x);A("h_cd",fg);fg.prototype.Y=function(){return z(this,2)};var gg=function(a){y(this,a,"h_hn",[])};p(gg,x);A("h_hn",gg);var hg=function(a){y(this,a,"h_hs",[])};p(hg,x);A("h_hs",hg);var ig=function(a){y(this,a,"h_jm",[2])};p(ig,x);A("h_jm",ig);var jg=function(a){y(this,a,"h_oc",[])};p(jg,x);A("h_oc",jg);var kg=function(a){y(this,a,"h_opc",[])};p(kg,x);A("h_opc",kg);var lg=function(a){y(this,a,"h_ogc",[])};p(lg,x);A("h_ogc",lg);var mg=function(a){y(this,a,"h_sc",[])};p(mg,x);A("h_sc",mg);var ng=function(a){y(this,a,"h_ssc",[5])};p(ng,x);A("h_ssc",ng);var og=function(a){y(this,a,"h_sm",[1,3])};p(og,x);A("h_sm",og);var pg=function(a){I.call(this);this.a=a};p(pg,I);var qg=new J("O9EQob");var rg=function(a){y(this,a,"capi:f_cfr",[])};p(rg,x);A("capi:f_cfr",rg);var sg=function(a){y(this,a,"capi:f_cvr",[])};p(sg,x);A("capi:f_cvr",sg);var tg=function(a){y(this,a,"capi:f_vsm",[])};p(tg,x);A("capi:f_vsm",tg);var ug=function(a){y(this,a,"capi:f_ccr",[])};p(ug,x);A("capi:f_ccr",ug);var vg=function(a){y(this,a,"capi:f_csm",[])};p(vg,x);A("capi:f_csm",vg);var wg=function(a){y(this,a,0,[])};p(wg,x);var xg=function(a){y(this,a,"capi:f_var",[])};p(xg,x);A("capi:f_var",xg);
xg.prototype.getState=function(){return Q(this,wg,1)};var yg=function(a){y(this,a,"capi:f_van",[])};p(yg,x);A("capi:f_van",yg);yg.prototype.getState=function(){return Q(this,wg,1)};var zg=function(a){y(this,a,0,[])};p(zg,x);var Ag=function(a){y(this,a,"capi:f_vcr",[])};p(Ag,x);A("capi:f_vcr",Ag);Ag.prototype.getState=function(){return Q(this,zg,1)};var Bg=function(a){y(this,a,"capi:f_vcn",[])};p(Bg,x);A("capi:f_vcn",Bg);Bg.prototype.getState=function(){return Q(this,zg,1)};
var Cg=function(a){y(this,a,0,[])};p(Cg,x);var Dg=function(a){y(this,a,"capi:f_vcor",[])};p(Dg,x);A("capi:f_vcor",Dg);Dg.prototype.getState=function(){return Q(this,Cg,1)};var Eg=function(a){y(this,a,"capi:f_vcon",[])};p(Eg,x);A("capi:f_vcon",Eg);Eg.prototype.getState=function(){return Q(this,Cg,1)};var Fg=function(a){y(this,a,0,[])};p(Fg,x);var Gg=function(a){y(this,a,"capi:f_vfr",[])};p(Gg,x);A("capi:f_vfr",Gg);Gg.prototype.getState=function(){return Q(this,Fg,1)};
Gg.prototype.ec=function(){return z(this,2)};Gg.prototype.xc=function(a){M(this,2,a)};var Hg=function(a){y(this,a,"capi:f_vfn",[])};p(Hg,x);A("capi:f_vfn",Hg);Hg.prototype.getState=function(){return Q(this,Fg,1)};var Ig=function(a){y(this,a,0,[])};p(Ig,x);var Jg=function(a){y(this,a,"capi:f_vmr",[])};p(Jg,x);A("capi:f_vmr",Jg);Jg.prototype.getState=function(){return Q(this,Ig,1)};var Kg=function(a){y(this,a,"capi:f_vmn",[])};p(Kg,x);A("capi:f_vmn",Kg);
Kg.prototype.getState=function(){return Q(this,Ig,1)};var Lg=function(a){y(this,a,0,[])};p(Lg,x);var Mg=function(a){y(this,a,"capi:f_vpr",[])};p(Mg,x);A("capi:f_vpr",Mg);Mg.prototype.getState=function(){return Q(this,Lg,1)};var Ng=function(a){y(this,a,"capi:f_vpn",[])};p(Ng,x);A("capi:f_vpn",Ng);Ng.prototype.getState=function(){return Q(this,Lg,1)};var Og=function(a){y(this,a,"capi:f_vsr",[])};p(Og,x);A("capi:f_vsr",Og);var Pg=function(a){y(this,a,"capi:f_vsn",[])};p(Pg,x);A("capi:f_vsn",Pg);
var Qg=function(a){y(this,a,"capi:f_vtr",[])};p(Qg,x);A("capi:f_vtr",Qg);Qg.prototype.setTitle=function(a){Dd(this,1,a)};var Rg=function(a){y(this,a,"capi:f_vtn",[])};p(Rg,x);A("capi:f_vtn",Rg);Rg.prototype.setTitle=function(a){Dd(this,1,a)};var Sg=function(a){y(this,a,0,[])};p(Sg,x);var Tg=function(a){y(this,a,"capi:f_vvr",[])};p(Tg,x);A("capi:f_vvr",Tg);Tg.prototype.getState=function(){return Q(this,Sg,1)};var Ug=function(a){y(this,a,"capi:f_vvn",[])};p(Ug,x);A("capi:f_vvn",Ug);
Ug.prototype.getState=function(){return Q(this,Sg,1)};var Vg=function(a){y(this,a,0,[])};p(Vg,x);var Wg=function(a){y(this,a,"capi:f_uvor",[])};p(Wg,x);A("capi:f_uvor",Wg);var Xg=function(a){y(this,a,"capi:f_uvon",[])};p(Xg,x);A("capi:f_uvon",Xg);var Yg=function(a){y(this,a,0,[])};p(Yg,x);var Zg=function(a){y(this,a,"capi:f_sp",[])};p(Zg,x);A("capi:f_sp",Zg);Zg.prototype.getState=function(){return Q(this,Yg,1)};var $g=function(a){y(this,a,"capi:f_spn",[])};p($g,x);A("capi:f_spn",$g); $g.prototype.getState=function(){return Q(this,Vg,1)};
var ah=function(a){y(this,a,"capi:clstup",[])};p(ah,x);A("capi:clstup",ah);var bh=function(a){y(this,a,"capi:r_clre",[])};p(bh,x);A("capi:r_clre",bh);var ch=function(a){y(this,a,"capi:r_rrst",[])};p(ch,x);A("capi:r_rrst",ch);var dh=function(a){y(this,a,"capi:r_rers",[])};p(dh,x);A("capi:r_rers",dh);var eh=function(a){y(this,a,"capi:r_recl",[])};p(eh,x);A("capi:r_recl",eh);var fh=function(a){y(this,a,"capi:r_rstr",[])};p(fh,x);A("capi:r_rstr",fh);
var gh=new J("nED8Yb"),hh=new J("xclgJb");var ih=function(a){y(this,a,"h_ec",[])};p(ih,x);A("h_ec",ih);var jh=function(a){y(this,a,"h_fr",[])};p(jh,x);A("h_fr",jh);var kh=function(a){y(this,a,"capii_c_cel",[])};p(kh,x);A("capii_c_cel",kh);var lh=function(a){y(this,a,"capi:rfc",[])};p(lh,x);A("capi:rfc",lh);var mh=function(a){y(this,a,"capii_c_ucmc",[])};p(mh,x);A("capii_c_ucmc",mh);var nh=function(a){y(this,a,"capii_c_rc",[])};p(nh,x);A("capii_c_rc",nh);nh.prototype.Y=function(){return z(this,1)};
var oh=function(a){I.call(this);this.c=a.get(gh);this.a=this.f=0;this.e=this.b=!1;a=new H(this);P(this,a);a.listen(this.c.ua(),"capii_c_ucmc",this.g);this.c.sendMessage(new mh)};p(oh,I);oh.prototype.g=function(a){a=new mh(a.gb);this.b||(this.b=!0,this.e&&(M(a,5,!0),this.e=!1));var b=this.f!=z(a,1);this.f=Number(z(a,1));var c=this.a!=z(a,2);this.a=Number(z(a,2));z(a,5)?N(this,"g"):(b&&N(this,"i"),c&&N(this,"h"))};
var ph=function(a){y(this,a,"h_rha",[])};p(ph,x);A("h_rha",ph);var qh=function(a){y(this,a,"h_ssf",[])};p(qh,x);A("h_ssf",qh);var rh=function(a,b){E.call(this);this.a=new H(this);P(this,this.a);this.a.listen(a.ua(),"h_ssf",function(a){a=new qh(a.gb);a=z(a,1);var c;if(null!=a&&JSON&&JSON.parse)try{c=JSON.parse(a)}catch(f){}b(c)});var c=new ph;M(c,1,1);Qf(a,c)};p(rh,E);var sh=function(a){y(this,a,"h_ext",[])};p(sh,x);A("h_ext",sh);var th=function(a){y(this,a,"h_sru",[])};p(th,x);A("h_sru",th);var wh=function(){H.call(this);this.b=new hd;P(this,this.b);this.l=this.h=this.k=this.a=null;this.q=Dc("quasar",""+(new Date).getTime());this.c=[];this.e=new bg(this.q);P(this,this.e);this.f=null;this.e.connect();Eb(this,this.e,"message",this.I,!0,this);this.p=new $f;P(this,this.p);this.listen(window,"unload",this.B);this.listen(window,"load",this.v);uh(this,r(function(){vh(this,["onHostReady"],"extensionLibrary")},this))},xh;p(wh,H);var uh=function(a,b){null==a.c?b():a.c.push(b)};
wh.prototype.v=function(){var a=new Oc(Sc.va().get("settings"));this.f=a.b[0];F(a);ag(this.p,this.f,r(function(){if(!this.C&&-1!=this.f.lastIndexOf("talkgadget/")){var a=new Df;M(a,2,!0);var a=new Cb,c=Oe(this.f),d=c.R;null!=c.ea&&(d+=":"+c.ea);M(a,1,d);M(a,2,23);d=chrome.i18n.getMessage("@@ui_locale");M(a,4,d);M(a,13,!0);M(a,17,!0);(d=this.p.b)&&M(a,3,d);c=be(c,"jsmode");null!=c&&M(a,11,c);c=new Pe;M(c,2,!0);M(c,1,!0);Dd(a,14,c);a=new Yf(a,void 0,r(this.D,this));t(void 0)&&(a.a.e=void 0);c=a.a;var e=
a.a.ca,d=a.a.b,f=Oe(e),h=f.N;if(0<=h.indexOf("/u/"))d=e;else{e=h.lastIndexOf("_/");if(0>e||e!=h.length-2)h+="_/";f.N="/u/"+d+h;d=f.toString()}c.ca=d;a.a.j=a.a.j.replace("notifierclient","chat");a.h||(c=rf(a.a.ca,a.a.a),a.h=new Kf(a.a,c,a.w,a.document,void 0),P(a,a.h));Lf(a.h,a.a.Ea,r(a.dd,a),r(a.c,a,"_rosterIframeLoaded"));Ob&&(a.b=a.document.createElement("IFRAME"),a.b.id="gth-talk-plugin-frame-id",a.b.name="gth-talk-plugin-frame-id",a.b.src=a.a.ca+"blank",a.b.style.cssText="width: 0px; height: 0px; position: absolute; top: 0px; left: 0px; visibility:hidden;",
a.document.documentElement.appendChild(a.b),a.k=r(a.cd,a,a.b.parentNode),a.b.parentNode.addEventListener("DOMAttrModified",a.k,!0));Rf(a);this.a=a;this.b.a(gh,this.a);this.k=new kf(this.a);this.b.a(Me,this.k);this.listen(this.k,"c",this.w);this.h=new pg(this.a);this.b.a(qg,this.h);this.l=new oh(this.b);this.b.a(hh,this.l);this.listen(this.l,"h",this.u);this.u();a=new rh(this.a,r(this.K,this));P(this,a);this.listen(this.a.ua(),"h_sru",this.L)}for(;this.c.length;)this.c.shift()();this.c=null},this))};
wh.prototype.D=function(a,b){if("extensionMessage"==a)if("__reload__"==b)chrome.runtime.reload();else{var c=new Fc;Gc(c,JSON.parse(b)||{});this.e.sendMessage(c)}};wh.prototype.w=function(){var a;switch(this.k.getState()){case gf.LOADING:a=2;break;case gf.Dc:a=4;break;case gf.Cc:a=3;break;default:return}vh(this,["changeDesktop",a],"desktopManager")};
wh.prototype.I=function(a){uh(this,r(function(){var b=a.message;switch(b.a){case "onSendHostMessage":var c=new sh,b=b.content().toString();M(c,1,b);this.a.sendMessage(c);break;case "onOpenConversation":var b=b.content()[0],c=this.h,d=new jg;M(d,1,b);Qf(c.a,d);d=new fg;M(d,1,[b]);b=new kg;Dd(b,1,d);Qf(c.a,b);break;case "h_icr":c=b.content()[0],b=this.h,d=new Ke,M(d,1,c),Qf(b.a,d)}},this))};var vh=function(a,b,c){var d=new Fc;Hc(d,a.q,"p");Ad(d,"","e");Jc(d,b);null!=c&&(d.g=c);Ic(d,""+m());a.e.sendMessage(d)}; wh.prototype.K=function(){var a=Ne();window.open(a)};wh.prototype.L=function(a){a=new th(a.gb);vh(this,["setRosterUrl",z(a,2)],"dataChannelManager")};wh.prototype.u=function(){vh(this,["setUnreadIndicator",!!this.l.a],"desktopManager")};
if(!n(xh)||null==xh||xh.C)xh=new wh;
}catch(e){_DumpException(e)}
// Google Inc.
