try{
var g,aa=aa||{},k=this,ba="closure_uid_"+(1E9*Math.random()>>>0),m=Date.now||function(){return+new Date};
}catch(e){_DumpException(e)}
try{
k.ace_i18n={chrome_ext_short_name:{message:"Hangouts"},chrome_ext_description:{message:"Hangouts brings conversations to life with photos, emoji, and even group video calls for free."},quasar_chat_toast_info:{message:"Click to go to page..."},quasar_answer_button_text:{message:"Answer"},quasar_decline_button_text:{message:"Decline"},quasar_help:{message:"Help"},quasar_legend_startup_shutdown:{message:"Application"},chrome_ext_run_at_browser_start:{message:"Sign in to Hangouts when Chrome starts"},
chrome_ext_run_after_browser_close:{message:"Allow background mode"},chrome_ext_new_windows_topmost:{message:"Keep Hangouts on top of other windows"},quasar_label_tray_icon:{message:"Show system tray icon"},quasar_legend_notifications:{message:"Notifications"},quasar_label_all_notification:{message:"Disable notifications"},quasar_label_chat_notification:{message:"Disable chat notifications"},quasar_label_toast_timeout_chat:{message:"Allow chat notifications to timeout automatically"},quasar_label_toast_duration_chat:{message:"Timeout length (in seconds):"},
quasar_button_save:{message:"Ok"},quasar_button_apply:{message:"Apply"},quasar_button_cancel:{message:"Cancel"},chrome_ext_menutext_feedback:{message:"Send feedback"},quasar_feedback_server_uri:{message:"https://www.google.com/tools/feedback"},chrome_ext_feedback_subtitle:{message:"Send feedback"},chrome_ext_feedback_comments:{message:"Comments"},quasar_feedback_system_legend:{message:"System Information"},quasar_feedback_platform_label:{message:"Platform:"},quasar_feedback_user_agent_label:{message:"User Agent:"},
quasar_feedback_privacy_legend:{message:"Privacy Statement"},quasar_feedback_privacy_text:{message:"The description, product information, additional information and your email address will be sent to Google. See the Google Feedback Terms of Service. By submitting this content you are granting to Google the right to use it to improve our products and services. See our Privacy Policy."},quasar_feedback_submit_button:{message:"Send Feedback"},quasar_feedback_cancel_button:{message:"Cancel"},quasar_video_title:{message:"Video call from $1...",
placeholders:{1:{content:"$1"}}},quasar_voice_title:{message:"Voice call from $1...",placeholders:{1:{content:"$1"}}},quasar_group_chat_title:{message:"From group chat..."},quasar_chat_title:{message:"$1 says...",placeholders:{1:{content:"$1"}}},quasar_hangout_title:{message:"$1 is hanging out",placeholders:{1:{content:"$1"}}},chrome_ext_oneonone_plus_hangout_details:{message:"is video calling you via Hangouts"},chrome_ext_group_plus_hangout_details:{message:"has invited you to a group Hangout video call"},
quasar_video_details:{message:"is calling you with video chat"},quasar_voice_details:{message:"is calling you"},quasar_tip_connected:{message:"Status: Connected"},chrome_ext_tip_connected_missed_messages:{message:"Status: Connected\nMissed messages"},quasar_tip_connecting:{message:"Status: Connecting"},quasar_tip_reconnecting:{message:"Status: Reconnecting"},quasar_tip_disconnected:{message:"Status: Disconnected"},quasar_tip_not_login:{message:"Status: Not logged in"},quasar_tip_not_load:{message:"Status: Loading error"},
chrome_ext_menutext_unsigned_user:{message:"Not signed in"},quasar_menutext_unknown_user:{message:"Unknown"},quasar_menutext_feedback:{message:"Feedback"},quasar_menutext_settings:{message:"Options"},quasar_menutext_quit:{message:"Exit"},quasar_menutext_signout:{message:"Sign out"},chrome_ext_cannot_connect:{message:"Unable to connect to Google. Please check your internet connection."},quasar_try_now:{message:"Try now"},quasar_sign_in_to_start_talking:{message:"Sign in to start talking with friends"},
quasar_sign_in:{message:"Sign in"},chrome_app_connection_error_title:{message:"Connection Error"},chrome_app_connection_error_detail:{message:"Make sure you are connected to the Internet and try again"},chrome_app_connection_error_button:{message:"Try again"},chrome_app_welcome_message:{message:"Enjoy private and group conversations with text, photos, gifs, voice, video and more."},chrome_app_chrome_signin_message:{message:"Sign in to Chrome to get started."},chrome_app_learn_more_message:{message:"Learn more"},
chrome_app_signin_button:{message:"Sign in"},chrome_app_exit_title:{message:"Are you sure you want to quit Hangouts?"},chrome_app_exit_detail:{message:"Once quit, you will not receive new messages or calls"},chrome_app_exit_no:{message:"No"},chrome_app_exit_quit:{message:"Quit"}};

}catch(e){_DumpException(e)}
try{
var n=function(a){return void 0!==a},da=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},ea=function(a,b,c){return a.call.apply(a.bind,arguments)},fa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);
if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},p=function(a,b){function c(){}c.prototype=b.prototype;
a.t=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Jd=function(a,c,f){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}},ga=function(a,b){var c=a.split("."),d=k;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&n(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}},r=function(a,b,c){r=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ea:da;return r.apply(null,arguments)},ha=function(a){var b=typeof a;
return"object"==b&&null!=a||"function"==b},s=function(a){return"function"==fa(a)},ia=function(a){return"number"==typeof a},t=function(a){return"string"==typeof a},ja=function(a){var b=fa(a);return"array"==b||"object"==b&&"number"==typeof a.length},u=function(a){return"array"==fa(a)},ka=function(){},ma=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,ma);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};p(ma,Error);ma.prototype.name="CustomError";
var oa=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},qa=function(a,b){for(var c=0,d=oa(String(a)).split("."),e=oa(String(b)).split("."),f=Math.max(d.length,e.length),h=0;0==c&&h<f;h++){var l=d[h]||"",q=e[h]||"",B=RegExp("(\\d*)(\\D*)","g"),K=RegExp("(\\d*)(\\D*)","g");do{var ca=B.exec(l)||["","",""],O=K.exec(q)||["","",""];if(0==ca[0].length&&0==O[0].length)break;c=pa(0==ca[1].length?0:parseInt(ca[1],10),0==O[1].length?0:parseInt(O[1], 10))||pa(0==ca[2].length,0==O[2].length)||pa(ca[2],O[2])}while(0==c)}return c},pa=function(a,b){return a<b?-1:a>b?1:0};
var v=Array.prototype,ra=v.indexOf?function(a,b,c){return v.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(t(a))return t(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},sa=v.lastIndexOf?function(a,b,c){return v.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(t(a))return t(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;
return-1},w=v.forEach?function(a,b,c){v.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},ta=v.filter?function(a,b,c){return v.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,h=t(a)?a.split(""):a,l=0;l<d;l++)if(l in h){var q=h[l];b.call(c,q,l,a)&&(e[f++]=q)}return e},ua=v.map?function(a,b,c){return v.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=t(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,
f[h],h,a));return e},va=v.reduce?function(a,b,c,d){d&&(b=r(b,d));return v.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;w(a,function(c,h){e=b.call(d,e,c,h,a)});return e},wa=v.some?function(a,b,c){return v.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1},xa=function(a,b){var c=ra(a,b),d;(d=0<=c)&&v.splice.call(a,c,1);return d};
var ya=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;var za=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},Aa=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},Ba=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};var x=function(){},y=function(a,b,c,d){a.a={};b||(b=c?[c]:[]);a.p=c?String(c):void 0;a.b=0===c?-1:0;a.G=b;t:{if(a.G.length&&(b=a.G.length-1,(c=a.G[b])&&"object"==typeof c&&"number"!=typeof c.length)){a.j=b-a.b;a.c=c;break t}a.j=Number.MAX_VALUE}if(d)for(b=0;b<d.length;b++)c=d[b],c<a.j?(c+=a.b,a.G[c]=a.G[c]||[]):a.c[c]=a.c[c]||[]},z=function(a,b){return b<a.j?a.G[b+a.b]:a.c[b]};x.prototype.toString=function(){return this.G.toString()};var A=function(a,b){Ca[a]=b;b.messageId=a},Ca={};
var Da="StopIteration"in k?k.StopIteration:Error("f"),Ea=function(){};Ea.prototype.next=function(){throw Da;};Ea.prototype.ha=function(){return this};var Fa;t:{var Ga=k.navigator;if(Ga){var Ha=Ga.userAgent;if(Ha){Fa=Ha;break t}}Fa=""}var Ia=function(a){return-1!=Fa.indexOf(a)};var C=function(a,b){this.a={};this.b=[];this.j=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("h");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof C?(c=a.M(),d=a.A()):(c=Ba(a),d=Aa(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};g=C.prototype;g.U=function(){return this.c};g.A=function(){Ja(this);for(var a=[],b=0;b<this.b.length;b++)a.push(this.a[this.b[b]]);return a};g.M=function(){Ja(this);return this.b.concat()};g.P=function(){return 0==this.c};
g.clear=function(){this.a={};this.j=this.c=this.b.length=0};g.remove=function(a){return Ka(this.a,a)?(delete this.a[a],this.c--,this.j++,this.b.length>2*this.c&&Ja(this),!0):!1};var Ja=function(a){if(a.c!=a.b.length){for(var b=0,c=0;b<a.b.length;){var d=a.b[b];Ka(a.a,d)&&(a.b[c++]=d);b++}a.b.length=c}if(a.c!=a.b.length){for(var e={},c=b=0;b<a.b.length;)d=a.b[b],Ka(e,d)||(a.b[c++]=d,e[d]=1),b++;a.b.length=c}};g=C.prototype;g.get=function(a,b){return Ka(this.a,a)?this.a[a]:b};
g.set=function(a,b){Ka(this.a,a)||(this.c++,this.b.push(a),this.j++);this.a[a]=b};g.forEach=function(a,b){for(var c=this.M(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};g.clone=function(){return new C(this)};g.ha=function(a){Ja(this);var b=0,c=this.b,d=this.a,e=this.j,f=this,h=new Ea;h.next=function(){for(;;){if(e!=f.j)throw Error("i");if(b>=c.length)throw Da;var h=c[b++];return a?h:d[h]}};return h};var Ka=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
var La=function(a){if("function"==typeof a.A)return a.A();if(t(a))return a.split("");if(ja(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Aa(a)},Ma=function(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(ja(a)||t(a))w(a,b,c);else{var d;if("function"==typeof a.M)d=a.M();else if("function"!=typeof a.A)if(ja(a)||t(a)){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else d=Ba(a);else d=void 0;for(var e=La(a),f=e.length,h=0;h<f;h++)b.call(c,e[h],d&&d[h],a)}};
var Na=Ia("Opera")||Ia("OPR"),D=Ia("Trident")||Ia("MSIE"),Oa=Ia("Gecko")&&-1==Fa.toLowerCase().indexOf("webkit")&&!(Ia("Trident")||Ia("MSIE")),Pa=-1!=Fa.toLowerCase().indexOf("webkit"),Qa=k.navigator||null,Ra=Qa&&Qa.platform||"",Sa=function(){var a=k.document;return a?a.documentMode:void 0},Ta=function(){var a="",b;if(Na&&k.opera)return a=k.opera.version,s(a)?a():a;Oa?b=/rv\:([^\);]+)(\)|;)/:D?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:Pa&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(Fa))?a[1]:"");return D&&(b= Sa(),b>parseFloat(a))?String(b):a}(),Ua={},Va=function(a){return Ua[a]||(Ua[a]=0<=qa(Ta,a))},Wa=k.document,Xa=Wa&&D?Sa()||("CSS1Compat"==Wa.compatMode?parseInt(Ta,10):5):void 0;
var E=function(){this.C=this.C;this.j=this.j};E.prototype.C=!1;E.prototype.Eb=function(){return this.C};E.prototype.B=function(){this.C||(this.C=!0,this.n())};E.prototype.n=function(){if(this.j)for(;this.j.length;)this.j.shift()()};var F=function(a){a&&"function"==typeof a.B&&a.B()};
var Ya=!D||D&&9<=Xa;!Oa&&!D||D&&D&&9<=Xa||Oa&&Va("1.9.1");D&&Va("9");var Za=function(a){Za[" "](a);return a};Za[" "]=ka;var $a=function(a,b){try{return Za(a[b]),!0}catch(c){}return!1};var ab=!D||D&&9<=Xa,bb=D&&!Va("9");!Pa||Va("528");Oa&&Va("1.9b")||D&&Va("8")||Na&&Va("9.5")||Pa&&Va("528");Oa&&!Va("8")||D&&Va("9");var G=function(a,b){this.type=a;this.a=this.target=b;this.wc=!0};G.prototype.B=function(){};G.prototype.b=function(){this.wc=!1};var cb=function(a,b){G.call(this,a?a.type:"");this.a=this.target=null;this.clientY=this.clientX=0;this.c=this.state=null;if(a){this.type=a.type;this.target=a.target||a.srcElement;this.a=b;var c=a.relatedTarget;c&&Oa&&$a(c,"nodeName");this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:a.pageY;this.state=a.state;this.c=a;a.defaultPrevented&&this.b()}};p(cb,G); cb.prototype.b=function(){cb.t.b.call(this);var a=this.c;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,bb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var eb="closure_listenable_"+(1E6*Math.random()|0),fb=function(a){return!(!a||!a[eb])},gb=0;var hb=function(a,b,c,d,e){this.qa=a;this.proxy=null;this.src=b;this.type=c;this.Ya=!!d;this.fb=e;this.key=++gb;this.removed=this.Xa=!1},ib=function(a){a.removed=!0;a.qa=null;a.proxy=null;a.src=null;a.fb=null};var jb=function(a){this.src=a;this.a={};this.b=0};jb.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var h=kb(a,b,d,e);-1<h?(b=a[h],c||(b.Xa=!1)):(b=new hb(b,this.src,f,!!d,e),b.Xa=c,a.push(b));return b};jb.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=kb(e,b,c,d);return-1<b?(ib(e[b]),v.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var lb=function(a,b){var c=b.type;if(!(c in a.a))return!1;var d=xa(a.a[c],b);d&&(ib(b),0==a.a[c].length&&(delete a.a[c],a.b--));return d};jb.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,ib(d[e]);delete this.a[c];this.b--}return b}; var mb=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=kb(a,c,d,e));return-1<b?a[b]:null},kb=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.qa==b&&f.Ya==!!c&&f.fb==d)return e}return-1};
var nb="closure_lm_"+(1E6*Math.random()|0),ob={},pb=0,qb=function(a,b,c,d,e){if(u(b)){for(var f=0;f<b.length;f++)qb(a,b[f],c,d,e);return null}c=rb(c);return fb(a)?a.listen(b,c,d,e):sb(a,b,c,!1,d,e)},sb=function(a,b,c,d,e,f){if(!b)throw Error("l");var h=!!e,l=tb(a);l||(a[nb]=l=new jb(a));c=l.add(b,c,d,e,f);if(c.proxy)return c;d=ub();c.proxy=d;d.src=a;d.qa=c;a.addEventListener?a.addEventListener(b.toString(),d,h):a.attachEvent(vb(b.toString()),d);pb++;return c},ub=function(){var a=wb,b=ab?function(c){return a.call(b.src,
b.qa,c)}:function(c){c=a.call(b.src,b.qa,c);if(!c)return c};return b},xb=function(a,b,c,d,e){if(u(b))for(var f=0;f<b.length;f++)xb(a,b[f],c,d,e);else c=rb(c),fb(a)?a.Mb(b,c,d,e):a&&(a=tb(a))&&(b=mb(a,b,c,!!d,e))&&yb(b)},yb=function(a){if(ia(a)||!a||a.removed)return!1;var b=a.src;if(fb(b))return lb(b.T,a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.Ya):b.detachEvent&&b.detachEvent(vb(c),d);pb--;(c=tb(b))?(lb(c,a),0==c.b&&(c.src=null,b[nb]=null)):ib(a);return!0},vb=function(a){return a in
ob?ob[a]:ob[a]="on"+a},Ab=function(a,b,c,d){var e=1;if(a=tb(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.Ya==c&&!f.removed&&(e&=!1!==zb(f,d))}return Boolean(e)},zb=function(a,b){var c=a.qa,d=a.fb||a.src;a.Xa&&yb(a);return c.call(d,b)},wb=function(a,b){if(a.removed)return!0;if(!ab){var c;if(!(c=b))t:{c=["window","event"];for(var d=k,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break t}c=d}e=c;c=new cb(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){t:{var f=
!1;if(0==e.keyCode)try{e.keyCode=-1;break t}catch(h){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.a;f;f=f.parentNode)e.push(f);for(var f=a.type,l=e.length-1;0<=l;l--)c.a=e[l],d&=Ab(e[l],f,!0,c);for(l=0;l<e.length;l++)c.a=e[l],d&=Ab(e[l],f,!1,c)}return d}return zb(a,new cb(b,this))},tb=function(a){a=a[nb];return a instanceof jb?a:null},Bb="__closure_events_fn_"+(1E9*Math.random()>>>0),rb=function(a){if(s(a))return a;a[Bb]||(a[Bb]=function(b){return a.handleEvent(b)});return a[Bb]};
var Cb=function(a){y(this,a,"h_cc",[])};p(Cb,x);A("h_cc",Cb);Cb.prototype.Y=function(){return z(this,19)};var H=function(a){E.call(this);this.J=a;this.g={}};p(H,E);var Db=[];H.prototype.listen=function(a,b,c,d){return Eb(this,a,b,c,d)};var Eb=function(a,b,c,d,e,f){u(c)||(c&&(Db[0]=c.toString()),c=Db);for(var h=0;h<c.length;h++){var l=qb(b,c[h],d||a.handleEvent,e||!1,f||a.J||a);if(!l)break;a.g[l.key]=l}return a};
H.prototype.Mb=function(a,b,c,d,e){if(u(b))for(var f=0;f<b.length;f++)this.Mb(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.J||this,c=rb(c),d=!!d,b=fb(a)?mb(a.T,String(b),c,d,e):a?(a=tb(a))?mb(a,b,c,d,e):null:null,b&&(yb(b),delete this.g[b.key]);return this};H.prototype.removeAll=function(){za(this.g,yb);this.g={}};H.prototype.n=function(){H.t.n.call(this);this.removeAll()};H.prototype.handleEvent=function(){throw Error("m");};
var I=function(){E.call(this);this.T=new jb(this);this.L=this;this.u=null};p(I,E);I.prototype[eb]=!0;g=I.prototype;g.addEventListener=function(a,b,c,d){qb(this,a,b,c,d)};g.removeEventListener=function(a,b,c,d){xb(this,a,b,c,d)};g.n=function(){I.t.n.call(this);this.T&&this.T.removeAll(void 0);this.u=null};g.listen=function(a,b,c,d){return this.T.add(String(a),b,!1,c,d)};g.Mb=function(a,b,c,d){return this.T.remove(String(a),b,c,d)}; g.da=function(a,b,c){a=this.T.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.Ya==b){var h=f.qa,l=f.fb||f.src;f.Xa&&lb(this.T,f);d=!1!==h.call(l,c)&&d}}return d&&0!=c.wc};
var Fb,Gb,Hb,Ib,Jb,Kb,Lb;Lb=Kb=Jb=Ib=Hb=Gb=Fb=!1;var Mb=Fa;Mb&&(-1!=Mb.indexOf("Firefox")?Fb=!0:-1!=Mb.indexOf("Camino")?Gb=!0:-1!=Mb.indexOf("iPhone")||-1!=Mb.indexOf("iPod")?Hb=!0:-1!=Mb.indexOf("iPad")?Ib=!0:-1!=Mb.indexOf("Chrome")?Kb=!0:-1!=Mb.indexOf("Android")?Jb=!0:-1!=Mb.indexOf("Safari")&&(Lb=!0));var Ob=Fb,Pb=Gb,Qb=Hb,Rb=Ib,Sb=Jb,Tb=Kb,Ub=Lb;
var Vb=function(a){k.setTimeout(function(){throw a;},0)},Yb=function(a,b){var c=a;b&&(c=r(a,b));!s(k.setImmediate)||k.Window&&k.Window.prototype.setImmediate==k.setImmediate?(Wb||(Wb=Xb()),Wb(c)):k.setImmediate(c)},Wb,Xb=function(){var a=k.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&(a=function(){var a=document.createElement("iframe");a.style.display="none";a.src="";document.documentElement.appendChild(a);var b=a.contentWindow,a=
b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=r(function(a){if(a.origin==d||a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!Ia("Trident")&&!Ia("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){c=c.next;var a=c.Xb;c.Xb=null;a()};return function(a){d.next={Xb:a};
d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in document.createElement("script")?function(a){var b=document.createElement("script");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};document.documentElement.appendChild(b)}:function(a){k.setTimeout(a,0)}};
var dc=function(a,b){Zb||$b();ac||(Zb(),ac=!0);bc.push(new cc(a,b))},Zb,$b=function(){if(k.Promise&&k.Promise.resolve){var a=k.Promise.resolve();Zb=function(){a.then(ec)}}else Zb=function(){Yb(ec)}},ac=!1,bc=[],ec=function(){for(;bc.length;){var a=bc;bc=[];for(var b=0;b<a.length;b++){var c=a[b];try{c.a.call(c.b)}catch(d){Vb(d)}}}ac=!1},cc=function(a,b){this.a=a;this.b=b};
var fc=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},gc=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var ic=function(a,b){this.b=0;this.f=void 0;this.a=this.c=null;this.j=this.e=!1;try{var c=this;a.call(b,function(a){hc(c,2,a)},function(a){hc(c,3,a)})}catch(d){hc(this,3,d)}},kc=function(){var a,b=new ic(function(b){a=b});return new jc(b,a)};ic.prototype.then=function(a,b,c){return lc(this,s(a)?a:null,s(b)?b:null,c)};fc(ic);
var oc=function(a){0==a.b&&dc(function(){var a=new mc(void 0);nc(this,a)},a)},nc=function(a,b){if(0==a.b)if(a.c){var c=a.c;if(c.a){for(var d=0,e=-1,f=0,h;h=c.a[f];f++)if(h=h.Za)if(d++,h==a&&(e=f),0<=e&&1<d)break;0<=e&&(0==c.b&&1==d?nc(c,b):(d=c.a.splice(e,1)[0],pc(c,d,3,b)))}}else hc(a,3,b)},rc=function(a,b){a.a&&a.a.length||2!=a.b&&3!=a.b||qc(a);a.a||(a.a=[]);a.a.push(b)},lc=function(a,b,c,d){var e={Za:null,qc:null,sc:null};e.Za=new ic(function(a,h){e.qc=b?function(c){try{var e=b.call(d,c);a(e)}catch(B){h(B)}}:
a;e.sc=c?function(b){try{var e=c.call(d,b);!n(e)&&b instanceof mc?h(b):a(e)}catch(B){h(B)}}:h});e.Za.c=a;rc(a,e);return e.Za};ic.prototype.g=function(a){this.b=0;hc(this,2,a)};ic.prototype.h=function(a){this.b=0;hc(this,3,a)};
var hc=function(a,b,c){if(0==a.b){if(a==c)b=3,c=new TypeError("Promise cannot resolve to itself");else{if(gc(c)){a.b=1;c.then(a.g,a.h,a);return}if(ha(c))try{var d=c.then;if(s(d)){sc(a,c,d);return}}catch(e){b=3,c=e}}a.f=c;a.b=b;qc(a);3!=b||c instanceof mc||tc(a,c)}},sc=function(a,b,c){a.b=1;var d=!1,e=function(b){d||(d=!0,a.g(b))},f=function(b){d||(d=!0,a.h(b))};try{c.call(b,e,f)}catch(h){f(h)}},qc=function(a){a.e||(a.e=!0,dc(a.k,a))};
ic.prototype.k=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=[];for(var b=0;b<a.length;b++)pc(this,a[b],this.b,this.f)}this.e=!1};var pc=function(a,b,c,d){if(2==c)b.qc(d);else{for(;a&&a.j;a=a.c)a.j=!1;b.sc(d)}},tc=function(a,b){a.j=!0;dc(function(){a.j&&uc.call(null,b)})},uc=Vb,mc=function(a){ma.call(this,a)};p(mc,ma);mc.prototype.name="cancel";var jc=function(a,b){this.b=a;this.a=b};
var J=function(a){this.a=a};J.prototype.toString=function(){return this.a};var vc=new J("fJuxOc"),wc=new J("ZtVrH"),xc=new J("zZa4xc"),yc=new J("pVbxBc"),zc=new J("byfTOb"),Ac=new J("LEikZe"),Bc=new J("rJmJrc");var Cc=new J("a");var Dc=function(a,b){for(var c=[],d=0;d<arguments.length;d++)c.push(arguments[d]||"");return c.join("_;_")},Ec=function(){return 0<=navigator.userAgent.indexOf("CrOS")};var Fc=function(a,b){this.j=a||"e";this.c=null!=a&&"p"==a?"e":"p";this.b=this.e=null;this.h=b||"u";this.a=this.g=null;this.f=[]};Fc.prototype.message=function(){var a={};a.i=this.a;a.m=this.f;a.r=this.h;a.o=this.g;a.s=this.b;a.st=this.c;a.d=this.e;a.dt=this.j;return a};ga("ace.base.Message.prototype.message",Fc.prototype.message);
var Gc=function(a,b){for(var c in b)switch(c){case "r":a.h=b[c];break;case "i":a.a=b[c];break;case "m":a.f=b[c];break;case "o":a.g=b[c];break;case "s":a.b=b[c];break;case "d":a.e=b[c];break;case "st":a.c=b[c];break;case "dt":a.j=b[c]}return a},Hc=function(a,b,c){null!=b&&(a.b=b,null!=c&&(a.c=c))},Ic=function(a,b){null!=b&&(a.a=b)},Jc=function(a,b){"object"==typeof b?a.f=b:a.f=[b]};Fc.prototype.source=function(){return this.b};Fc.prototype.target=function(){return this.e};Fc.prototype.content=function(){return this.f};
var Kc=function(a,b,c,d,e){E.call(this);this.b=a;this.Ta=b;this.a=typeof b;this.Hb=c?c:!1;this.ba=!0;this.Cb=d?d:!1;this.vb=e?e:!1};p(Kc,E);g=Kc.prototype;g.n=function(){Kc.t.n.call(this);this.b="";this.Ta=null;this.a=""};g.id=function(){return this.b};g.type=function(){return this.a};g.F=function(){return this.Ta};g.setEnabled=function(a){this.ba=a};
var Lc=function(a){return(a=a.exec(Fa))?a[1]:""},Mc=function(){if(Ob)return Lc(/Firefox\/([0-9.]+)/);if(D||Na)return Ta;if(Tb)return Lc(/Chrome\/([0-9.]+)/);if(Ub)return Lc(/Version\/([0-9.]+)/);if(Qb||Rb){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(Fa))return a[1]+"."+a[2]}else{if(Sb)return(a=Lc(/Android\s+([0-9.]+)/))?a:Lc(/Version\/([0-9.]+)/);if(Pb)return Lc(/Camino\/([0-9.]+)/)}return""}();
var Oc=function(a){E.call(this);this.a=new C;this.b=["https://talkgadget.google.com/talkgadget/notifier-js","","https://test.talkgadget.google.com/talkgadget/notifier-js?jsmode=debug_unobfuscated"];a&&Nc(this,a)};p(Oc,E);var Pc=0<=qa(Mc,"23.0.1262.0")&&!Ec();Oc.prototype.n=function(){Oc.t.n.call(this);for(var a=this.a.M(),b=0;b<a.length;++b)F(this.a.get(a[b]));delete this.a};Oc.prototype.getItem=function(a){return Ka(this.a.a,a)?this.a.get(a):null};
Oc.prototype.setItem=function(a){this.a.set(a.id(),a)};var Nc=function(a,b){for(var c in b){var d=b[c],e=null;Ka(a.a.a,c)?(e=a.a.get(c),e.Ta=d.value,d.changed&&(e.vb=d.changed)):(e=new Kc(c,d.value,d.multiple,d.inverse,d.changed),e.setEnabled(!d.disabled));a.a.set(c,e)}};
var Sc=function(){this.c=new C;this.a=null;this.b=!1;this.a=new Qc;this.b=!0;Rc(this)};Sc.va=function(){return Sc.a?Sc.a:Sc.a=new Sc};var Rc=function(a,b){var c=b||ka;a.b?c():chrome.storage.local.get(r(function(a){if(!this.b){for(var b in a)this.c.set(b,a[b]);this.b=!0}c()},a))};Sc.prototype.get=function(a){return this.a.get(a)};Sc.prototype.set=function(a,b){var c=kc();this.a.set(a,b);c.a(void 0);return c.b};Sc.prototype.remove=function(a){this.a.remove(a)};Sc.prototype.clear=function(){this.a.clear()};
var Qc=function(){this.a=window.localStorage};Qc.prototype.clear=function(){this.a.clear()};Qc.prototype.get=function(a){a=this.a.getItem(a);if(a){var b=JSON.parse(a);a=b.data;if("jspb"==b.type){b=Ca[a[0]];if(!b)throw Error("e`"+a[0]);a=new b(a)}}else a=null;return a};Qc.prototype.set=function(a,b){var c=null;b instanceof x&&(b=b.G,c="jspb");var d={};d.data=b;d.timestamp=m();c&&(d.type=c);c=JSON.stringify(d);try{this.a.setItem(a,c)}catch(e){}};Qc.prototype.remove=function(a){try{this.a.removeItem(a)}catch(b){}};
var Tc=function(a,b){this.b=a;this.a=b;this.constructor.Vb||(this.constructor.Vb={});this.constructor.Vb[this.toString()]=this};Tc.prototype.toString=function(){this.c||(this.c=this.b.a+":"+this.a);return this.c};var L=function(a,b){Tc.call(this,a,b)};p(L,Tc);var Uc=function(a){this.a=a},Vc=new Uc("lib");/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
var Wc=function(a,b){this.j=[];this.u=b||null;this.b=this.a=!1;this.c=void 0;this.l=this.p=this.f=!1;this.e=0;this.h=null;this.q=0};Wc.prototype.k=function(a,b){this.f=!1;Xc(this,a,b)};var Xc=function(a,b,c){a.a=!0;a.c=c;a.b=!b;Yc(a)},$c=function(a){if(a.a){if(!a.l)throw new Zc;a.l=!1}};Wc.prototype.g=function(a){$c(this);Xc(this,!0,a)};var ad=function(a,b,c,d){a.j.push([b,c,d]);a.a&&Yc(a)};
Wc.prototype.then=function(a,b,c){var d,e,f=new ic(function(a,b){d=a;e=b});ad(this,d,function(a){"undefined"!=typeof bd&&a instanceof bd?oc(f):e(a)});return f.then(a,b,c)};fc(Wc);
var cd=function(a){return wa(a.j,function(a){return s(a[1])})},Yc=function(a){if(a.e&&a.a&&cd(a)){var b=a.e,c=dd[b];c&&(k.clearTimeout(c.ab),delete dd[b]);a.e=0}a.h&&(a.h.q--,delete a.h);for(var b=a.c,d=c=!1;a.j.length&&!a.f;){var e=a.j.shift(),f=e[0],h=e[1],e=e[2];if(f=a.b?h:f)try{var l=f.call(e||a.u,b);n(l)&&(a.b=a.b&&(l==b||l instanceof Error),a.c=b=l);gc(b)&&(d=!0,a.f=!0)}catch(q){b=q,a.b=!0,cd(a)||(c=!0)}}a.c=b;d&&(l=r(a.k,a,!0),d=r(a.k,a,!1),b instanceof Wc?(ad(b,l,d),b.p=!0):b.then(l,d));c&&
(b=new ed(b),dd[b.ab]=b,a.e=b.ab)},Zc=function(){ma.call(this)};p(Zc,ma);Zc.prototype.message="Deferred has already fired";Zc.prototype.name="AlreadyCalledError";var ed=function(a){this.ab=k.setTimeout(r(this.b,this),0);this.a=a};ed.prototype.b=function(){delete dd[this.ab];throw this.a;};var dd={};

}catch(e){_DumpException(e)}
try{
var nd={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},od=function(a,b){b.push('"',a.replace(ya,function(a){if(a in nd)return nd[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return nd[a]=e+b.toString(16)}),'"')},pd="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),qd=function(a,b,c){switch(typeof b){case "string":od(b,c);break;case "number":c.push(isFinite(b)&&
!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(null==b){c.push("null");break}if(u(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),qd(a,b[f],c),e=",";c.push("]");break}c.push("{");d="";for(e in b)Object.prototype.hasOwnProperty.call(b,e)&&(f=b[e],"function"!=typeof f&&(c.push(d),od(e,c),c.push(":"),qd(a,f,c),d=","));c.push("}");break;case "function":break;default:throw Error("d`"+typeof b);}},rd=function(){},sd=function(a,
b,c,d,e){if(u(b)){for(var f=0;f<b.length;f++)sd(a,b[f],c,d,e);return null}c=rb(c);return fb(a)?a.T.add(String(b),c,!0,d,e):sb(a,b,c,!0,d,e)},td=function(a){return a?decodeURI(a):a},ud=Pa,vd=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#(.*))?$/,wd=function(a,b){a.j||(a.j=[]);a.j.push(n(void 0)?r(b,void 0):b)},M=function(a,b,c){b<a.j?a.G[b+a.b]=c:a.c[b]=c},xd=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=
d[c];for(var f=0;f<pd.length;f++)c=pd[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}},yd=function(a){var b=[];qd(new rd,a,b);return b.join("")},zd=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}},Ad=function(a,b,c){null!=b&&(a.e=b,null!=c&&(a.j=c))},N=function(a,b){var c,d=a.u;if(d)for(c=[];d;d=d.u)c.push(d);var d=a.L,e=b,f=e.type||e;if(t(e))e=new G(e,d);else if(e instanceof G)e.target=e.target||
d;else{var h=e,e=new G(f,d);xd(e,h)}var h=!0,l;if(c)for(var q=c.length-1;0<=q;q--)l=e.a=c[q],h=l.da(f,!0,e)&&h;l=e.a=d;h=l.da(f,!0,e)&&h;h=l.da(f,!1,e)&&h;if(c)for(q=0;q<c.length;q++)l=e.a=c[q],h=l.da(f,!1,e)&&h},Bd=function(a,b,c,d,e,f){if(u(c))for(var h=0;h<c.length;h++)Bd(a,b,c[h],d,e,f);else{b=sd(b,c,d||a.handleEvent,e,f||a.J||a);if(!b)return a;a.g[b.key]=b}return a},Cd=function(a){if(ud){ud=!1;var b=k.location;if(b){var c=b.href;if(c&&(c=td(Cd(c)[3]||null))&&c!=b.hostname)throw ud=!0,Error();
}}return a.match(vd)},P=function(a,b){wd(a,zd(F,b))},Dd=function(a,b,c){var d=c?c.G:c;a.a[b]=c;M(a,b,d)},Q=function(a,b,c){if(!a.a[c]){var d=z(a,c);d&&(a.a[c]=new b(d))}return a.a[c]},Ed=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},Fd=function(a,b){return a?b?decodeURI(a):decodeURIComponent(a):""},Gd=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},Hd=function(a){return v.concat.apply(v,arguments)},Jd=function(a,
b,c){this.a=a||null;this.b=!!c},Ld=function(a){if(!a.H&&(a.H=new C,a.O=0,a.a))for(var b=a.a.split("&"),c=0;c<b.length;c++){var d=b[c].indexOf("="),e=null,f=null;0<=d?(e=b[c].substring(0,d),f=b[c].substring(d+1)):e=b[c];e=decodeURIComponent(e.replace(/\+/g," "));e=Kd(a,e);a.add(e,f?decodeURIComponent(f.replace(/\+/g," ")):"")}};g=Jd.prototype;g.H=null;g.O=null;g.U=function(){Ld(this);return this.O};
g.add=function(a,b){Ld(this);this.a=null;a=Kd(this,a);var c=this.H.get(a);c||this.H.set(a,c=[]);c.push(b);this.O++;return this};g.remove=function(a){Ld(this);a=Kd(this,a);return Ka(this.H.a,a)?(this.a=null,this.O-=this.H.get(a).length,this.H.remove(a)):!1};g.clear=function(){this.H=this.a=null;this.O=0};g.P=function(){Ld(this);return 0==this.O};var Md=function(a,b){Ld(a);b=Kd(a,b);return Ka(a.H.a,b)};
Jd.prototype.M=function(){Ld(this);for(var a=this.H.A(),b=this.H.M(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};Jd.prototype.A=function(a){Ld(this);var b=[];if(t(a))Md(this,a)&&(b=Hd(b,this.H.get(Kd(this,a))));else{a=this.H.A();for(var c=0;c<a.length;c++)b=Hd(b,a[c])}return b};Jd.prototype.set=function(a,b){Ld(this);this.a=null;a=Kd(this,a);Md(this,a)&&(this.O-=this.H.get(a).length);this.H.set(a,[b]);this.O++;return this};
Jd.prototype.get=function(a,b){var c=a?this.A(a):[];return 0<c.length?String(c[0]):b};var Nd=function(a,b,c){a.remove(b);0<c.length&&(a.a=null,a.H.set(Kd(a,b),Gd(c)),a.O+=c.length)};Jd.prototype.toString=function(){if(this.a)return this.a;if(!this.H)return"";for(var a=[],b=this.H.M(),c=0;c<b.length;c++)for(var d=b[c],e=encodeURIComponent(String(d)),d=this.A(d),f=0;f<d.length;f++){var h=e;""!==d[f]&&(h+="="+encodeURIComponent(String(d[f])));a.push(h)}return this.a=a.join("&")};
Jd.prototype.clone=function(){var a=new Jd;a.a=this.a;this.H&&(a.H=this.H.clone(),a.O=this.O);return a};
var Kd=function(a,b){var c=String(b);a.b&&(c=c.toLowerCase());return c},Od=function(a,b){b&&!a.b&&(Ld(a),a.a=null,a.H.forEach(function(a,b){var e=b.toLowerCase();b!=e&&(this.remove(b),Nd(this,e,a))},a));a.b=b},Pd=/#/g,Qd=/[\#\?@]/g,Rd=/[\#\?]/g,Sd=/[\#\?:]/g,Td=/[#\/\?@]/g,Ud=function(a,b,c){return t(a)?(a=encodeURI(a).replace(b,Ed),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},Vd=function(){return Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^
m()).toString(36)},Wd=function(a,b){var c;"undefined"!=typeof Wd&&a instanceof Wd?(this.ma=n(b)?b:a.ma,Xd(this,a.fa),this.sa=a.sa,this.R=a.R,Yd(this,a.ea),this.N=a.N,Zd(this,a.a.clone()),this.la=a.la):a&&(c=Cd(String(a)))?(this.ma=!!b,Xd(this,c[1]||"",!0),this.sa=Fd(c[2]||""),this.R=Fd(c[3]||"",!0),Yd(this,c[4]),this.N=Fd(c[5]||"",!0),Zd(this,c[6]||"",!0),this.la=Fd(c[7]||"")):(this.ma=!!b,this.a=new Jd(null,0,this.ma))};g=Wd.prototype;g.fa="";g.sa="";g.R="";g.ea=null;g.N="";g.la="";g.ma=!1;
g.toString=function(){var a=[],b=this.fa;b&&a.push(Ud(b,Td,!0),":");if(b=this.R){a.push("//");var c=this.sa;c&&a.push(Ud(c,Td,!0),"@");a.push(encodeURIComponent(String(b)).replace(/%25([0-9a-fA-F]{2})/g,"%$1"));b=this.ea;null!=b&&a.push(":",String(b))}if(b=this.N)this.R&&"/"!=b.charAt(0)&&a.push("/"),a.push(Ud(b,"/"==b.charAt(0)?Rd:Sd,!0));(b=this.a.toString())&&a.push("?",b);(b=this.la)&&a.push("#",Ud(b,Pd));return a.join("")};
var $d=function(a,b){var c=a.clone(),d=!!b.fa;d?Xd(c,b.fa):d=!!b.sa;d?c.sa=b.sa:d=!!b.R;d?c.R=b.R:d=null!=b.ea;var e=b.N;if(d)Yd(c,b.ea);else if(d=!!b.N){if("/"!=e.charAt(0))if(a.R&&!a.N)e="/"+e;else{var f=c.N.lastIndexOf("/");-1!=f&&(e=c.N.substr(0,f+1)+e)}f=e;if(".."==f||"."==f)e="";else if(-1!=f.indexOf("./")||-1!=f.indexOf("/.")){for(var e=0==f.lastIndexOf("/",0),f=f.split("/"),h=[],l=0;l<f.length;){var q=f[l++];"."==q?e&&l==f.length&&h.push(""):".."==q?((1<h.length||1==h.length&&""!=h[0])&&h.pop(),
e&&l==f.length&&h.push("")):(h.push(q),e=!0)}e=h.join("/")}else e=f}d?c.N=e:d=""!==b.a.toString();d?Zd(c,Fd(b.a.toString())):d=!!b.la;d&&(c.la=b.la);return c};Wd.prototype.clone=function(){return new Wd(this)};
var Xd=function(a,b,c){a.fa=c?Fd(b,!0):b;a.fa&&(a.fa=a.fa.replace(/:$/,""))},Yd=function(a,b){if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("j`"+b);a.ea=b}else a.ea=null},Zd=function(a,b,c){b instanceof Jd?(a.a=b,Od(a.a,a.ma)):(c||(b=Ud(b,Qd)),a.a=new Jd(b,0,a.ma))},R=function(a,b,c){a.a.set(b,c)},ae=function(a,b,c){u(c)||(c=[String(c)]);Nd(a.a,b,c)},be=function(a,b){return a.a.get(b)},ce=function(a,b){return 0<=ra(a,b)},de=function(a,b,c){if(s(a))c&&(a=r(a,c));else if(a&&"function"==typeof a.handleEvent)a=
r(a.handleEvent,a);else throw Error("n");return 2147483647<b?-1:k.setTimeout(a,b||0)},ee=function(a){k.clearTimeout(a)},fe=function(a){var b={},c;for(c in a)b[c]=a[c];return b},ge=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c],e;if(u(d)||(e=ja(d))&&Object.prototype.hasOwnProperty.call(d,"callee"))a.push.apply(a,d);else if(e)for(var f=a.length,h=d.length,l=0;l<h;l++)a[f+l]=d[l];else a.push(d)}},he=function(a,b){var c;t:{c=a.length;for(var d=t(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){c=e;break t}c=-1}return 0>c?null:t(a)?a.charAt(c):a[c]};
var ie=function(){},le=function(a){var b=a.ia,c=function(a){c.t.constructor.call(this,a);var b=this.S.length;this.a=[];for(var d=0;d<b;++d)this.S[d].Ld||(this.a[d]=new this.S[d](a))};p(c,b);for(var d=[];a;){if(b=a.ia){b.S&&ge(d,b.S);var b=b.prototype,e;for(e in b)if(b.hasOwnProperty(e)&&s(b[e])&&b[e]!==a){var f=!!b[e].Uc,h=je(e,b,d,f);(f=ke(e,b,h,f))&&(c.prototype[e]=f)}}a=a.t&&a.t.constructor}c.prototype.S=d;return c},je=function(a,b,c,d){for(var e=[],f=0;f<c.length&&(c[f].prototype[a]===b[a]||(e.push(f),
!d));++f);return e},ke=function(a,b,c,d){var e;c.length?d?e=function(b){var d=this.a[c[0]];return d?d[a].apply(this.a[c[0]],arguments):this.S[c[0]].prototype[a].apply(this,arguments)}:b[a].Wc?e=function(b){var d;t:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var q=this.a[c[e]];if(q=q?q[a].apply(q,d):this.S[c[e]].prototype[a].apply(this,d)){d=q;break t}}d=!1}return d}:b[a].Vc?e=function(b){var d;t:{d=Array.prototype.slice.call(arguments,0);for(var e=0;e<c.length;++e){var q=
this.a[c[e]],q=q?q[a].apply(q,d):this.S[c[e]].prototype[a].apply(this,d);if(null!=q){d=q;break t}}d=void 0}return d}:b[a].oc?e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=0;e<c.length;++e){var q=this.a[c[e]];q?q[a].apply(q,d):this.S[c[e]].prototype[a].apply(this,d)}}:e=function(b){for(var d=Array.prototype.slice.call(arguments,0),e=[],q=0;q<c.length;++q){var B=this.a[c[q]];e.push(B?B[a].apply(B,d):this.S[c[q]].prototype[a].apply(this,d))}return e}:d||b[a].Wc||b[a].Vc||b[a].oc? e=null:e=me;return e},me=function(){return[]};ie.prototype.zb=function(a){if(this.a)for(var b=0;b<this.a.length;++b)if(this.a[b]instanceof a)return this.a[b];return null};
var oe=function(a){if(!a.wb){var b;for(b=a.constructor;b&&!b.ia;)b=b.t&&b.t.constructor;b.ia.$b||(b.ia.$b=le(b));b=new b.ia.$b(a);a.wb=b;a.zb||(a.zb=ne)}},ne=function(a){return this.wb.zb(a)};var pe=function(){};pe.prototype.a=null;var re=function(a){var b;(b=a.a)||(b={},qe(a)&&(b[0]=!0,b[1]=!0),b=a.a=b);return b};var se,te=function(){};p(te,pe);var ue=function(a){return(a=qe(a))?new ActiveXObject(a):new XMLHttpRequest},qe=function(a){if(!a.b&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.b=d}catch(e){}}throw Error("t");}return a.b};se=new te;
var ve=function(a){I.call(this);this.D=new C;this.k=a||null;this.b=!1;this.h=this.a=null;this.q="";this.e=0;this.c=this.p=this.f=this.l=!1;this.v=0;this.g=null;this.J="";this.w=this.aa=!1};p(ve,I);var we=/^https?$/i,xe=["POST","PUT"],ye=[];ve.prototype.V=function(){this.B();xa(ye,this)};
ve.prototype.send=function(a,b,c,d){if(this.a)throw Error("u`"+this.q+"`"+a);b=b?b.toUpperCase():"GET";this.q=a;this.e=0;this.l=!1;this.b=!0;this.a=this.k?ue(this.k):ue(se);this.h=this.k?re(this.k):re(se);this.a.onreadystatechange=r(this.I,this);try{this.p=!0,this.a.open(b,String(a),!0),this.p=!1}catch(e){ze(this);return}a=c||"";var f=this.D.clone();d&&Ma(d,function(a,b){f.set(b,a)});d=he(f.M(),Ae);c=k.FormData&&a instanceof k.FormData;!ce(xe,b)||d||c||f.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");
f.forEach(function(a,b){this.a.setRequestHeader(b,a)},this);this.J&&(this.a.responseType=this.J);"withCredentials"in this.a&&(this.a.withCredentials=this.aa);try{Be(this),0<this.v&&((this.w=Ce(this.a))?(this.a.timeout=this.v,this.a.ontimeout=r(this.K,this)):this.g=de(this.K,this.v,this)),this.f=!0,this.a.send(a),this.f=!1}catch(h){ze(this)}};var Ce=function(a){return D&&Va(9)&&ia(a.timeout)&&n(a.ontimeout)},Ae=function(a){return"content-type"==a.toLowerCase()};
ve.prototype.K=function(){"undefined"!=typeof aa&&this.a&&(this.e=8,N(this,"timeout"),De(this,8))};var ze=function(a){a.b=!1;a.a&&(a.c=!0,a.a.abort(),a.c=!1);a.e=5;Ee(a);Fe(a)},Ee=function(a){a.l||(a.l=!0,N(a,"complete"),N(a,"error"))},De=function(a,b){a.a&&a.b&&(a.b=!1,a.c=!0,a.a.abort(),a.c=!1,a.e=b||7,N(a,"complete"),N(a,"abort"),Fe(a))};ve.prototype.n=function(){this.a&&(this.b&&(this.b=!1,this.c=!0,this.a.abort(),this.c=!1),Fe(this,!0));ve.t.n.call(this)};
ve.prototype.I=function(){this.C||(this.p||this.f||this.c?Ge(this):this.$())};ve.prototype.$=function(){Ge(this)};
var Ge=function(a){if(a.b&&"undefined"!=typeof aa&&(!a.h[1]||4!=(a.a?a.a.readyState:0)||2!=He(a)))if(a.f&&4==(a.a?a.a.readyState:0))de(a.I,0,a);else if(N(a,"readystatechange"),4==(a.a?a.a.readyState:0)){a.b=!1;try{Ie(a)?(N(a,"complete"),N(a,"success")):(a.e=6,Ee(a))}finally{Fe(a)}}},Fe=function(a,b){if(a.a){Be(a);var c=a.a,d=a.h[0]?ka:null;a.a=null;a.h=null;b||N(a,"ready");try{c.onreadystatechange=d}catch(e){}}},Be=function(a){a.a&&a.w&&(a.a.ontimeout=null);ia(a.g)&&(ee(a.g),a.g=null)},Ie=function(a){var b=
He(a),c;t:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:c=!0;break t;default:c=!1}if(!c){if(b=0===b)a=Cd(String(a.q))[1]||null,!a&&self.location&&(a=self.location.protocol,a=a.substr(0,a.length-1)),b=!we.test(a?a.toLowerCase():"");c=b}return c},He=function(a){try{return 2<(a.a?a.a.readyState:0)?a.a.status:-1}catch(b){return-1}},Je=function(a){try{return a.a?a.a.responseText:""}catch(b){return""}};
var Ke=function(a){y(this,a,"h_icr",[])};p(Ke,x);A("h_icr",Ke);var Le=function(a){y(this,a,"h_cs",[])};p(Le,x);A("h_cs",Le);Le.prototype.getState=function(){return z(this,1)};var Me=new J("HwdKC");
}catch(e){_DumpException(e)}
try{
var yh=function(a){for(var b=a.a.M(),c={},d=0;d<b.length;d++){var e=b[d],f=a.a.get(e);c[e]={value:f.F(),type:f.type(),multiple:f.Hb,disabled:!f.ba,inverse:f.Cb,changed:f.vb}}return c},zh=function(a,b){return t(b)?a.getElementById(b):b},S=function(a){return zh(document,a)},T=function(a){var b;b=b||[];b.length||(b[0]="");var c=chrome.i18n.getMessage(a,b);if(c)return c;(c=(c=k.ace_i18n[a.toLowerCase()])?c.message:k.ace_i18n["MSG_"+a])&&(c=c.replace("$1",b[0]).replace("$2",b[1]).replace("$3",b[2]));return c};

}catch(e){_DumpException(e)}
try{
var Ah=function(a){return a.b[0]},Bh=function(a){return(a=a.a.get("TopMost"))&&a.ba?a.F():!0},Ch=function(){return!0},Dh={},Eh=0,Fh=function(a){a&&a!=chrome.windows.WINDOW_ID_NONE&&chrome.windows.update(a,{focused:!0})},Gh=function(a){if(Dh[a])return Dh[a];a=String(a);if(!Dh[a]){var b=/function ([^\(]+)/.exec(a);Dh[a]=b?b[1]:"[Anonymous]"}return Dh[a]},Hh=function(a){return a[ba]||(a[ba]=++Eh)},Ih=function(a){chrome.windows.getAll({populate:!0},function(b){for(var c=0;c<b.length;++c){var d=b[c].tabs;
if(null!=d)for(var e=0;e<d.length;++e)if(d[e].selected&&d[e].url==a){Fh(b[c].id);return}}})},Jh=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c},Kh=function(){return null!=navigator.platform.match(/Mac.*/)},Lh=function(){return!Ec()&&null!=navigator.platform.match(/Linux.*/)},Mh=function(a){this.a=a||k.document||document};Mh.prototype.fc=function(){var a=this.a;return a.parentWindow||a.defaultView};
Mh.prototype.contains=function(a,b){if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||Boolean(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};
var Nh=function(a,b){var c=[];if(ce(b,a))c.push("[...circular reference...]");else if(a&&50>b.length){c.push(Gh(a)+"(");for(var d=a.arguments,e=0;d&&e<d.length;e++){0<e&&c.push(", ");var f;f=d[e];switch(typeof f){case "object":f=f?"object":"null";break;case "string":break;case "number":f=String(f);break;case "boolean":f=f?"true":"false";break;case "function":f=(f=Gh(f))?f:"[fn]";break;default:f=typeof f}40<f.length&&(f=f.substr(0,40)+"...");c.push(f)}b.push(a);c.push(")\n");try{c.push(Nh(a.caller,
b))}catch(h){c.push("[exception trying to get caller]\n")}}else a?c.push("[...long stack...]"):c.push("[end]");return c.join("")},Oh=function(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+Hh(a):b.substr(0,1)+a},Ph=function(a){if(a instanceof Ea)return a;if("function"==typeof a.ha)return a.ha(!1);if(ja(a)){var b=0,c=new Ea;c.next=function(){for(;;){if(b>=a.length)throw Da;if(b in a)return a[b++];b++}};return c}throw Error("g");},Qh=function(a,b){return a>b?1:a<b?-1:0},Rh=function(a,b){null!=
a&&(window.open(a,"winid_"+(new Date).getTime(),b),de(r(Ih,null,a),1E3))},Sh=function(a,b){null!=a&&(b?a=chrome.runtime.getURL("images_4/"+a):0==a.indexOf("images_4/")&&(a=chrome.runtime.getURL(a)));return a},Th=function(a,b,c,d){this.left=a;this.top=b;this.width=c;this.height=d};Th.prototype.clone=function(){return new Th(this.left,this.top,this.width,this.height)};
Th.prototype.contains=function(a){return"undefined"!=typeof Th&&a instanceof Th?this.left<=a.left&&this.left+this.width>=a.left+a.width&&this.top<=a.top&&this.top+this.height>=a.top+a.height:a.x>=this.left&&a.x<=this.left+this.width&&a.y>=this.top&&a.y<=this.top+this.height};Th.prototype.floor=function(){this.left=Math.floor(this.left);this.top=Math.floor(this.top);this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};
Th.prototype.round=function(){this.left=Math.round(this.left);this.top=Math.round(this.top);this.width=Math.round(this.width);this.height=Math.round(this.height);return this};var Uh=[/^https?:\/\/.*.google.com(:[0-9]+)?\/talkgadget\/success/,/^https:\/\/accounts.google.com\/ServiceLogin/],Vh=[1E4,12E4,144E5],Wh=[200,2E3,3E5],U=function(a){return U.b(a)};U.b=function(a){return a+"_"};U.g=function(){throw Error("o");};
U.e=function(a){if(a&&a.constructor&&a.constructor.toString()===Object.toString()){var b={},c;for(c in a)a.hasOwnProperty(c)&&(b[U.b(c)]=a[c]);return b}throw Error("p");};U.c=!0;U.j=function(a){return a};U.f=function(){return!0};var Xh=function(a,b){I.call(this);this.c=a||1;this.b=b||k;this.f=r(this.h,this);this.g=m()};p(Xh,I);Xh.prototype.e=!1;Xh.prototype.a=null;Xh.prototype.setInterval=function(a){this.c=a;this.a&&this.e?(this.stop(),Yh(this)):this.a&&this.stop()};
Xh.prototype.h=function(){if(this.e){var a=m()-this.g;0<a&&a<.8*this.c?this.a=this.b.setTimeout(this.f,this.c-a):(this.a&&(this.b.clearTimeout(this.a),this.a=null),N(this,"tick"),this.e&&(this.a=this.b.setTimeout(this.f,this.c),this.g=m()))}};var Yh=function(a){a.e=!0;a.a||(a.a=a.b.setTimeout(a.f,a.c),a.g=m())};Xh.prototype.stop=function(){this.e=!1;this.a&&(this.b.clearTimeout(this.a),this.a=null)};Xh.prototype.n=function(){Xh.t.n.call(this);this.stop();delete this.b};
var Zh=function(a,b){this.width=a;this.height=b};Zh.prototype.clone=function(){return new Zh(this.width,this.height)};Zh.prototype.P=function(){return!(this.width*this.height)};Zh.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};Zh.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};
var $h=function(a){var b;b||(b=Nh(a||arguments.callee.caller,[]));return b},ai=function(a){this.a=new C;if(a){a=La(a);for(var b=a.length,c=0;c<b;c++)this.add(a[c])}};g=ai.prototype;g.U=function(){return this.a.U()};g.add=function(a){this.a.set(Oh(a),a)};g.removeAll=function(a){a=La(a);for(var b=a.length,c=0;c<b;c++)this.remove(a[c])};g.remove=function(a){return this.a.remove(Oh(a))};g.clear=function(){this.a.clear()};g.P=function(){return this.a.P()};
g.contains=function(a){a=Oh(a);return Ka(this.a.a,a)};g.A=function(){return this.a.A()};g.clone=function(){return new ai(this)};g.ha=function(){return this.a.ha(!1)};
var bi=function(a,b){if(ja(a))try{w(a,b,void 0)}catch(c){if(c!==Da)throw c;}else{a=Ph(a);try{for(;;)b.call(void 0,a.next(),void 0,a)}catch(d){if(d!==Da)throw d;}}},ci=function(a,b,c){c=c||[];for(var d=[],e=0;e<c.length;e++)d[e]=c[e].G;a.a[b]=c;M(a,b,d)},di=function(a,b,c){if(!a.a[c]){for(var d=z(a,c),e=[],f=0;f<d.length;f++)e[f]=new b(d[f]);a.a[c]=e}return a.a[c]},ei=function(a){var b=arguments.length;if(1==b&&u(arguments[0]))return ei.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]= !0;return c},fi=function(a,b){a.sort(b||Qh)},gi=function(a){for(var b=0,c=0;c<a.length;++c)b=31*b+a.charCodeAt(c),b%=4294967296;return b};
var hi=function(a){y(this,a,"dpgi",[])};p(hi,x);A("dpgi",hi);var ii=function(a){y(this,a,"dri",[])};p(ii,x);A("dri",ii);var ji=function(a){y(this,a,"di",[6,7,10,11,12])};p(ji,x);A("di",ji);var ki=function(a){y(this,a,"e",[])};p(ki,x);A("e",ki);var li=function(a){y(this,a,"f.ri",[])};p(li,x);A("f.ri",li);var mi=function(){E.call(this)};p(mi,E);
var pi=function(a,b){var c=ni;if(!(c.C||"undefined"!=typeof bd&&b instanceof bd))if(c.b){var c=c.b,d=oi();d["call-stack"]=$h();a&&(d.message=a);var e;b instanceof Error?e=b:e=b||"";var f,h="";e&&(h=(e.lineNumber||"unknown")+":"+gi(e.fileName||"unknown")+":"+gi(e.message||"unknown"));var l="";for(f in d){var q;q="call-stack"==f?d[f].replace(/\(.*\)/g,""):d[f];l=l+f+":"+q+":"}f=h+"::"+l;h=c.c[f];h||(h={time:0,count:0},c.c[f]=h);if(1E4>m()-h.time)h.count++,1==h.count&&(d=oi(),d.message="Throttling: "+ f,c.a.a(e,d));else{h.count&&(d["dropped-instances"]=h.count);h.time=m();for(f=h.count=0;f<c.b.length;f++)c.b[f](e,d);c.a.a(e,d)}}else c.a&&10>c.a.length&&c.a.push([a,b])},ni=new mi;
var qi=function(a){var b=window;if(!b.location){var c;try{c=yd(b)}catch(d){c=Ba(b).toString()}pi(null,Error("x`"+c))}c=b.location&&b.location.ancestorOrigins;if(n(c))return c&&c.length?c[a?0:c.length-1]==b.location.origin:!0;try{return n((a?b.parent:b.top).location.href)}catch(e){return!1}};
var ri={},oi=function(){var a={};a.location=document.location.toString();if(qi(!1))try{a["top.location"]=top.location.toString()}catch(b){a["top.location"]="[external]"}else a["top.location"]="[external]";for(var c in ri)try{a[c]=ri[c].call()}catch(d){a[c]="[error] "+d.message}return a};
ei("area base br col command embed hr img input keygen link meta param source track wbr".split(" "));ei("action","cite","data","formaction","href","manifest","poster","src");ei("link","script","style");var si={},ti=function(){delete si.W},ui=function(){si.W(1)};var vi=function(a,b){if(a)this.focused=a.focused,this.alwaysOnTop=a.alwaysOnTop,this.top=a.top,this.left=a.left,this.width=a.width,this.height=a.height,this.state=a.state;else if(b){this.focused=b.contentWindow.document.hasFocus();this.alwaysOnTop=b.isAlwaysOnTop();var c=b.getBounds();this.top=c.top;this.left=c.left;this.width=c.width;this.height=c.height;this.state=b.isMinimized()?"minimized":"normal"}else this.alwaysOnTop=this.focused=!1,this.height=this.width=this.left=this.top=0,this.state=""}; vi.prototype.isMinimized=function(){return"minimized"==this.state};
var wi=function(){E.call(this);this.a=new ai};p(wi,E);wi.prototype.da=function(a){var b,c=Array.prototype.slice.call(arguments);w(this.a.A(),function(a){b=a.apply(null,c)});return b};wi.prototype.addListener=function(a){this.a.add(a)};wi.prototype.removeListener=function(a){this.a.remove(a)};wi.prototype.n=function(){this.a.clear();wi.t.n.call(this)};
var zi=function(){E.call(this);this.b=[];this.h=new wi;P(this,this.h);this.f=new wi;P(this,this.f);this.onClosed=new wi;this.g=!1;this.c=null;this.k=r(this.w,this);xi.addListener(this.k);this.l=r(this.v,this);yi.addListener(this.l)};p(zi,E);zi.prototype.n=function(){Ai(this)||void 0!=this.a&&chrome.windows.remove(this.a);Bi(this);this.k&&(xi.removeListener(this.k),yi.removeListener(this.l));F(this.onClosed);zi.t.n.call(this)};var xi=chrome.windows&&chrome.windows.onRemoved,yi=chrome.windows&&chrome.windows.onFocusChanged;
zi.prototype.create=function(a){chrome.windows.create(a,r(function(a){this.C?chrome.windows.remove(a.id):(this.a=a.id,Ci(this))},this))};var Ci=function(a){if(null!=a.b&&Di(a))if(Ai(a))Bi(a);else{for(;a.b.length&&!Ai(a);)a.b.shift()(a);a.b=null}},Di=function(a){return!(!ia(a.a)||!a.e)},Ei=function(a,b){Ai(a)?Bi(a):null==a.b?b(a):a.b.push(b)},Ai=function(a){return!(!a.e||!a.e.closed)};zi.prototype.w=function(){Ai(this)&&Bi(this)};
var Bi=function(a){if(!a.g){var b=a.onClosed;a.onClosed=new wi;de(r(function(){this.g||(this.g=!0,b.da(this));F(b)},a))}};zi.prototype.v=function(a){if(a!=this.a){if(null===this.c||this.c)this.c&&(this.c=!1),this.f.da(this)}else this.c=!0,this.h.da(this)};var Fi=function(a){var b;b=a.a?a.e:null;return!b||Ai(a)?null:b};zi.prototype.minimize=function(){Ei(this,r(function(){chrome.windows.update(this.a,{state:"minimized"})},this))};
zi.prototype.focus=function(){Ei(this,r(function(){chrome.windows.update(this.a,{focused:!0})},this))};var Gi=function(a,b){Ei(a,r(function(){chrome.windows.update(this.a,{drawAttention:b})},a))};zi.prototype.getProperties=function(a){Ei(this,zd(Hi,[this],function(b){a(b[0])}))};var Hi=function(a,b){chrome.windows.getAll(function(c){var d={};w(c,function(a){d[a.id]=a});var e=[];w(a,function(a){var b;a&&Di(a)&&!Ai(a)&&(b=d[a.a]);var c;b&&(c=new vi(b));e.push(c)});b(e)})};
var Ii=new J("b"),Ji=new J("c"),Ki=new J("d"),Li=new J("e"),Mi=new J("f"),Ni=new J("g"),Oi=new J("h"),kd=new J("i"),Pi=new J("j");var Qi=function(a,b){this.a=a;this.q=b;this.l=this.p=this.j="";this.b=null;this.f="";this.g=0;this.c=[];this.h=!1;this.k=""},Ri=function(a,b){this.name=a;this.title=b||""};g=Qi.prototype;g.setTitle=function(a){this.p=a};g.sb=function(){return this.p||""};g.Ka=function(){return this.f||""};g.type=function(){return this.q};g.wa=function(){if(this.Fb())return null;var a=this.a;null!=this.e?a+=this.e:null!=this.f&&(a+=this.f);return a};g.Fb=function(){return!1};
var Si=function(a){return a.replace(/^(\<br\>)+/,"")},Ti=function(a){var b=a.sb();a.l&&(b+=" "+(a.l||""));var c=Si(a.Ka()),d=ua(a.c,function(a){var b;if(!(b=a.title))t:{switch(a.name){case "answer":case "join hangout":b=T("QUASAR_ANSWER_BUTTON_TEXT");break t;case "ignore":b=T("QUASAR_DECLINE_BUTTON_TEXT");break t}b=""}return{title:b}},a);return{type:"basic",iconUrl:(0==a.j.indexOf("data:")||0==a.j.indexOf("chrome-extension:")?a.j:"")||chrome.runtime.getURL("images_4/icon-128x128.png"),title:b,message:c, buttons:d,priority:2}};
var Ui=function(a){Qi.call(this,a,2)};p(Ui,Qi);Ui.prototype.sb=function(){var a=Ui.t.sb.call(this);return this.h&&!a?T("QUASAR_GROUP_CHAT_TITLE"):a};Ui.prototype.Ka=function(){return 0<=this.a.indexOf("video")?T("QUASAR_VIDEO_DETAILS"):0<=this.a.indexOf("voice")?T("QUASAR_VOICE_DETAILS"):Ui.t.Ka.call(this)};Ui.prototype.Fb=function(){return 0<=this.a.indexOf("voice")||0<=this.a.indexOf("video")};
var V;var Vi=function(a){Qi.call(this,a,2)};p(Vi,Qi);Vi.prototype.wa=function(){return null!=this.e?Vi.t.wa.call(this):null};var Wi=function(a){this.c=a;this.a=new Oc;this.b=a.get(Cc);this.a.setItem(new Kc("StartOnBrowserLaunch",!0,!1,!1));Pc&&this.a.setItem(new Kc("TopMost",!0));a=new Kc("StopOnBrowserClose",!1,!1,!1);a.setEnabled(!1);this.a.setItem(a);a=new Kc("TrayIcon",!0,!1,!1);a.setEnabled(null!=navigator.platform.match(/Win.*/)||Lh()||Kh());this.a.setItem(a);(a=this.b.get("settings"))&&Nc(this.a,a);this.b.set("settings",yh(this.a))};ga("ace.core.SettingsManager",Wi);
var Xi=chrome.runtime&&chrome.runtime.getURL&&chrome.runtime.getURL("settingsdialog.html")||"";Wi.prototype.e=function(){this.b.set("settings",yh(this.a));var a=V.e("setting");if(a&&0!=a.length)Yi(a[0],"focus");else{var a=Math.floor((screen.height-200)/2),b=Math.floor((screen.width-520)/2),c=["width=520"];c.push("height=200");c.push("top="+a);c.push("left="+b);c.push("location=no");Rh(Xi,c.join(","))}};Wi.prototype.launchSettingsDialog=Wi.prototype.e;
Wi.prototype.f=function(){var a=new Oc(yh(this.a)),b=this.b.get("settings");Nc(this.a,b);var c=new Oc(b),b=c.getItem("StopOnBrowserClose"),a=a.getItem("TrayIcon"),c=c.getItem("TrayIcon");a.ba&&(c.F()||b.F()?(b=this.c.get(Ji),Zi(b),$i(b)):c.F()||b.F()||aj(this.c.get(Ji)))};Wi.prototype.updateSettingsFromStorage=Wi.prototype.f;Wi.prototype.j=function(){var a=V.e("setting");if(a)for(var b=0;b<a.length;++b)Yi(a[b],"close")};Wi.prototype.closeUI=Wi.prototype.j; var Yi=function(a,b){var c=new Fc;Ic(c,b);Jc(c,[]);V.b(a).sendMessage(c)};
var W=new Uc("act"),bj=new Uc("impr"),cj=new Uc("tran"),dj=new Uc("perf");new L(W,1);new L(W,2);new L(W,3);new L(W,4);new L(W,5);new L(W,6);new L(W,7);new L(W,8);new L(W,9);new L(W,10);new L(W,11);new L(W,12);new L(W,13);new L(W,14);new L(W,15);new L(W,22);new L(W,16);new L(W,17);new L(W,18);new L(W,19);new L(W,20);new L(W,21);new L(W,23);new L(W,24);var ej=new L(bj,1E3);new L(cj,1001);new L(dj,1002);
var fj=new J("k");var X=function(a){this.k=a;this.p=a.get(Oi);this.b=a.get(Cc);this.a=1;this.e=this.h=null;this.g=this.c=!1;this.l=r(this.q,this);Zi(this);$i(this);null!=this.b.a.get("UnreadIndicator")&&this.b.remove("UnreadIndicator");null!=this.b.a.get("app_status")&&this.b.remove("app_status");null!=this.b.a.get("user_id")&&this.b.remove("user_id");null!=this.b.a.get("client_state")&&this.b.remove("client_state")};p(X,E);ga("ace.core.DesktopManager",X);X.prototype.n=function(){aj(this);X.t.n.call(this)};
X.prototype.f=function(a,b){this.a!=b&&(this.a=b,$i(this),gj(this),1==this.a&&(this.e=this.h=null,this.g=this.c=!1,aj(this),this.p.j(),this.k.get(Mi).b()),V.g())};X.prototype.changeDesktop=X.prototype.f;X.prototype.u=function(a,b){this.c!=b&&(this.c=b,$i(this),gj(this))};X.prototype.setMainUiShowing=X.prototype.u;
var Zi=function(a){var b=a.p.a,c;if(c=null!=navigator.platform.match(/Win.*/)||Lh()||Kh())c=b.a.get("StopOnBrowserClose"),(c=c&&c.ba?c.F():!1)||(c=(b=b.a.get("TrayIcon"))&&b.ba?b.F():!1);c&&chrome.systemIndicator&&(chrome.systemIndicator.enable(),chrome.systemIndicator.onClicked.addListener(a.l))},aj=function(a){chrome.systemIndicator&&(chrome.systemIndicator.disable(),chrome.systemIndicator.onClicked.removeListener(a.l))},gj=function(a){var b;switch(a.a){case 2:b=T("QUASAR_TIP_CONNECTING");break;
case 3:b=T("QUASAR_TIP_NOT_LOGIN");break;case 4:case 9:case 8:b=a.c?a.g?T("CHROME_EXT_TIP_CONNECTED_MISSED_MESSAGES"):T("QUASAR_TIP_CONNECTED"):T("QUASAR_TIP_NOT_LOGIN");break;case 6:b=T("QUASAR_TIP_NOT_LOAD");break;default:b=T("QUASAR_TIP_DISCONNECTED")}a=a.e?"\n"+a.e:"";(b=T("CHROME_EXT_SHORT_NAME")+a+"\n"+b)&&chrome.browserAction.setTitle({title:b})};X.prototype.w=function(a,b,c){1!=this.a&&(a=b||T("QUASAR_MENUTEXT_UNKNOWN_USER"),a!=this.h&&(this.h=a),this.e=c)};X.prototype.updateUserName=X.prototype.w;
X.prototype.v=function(a,b){this.g!=b&&(this.g=b,$i(this),gj(this))};X.prototype.setUnreadIndicator=X.prototype.v;
var $i=function(a){chrome.browserAction.setIcon(hj(a,!0));chrome.systemIndicator&&chrome.systemIndicator.setIcon(hj(a))},ij=function(a){switch(a.a){case 2:return"offline_working";case 4:case 9:case 8:return a.c?a.g?"available_missed":"available":"offline";case 6:return"offline_unknown";default:return"offline"}},hj=function(a,b){var c=!b&&Kh()?"_mac_":"_",d=ij(a),e=chrome.runtime.getURL("images_4/presence/"+d+c+"19.png"),c=chrome.runtime.getURL("images_4/presence/"+d+c+"38.png");return{path:{19:e, 38:c}}};X.prototype.q=function(){var a=V.a();this.k.get(fj).a("qstcl");a.rb();a.b("onTrayClick",[1])};
var jj=function(a,b,c){I.call(this);this.a=b.createElement("IFRAME");b.body.appendChild(this.a);this.a.src=a;c&&(this.a.id=c,this.a.name=c);a=new H(this);P(this,a);a=Bd(a,this.a,"load",this.c,void 0);Bd(a,this.a,"error",ui,void 0).listen(b.defaultView,"focus",this.b).listen(b.body,"focus",this.b)};p(jj,I);jj.prototype.b=function(){Yb(this.a.focus,this.a)};jj.prototype.c=function(){this.b()};jj.prototype.n=function(){this.a.parentElement.removeChild(this.a);this.a=null;jj.t.n.call(this)};
var oj=function(a,b){H.call(this);this.b=a;Dc("viewer",""+(new Date).getTime());this.e=this.f=null;this.l=V;this.u=m();this.k=a.get(Ji);var c=a.get(Ni),d=T("CHROME_EXT_SHORT_NAME"),e=Sh("viewer-14.png",!0),f=Sh("viewer-28.png",!0),d=kj(c,"viewer","viewer","viewer.html?viewer",d,e,f),e=b?Q(b,lj,2).Ma():null,e=mj(c,new Zh(260,460),!0,e);nj(c,d.id,e);this.a=d;this.a.onClosed.addListener(r(this.B,this));Ei(this.a,r(this.p,this))};p(oj,H);
oj.prototype.n=function(){this.b.b(kd)==this&&this.b.u();this.removeAll();oj.t.n.call(this)};var pj=function(a){F(a.f);a.f=null;F(a.e);a.e=null;zh(a.c.a,"retryInfo").style.display="none"};oj.prototype.close=function(){F(this.a);this.b.b(kd)==this&&this.b.u()};
oj.prototype.p=function(){this.c=new Mh(Fi(this.a).document);this.a.setTitle(T("CHROME_EXT_SHORT_NAME"));zh(this.c.a,"retryMessage").textContent=T("CHROME_EXT_CANNOT_CONNECT");var a=zh(this.c.a,"retryLink");a.textContent=T("QUASAR_TRY_NOW");this.listen(a,"click",this.q);this.listen(this.l,"onStatusChange",this.h);this.h()};oj.prototype.q=function(a){a.b();this.b.get(Ii).f()};
oj.prototype.h=function(){switch(this.k.a){case 3:if(!this.f){pj(this);var a;a=this.b.get(Oi).a;a=new Wd(a.b[0]);var b=new Wd("/talkgadget/qsignin");R(b,"passive","1");R(b,"hl",chrome.i18n.getMessage("@@ui_locale"));a=$d(a,b).toString();this.f=new jj(a,this.c.a)}break;case 2:pj(this);break;case 6:pj(this);zh(this.c.a,"retryInfo").style.display="block";break;default:qj(this)}};var qj=function(a){a.e||(pj(a),rj(a.b.get(Ii)).then(function(a){this.e=new jj(a,this.c.a,"popoutRoster")},void 0,a))};
var sj=function(a,b){this.b=Gd(a);this.a=0;this.c=b||!1};sj.prototype.F=function(a){var b=this.b[this.a],b=(.5+1*Math.random())*b;a&&tj(this);return b};var tj=function(a){a.c&&a.a==a.b.length-1||a.a++};var uj=function(a,b,c){E.call(this);this.b=a;this.e=b||0;this.c=c;this.W=r(this.f,this)};p(uj,E);uj.prototype.a=0;uj.prototype.n=function(){uj.t.n.call(this);this.stop();delete this.b;delete this.c};var vj=function(a,b){a.stop();a.a=de(a.W,n(b)?b:a.e)};uj.prototype.stop=function(){0!=this.a&&ee(this.a);this.a=0};uj.prototype.f=function(){this.a=0;this.b&&this.b.call(this.c)};
var wj=function(a,b,c){E.call(this);this.c=a;this.b=b;this.a=c;this.W=r(this.$c,this)};p(wj,E);g=wj.prototype;g.Sa=!1;g.na=null;g.stop=function(){this.na&&(ee(this.na),this.na=null,this.Sa=!1)};g.n=function(){wj.t.n.call(this);this.stop()};g.$c=function(){this.na=null;this.Sa&&(this.Sa=!1,xj(this))};var xj=function(a){a.na=de(a.W,a.b);a.c.call(a.a)};
var Y=function(a){H.call(this);this.a=a;this.c=a.get(Ji);this.V=a.b(Ni);this.L=kc();this.l=null;this.I=new wj(this.f,6E4,this);P(this,this.I);a=r(this.md,this);si.W=a;wd(this,ti);this.h=!1;this.q=new sj(Vh,!0);this.K=new uj(this.zd,this.q.F(),this);P(this,this.K);this.k=new uj(this.vc,2E4,this);P(this,this.k);this.listen(window,"online",this.sd);this.w=this.D=0;this.b=new sj(Wh);this.e=new uj(this.Ca,this.b.F(),this);P(this,this.e);chrome.cookies.onChanged.addListener(r(this.Da,this));this.v=r(this.aa,
this);this.u=r(this.$,this);chrome.tabs.onUpdated.addListener(this.v);chrome.tabs.onCreated.addListener(this.u)};p(Y,H);ga("ace.core.DataChannelManager",Y);Y.prototype.n=function(){chrome.tabs.onCreated.removeListener(this.u);chrome.tabs.onUpdated.removeListener(this.v);delete this.u;delete this.v;F(this.l);Y.t.n.call(this)};Y.prototype.p=function(a,b){yj(this);t:{var c=this.a,d=c.b(kd);if(d){if(Di(d.a)?!Ai(d.a):1E3>m()-d.u){d.a.focus();break t}d.close()}d=new oj(c,b);c.a(kd,d,!0)}};
Y.prototype.showViewer=Y.prototype.p;Y.prototype.Ua=function(a,b){this.L.a(b||"")};Y.prototype.setRosterUrl=Y.prototype.Ua;var rj=function(a){return a.L.b};Y.prototype.Ba=function(){this.c.f(0,1);var a=this.a.b(kd);a&&a.close();zj(this);this.h=!1};Y.prototype.terminateApplication=Y.prototype.Ba;var yj=function(a){a.h||(a.listen(V,"onStatusChange",a.Pc),a.f(),a.a.get(Oi),a.h=!0)};
Y.prototype.f=function(){this.C||(this.c.f(0,2),zj(this),this.l=new jj(chrome.runtime.getURL("datachannel.html"),document,"centralRoster"))};var zj=function(a){a.V.f();a.a.get(Mi).b();F(a.l);a.l=null;a.L=kc()},Bj=function(a,b){var c=Ah(a.a.get(Oi).a);chrome.cookies.getAll({url:c},r(function(a){a=a&&Aj("SID",a)&&Aj("SSID",a)&&Aj("SAPISID",a);b(a)},a))};Y.prototype.Ea=function(a){var b=this.c.a;if(a){if(3==b){if(a=0==this.e.a)a=this.b,a=a.a<a.b.length;a&&vj(this.e,this.b.F())}}else 3!=b&&this.f()};
Y.prototype.Da=function(a){"SSID"!=a.cookie.name&&"SAPISID"!=a.cookie.name||".google.com"!=a.cookie.domain||Bj(this,r(this.Ea,this))};var Aj=function(a,b){return wa(b,function(b){var d=b.expirationDate&&b.expirationDate<m()/1E3;return b.name==a&&".google.com"==b.domain&&!d})};g=Y.prototype;g.Pc=function(){this.K.stop();this.k.stop();switch(this.c.a){case 2:vj(this.k);break;case 6:vj(this.K,this.q.F());break;case 4:case 9:case 8:case 5:this.q.a=0,this.e.stop()}};
g.sd=function(){if(4!=this.c.a){var a=this.I;a.na?a.Sa=!0:xj(a)}};g.zd=function(){tj(this.q);this.f()};g.md=function(a){zj(this);switch(a){case 1:this.vc();break;case 2:a=this.I,a.na?a.Sa=!0:xj(a)}};g.vc=function(){this.C||(this.k.stop(),this.c.f(0,6))};var Cj=function(a){a.w++;var b=a.a.get(fj);1==a.w?b.a("qccro"):2==a.w?b.a("qccrt"):b.a("qccrm")};Y.prototype.Ca=function(){tj(this.b);Cj(this);Bj(this,r(function(a){a&&this.f()},this))};Y.prototype.aa=function(a,b){b.url&&Dj(this,b.url)};
Y.prototype.$=function(a){a.url&&Dj(this,a.url)};var Ej=function(a){a.D++;var b=a.a.get(fj);1==a.D?b.a("qctro"):2==a.D?b.a("qctrt"):b.a("qctrm")},Dj=function(a,b){wa(Uh,function(a){return a.test(b)})&&0!=a.b.a&&(a.b.a=0,Ej(a),0!=a.e.a&&vj(a.e,a.b.F()))};
var Fj=function(a){this.a=0;this.c=a.get(Cc);null!=this.c.a.get("dupDetectionQueue.latestChat")&&(this.a=this.c.get("dupDetectionQueue.latestChat"));this.b=0;this.f=new C;this.e=new Xh(18E5);qb(this.e,"tick",r(this.g,this,this.f,0,200));Yh(this.e)};p(Fj,E);Fj.prototype.n=function(){this.e.B()};var Gj=function(a,b){var c=b.wa();if(null==c)return!1;switch(b.type()){case 7:case 2:if(null!=b.b&&b.b<=a.a)if(31536E7<a.a-b.b)a.a=0,a.b=0;else return!0;else return Ka(a.f.a,c)}return!1};
Fj.prototype.add=function(a){var b=a.wa();if(null!=b&&!Gj(this,a))switch(a.type()){case 7:case 2:null!=a.b&&this.b<a.b&&(this.b=a.b,this.c.set("dupDetectionQueue.latestChat",this.b)),this.f.set(b,m()+18E5)}};
Fj.prototype.g=function(a,b,c){var d=a.U();if(0!=d){var e=0;null!=b&&0<b&&(e=b<d?b:d);b=d;null!=c&&c<d&&(b=0<c?c:0);e>b&&(e=b);var f=[];c=a.ha(!0);bi(c,function(b){f.push([b,a.get(b)])});f.sort(function(a,b){return a[1]-b[1]});if(31536E7<f[d-1][1]-f[0][1])a.clear();else{c=0;b=d-b;for(var d=d-e,e=m(),h=0;h<f.length;++h)if(c<b||c<d&&f[h][1]<=e)a.remove(f[h][0]),c+=1;else break}}};
var Hj=function(a){y(this,a,"acr:bcr",[])};p(Hj,x);A("acr:bcr",Hj);var Ij=function(a){y(this,a,"acr:srs",[])};p(Ij,x);A("acr:srs",Ij);var Jj=function(a){y(this,a,"acr:rss",[])};p(Jj,x);A("acr:rss",Jj);var Kj=function(a){y(this,a,"acr:rrs",[])};p(Kj,x);A("acr:rrs",Kj);var Lj=function(a){y(this,a,"acr:rsr",[])};p(Lj,x);A("acr:rsr",Lj);var Mj=function(a){y(this,a,"acr:wrs",[1])};p(Mj,x);A("acr:wrs",Mj);var Nj=function(a){y(this,a,0,[])};p(Nj,x);Nj.prototype.Y=function(){return z(this,2)}; Nj.prototype.La=function(){return z(this,11)};
var Oj=function(a){y(this,a,"acq:rs",[3])};p(Oj,x);A("acq:rs",Oj);var Pj=function(a){y(this,a,0,[])};p(Pj,x);Pj.prototype.getState=function(){return z(this,6)};var lj=function(a){y(this,a,0,[])};p(lj,x);lj.prototype.Ma=function(){return Q(this,Pj,1)};var Qj=function(a,b){Dd(a,1,b)},Rj=function(a){y(this,a,0,[])};p(Rj,x);Rj.prototype.Y=function(){return z(this,1)};Rj.prototype.Ma=function(){return Q(this,Pj,2)};var Sj=function(a,b){Dd(a,2,b)};Rj.prototype.La=function(){return z(this,3)};
var Tj=function(a){this.c=a;this.a={};this.b=a.get(Cc)},Uj=function(a,b){return(null!=a?a:"null")+"-"+(null!=b?b:"null")},Xj=function(a,b){de(a.reload,6E4,a);var c=[],d={},e=a.c.get(Ni),f=di(b,Nj,1)||[];w(f,function(a){c.push(z(a,1));d[Uj(a.Y(),a.La())]=a});var h=c.length;c.push("viewer");Vj(e,c,r(function(a){for(var c=[],e=0;e<f.length;e++){var K=a[e];if(K){var ca=f[e],O=new Rj;M(O,3,ca.La());M(O,1,ca.Y());Sj(O,Wj(K));c.push(O)}}fi(c,function(a,b){var c=b.Ma(),c=z(c,2),d=a.Ma();return c-z(d,2)});
w(c,function(a,b){M(d[Uj(a.Y(),a.La())],3,b)});a=a[h];e=new Oj;a&&(K=new lj,Qj(K,Wj(a)),Dd(e,2,K));ci(e,3,c);ci(b,1,f);Dd(e,1,b);this.b.set("ReloadState",e.G);V.a().b("eventReloadStateSaved",[])},a))},Wj=function(a){var b=new Pj;M(b,1,a.top);M(b,2,a.left);M(b,3,a.width);M(b,4,a.height);M(b,5,a.focused);M(b,6,a.state);M(b,7,a.alwaysOnTop);return b};Tj.prototype.read=function(){var a=this.j;this.j=null;V.a().b("eventReloadStateRead",[a&&a.G||null])};Tj.prototype.reload=function(){chrome.runtime.reload()};
var Z=function(a){this.a=new Tj(a);this.b=a;chrome.runtime.onUpdateAvailable.addListener(r(this.g,this))};ga("ace.core.ExtensionLibrary",Z);Z.prototype.g=function(){V.a().b("eventReloadClient",[]);de(this.a.reload,864E5+288E5*Math.random(),this.a)};Z.prototype.q=function(a,b,c,d){a=V.b(b);null!=a&&n(d)&&d&&(d=a.h,null!=d&&null!=d.id&&(chrome.tabs.update(d.id,{selected:!0}),c&&chrome.tabs.get(d.id,function(a){Fh(a.windowId)})))};Z.prototype.selectTab=Z.prototype.q;
Z.prototype.h=function(a,b,c){c?Rh(b,"width=500,height=400"):chrome.tabs.create({url:b,selected:!0},function(a){null!=a?de(function(){chrome.tabs.get(a.id,function(a){Fh(a.windowId)})},2E3):Rh(b)})};Z.prototype.openUrl=Z.prototype.h;Z.prototype.f=function(a,b){this.c=this.b.get(Ni);this.c.focus(b)};Z.prototype.focusMoleByFrameId=Z.prototype.f;Z.prototype.e=function(){V.a().rb()};Z.prototype.showApplication=Z.prototype.e;Z.prototype.p=function(a,b){var c=new Mj(b);Xj(this.a,c)};
Z.prototype.saveReloadState=Z.prototype.p;Z.prototype.k=function(){this.a.read()};Z.prototype.readReloadState=Z.prototype.k;Z.prototype.l=function(){this.a.reload()};Z.prototype.reloadExtension=Z.prototype.l;Z.prototype.j=function(){V.a().Nc()};Z.prototype.onHostReady=Z.prototype.j;
var Yj=function(a){Qi.call(this,a,7);this.c.push(new Ri("join hangout"));this.c.push(new Ri("ignore"))};p(Yj,Qi);Yj.prototype.Ka=function(){var a=Yj.t.Ka.call(this);return a?a:this.h?T("CHROME_EXT_GROUP_PLUS_HANGOUT_DETAILS"):T("CHROME_EXT_ONEONONE_PLUS_HANGOUT_DETAILS")};Yj.prototype.wa=function(){return null!=this.e?Yj.t.wa.call(this):null};
var Zj=function(a,b,c){this.a=c||new vi;c||(this.a.alwaysOnTop=Bh(a.get(Oi).a))};Zj.prototype.getProperties=function(){return this.a};var bk=function(a,b,c){(b=b.k)?ak(a.get(Ni),b,function(b){c(new Zj(a,0,b))}):c(new Zj(a))};var ck=function(){zi.call(this)};p(ck,zi);ck.prototype.setTitle=function(a){Ei(this,r(function(){Fi(this).document.title=a},this))};
var ek=function(a,b){a.q=b;Ei(a,r(function(){dk(this)},a))},fk=function(a,b){a.u=b;Ei(a,r(function(){dk(this)},a))},dk=function(a){var b=Fi(a).document,c=b.querySelector("HEAD"),d=c.querySelectorAll("link[rel='shortcut icon']"),e=Sh("icon-24x24.png",!0);a=[a.q||e,a.u];for(var e=Ec()?2:1,f="",h=0;h<e;++h)if(a[h]&&a!=f){var f=a[h],l=d[h];l||(l=b.createElement("LINK"),c.appendChild(l));l.rel="shortcut icon";var q=a[h];l.type=Jh(q,".ico")?"image/x-icon":Jh(q,".gif")?"image/gif":"image/png";l.href=a[h]}};
var hk=function(a){this.a={};if(a)for(var b=0;b<a.length;b++)this.a[gk(a[b])]=null;for(var c in Object.prototype);},ik={},gk=function(a){return a in ik||32==String(a).charCodeAt(0)?" "+a:a},jk=function(a){return 32==a.charCodeAt(0)?a.substr(1):a};g=hk.prototype;g.add=function(a){this.a[gk(a)]=null};g.clear=function(){this.a={}};g.clone=function(){var a=new hk,b;for(b in this.a)a.a[b]=null;return a};g.contains=function(a){return gk(a)in this.a};
g.forEach=function(a,b){for(var c in this.a)a.call(b,jk(c),void 0,this)};g.U=Object.keys?function(){return Object.keys(this.a).length}:function(){var a=0,b;for(b in this.a)a++;return a};g.A=Object.keys?function(){return Object.keys(this.a).map(jk,this)}:function(){var a=[],b;for(b in this.a)a.push(jk(b));return a};g.P=function(){for(var a in this.a)return!1;return!0};g.remove=function(a){a=gk(a);return a in this.a?(delete this.a[a],!0):!1};g.ha=function(){return Ph(this.A())};
var $=function(a){E.call(this);this.h=a;this.a={};this.c={};this.b=new hk;ga("__onPanelLoad",r(this.J,this));this.p=a.get(Ji);a=new H(this);P(this,a);a.listen(V,"onStatusChange",this.u)};p($,E);ga("ace.core.PanelsManager",$);$.prototype.n=function(){for(var a in this.a)this.kb(this.a[a]);$.t.n.call(this)};$.prototype.isMaximized=function(a,b){var c=function(a){a=a?!a.isMinimized():null;V.a().b("eventIsMinimizedResponse",[b,a])},d=this.a[b];d?d.getProperties(c):c(void 0)};$.prototype.isMaximized=$.prototype.isMaximized;
$.prototype.I=function(a,b,c,d,e,f,h,l,q,B){a="panel.html?"+b;d=d||T("CHROME_EXT_SHORT_NAME");b=kj(this,b,l||b,a,d,e,h);Ei(b,r(this.k,this,c));c=new Zh(280,420);q||B?(q=q||null,e=B||null,B=this.h.get(Ki).a,q=Uj(q,e),(e=B.a[q])&&delete B.a[q],B=e?e.Ma():null):B=null;f=mj(this,c,!!f,B);nj(this,b.id,f)};$.prototype.openPanel=$.prototype.I;
$.prototype.v=function(a,b,c,d,e,f,h){a="dialog.html?"+b;d=d||T("CHROME_EXT_SHORT_NAME");b=kj(this,b,b,a,d);Ei(b,r(this.k,this,c));c=mj(this,new Zh(f,h),e,null);c.ed=!0;nj(this,b.id,c);return b};$.prototype.openDialog=$.prototype.v;var kj=function(a,b,c,d,e,f,h){a.a[b]&&a.kb(a.a[b]);var l=new ck;l.id=b;l.key=c;l.url=d;l.setTitle(e);ek(l,f);fk(l,h);a.a[b]=l;a.c[c]=b;return l};$.prototype.k=function(a,b){b.p=new jj(a,Fi(b).document);P(b,b.p)};
var mj=function(a,b,c,d){b={focus:c,Aa:null,width:b.width,height:b.height,minimize:!1};if(d){b.top=z(d,1);b.left=z(d,2);c=z(d,3);var e=z(d,4);z(d,7)?(b.width=Math.max(b.width,c),b.height=Math.max(b.height,e)):(b.width=c,b.height=e);"minimized"==d.getState()&&(b.minimize=!0);b.Aa=z(d,7);b.focus=z(d,5)}b.Aa="boolean"==typeof b.Aa?b.Aa:Bh(a.h.get(Oi).a);return b},nj=function(a,b,c){var d=a.a[b];d.onClosed.addListener(r(a.kb,a));d.h.addListener(r(a.D,a));d.f.addListener(r(a.w,a));c.minimize&&d.minimize();
b="panel";c.Aa||(b=Lh()?"popup":"detached_panel");c.ed&&(b="popup");var e={type:b,url:d.url,focused:c.focus,width:c.width,height:c.height};if(b=null!=c.top&&null!=c.left)e.top=c.top,e.left=c.left;b||c.Aa?d.create(e):Vj(a,Object.keys(a.c),r(function(a){var b=screen,c;c=new Zh(260,460);var q=new Zh(280,420);c=new Zh(Math.max(c.width,q.width),Math.max(c.height,q.height));for(var B=b.availWidth,K=b.availHeight-50,q=b.availTop+K%c.height,b=b.availLeft+B%c.width,B=Math.floor(B/c.width),ca=Math.floor(K/
c.height),K=Array(B*ca),O=0;O<a.length;O++){var la=a[O];if(la){for(var Nb=[la.left,la.left+la.width-1],la=[la.top,la.top+la.height-1],na=0;2>na;na++)Nb[na]=Math.floor(Math.max(0,Nb[na]-b)/c.width),la[na]=Math.floor(Math.max(0,la[na]-q)/c.height);for(na=Nb[0];na<=Nb[1];na++)for(var db=la[0];db<=la[1];db++)na<B&&db<ca&&(K[na+db*B]=1)}}a=K.length-1;for(O=K.length-1;0<=O;O--)if(!K[O]){a=O;break}K=a%B*c.width;e.top=q+Math.floor(a/B)*c.height+(c.height-e.height);e.left=b+K+(c.width-e.width);d.create(e)},
a))};$.prototype.g=function(a,b){var c=this.a[b];c&&F(c)};$.prototype.closePanel=$.prototype.g;$.prototype.f=function(){for(var a in this.a)0==this.a[a].url.indexOf("panel.html")&&this.g(0,a)};$.prototype.closeAllPanels=$.prototype.f;$.prototype.setTitle=function(a,b,c){(a=this.a[b])&&a.setTitle(c)};$.prototype.setTitle=$.prototype.setTitle;$.prototype.q=function(a,b,c){this.a[b]&&Gi(this.a[b],c)};$.prototype.drawAttention=$.prototype.q;
$.prototype.focus=function(a){if(this.a[a]){var b=this.a[a];b.getProperties(r(function(a){if(a&&(a=Fi(b),0==a.outerWidth&&0==a.outerHeight)){this.kb(b);return}b.focus()},this))}};$.prototype.L=function(a,b,c){this.a[b]&&ek(this.a[b],c)};$.prototype.setPresence=$.prototype.L;$.prototype.K=function(a,b,c){this.a[b]&&fk(this.a[b],c)};$.prototype.setAvatar=$.prototype.K;$.prototype.e=function(a,b,c){for(var d in this.a)(b||this.b.contains(d))&&this.l(0,d,b,c);b||this.b.clear()};
$.prototype.minimizeAllPanelsIfTopmost=$.prototype.e;$.prototype.l=function(a,b,c,d){var e=this.a[b];e&&e.getProperties(r(function(a){if(a&&a.alwaysOnTop&&!this.C)if(c){var h;(h=!d)||(h=new Th(a.left,a.top,a.width,a.height),h=h.left<=d.left+d.width&&d.left<=h.left+h.width&&h.top<=d.top+d.height&&d.top<=h.top+h.height);h&&!a.isMinimized()&&(e.minimize(),this.b.add(b))}else chrome.windows.update(e.a,{state:"normal"}),this.b.remove(b)},this))};$.prototype.minimizePanelIfTopmost=$.prototype.l;
$.prototype.J=function(a){var b=this.a[a.location.search.substring(1)];b&&(b.e=a,Ci(b))};var ak=function(a,b,c){a=a.a[a.c[b]];!a||Ai(a)?c(void 0):a.getProperties(c)},Vj=function(a,b,c){var d=[];w(b,r(function(a){d.push(this.a[this.c[a]])},a));Hi(d,c)};$.prototype.kb=function(a){this.a[a.id]==a&&(this.b.remove(a.id),delete this.c[a.key],delete this.a[a.id],F(a))};$.prototype.D=function(a){this.a[a.id]==a&&this.b.remove(a.id)};$.prototype.w=function(a){this.a[a.id]==a&&V.a().b("eventBlurred",[a.id])}; $.prototype.u=function(){3==this.p.a&&this.f()};
var kk=function(a){E.call(this);this.k=a;this.a=new C;this.h=new C;this.c=new Fj(a);P(this,this.c);this.g=r(this.hd,this);chrome.notifications.onClosed.addListener(this.g);this.e=r(this.Qc,this);chrome.notifications.onClicked.addListener(this.e);this.f=r(this.gd,this);chrome.notifications.onButtonClicked.addListener(this.f)};p(kk,E);ga("ace.core.NotificationManager",kk);
kk.prototype.n=function(){w(this.a.A(),F);this.a.clear();chrome.notifications.onClosed.removeListener(this.g);chrome.notifications.onClicked.removeListener(this.e);chrome.notifications.onButtonClicked.removeListener(this.f);kk.t.n.call(this)};
kk.prototype.p=function(a,b){var c;if(b&&b.Content){c=[b.Id.ServiceUrl,b.Id.ServiceId].join(";");c=0==c.indexOf("bc")?new Vi(c):0<c.indexOf("chat")||0<=c.indexOf("voice")||0<=c.indexOf("video")?new Ui(c):0==c.indexOf("hangout")?new Yj(c):new Qi(c,8);c.setTitle(b.Content.TitleText);c.l=b.Content.SubtitleText;c.f=b.Content.BodyText;c.e=b.Content.BodyTextId||b.Content.BodyTimestamp;c.b=b.Content.BodyTimestamp;var d=0;b.Content.EndTimeMs&&(d=b.Content.EndTimeMs,isNaN(d)||!isFinite(d))&&(d=0);d=d||m()+
1E4;c.g=d;b.Content.ServiceIcon?(d=b.Content.ServiceIcon,c.j=d&&Sh(d)||""):b.Content.TitleTemplate&&(d=b.Content.TitleTemplate.IconUrl,c.j=d&&Sh(d)||"");b.Content.IsGroupChat&&(c.h=!0);b.Content.FrameId&&(c.k=b.Content.FrameId);if(b.Content.BodyTemplate)for(var d=b.Content.BodyTemplate.Action,e=0;e<d.length;e++)d[e].Name&&c.c.push(new Ri(d[e].Name,d[e].Text))}else c=null;c&&(V.a().b("eventLogImpression",["qnop"]),Gj(this.c,c)?lk(c.a,"toastEventOnNotDisplayed"):(this.c.add(c),mk(this,c)))};
kk.prototype.registerNotification=kk.prototype.p;var mk=function(a,b){2==b.type()||b.k?bk(a.k,b,function(c){c=c.getProperties();c.focused||c.alwaysOnTop?lk(b.a,"toastEventOnNotDisplayed"):nk(a,b)}):nk(a,b)},nk=function(a,b){var c=b.a,d=b.g-m();0>=d?a.ic(c):(a.a.set(c,b),chrome.notifications.create(c,Ti(b),function(){V.a().b("eventLogImpression",["qtod"])}),ee(a.h.get(c,null)),b.g!=Number.MAX_VALUE&&a.h.set(c,de(r(a.ic,a,c),d)),V.a().b("eventLogImpression",["qnst"]))};
kk.prototype.b=function(){w(ta(this.a.A(),Ch),this.Ga,this)};kk.prototype.cleanAllNotifications=kk.prototype.b;kk.prototype.l=function(a,b){var c=this.a.get(b);c&&this.Ga(c)};kk.prototype.cleanANotification=kk.prototype.l;g=kk.prototype;g.Ga=function(a){a=a.a;chrome.notifications.clear(a,ka);this.a.remove(a)};g.hd=function(a,b){if(b){var c=this.a.get(a);c&&(this.a.remove(a),c.Fb()?lk(a,"toastEventOnButton","ignore"):lk(a,"toastEventOnClose"))}};
g.Qc=function(a){var b=this.a.get(a);b&&(lk(a,"toastEventOnBody"),this.Ga(b))};g.gd=function(a,b){var c=this.a.get(a);c&&(lk(a,"toastEventOnButton",c.c[b].name),this.Ga(c))};g.ic=function(a){var b=this.a.get(a);b&&(lk(a,"toastEventOnTimeout"),this.Ga(b))};var lk=function(a,b,c){var d=V;(d=d&&d.a())&&!d.C&&V.a().b(b,[a,c,"",!1])};
var ok=function(a){y(this,a,"f.mt",[])};p(ok,x);A("f.mt",ok);var pk=function(a){y(this,a,"er",[])};p(pk,x);A("er",pk);pk.prototype.Bb=function(){return z(this,9)};pk.prototype.getData=function(){return z(this,4)};new ai;D&&Va(8);var qk=function(){throw Error("y");};qk.prototype.a=null;qk.prototype.toString=function(){return this.content};var rk=function(){qk.call(this)};p(rk,qk);(function(a){function b(a){this.content=a}b.prototype=a.prototype;return function(a,d){var e=new b(String(a));void 0!==d&&(e.a=d);return e}})(rk);(function(a){function b(a){this.content=a}b.prototype=a.prototype;return function(a,d){var e=String(a);if(!e)return"";e=new b(e);void 0!==d&&(e.a=d);return e}})(rk);
var sk=function(a,b){Tc.call(this,a,b)};p(sk,Tc);var tk=function(a){this.a=a?z(a,1)||-1:-1},uk=new tk;var vk=function(){};p(vk,ie);vk.prototype.b=function(){};vk.prototype.b.oc=!0;vk.t||p(vk,ie);U.a={};U.a.pb="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ";U.a.nb=U.a.pb+"0123456789";U.a.qb=U.a.pb.length;U.a.ob=U.a.nb.length;U.a.Nb=-2147483648;U.a.Ad=function(a){for(var b=0,c=a.length-1;0<=c;c--)b=b*(0==c?U.a.qb:U.a.ob)+U.a.nb.indexOf(a.charAt(c));return b+U.a.Nb};U.a.toString=function(a){var b=[],c=0;a-=U.a.Nb;b[c++]=U.a.pb.charAt(a%U.a.qb);for(a=Math.floor(a/U.a.qb);0<a;)b[c++]=U.a.nb.charAt(a%U.a.ob),a=Math.floor(a/U.a.ob);return b.join("")};
new sk(Vc,"f_req");
}catch(e){_DumpException(e)}
try{
var jn=function(a,b,c){a.timeOfStartCall=(new Date).getTime();if(b&&JSON&&JSON.stringify){var d=JSON.stringify(b);200>=d.length&&(a.psdJson=d)}d=c||k;d.GOOGLE_FEEDBACK_START_ARGUMENTS=arguments;var e=a.serverUri||"//www.google.com/tools/feedback",f=d.GOOGLE_FEEDBACK_START;if(f)f.apply(d,arguments);else{var e=e+"/load.js?",h;for(h in a)f=a[h],null!=f&&!ha(f)&&(e+=encodeURIComponent(h)+"="+encodeURIComponent(f)+"&");h=d.document;d=h.createElement("script");d.src=e;h.body.appendChild(d)}}; ga("userfeedback.api.startFeedback",jn);
var kn=function(){H.call(this);this.listen(window,"unload",this.B);document.title=T("CHROME_EXT_SHORT_NAME")+": "+T("CHROME_EXT_FEEDBACK_SUBTITLE");S("system-legend").innerText=T("QUASAR_FEEDBACK_SYSTEM_LEGEND");S("system-platform-label").innerText=T("QUASAR_FEEDBACK_PLATFORM_LABEL");S("system-platform-value").innerText=navigator.platform;S("system-user-agent-label").innerText=T("QUASAR_FEEDBACK_USER_AGENT_LABEL");S("system-user-agent-value").innerText=navigator.userAgent;S("user-legend").innerText=
T("CHROME_EXT_FEEDBACK_COMMENTS");S("privacy-legend").innerText=T("QUASAR_FEEDBACK_PRIVACY_LEGEND");S("privacy-text").innerText=T("QUASAR_FEEDBACK_PRIVACY_TEXT");var a=S("submit-button");a.innerText=T("QUASAR_FEEDBACK_SUBMIT_BUTTON");this.listen(a,"click",this.b);a=S("cancel-button");a.innerText=T("QUASAR_FEEDBACK_CANCEL_BUTTON");this.listen(a,"click",this.a);S("user-text-value").focus()};p(kn,H);
kn.prototype.b=function(){var a=S("user-text-value").value;if(a&&(a=a.trim())){var a={flow:"submit",serverUri:T("QUASAR_FEEDBACK_SERVER_URI"),productId:83052,locale:chrome.i18n.getMessage("@@ui_locale"),report:{description:a},callback:this.a},b={version:chrome.runtime.getManifest().version,build:chrome.runtime.id};S("submit-button").disabled=!0;jn(a,b)}};kn.prototype.a=function(){window.close()};window.addEventListener("load",function(){new kn},!1);

}catch(e){_DumpException(e)}
// Google Inc.
