try{
var g,aa=aa||{},k=this,ba="closure_uid_"+(1E9*Math.random()>>>0),m=Date.now||function(){return+new Date};
}catch(e){_DumpException(e)}
try{
k.ace_i18n={chrome_ext_short_name:{message:"Hangouts"},chrome_ext_description:{message:"Hangouts brings conversations to life with photos, emoji, and even group video calls for free."},quasar_chat_toast_info:{message:"Click to go to page..."},quasar_answer_button_text:{message:"Answer"},quasar_decline_button_text:{message:"Decline"},quasar_help:{message:"Help"},quasar_legend_startup_shutdown:{message:"Application"},chrome_ext_run_at_browser_start:{message:"Sign in to Hangouts when Chrome starts"},
chrome_ext_run_after_browser_close:{message:"Allow background mode"},chrome_ext_new_windows_topmost:{message:"Keep Hangouts on top of other windows"},quasar_label_tray_icon:{message:"Show system tray icon"},quasar_legend_notifications:{message:"Notifications"},quasar_label_all_notification:{message:"Disable notifications"},quasar_label_chat_notification:{message:"Disable chat notifications"},quasar_label_toast_timeout_chat:{message:"Allow chat notifications to timeout automatically"},quasar_label_toast_duration_chat:{message:"Timeout length (in seconds):"},
quasar_button_save:{message:"Ok"},quasar_button_apply:{message:"Apply"},quasar_button_cancel:{message:"Cancel"},chrome_ext_menutext_feedback:{message:"Send feedback"},quasar_feedback_server_uri:{message:"https://www.google.com/tools/feedback"},chrome_ext_feedback_subtitle:{message:"Send feedback"},chrome_ext_feedback_comments:{message:"Comments"},quasar_feedback_system_legend:{message:"System Information"},quasar_feedback_platform_label:{message:"Platform:"},quasar_feedback_user_agent_label:{message:"User Agent:"},
quasar_feedback_privacy_legend:{message:"Privacy Statement"},quasar_feedback_privacy_text:{message:"The description, product information, additional information and your email address will be sent to Google. See the Google Feedback Terms of Service. By submitting this content you are granting to Google the right to use it to improve our products and services. See our Privacy Policy."},quasar_feedback_submit_button:{message:"Send Feedback"},quasar_feedback_cancel_button:{message:"Cancel"},quasar_video_title:{message:"Video call from $1...",
placeholders:{1:{content:"$1"}}},quasar_voice_title:{message:"Voice call from $1...",placeholders:{1:{content:"$1"}}},quasar_group_chat_title:{message:"From group chat..."},quasar_chat_title:{message:"$1 says...",placeholders:{1:{content:"$1"}}},quasar_hangout_title:{message:"$1 is hanging out",placeholders:{1:{content:"$1"}}},chrome_ext_oneonone_plus_hangout_details:{message:"is video calling you via Hangouts"},chrome_ext_group_plus_hangout_details:{message:"has invited you to a group Hangout video call"},
quasar_video_details:{message:"is calling you with video chat"},quasar_voice_details:{message:"is calling you"},quasar_tip_connected:{message:"Status: Connected"},chrome_ext_tip_connected_missed_messages:{message:"Status: Connected\nMissed messages"},quasar_tip_connecting:{message:"Status: Connecting"},quasar_tip_reconnecting:{message:"Status: Reconnecting"},quasar_tip_disconnected:{message:"Status: Disconnected"},quasar_tip_not_login:{message:"Status: Not logged in"},quasar_tip_not_load:{message:"Status: Loading error"},
chrome_ext_menutext_unsigned_user:{message:"Not signed in"},quasar_menutext_unknown_user:{message:"Unknown"},quasar_menutext_feedback:{message:"Feedback"},quasar_menutext_settings:{message:"Options"},quasar_menutext_quit:{message:"Exit"},quasar_menutext_signout:{message:"Sign out"},chrome_ext_cannot_connect:{message:"Unable to connect to Google. Please check your internet connection."},quasar_try_now:{message:"Try now"},quasar_sign_in_to_start_talking:{message:"Sign in to start talking with friends"},
quasar_sign_in:{message:"Sign in"},chrome_app_connection_error_title:{message:"Connection Error"},chrome_app_connection_error_detail:{message:"Make sure you are connected to the Internet and try again"},chrome_app_connection_error_button:{message:"Try again"},chrome_app_welcome_message:{message:"Enjoy private and group conversations with text, photos, gifs, voice, video and more."},chrome_app_chrome_signin_message:{message:"Sign in to Chrome to get started."},chrome_app_learn_more_message:{message:"Learn more"},
chrome_app_signin_button:{message:"Sign in"},chrome_app_exit_title:{message:"Are you sure you want to quit Hangouts?"},chrome_app_exit_detail:{message:"Once quit, you will not receive new messages or calls"},chrome_app_exit_no:{message:"No"},chrome_app_exit_quit:{message:"Quit"}};

}catch(e){_DumpException(e)}
try{
var n=function(a){return void 0!==a},da=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},ea=function(a,b,c){return a.call.apply(a.bind,arguments)},fa=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);
if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},p=function(a,b){function c(){}c.prototype=b.prototype;
a.t=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Jd=function(a,c,f){return b.prototype[c].apply(a,Array.prototype.slice.call(arguments,2))}},ga=function(a,b){var c=a.split("."),d=k;c[0]in d||!d.execScript||d.execScript("var "+c[0]);for(var e;c.length&&(e=c.shift());)!c.length&&n(b)?d[e]=b:d[e]?d=d[e]:d=d[e]={}},r=function(a,b,c){r=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ea:da;return r.apply(null,arguments)},ha=function(a){var b=typeof a;
return"object"==b&&null!=a||"function"==b},s=function(a){return"function"==fa(a)},ia=function(a){return"number"==typeof a},t=function(a){return"string"==typeof a},ja=function(a){var b=fa(a);return"array"==b||"object"==b&&"number"==typeof a.length},u=function(a){return"array"==fa(a)},ka=function(){},ma=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,ma);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};p(ma,Error);ma.prototype.name="CustomError";
var oa=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},qa=function(a,b){for(var c=0,d=oa(String(a)).split("."),e=oa(String(b)).split("."),f=Math.max(d.length,e.length),h=0;0==c&&h<f;h++){var l=d[h]||"",q=e[h]||"",B=RegExp("(\\d*)(\\D*)","g"),K=RegExp("(\\d*)(\\D*)","g");do{var ca=B.exec(l)||["","",""],O=K.exec(q)||["","",""];if(0==ca[0].length&&0==O[0].length)break;c=pa(0==ca[1].length?0:parseInt(ca[1],10),0==O[1].length?0:parseInt(O[1], 10))||pa(0==ca[2].length,0==O[2].length)||pa(ca[2],O[2])}while(0==c)}return c},pa=function(a,b){return a<b?-1:a>b?1:0};
var v=Array.prototype,ra=v.indexOf?function(a,b,c){return v.indexOf.call(a,b,c)}:function(a,b,c){c=null==c?0:0>c?Math.max(0,a.length+c):c;if(t(a))return t(b)&&1==b.length?a.indexOf(b,c):-1;for(;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},sa=v.lastIndexOf?function(a,b,c){return v.lastIndexOf.call(a,b,null==c?a.length-1:c)}:function(a,b,c){c=null==c?a.length-1:c;0>c&&(c=Math.max(0,a.length+c));if(t(a))return t(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;
return-1},w=v.forEach?function(a,b,c){v.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=t(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},ta=v.filter?function(a,b,c){return v.filter.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=[],f=0,h=t(a)?a.split(""):a,l=0;l<d;l++)if(l in h){var q=h[l];b.call(c,q,l,a)&&(e[f++]=q)}return e},ua=v.map?function(a,b,c){return v.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=t(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,
f[h],h,a));return e},va=v.reduce?function(a,b,c,d){d&&(b=r(b,d));return v.reduce.call(a,b,c)}:function(a,b,c,d){var e=c;w(a,function(c,h){e=b.call(d,e,c,h,a)});return e},wa=v.some?function(a,b,c){return v.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=t(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1},xa=function(a,b){var c=ra(a,b),d;(d=0<=c)&&v.splice.call(a,c,1);return d};
var ya=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;var za=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},Aa=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},Ba=function(a){var b=[],c=0,d;for(d in a)b[c++]=d;return b};var x=function(){},y=function(a,b,c,d){a.a={};b||(b=c?[c]:[]);a.p=c?String(c):void 0;a.b=0===c?-1:0;a.G=b;t:{if(a.G.length&&(b=a.G.length-1,(c=a.G[b])&&"object"==typeof c&&"number"!=typeof c.length)){a.j=b-a.b;a.c=c;break t}a.j=Number.MAX_VALUE}if(d)for(b=0;b<d.length;b++)c=d[b],c<a.j?(c+=a.b,a.G[c]=a.G[c]||[]):a.c[c]=a.c[c]||[]},z=function(a,b){return b<a.j?a.G[b+a.b]:a.c[b]};x.prototype.toString=function(){return this.G.toString()};var A=function(a,b){Ca[a]=b;b.messageId=a},Ca={};
var Da="StopIteration"in k?k.StopIteration:Error("f"),Ea=function(){};Ea.prototype.next=function(){throw Da;};Ea.prototype.ha=function(){return this};var Fa;t:{var Ga=k.navigator;if(Ga){var Ha=Ga.userAgent;if(Ha){Fa=Ha;break t}}Fa=""}var Ia=function(a){return-1!=Fa.indexOf(a)};var C=function(a,b){this.a={};this.b=[];this.j=this.c=0;var c=arguments.length;if(1<c){if(c%2)throw Error("h");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else if(a){a instanceof C?(c=a.M(),d=a.A()):(c=Ba(a),d=Aa(a));for(var e=0;e<c.length;e++)this.set(c[e],d[e])}};g=C.prototype;g.U=function(){return this.c};g.A=function(){Ja(this);for(var a=[],b=0;b<this.b.length;b++)a.push(this.a[this.b[b]]);return a};g.M=function(){Ja(this);return this.b.concat()};g.P=function(){return 0==this.c};
g.clear=function(){this.a={};this.j=this.c=this.b.length=0};g.remove=function(a){return Ka(this.a,a)?(delete this.a[a],this.c--,this.j++,this.b.length>2*this.c&&Ja(this),!0):!1};var Ja=function(a){if(a.c!=a.b.length){for(var b=0,c=0;b<a.b.length;){var d=a.b[b];Ka(a.a,d)&&(a.b[c++]=d);b++}a.b.length=c}if(a.c!=a.b.length){for(var e={},c=b=0;b<a.b.length;)d=a.b[b],Ka(e,d)||(a.b[c++]=d,e[d]=1),b++;a.b.length=c}};g=C.prototype;g.get=function(a,b){return Ka(this.a,a)?this.a[a]:b};
g.set=function(a,b){Ka(this.a,a)||(this.c++,this.b.push(a),this.j++);this.a[a]=b};g.forEach=function(a,b){for(var c=this.M(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};g.clone=function(){return new C(this)};g.ha=function(a){Ja(this);var b=0,c=this.b,d=this.a,e=this.j,f=this,h=new Ea;h.next=function(){for(;;){if(e!=f.j)throw Error("i");if(b>=c.length)throw Da;var h=c[b++];return a?h:d[h]}};return h};var Ka=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
var La=function(a){if("function"==typeof a.A)return a.A();if(t(a))return a.split("");if(ja(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Aa(a)},Ma=function(a,b,c){if("function"==typeof a.forEach)a.forEach(b,c);else if(ja(a)||t(a))w(a,b,c);else{var d;if("function"==typeof a.M)d=a.M();else if("function"!=typeof a.A)if(ja(a)||t(a)){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else d=Ba(a);else d=void 0;for(var e=La(a),f=e.length,h=0;h<f;h++)b.call(c,e[h],d&&d[h],a)}};
var Na=Ia("Opera")||Ia("OPR"),D=Ia("Trident")||Ia("MSIE"),Oa=Ia("Gecko")&&-1==Fa.toLowerCase().indexOf("webkit")&&!(Ia("Trident")||Ia("MSIE")),Pa=-1!=Fa.toLowerCase().indexOf("webkit"),Qa=k.navigator||null,Ra=Qa&&Qa.platform||"",Sa=function(){var a=k.document;return a?a.documentMode:void 0},Ta=function(){var a="",b;if(Na&&k.opera)return a=k.opera.version,s(a)?a():a;Oa?b=/rv\:([^\);]+)(\)|;)/:D?b=/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/:Pa&&(b=/WebKit\/(\S+)/);b&&(a=(a=b.exec(Fa))?a[1]:"");return D&&(b= Sa(),b>parseFloat(a))?String(b):a}(),Ua={},Va=function(a){return Ua[a]||(Ua[a]=0<=qa(Ta,a))},Wa=k.document,Xa=Wa&&D?Sa()||("CSS1Compat"==Wa.compatMode?parseInt(Ta,10):5):void 0;
var E=function(){this.C=this.C;this.j=this.j};E.prototype.C=!1;E.prototype.Eb=function(){return this.C};E.prototype.B=function(){this.C||(this.C=!0,this.n())};E.prototype.n=function(){if(this.j)for(;this.j.length;)this.j.shift()()};var F=function(a){a&&"function"==typeof a.B&&a.B()};
var Ya=!D||D&&9<=Xa;!Oa&&!D||D&&D&&9<=Xa||Oa&&Va("1.9.1");D&&Va("9");var Za=function(a){Za[" "](a);return a};Za[" "]=ka;var $a=function(a,b){try{return Za(a[b]),!0}catch(c){}return!1};var ab=!D||D&&9<=Xa,bb=D&&!Va("9");!Pa||Va("528");Oa&&Va("1.9b")||D&&Va("8")||Na&&Va("9.5")||Pa&&Va("528");Oa&&!Va("8")||D&&Va("9");var G=function(a,b){this.type=a;this.a=this.target=b;this.wc=!0};G.prototype.B=function(){};G.prototype.b=function(){this.wc=!1};var cb=function(a,b){G.call(this,a?a.type:"");this.a=this.target=null;this.clientY=this.clientX=0;this.c=this.state=null;if(a){this.type=a.type;this.target=a.target||a.srcElement;this.a=b;var c=a.relatedTarget;c&&Oa&&$a(c,"nodeName");this.clientX=void 0!==a.clientX?a.clientX:a.pageX;this.clientY=void 0!==a.clientY?a.clientY:a.pageY;this.state=a.state;this.c=a;a.defaultPrevented&&this.b()}};p(cb,G); cb.prototype.b=function(){cb.t.b.call(this);var a=this.c;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,bb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};
var eb="closure_listenable_"+(1E6*Math.random()|0),fb=function(a){return!(!a||!a[eb])},gb=0;var hb=function(a,b,c,d,e){this.qa=a;this.proxy=null;this.src=b;this.type=c;this.Ya=!!d;this.fb=e;this.key=++gb;this.removed=this.Xa=!1},ib=function(a){a.removed=!0;a.qa=null;a.proxy=null;a.src=null;a.fb=null};var jb=function(a){this.src=a;this.a={};this.b=0};jb.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var h=kb(a,b,d,e);-1<h?(b=a[h],c||(b.Xa=!1)):(b=new hb(b,this.src,f,!!d,e),b.Xa=c,a.push(b));return b};jb.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=kb(e,b,c,d);return-1<b?(ib(e[b]),v.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};
var lb=function(a,b){var c=b.type;if(!(c in a.a))return!1;var d=xa(a.a[c],b);d&&(ib(b),0==a.a[c].length&&(delete a.a[c],a.b--));return d};jb.prototype.removeAll=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,ib(d[e]);delete this.a[c];this.b--}return b}; var mb=function(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=kb(a,c,d,e));return-1<b?a[b]:null},kb=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.removed&&f.qa==b&&f.Ya==!!c&&f.fb==d)return e}return-1};
var nb="closure_lm_"+(1E6*Math.random()|0),ob={},pb=0,qb=function(a,b,c,d,e){if(u(b)){for(var f=0;f<b.length;f++)qb(a,b[f],c,d,e);return null}c=rb(c);return fb(a)?a.listen(b,c,d,e):sb(a,b,c,!1,d,e)},sb=function(a,b,c,d,e,f){if(!b)throw Error("l");var h=!!e,l=tb(a);l||(a[nb]=l=new jb(a));c=l.add(b,c,d,e,f);if(c.proxy)return c;d=ub();c.proxy=d;d.src=a;d.qa=c;a.addEventListener?a.addEventListener(b.toString(),d,h):a.attachEvent(vb(b.toString()),d);pb++;return c},ub=function(){var a=wb,b=ab?function(c){return a.call(b.src,
b.qa,c)}:function(c){c=a.call(b.src,b.qa,c);if(!c)return c};return b},xb=function(a,b,c,d,e){if(u(b))for(var f=0;f<b.length;f++)xb(a,b[f],c,d,e);else c=rb(c),fb(a)?a.Mb(b,c,d,e):a&&(a=tb(a))&&(b=mb(a,b,c,!!d,e))&&yb(b)},yb=function(a){if(ia(a)||!a||a.removed)return!1;var b=a.src;if(fb(b))return lb(b.T,a);var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.Ya):b.detachEvent&&b.detachEvent(vb(c),d);pb--;(c=tb(b))?(lb(c,a),0==c.b&&(c.src=null,b[nb]=null)):ib(a);return!0},vb=function(a){return a in
ob?ob[a]:ob[a]="on"+a},Ab=function(a,b,c,d){var e=1;if(a=tb(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.Ya==c&&!f.removed&&(e&=!1!==zb(f,d))}return Boolean(e)},zb=function(a,b){var c=a.qa,d=a.fb||a.src;a.Xa&&yb(a);return c.call(d,b)},wb=function(a,b){if(a.removed)return!0;if(!ab){var c;if(!(c=b))t:{c=["window","event"];for(var d=k,e;e=c.shift();)if(null!=d[e])d=d[e];else{c=null;break t}c=d}e=c;c=new cb(e,this);d=!0;if(!(0>e.keyCode||void 0!=e.returnValue)){t:{var f=
!1;if(0==e.keyCode)try{e.keyCode=-1;break t}catch(h){f=!0}if(f||void 0==e.returnValue)e.returnValue=!0}e=[];for(f=c.a;f;f=f.parentNode)e.push(f);for(var f=a.type,l=e.length-1;0<=l;l--)c.a=e[l],d&=Ab(e[l],f,!0,c);for(l=0;l<e.length;l++)c.a=e[l],d&=Ab(e[l],f,!1,c)}return d}return zb(a,new cb(b,this))},tb=function(a){a=a[nb];return a instanceof jb?a:null},Bb="__closure_events_fn_"+(1E9*Math.random()>>>0),rb=function(a){if(s(a))return a;a[Bb]||(a[Bb]=function(b){return a.handleEvent(b)});return a[Bb]};
var Cb=function(a){y(this,a,"h_cc",[])};p(Cb,x);A("h_cc",Cb);Cb.prototype.Y=function(){return z(this,19)};var H=function(a){E.call(this);this.J=a;this.g={}};p(H,E);var Db=[];H.prototype.listen=function(a,b,c,d){return Eb(this,a,b,c,d)};var Eb=function(a,b,c,d,e,f){u(c)||(c&&(Db[0]=c.toString()),c=Db);for(var h=0;h<c.length;h++){var l=qb(b,c[h],d||a.handleEvent,e||!1,f||a.J||a);if(!l)break;a.g[l.key]=l}return a};
H.prototype.Mb=function(a,b,c,d,e){if(u(b))for(var f=0;f<b.length;f++)this.Mb(a,b[f],c,d,e);else c=c||this.handleEvent,e=e||this.J||this,c=rb(c),d=!!d,b=fb(a)?mb(a.T,String(b),c,d,e):a?(a=tb(a))?mb(a,b,c,d,e):null:null,b&&(yb(b),delete this.g[b.key]);return this};H.prototype.removeAll=function(){za(this.g,yb);this.g={}};H.prototype.n=function(){H.t.n.call(this);this.removeAll()};H.prototype.handleEvent=function(){throw Error("m");};
var I=function(){E.call(this);this.T=new jb(this);this.L=this;this.u=null};p(I,E);I.prototype[eb]=!0;g=I.prototype;g.addEventListener=function(a,b,c,d){qb(this,a,b,c,d)};g.removeEventListener=function(a,b,c,d){xb(this,a,b,c,d)};g.n=function(){I.t.n.call(this);this.T&&this.T.removeAll(void 0);this.u=null};g.listen=function(a,b,c,d){return this.T.add(String(a),b,!1,c,d)};g.Mb=function(a,b,c,d){return this.T.remove(String(a),b,c,d)}; g.da=function(a,b,c){a=this.T.a[String(a)];if(!a)return!0;a=a.concat();for(var d=!0,e=0;e<a.length;++e){var f=a[e];if(f&&!f.removed&&f.Ya==b){var h=f.qa,l=f.fb||f.src;f.Xa&&lb(this.T,f);d=!1!==h.call(l,c)&&d}}return d&&0!=c.wc};
var Fb,Gb,Hb,Ib,Jb,Kb,Lb;Lb=Kb=Jb=Ib=Hb=Gb=Fb=!1;var Mb=Fa;Mb&&(-1!=Mb.indexOf("Firefox")?Fb=!0:-1!=Mb.indexOf("Camino")?Gb=!0:-1!=Mb.indexOf("iPhone")||-1!=Mb.indexOf("iPod")?Hb=!0:-1!=Mb.indexOf("iPad")?Ib=!0:-1!=Mb.indexOf("Chrome")?Kb=!0:-1!=Mb.indexOf("Android")?Jb=!0:-1!=Mb.indexOf("Safari")&&(Lb=!0));var Ob=Fb,Pb=Gb,Qb=Hb,Rb=Ib,Sb=Jb,Tb=Kb,Ub=Lb;
var Vb=function(a){k.setTimeout(function(){throw a;},0)},Yb=function(a,b){var c=a;b&&(c=r(a,b));!s(k.setImmediate)||k.Window&&k.Window.prototype.setImmediate==k.setImmediate?(Wb||(Wb=Xb()),Wb(c)):k.setImmediate(c)},Wb,Xb=function(){var a=k.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&(a=function(){var a=document.createElement("iframe");a.style.display="none";a.src="";document.documentElement.appendChild(a);var b=a.contentWindow,a=
b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host,a=r(function(a){if(a.origin==d||a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!Ia("Trident")&&!Ia("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){c=c.next;var a=c.Xb;c.Xb=null;a()};return function(a){d.next={Xb:a};
d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in document.createElement("script")?function(a){var b=document.createElement("script");b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};document.documentElement.appendChild(b)}:function(a){k.setTimeout(a,0)}};
var dc=function(a,b){Zb||$b();ac||(Zb(),ac=!0);bc.push(new cc(a,b))},Zb,$b=function(){if(k.Promise&&k.Promise.resolve){var a=k.Promise.resolve();Zb=function(){a.then(ec)}}else Zb=function(){Yb(ec)}},ac=!1,bc=[],ec=function(){for(;bc.length;){var a=bc;bc=[];for(var b=0;b<a.length;b++){var c=a[b];try{c.a.call(c.b)}catch(d){Vb(d)}}}ac=!1},cc=function(a,b){this.a=a;this.b=b};
var fc=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0},gc=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var ic=function(a,b){this.b=0;this.f=void 0;this.a=this.c=null;this.j=this.e=!1;try{var c=this;a.call(b,function(a){hc(c,2,a)},function(a){hc(c,3,a)})}catch(d){hc(this,3,d)}},kc=function(){var a,b=new ic(function(b){a=b});return new jc(b,a)};ic.prototype.then=function(a,b,c){return lc(this,s(a)?a:null,s(b)?b:null,c)};fc(ic);
var oc=function(a){0==a.b&&dc(function(){var a=new mc(void 0);nc(this,a)},a)},nc=function(a,b){if(0==a.b)if(a.c){var c=a.c;if(c.a){for(var d=0,e=-1,f=0,h;h=c.a[f];f++)if(h=h.Za)if(d++,h==a&&(e=f),0<=e&&1<d)break;0<=e&&(0==c.b&&1==d?nc(c,b):(d=c.a.splice(e,1)[0],pc(c,d,3,b)))}}else hc(a,3,b)},rc=function(a,b){a.a&&a.a.length||2!=a.b&&3!=a.b||qc(a);a.a||(a.a=[]);a.a.push(b)},lc=function(a,b,c,d){var e={Za:null,qc:null,sc:null};e.Za=new ic(function(a,h){e.qc=b?function(c){try{var e=b.call(d,c);a(e)}catch(B){h(B)}}:
a;e.sc=c?function(b){try{var e=c.call(d,b);!n(e)&&b instanceof mc?h(b):a(e)}catch(B){h(B)}}:h});e.Za.c=a;rc(a,e);return e.Za};ic.prototype.g=function(a){this.b=0;hc(this,2,a)};ic.prototype.h=function(a){this.b=0;hc(this,3,a)};
var hc=function(a,b,c){if(0==a.b){if(a==c)b=3,c=new TypeError("Promise cannot resolve to itself");else{if(gc(c)){a.b=1;c.then(a.g,a.h,a);return}if(ha(c))try{var d=c.then;if(s(d)){sc(a,c,d);return}}catch(e){b=3,c=e}}a.f=c;a.b=b;qc(a);3!=b||c instanceof mc||tc(a,c)}},sc=function(a,b,c){a.b=1;var d=!1,e=function(b){d||(d=!0,a.g(b))},f=function(b){d||(d=!0,a.h(b))};try{c.call(b,e,f)}catch(h){f(h)}},qc=function(a){a.e||(a.e=!0,dc(a.k,a))};
ic.prototype.k=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=[];for(var b=0;b<a.length;b++)pc(this,a[b],this.b,this.f)}this.e=!1};var pc=function(a,b,c,d){if(2==c)b.qc(d);else{for(;a&&a.j;a=a.c)a.j=!1;b.sc(d)}},tc=function(a,b){a.j=!0;dc(function(){a.j&&uc.call(null,b)})},uc=Vb,mc=function(a){ma.call(this,a)};p(mc,ma);mc.prototype.name="cancel";var jc=function(a,b){this.b=a;this.a=b};
var J=function(a){this.a=a};J.prototype.toString=function(){return this.a};var vc=new J("fJuxOc"),wc=new J("ZtVrH"),xc=new J("zZa4xc"),yc=new J("pVbxBc"),zc=new J("byfTOb"),Ac=new J("LEikZe"),Bc=new J("rJmJrc");var Cc=new J("a");var Dc=function(a,b){for(var c=[],d=0;d<arguments.length;d++)c.push(arguments[d]||"");return c.join("_;_")},Ec=function(){return 0<=navigator.userAgent.indexOf("CrOS")};var Fc=function(a,b){this.j=a||"e";this.c=null!=a&&"p"==a?"e":"p";this.b=this.e=null;this.h=b||"u";this.a=this.g=null;this.f=[]};Fc.prototype.message=function(){var a={};a.i=this.a;a.m=this.f;a.r=this.h;a.o=this.g;a.s=this.b;a.st=this.c;a.d=this.e;a.dt=this.j;return a};ga("ace.base.Message.prototype.message",Fc.prototype.message);
var Gc=function(a,b){for(var c in b)switch(c){case "r":a.h=b[c];break;case "i":a.a=b[c];break;case "m":a.f=b[c];break;case "o":a.g=b[c];break;case "s":a.b=b[c];break;case "d":a.e=b[c];break;case "st":a.c=b[c];break;case "dt":a.j=b[c]}return a},Hc=function(a,b,c){null!=b&&(a.b=b,null!=c&&(a.c=c))},Ic=function(a,b){null!=b&&(a.a=b)},Jc=function(a,b){"object"==typeof b?a.f=b:a.f=[b]};Fc.prototype.source=function(){return this.b};Fc.prototype.target=function(){return this.e};Fc.prototype.content=function(){return this.f};
var Kc=function(a,b,c,d,e){E.call(this);this.b=a;this.Ta=b;this.a=typeof b;this.Hb=c?c:!1;this.ba=!0;this.Cb=d?d:!1;this.vb=e?e:!1};p(Kc,E);g=Kc.prototype;g.n=function(){Kc.t.n.call(this);this.b="";this.Ta=null;this.a=""};g.id=function(){return this.b};g.type=function(){return this.a};g.F=function(){return this.Ta};g.setEnabled=function(a){this.ba=a};
var Lc=function(a){return(a=a.exec(Fa))?a[1]:""},Mc=function(){if(Ob)return Lc(/Firefox\/([0-9.]+)/);if(D||Na)return Ta;if(Tb)return Lc(/Chrome\/([0-9.]+)/);if(Ub)return Lc(/Version\/([0-9.]+)/);if(Qb||Rb){var a;if(a=/Version\/(\S+).*Mobile\/(\S+)/.exec(Fa))return a[1]+"."+a[2]}else{if(Sb)return(a=Lc(/Android\s+([0-9.]+)/))?a:Lc(/Version\/([0-9.]+)/);if(Pb)return Lc(/Camino\/([0-9.]+)/)}return""}();
var Oc=function(a){E.call(this);this.a=new C;this.b=["https://talkgadget.google.com/talkgadget/notifier-js","","https://test.talkgadget.google.com/talkgadget/notifier-js?jsmode=debug_unobfuscated"];a&&Nc(this,a)};p(Oc,E);var Pc=0<=qa(Mc,"23.0.1262.0")&&!Ec();Oc.prototype.n=function(){Oc.t.n.call(this);for(var a=this.a.M(),b=0;b<a.length;++b)F(this.a.get(a[b]));delete this.a};Oc.prototype.getItem=function(a){return Ka(this.a.a,a)?this.a.get(a):null};
Oc.prototype.setItem=function(a){this.a.set(a.id(),a)};var Nc=function(a,b){for(var c in b){var d=b[c],e=null;Ka(a.a.a,c)?(e=a.a.get(c),e.Ta=d.value,d.changed&&(e.vb=d.changed)):(e=new Kc(c,d.value,d.multiple,d.inverse,d.changed),e.setEnabled(!d.disabled));a.a.set(c,e)}};
var Sc=function(){this.c=new C;this.a=null;this.b=!1;this.a=new Qc;this.b=!0;Rc(this)};Sc.va=function(){return Sc.a?Sc.a:Sc.a=new Sc};var Rc=function(a,b){var c=b||ka;a.b?c():chrome.storage.local.get(r(function(a){if(!this.b){for(var b in a)this.c.set(b,a[b]);this.b=!0}c()},a))};Sc.prototype.get=function(a){return this.a.get(a)};Sc.prototype.set=function(a,b){var c=kc();this.a.set(a,b);c.a(void 0);return c.b};Sc.prototype.remove=function(a){this.a.remove(a)};Sc.prototype.clear=function(){this.a.clear()};
var Qc=function(){this.a=window.localStorage};Qc.prototype.clear=function(){this.a.clear()};Qc.prototype.get=function(a){a=this.a.getItem(a);if(a){var b=JSON.parse(a);a=b.data;if("jspb"==b.type){b=Ca[a[0]];if(!b)throw Error("e`"+a[0]);a=new b(a)}}else a=null;return a};Qc.prototype.set=function(a,b){var c=null;b instanceof x&&(b=b.G,c="jspb");var d={};d.data=b;d.timestamp=m();c&&(d.type=c);c=JSON.stringify(d);try{this.a.setItem(a,c)}catch(e){}};Qc.prototype.remove=function(a){try{this.a.removeItem(a)}catch(b){}};
var Tc=function(a,b){this.b=a;this.a=b;this.constructor.Vb||(this.constructor.Vb={});this.constructor.Vb[this.toString()]=this};Tc.prototype.toString=function(){this.c||(this.c=this.b.a+":"+this.a);return this.c};var L=function(a,b){Tc.call(this,a,b)};p(L,Tc);var Uc=function(a){this.a=a},Vc=new Uc("lib");/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
var Wc=function(a,b){this.j=[];this.u=b||null;this.b=this.a=!1;this.c=void 0;this.l=this.p=this.f=!1;this.e=0;this.h=null;this.q=0};Wc.prototype.k=function(a,b){this.f=!1;Xc(this,a,b)};var Xc=function(a,b,c){a.a=!0;a.c=c;a.b=!b;Yc(a)},$c=function(a){if(a.a){if(!a.l)throw new Zc;a.l=!1}};Wc.prototype.g=function(a){$c(this);Xc(this,!0,a)};var ad=function(a,b,c,d){a.j.push([b,c,d]);a.a&&Yc(a)};
Wc.prototype.then=function(a,b,c){var d,e,f=new ic(function(a,b){d=a;e=b});ad(this,d,function(a){"undefined"!=typeof bd&&a instanceof bd?oc(f):e(a)});return f.then(a,b,c)};fc(Wc);
var cd=function(a){return wa(a.j,function(a){return s(a[1])})},Yc=function(a){if(a.e&&a.a&&cd(a)){var b=a.e,c=dd[b];c&&(k.clearTimeout(c.ab),delete dd[b]);a.e=0}a.h&&(a.h.q--,delete a.h);for(var b=a.c,d=c=!1;a.j.length&&!a.f;){var e=a.j.shift(),f=e[0],h=e[1],e=e[2];if(f=a.b?h:f)try{var l=f.call(e||a.u,b);n(l)&&(a.b=a.b&&(l==b||l instanceof Error),a.c=b=l);gc(b)&&(d=!0,a.f=!0)}catch(q){b=q,a.b=!0,cd(a)||(c=!0)}}a.c=b;d&&(l=r(a.k,a,!0),d=r(a.k,a,!1),b instanceof Wc?(ad(b,l,d),b.p=!0):b.then(l,d));c&&
(b=new ed(b),dd[b.ab]=b,a.e=b.ab)},Zc=function(){ma.call(this)};p(Zc,ma);Zc.prototype.message="Deferred has already fired";Zc.prototype.name="AlreadyCalledError";var ed=function(a){this.ab=k.setTimeout(r(this.b,this),0);this.a=a};ed.prototype.b=function(){delete dd[this.ab];throw this.a;};var dd={};

}catch(e){_DumpException(e)}
try{
var fd=function(a,b){for(var c=t(a)?a.split(""):a,d=a.length-1;0<=d;--d)d in c&&b.call(void 0,c[d],d,a)};var hd=function(a){E.call(this);this.c={};this.h={};this.k={};this.e={};this.l={};this.q={};this.p=a?a.ua():new I;this.w=!a;this.f=null;a?(this.f=a,this.k=a.k,this.e=a.e,this.h=a.h,this.l=a.l):m();a=gd(this);this!=a&&(a.g?a.g.push(this):a.g=[this])};p(hd,E);var gd=function(a){for(;a.f;)a=a.f;return a};hd.prototype.get=function(a){var b=this.b(a);if(null==b)throw new id(a);return b};
hd.prototype.b=function(a){for(var b=this;b;b=b.f){if(b.C)throw Error("q");if(b.c[a])return b.c[a][0];if(b.q[a])break}if(b=this.k[a]){b=b(this);if(null==b)throw Error("r`"+a);this.a(a,b);return b}return null};hd.prototype.a=function(a,b,c){if(this.C)c||F(b);else{this.c[a]=[b,!c];b=jd(this,this,a);for(c=0;c<b.length;c++)b[c].g(null);delete this.h[a]}};hd.prototype.u=function(){var a=kd;if(!this.c[a])throw Error("s`"+a);var b=this.c[a];delete this.c[a];b[1]&&F(b[0])};
var jd=function(a,b,c){var d=[],e=a.e[c];e&&(fd(e,function(a){var c;t:{for(c=a.Wb;c;){if(c==b){c=!0;break t}c=c.f}c=!1}c&&(d.push(a.Kd),xa(e,a))}),0==e.length&&delete a.e[c]);return d},ld=function(a,b){a.e&&Ma(a.e,function(a,d,e){fd(a,function(d){d.Wb==b&&xa(a,d)});0==a.length&&delete e[d]})};
hd.prototype.n=function(){if(gd(this)==this){var a=this.g;if(a)for(;a.length;)a[0].B()}else for(var a=gd(this).g,b=0;b<a.length;b++)if(a[b]==this){a.splice(b,1);break}for(var c in this.c)a=this.c[c],a[1]&&"undefined"!=typeof a[0].B&&a[0].B();this.c=null;this.w&&this.p.B();ld(this,this);this.e=null;F(this.v);this.q=this.v=null;hd.t.n.call(this)};hd.prototype.ua=function(){return this.p};var id=function(a){ma.call(this);this.id=a;this.message='Service for "'+a+'" is not registered'};p(id,ma); var md=new Uc("fva");new L(md,1);

}catch(e){_DumpException(e)}
try{
var Ne=function(){return chrome.runtime.getURL("feedbackdialog.html")};
}catch(e){_DumpException(e)}
try{
var yh=function(a){for(var b=a.a.M(),c={},d=0;d<b.length;d++){var e=b[d],f=a.a.get(e);c[e]={value:f.F(),type:f.type(),multiple:f.Hb,disabled:!f.ba,inverse:f.Cb,changed:f.vb}}return c},zh=function(a,b){return t(b)?a.getElementById(b):b},S=function(a){return zh(document,a)},T=function(a){var b;b=b||[];b.length||(b[0]="");var c=chrome.i18n.getMessage(a,b);if(c)return c;(c=(c=k.ace_i18n[a.toLowerCase()])?c.message:k.ace_i18n["MSG_"+a])&&(c=c.replace("$1",b[0]).replace("$2",b[1]).replace("$3",b[2]));return c};

}catch(e){_DumpException(e)}
try{
var ln=function(a,b){for(var c=a.split("%s"),d="",e=Array.prototype.slice.call(arguments,1);e.length&&1<c.length;)d+=c.shift()+e.shift();return d+c.join("%s")},mn=function(){var a=S("fieldsetDestPage");a&&a.parentNode&&a.parentNode.removeChild(a)},nn=function(a){this.e=Dc("setting",""+m());this.c=null;this.b=new H;this.a=new C;this.f=a.get(Cc);this.b.listen(window,"unload",this.B)};p(nn,E);ga("ace.ui.SettingsDialog",nn);ga("ace.ui.SettingsDialog",nn);
nn.prototype.h=function(){document.title=T("CHROME_EXT_SHORT_NAME");this.c=chrome.runtime.connect({name:this.e});var a=this;this.c.onMessage.addListener(function(b){switch(Gc(new Fc,b).a){case "focus":pn(a);a.sendMessage("extensionLibrary",["selectTab",a.e,!0,!0]);window.focus();break;case "close":a.g()}});this.a.set("StartOnBrowserLaunch",["BrowserStartup",1]);this.a.set("StopOnBrowserClose",["Shutdown",1]);this.a.set("TopMost",["TopMost",1]);this.a.set("TrayIcon",["TrayIcon",1]);mn();qn("legendApp",
T("QUASAR_LEGEND_STARTUP_SHUTDOWN"));qn("legendNotice",T("QUASAR_LEGEND_NOTIFICATIONS"));rn(this,"StartOnBrowserLaunch",T("CHROME_EXT_RUN_AT_BROWSER_START"));rn(this,"StopOnBrowserClose",T("CHROME_EXT_RUN_AFTER_BROWSER_CLOSE"));rn(this,"TrayIcon",T("QUASAR_LABEL_TRAY_ICON"));Pc?rn(this,"TopMost",T("CHROME_EXT_NEW_WINDOWS_TOPMOST")):sn(this,"TopMost");Ec()&&sn(this,"TrayIcon");pn(this);var b=S("feedbackLink");b.innerText=T("CHROME_EXT_MENUTEXT_FEEDBACK");b.href=Ne();b=S("helpLink");b.innerText=T("QUASAR_HELP");
b.href=ln("https://support.google.com/hangouts?p=help&hl=%s",chrome.i18n.getMessage("@@ui_locale"));this.l=S("buttonSave");this.l.innerText=T("QUASAR_BUTTON_SAVE");this.b.listen(this.l,"click",r(this.p,this),!1);this.k=S("buttonCancel");this.k.innerText=T("QUASAR_BUTTON_CANCEL");this.b.listen(this.k,"click",r(this.g,this),!1)};nn.prototype.init=nn.prototype.h;nn.prototype.n=function(){nn.t.n.call(this);F(this.b)};
var tn=function(a,b,c){var d=[];b=b+a.a.get(c)[0];a=a.a.get(c)[1];if(1<a)for(c=0;c<a;c++)d.push(S(b+c));else d.push(S(b));return d},pn=function(a){for(var b=new Oc(a.f.get("settings")),c=a.a.M(),d=0;d<c.length;d++){var e=b.getItem(c[d]);if(e){var f=tn(a,"field",c[d]);if(e.Hb){var h=e.F();0<=h&&f[h]&&(f[h].checked=!0)}else f[0]&&("boolean"==e.a?e.Cb?f[0].checked=!e.F():f[0].checked=e.F():f[0].value=e.F());if(!e.ba)for(e=tn(a,"label",c[d]),h=0;h<e.length;h++)e[h]&&(e[h].disabled=!0),f[h]&&(f[h].disabled=
!0)}}},qn=function(a,b){var c=S(a);c&&(c.innerText=b)},rn=function(a,b,c){var d=a.a.get(b)[0];a=a.a.get(b)[1];if(1<a)for(b=0;b<a;b++){var e=S("label"+d+b);e&&c&&(e.innerText=c[b])}else(e=S("label"+d))&&c&&(e.innerText=c)},sn=function(a,b){var c=a.a.get(b)[0],d=S("field"+c);(d=(c=(c=S("label"+c)||d)&&c.parentNode)&&c.parentNode)&&d.removeChild(c)};
nn.prototype.p=function(){for(var a=new Oc(this.f.get("settings")),b=this.a.M(),c=0;c<b.length;c++){var d=a.getItem(b[c]);if(d){var e=tn(this,"field",b[c]),f=d.F();if(d.Hb){for(var h=-1,l=0;l<e.length;l++)if(e[l]&&e[l].checked){h=l;break}-1==h&&(h=0);d.Ta=h}else e[0]&&(d.Ta="boolean"==d.a?d.Cb?!e[0].checked:e[0].checked:e[0].value);f!=d.F()&&(d.vb=!0,a.setItem(d))}}this.f.set("settings",yh(a));this.g()};nn.prototype.g=function(){this.sendMessage("settingsManager",["updateSettingsFromStorage"]);window.close()}; nn.prototype.sendMessage=function(a,b,c){c=c?c:""+m();var d=new Fc;Hc(d,this.e,"p");null!=a&&(d.g=a);Ic(d,c);Jc(d,b);this.c&&this.c.postMessage(d.message())};
window.addEventListener("load",function(){Rc(Sc.va(),function(){var a=new hd;a.a(Cc,Sc.va());(new nn(a)).h()})},!1);
}catch(e){_DumpException(e)}
// Google Inc.
